### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by sohail579** [kasmtech/workspaces-issues#101]
Initially I came across Kasm on docker hub while i was looking for a chrome container.  I installed it on my Unraid server and wow it was lighting smooth and fast.  yes there was the down side of not having sound etc.  

I decided to go all in and create a VM and install the complete workspace.

My VM is:
6 Cores 6 Threads (from a Intel® Xeon® CPU E5-2690 v3 @ 2.60GHz)
8GB RAM
60GB SSD

after an initial hiccup its all up and running and I must say this is a great piece of software.

however its extremely leggy and slow, also the internet throughput is really slow also.  the Docker container for just Chrome which i had installed was really snappy and fast.  is there some sort of performance optimization which can be done?

**Comment by mmcclaskey** [comment]
When you run a container directly, without the full framework, no CPU and RAM restrictions are placed on the container, so it gets the full 6 cores and 8GB of RAM. When you use the full Workspaces platform, it places CPU and RAM restrictions on the container and you control those through the image settings: https://kasmweb.com/docs/latest/guide/custom_images.html#add-edit-images

The default CPUs is set to 1 and the default RAM is 1768MB. So you should obviously adjust those to meet your needs. If you set those to the same as running the container directly, there should be no difference in performance.

**Comment by sohail579** [comment]
Thank you for the information
