### ISSUE TITLE
Session load issue: insufficient permissions

### ISSUE THREAD

**Issue by rustsind** [kasmtech/workspaces-issues#103]
Hi,

Trying to deploy KASM today. 

So I'm running t3.medium instance on AWS with Ubuntu 20.04.3 LTS.

Installed Kasm with -L param on 8080 port, because I have NGINX as reverse proxy for multiple domains running on 433.

Firstly I got error from [Kasm does not load sessions](https://github.com/kasmtech/workspaces-issues/issues/89) ticket, but link with [Update Zones](https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones)  helped, thanks for that.

Now my "Loading APPLICATION Creating a secure connection..." screen just get stuck forever.

In newly created APP containers  always the same error:
`websocket 34: Requested file '/websockify'`
 `websocket 34: file not found or insufficient permissions`

Waiting to hear your thoughts, thanks!

**Comment by j-travis** [comment]
Can you share your nginx config?
If you havent seen, we have an example config that recommended settings: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#example-nginx-config

**Comment by rustsind** [comment]
I've missed this configuration example, it works now! Thanks!
