### ISSUE TITLE
kasm login error

### ISSUE THREAD

**Issue by ry44an** [kasmtech/workspaces-issues#104]
whenever I type username: admin@kasm.local and my password it sais a error and to contact a admin but I actually made the server and dont have a company for it how do I fix this

**Comment by j-travis** [comment]
Can you please review this ticket and see if its the same issue? The drive was full causing the services to crash
https://github.com/kasmtech/workspaces-issues/issues/90

**Comment by ry44an** [comment]
yep still the same

**Comment by ry44an** [comment]
should i update my storage (im using a vm to run it)

**Comment by j-travis** [comment]
Is your drive full?

please paste the output of the following commands

```
df
sudo docker ps
sudo docker info
uname -a
cat /ets/os-release
```

**Comment by ry44an** [comment]
lemme check

**Comment by ry44an** [comment]
one seccond im just rebooting it

**Comment by ry44an** [comment]
holy s*it it sais im using 23 gb isntead of my 100

**Comment by ry44an** [comment]
how do you fix this????

**Comment by ry44an** [comment]
when i do sudo docker ps it constantly restarts what to do

**Comment by j-travis** [comment]
I'm going to consider this issue closed in regard to Kasm. You'll need to ensure you have the recommended 50GB of hard drive spaces.
https://kasmweb.com/docs/latest/install/system_requirements.html

**Comment by ry44an** [comment]
I do have 50 gb

**Comment by j-travis** [comment]
Please be respectful of our developers' time. I've asked you to review a related ticket and provide the output of certain commands to help us troubleshoot your issue. You have not done these things
