### ISSUE TITLE
After enabling persitent profiles on Kali, Kali fails to boot

### ISSUE THREAD

**Issue by lavavex** [kasmtech/workspaces-issues#106]
After enabling persistent profiles on Kali, Kali will not boot and gets stuck at "Creating a Secure Connection" after first boot with persist and trashing the instance the first time. Kali will boot if persist is Disabled or Reset.

**Comment by lavavex** [comment]
can confirm that ubuntu works with persist in same directory

**Comment by j-travis** [comment]
Are you running Kali as root?

Please try to the following

1. Start your session 
2. While its failing to connect run the following command to find the ID of  the running kali container `sudo docker ps` 
3. Run the following command to get the logs from the container and paste them here `sudo docker logs --tail 100 <container-id>`

**Comment by lavavex** [comment]
This is what i get from that command:

------------------ EXECUTE COMMAND ------------------
+ echo 'Executing command: '\''/dockerstartup/vnc_startup.sh' /dockerstartup/kasm_startup.sh '--wait'\'''
Executing command: '/dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait'
+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
Generating a RSA private key
...........................................................................................................................................................................+++++
..................................+++++
writing new private key to '/home/kasm-user/.vnc/self.pem'
-----

---------  purging existing VNC password settings  ---------

New '9b6f5504640f:1 ()' desktop is 9b6f5504640f:1

Username: root

Starting applications specified in /home/kasm-user/.vnc/xstartup
Log file is /home/kasm-user/.vnc/9b6f5504640f:1.log

start window manager
...

------------------ Xfce4 window manager startup------------------
Skipping XFCE Startup
Starting audio websocket server
Starting audio server
Starting Pulse
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [autospawn] core-util.c: Home directory not accessible: Permission denied
W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
E: [pulseaudio] main.c: Failed to acquire autospawn lock
+ DEFAULT_PROFILE_HOME=/home/kasm-default-profile
+ PROFILE_SYNC_DIR=/kasm_profile_sync
+ '[' -f /home/kasm-user/.bashrc ']'
+ echo 'Profile already exists. Will not copy default contents'
+ verify_profile_config
+ echo 'Verifying Uploads/Downloads Configurations'
+ mkdir -p /home/kasm-user/Uploads
Profile already exists. Will not copy default contents
Verifying Uploads/Downloads Configurations
+ '[' -d /home/kasm-user/Desktop/Uploads ']'
+ echo 'Uploads Desktop Symlink Exists'
+ mkdir -p /home/kasm-user/Downloads
Uploads Desktop Symlink Exists
+ '[' -d /home/kasm-user/Desktop/Downloads ']'
Downloads Desktop Symlink Exists
+ echo 'Downloads Desktop Symlink Exists'
+ '[' -d /usr/share/kasmvnc/Downloads/Downloads ']'
+ echo 'Creating Downloads RX Symlink'
+ ln -sf /home/kasm-user/Downloads /usr/share/kasmvnc/www/Downloads/Downloads
Creating Downloads RX Symlink
+ ls -la /home/kasm-user/Desktop
total 10
drwxrwxrwx  2 root root  4 Jan 20 00:04 .
drwxrwxrwx 18 1000 1000 23 Jan 20 01:12 ..
lrwxrwxrwx  1 root root 25 Jan 20 00:04 Downloads -> /home/kasm-user/Downloads
lrwxrwxrwx  1 root root 23 Jan 20 00:04 Uploads -> /home/kasm-user/Uploads
+ rm -rf /home/kasm-user/.config/pulse
Removing Default Profile Directory
+ echo 'Removing Default Profile Directory'
+ rm -rf '/home/kasm-default-profile/*'
+ /dockerstartup/browser_proxy_config.sh
proxy configs not set
browser_startup_url not set
+ echo -e '\n\n------------------ EXECUTE COMMAND ------------------'


+ echo 'Executing command: '\''/dockerstartup/vnc_startup.sh' /dockerstartup/kasm_startup.sh '--wait'\'''
------------------ EXECUTE COMMAND ------------------
Executing command: '/dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait'
+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
Generating a RSA private key
........................+++++
...+++++
writing new private key to '/home/kasm-user/.vnc/self.pem'
-----

---------  purging existing VNC password settings  ---------

New '9b6f5504640f:1 ()' desktop is 9b6f5504640f:1

Username: root

Starting applications specified in /home/kasm-user/.vnc/xstartup
Log file is /home/kasm-user/.vnc/9b6f5504640f:1.log

start window manager
...

------------------ Xfce4 window manager startup------------------
Skipping XFCE Startup
Starting audio websocket server
Starting audio server
Starting Pulse
W: [pulseaudio] main.c: This program is not intended to be run as root (unless --system is specified).
E: [autospawn] core-util.c: Home directory not accessible: Permission denied
W: [autospawn] lock-autospawn.c: Cannot access autospawn lock.
E: [pulseaudio] main.c: Failed to acquire autospawn lock

**Comment by j-travis** [comment]
Thank you,
It looks like there is an issue with Audio when running the Kali container as root and resuming a persistent profiles. You can work around this by doing the following


- Log into workspaces as an admin
- Select Images
- Select edit next to Kali
- In the Docker Run Config enter the following `{"user":"root","environment":{"START_PULSEAUDIO":"0"}}`
- Click Submit. 
- Create a new session with the persistent profile enabled (to resume)

**Comment by lavavex** [comment]
Thanks for the extremely fast responses! This fixed my issue.
