### ISSUE TITLE
Disable Session Time Limit

### ISSUE THREAD

**Issue by slashtechno** [kasmtech/workspaces-issues#108]
Hello,
How is it possible to disable the session time limit? I have tried setting a group setting but I cannot get it to work.

**Comment by j-travis** [comment]
You cant disable it completely but you can set it as high as you like.

- log into workspaces as an admin
- Select Groups
- Select View next to the administators group
- Navigate down to the Group settings. Change keepalive_expiration. the default is 3600 seconds 1 hour
- Repeat the same for the All Users Group - you'll need to Add the setting as it doesnt exist by default
- Create a new session  or reconnect to an existing one. You should see the change apply.


I recommend watching this video to get an understanding of how the group settings work: https://www.youtube.com/watch?v=teJSUxKEbfE&t=130s

**Comment by slashtechno** [comment]
Oh okay, thanks.
Would persistent profiles be better for long term sessions?

**Comment by j-travis** [comment]
It depends on what youre after.

The persistent profiles feature works by saving the users home directory outside of the container. The allows things like documents and application settings (e.g browser history / favorites) to be remembered between sessions.

If you want long running processes to occur within the session while its unattended , you'll want to increase the keepalive.

If you want Workspaces to feel more like a VM , you'll probably want to set a high keepalive (e.g multiple days) and also use persistent profiles

**Comment by slashtechno** [comment]
Oh okay. Just to clarify, persistent profiles only backup the home
directory, so software installed outside of the home directory don't get
backed up?

**Comment by j-travis** [comment]
That is correct

**Comment by slashtechno** [comment]
> That is correct

Thanks for the clarification. Time to try to max out Kasm's time limit.

**Comment by slashtechno** [comment]
One more thing, how do I disable the time limit banner?
![image](https://user-images.githubusercontent.com/77907286/150245340-8d9820f6-357d-4cf7-9127-d7a3c67bbec1.png)

**Comment by j-travis** [comment]
This is controlled by the session time limit group setting. You should remove that setting.  You want the keepalive_expiration setting

**Comment by slashtechno** [comment]
Oh okay, I understand. I was confusing `keepalive_expiration` with `session_time_limit`

**Comment by j-travis** [comment]
Yes , i agree its kindof confusing. We should work to improve that.

**Comment by slashtechno** [comment]
It now is working. Thank you for your help @j-travis
![image](https://user-images.githubusercontent.com/77907286/150245873-266f5515-4f23-4c47-aded-19cc956000a0.png)

**Comment by idchlife** [comment]
Unfortunately, removing `keepalive_expiration` or `session_time_limit` does not affect client timer on the bottom of the screen.

Kasm Workspaces 1.12.0, Community Edition.

`session_time_limit` was not present in the Administrators group, there was `keepalive_expiration`.

Removing does nothing to the timer at the bottom of the screen.

All Users group has no settings at all.
