### ISSUE TITLE
Kasm limit exceeded for user when running more than 2 simultaneous sessions.

### ISSUE THREAD

**Issue by andygold99** [kasmtech/workspaces-issues#109]
After running 2 simultaneous sessions I am unable to start another session. I thought the limit was 5 simultaneous sessions, but when starting the 3rd session I get the error message saying "kasm limit exceeded for user". I have tried while logged in both as admin and user. I am using the free community tier.

**Comment by j-travis** [comment]
Hi @andygold99 , 
This is covered here: https://github.com/kasmtech/workspaces-issues/issues/22

It's a setting that can be changed. 

You may find this video helpful as it goes over the basics of administering the system:
https://www.youtube.com/watch?v=teJSUxKEbfE
