### ISSUE TITLE
Android docker image not working

### ISSUE THREAD

**Issue by SKM33** [kasmtech/workspaces-issues#113]
I'm facing a problem with running android 86 docker image on kasm.
when I try to run it it says "agent may still be downloading the image"
I waited for hours without a result.
this is the image I'm trying to use: 
budtmo/docker-android-x86-8.1

**Comment by j-travis** [comment]
Hi,
Typical problems with why an image might not be downloading include

- The image isnt Enabled in the Image Settings
- The image doesn't have a docker registry defined in the Image settings. If using dockerhub the value should be `https://index.docker.io/v1/` . 
- The image is using a private registry and credentials are not defined or are incorrect within the Image definition

If you correct these and are still having a problem you can review the error logs within the UI


All that being said, you can't run an arbitrary container inside Kasm and get it streamed to your browser.  For that functionality, the images must be based from one of our [Core Images](https://github.com/kasmtech/workspaces-core-images).  The Core images contain the base level of functionality to allow the containers to be streamed to your browser.

More information on creating custom images can be found here:

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://www.youtube.com/watch?v=BGP69_f1wq0


At this time its not possible to stream android based containers but its something we may investigate in the future
