### ISSUE TITLE
Issue with Kasm - Open In Isolation Firefox Add-On

### ISSUE THREAD

**Issue by numb699** [kasmtech/workspaces-issues#116]
Right click option to open in insolation doesn't appear. Tried disabeling other Add-Ons, but no luck. If I reset Firefox it sometimes works for a little while. Firefox 96.0.2 (64-bit) on Windows 11 Pro version 10.0.22000 Build 22000. Kasm - Open in Isolation add-on v 0.0.4

**Comment by j-travis** [comment]
Thank you for reporting.
We've been able to reproduce the problem and have someone looking into it.

Initial triage suggests that selecting "Allow this extension to run in Private Windows" causes the extension to fail to render the right click menu item.

![image](https://user-images.githubusercontent.com/48762190/150610282-5a59a8b4-78a7-4baf-a39b-9d115a0eb57e.png)

We were able to get the extension to function if we:
- remove the extension
- closed all browser windows
- opened the browser
- installed the extension and did NOT check the option listed above during installation.


We will report back when we have fully identified and corrected the issue

**Comment by numb699** [comment]
That seems to work, although I can't remember enabling it in Private Windows. Anyways, seems to work fine now. Thank you!

**Comment by numb699** [comment]
Unfortunately it didn't last. After a reboot it still disappears. Definately did not check the box for private windows.

**Comment by antunesn** [comment]
same issue here...
remove it, reinstall it, the first time run fine... after reboot, it disappears again.
Has nothing to do with the "private windows".

**Comment by tfagler** [comment]
I have tried not allowing it to private browse and it does not show up on right click any more.using 96.0.2 (64-bit) Firefox.

**Comment by j-travis** [comment]
Thank you for the feedback. We have pushed a new version of the add on (`0.0.5`) , and it should include the fix. You can also run it in private windows now.

https://addons.mozilla.org/en-US/firefox/addon/kasm-open-in-isolation/

**Comment by numb699** [comment]
This still doesn't really work. I'm on FF 132.
