### ISSUE TITLE
Feature Request - ParrotOS

### ISSUE THREAD

**Issue by numb699** [kasmtech/workspaces-issues#117]
A lightweight ParrotOS Home or Security with anonsurf would be a very useful addition to the great selection of images already there.

**Comment by fdelucchijr** [comment]
Kali Linux is good, but as a SecOps engineer, ParrotOS is by far superior. Very much recommended!!!

**Comment by mmcclaskey** [comment]
I have created an internal ticket for this and placed in our backlog. Given that it is based on Debian, it likely would be less of a heavy lift than others. However, we will not know for sure until we start looking into it.

**Comment by nyxb** [comment]
y pls parrotOS <3

**Comment by sca255** [comment]
parrot os is the best please add the security edition

**Comment by MrAshRhodes** [comment]
+1 for parrot OS.

**Comment by camhghs** [comment]
Any update on this?

**Comment by mmcclaskey** [comment]
Before we could make a Workspace image for Parrot OS we would need KasmVNC working on Parrot OS. See this issue here https://github.com/kasmtech/KasmVNC/issues/126.

If there is someone in the Parrot community that could help get us with a pipelined build of KasmVNC for Parrot OS, that would be the first step.

**Comment by PhasmaShell** [comment]
@mmcclaskey

I may know someone who has a good connection with the Parrot OS team. I'll see what I can do.

**Comment by PalinuroSec** [comment]
hold my beer and let's see what i can do

**Comment by infocentr** [comment]
+1 for Parrot OS

**Comment by j-travis** [comment]
Thanks for your feedback.
We are going to take a look at this in the coming weeks. Hopefully before too long we can have something for you all to beta test.

**Comment by j-travis** [comment]
We have two images available for preview if you all would like to test.

- kasmweb/parrotos-5-desktop:develop (https://hub.docker.com/r/kasmweb/parrotos-5-desktop)
- kasmweb/core-parrotos-5:develop (https://hub.docker.com/r/kasmweb/core-parrotos-5)

The core image contains the minimal set of packages that makes the image usable within the workspaces platform, The "desktop" image builds upon that and installs a number of the tools meta-packages you can see here:
- https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-parrotos-5-desktop
- https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/parrot/install_parrot.sh
