### ISSUE TITLE
Cloudflare 500 error

### ISSUE THREAD

**Issue by FOREVEREALIZE** [kasmtech/workspaces-issues#121]
Hi!
I have set up Kasm Workspaces on my OCI server and every time I create a session and try to connect, it fails a few requests with 500 status code and returns me to the dashboard.

I have tried #41, #110 and all other issues that pop up by searching for cloudflare.
The way i have it set up is: A non-proxied A record on CF and CF Certs on NGINX.
My zone settings are:

Zone Name: default
Allow Origin Domain: $request_host$
Upsteram Auth Address: 10.0.0.196 (Servers' Private IP)
Load Balance Startegy: Least Load
Search Alternate Zones: ON
Proxy Connections: ON
Proxy Hostname: $request_host$
Proxy Path: desktop
Proxy Port: 443

Any help' would be appreciated!

**Comment by j-travis** [comment]
Lets see if `kasm_proxy` can make connections back to your server. Can you please run the following command and provide the output

```
sudo docker exec -it kasm_proxy curl -k https://10.0.0.196
```

**Comment by FOREVEREALIZE** [comment]
Well...
Something is clearly not adding up...
`curl: (7) Failed to connect to 10.0.0.196 port 443 after 0 ms: Host is unreachable`

**Comment by FOREVEREALIZE** [comment]
Ok, so.
Feel like a big dum dum for not trying this but, what fixed it was setting the Upstream Auth Address to 127.0.0.1
I think it is OCI networking being weird, cuz it does some pretty weird things sometimes.
Anyways, fixed it!
