### ISSUE TITLE
 Cannot make it work on AWS

### ISSUE THREAD

**Issue by ToontjeM** [kasmtech/workspaces-issues#122]
Can someone do a How-To on installing it on an EC2 instance? I tried a couple of times and always run into the same issue:
Installation works fine.
Dashboard loads up find.
I can install, download and enable new images fine.
When I launch an image the session gets stuck at Creating Secure Connection and eventually times out and goes back to the dashboard.
I tried many different settings, ports, etc. Preferably I would like to run it on a port that is not well-known as an HTTP/S port, so not something like 80, 443, 8080, 8181, etc. More like 12773 or something like that.
The objective is to have a working environment for when I'm traveling. 

Can someone guide me on getting this running?

**Comment by j-travis** [comment]
Kasm needs to be able to connect back to itself to authorize connections to sessions. You likely need to update your AWS security group to allow HTTPS connections for the local server , You can find more info about this in our troubleshooting guide
https://kasmweb.com/docs/latest/guide/troubleshooting.html#server-side-issues

You can install workspaces on a separate port by passing the `-L` flag during the install. Its covered  in the install guide;
https://kasmweb.com/docs/latest/index.html#installation-guide

**Comment by ToontjeM** [comment]
I have incoming for TCP 443 and my non-standard port from my IP to the EC2 instance. Otherwise the web interface would not be working either. 
Am I missing something?

**Comment by ToontjeM** [comment]
It only seems to work correctly if I open port 443 to 0.0.0.0/0 
For now I'm good.
