### ISSUE TITLE
Requesting -- openSUSE

### ISSUE THREAD

**Issue by terrorpup** [kasmtech/workspaces-issues#123]
Is it possible to get openSUSE as a desktop?

**Comment by mmcclaskey** [comment]
It is possible and it is in our backlog, however, it is not currently selected for development. There are two major steps that need to occur. 

1. KasmVNC would need a build for the version of OpenSUSE being targeting.
https://github.com/kasmtech/KasmVNC

2. A new core docker desktop image that bases the version of OpenSUSE being targeted
https://github.com/kasmtech/workspaces-core-images

**Comment by j-travis** [comment]
We now have an openSUSE 15 (Leap) Core and Desktop Image

![image](https://user-images.githubusercontent.com/48762190/162709364-5f7435b7-f9bb-4ee4-8b10-e7a8c5126f76.png)

- https://hub.docker.com/r/kasmweb/core-opensuse-15
- https://hub.docker.com/r/kasmweb/opensuse-15-desktop
- https://github.com/kasmtech/workspaces-core-images
- https://github.com/kasmtech/workspaces-images

They will be using the `develop` tags until the official release of 1.11.0 , but you can try them now if you like

**Comment by niktok5** [comment]
Is there an equivalent of 

{
 "first_launch":{
      "user":"root",
      "cmd":"bash -c '/usr/bin/desktop_ready && apt-get update && apt-get install -y sudo && echo \"kasm-user  ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers'"
  }
}

for running OpenSUSE as root?
