### ISSUE TITLE
Kali & Openvpn fails to connect

### ISSUE THREAD

**Issue by sha1024zz** [kasmtech/workspaces-issues#125]
I am unable to connect to openvpn inside kali.  

Based on the error message it looks like i need to add to docker '--device=/dev/net/tun --cap-add=net_admin'.  How can i do this from kasm?

' ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)'

thanks

**Comment by j-travis** [comment]
@sha1024zz ,
you can find a guide on running OpenVPN inside a Kasm session at the link below.

https://kasm.medium.com/secure-vpn-via-kasm-container-streaming-platform-b776bd58f109

**Comment by sha1024zz** [comment]
Thanks - got it working.
