### ISSUE TITLE
Can't see the all images in admin/images tab

### ISSUE THREAD

**Issue by imhari** [kasmtech/workspaces-issues#126]
Hello,
I installed the kasm into my new server by following the installation guide. Still, when I open the images to enable kali and other applications, I can't see all images there. Please help me troubleshoot this.

![Screenshot 2022-01-24 151809](https://user-images.githubusercontent.com/22318771/150858449-c90d0403-097f-4302-847b-ee541fa3f033.png)
![Screenshot 2022-01-24 151836](https://user-images.githubusercontent.com/22318771/150858466-de1634fe-8bbc-4eff-a281-0b7087587d5f.png)

**Comment by j-travis** [comment]
It looks like you may be running on an ARM64 system.
Not all of the images are supported. You can see a list here:
https://kasmweb.com/docs/latest/guide/custom_images.html

Just recently we created a testing version of Kali that will run on arm64. You can see more info about that here:
https://github.com/kasmtech/workspaces-issues/issues/84#issuecomment-1016854785

**Comment by imhari** [comment]
Oh, okay, and can I use the kasm on the AMD processer?

**Comment by j-travis** [comment]
Yes. Here are our supported platforms:
https://kasmweb.com/docs/latest/install/system_requirements.html
