### ISSUE TITLE
Can't login after installation

### ISSUE THREAD

**Issue by sguilite** [kasmtech/workspaces-issues#127]
Hi,

I tried to install kasm by using my Portainer platform (installed on my OpenMediaVault Server).

I used this docker-compose file :

file:///C:/Users/sgui/Downloads/kasmweb-docker-composeyml-container-template-db-tech-custom.html

Normaly, i should be able to login on https://<myip>:6901 by using :

User : kasm_user
Password: password

But it doesn't work. I can't login for the first time. Is there a way to find the user/password by default ?

![image](https://user-images.githubusercontent.com/81743299/150863751-edbbba8d-d1c0-47e4-8dbc-58d4fe37c8e2.png)

here is docker ps :
`
            NAMES
43e7cf158a48   kasmweb/firefox:1.9.0              "/dockerstartup/kasm…"   3 hours ago    Up 3 hours   4901/tcp, 5901/tcp, 0.0.0.0:6911->6901/tcp, :::6911->6901/tcp                                                                             kasm_firefox_1
b1891a2c3838   diouxx/glpi                        "/opt/glpi-start.sh"     5 hours ago    Up 5 hours   443/tcp, 0.0.0.0:5000->80/tcp, :::5000->80/tcp                                                                                            glpi
aa39bef92983   mariadb:10.7                       "docker-entrypoint.s…"   5 hours ago    Up 5 hours   3306/tcp                                                                                                                                  glpi_mariadb
0d044f0648ef   jc21/nginx-proxy-manager:latest    "/init"                  2 weeks ago    Up 13 days   0.0.0.0:80-81->80-81/tcp, :::80-81->80-81/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                      nginx_proxy_manager_app_1
2f42122f078f   jc21/mariadb-aria:latest           "/scripts/run.sh"        2 weeks ago    Up 13 days   3306/tcp                                                                                                                                  nginx_proxy_manager_db_1
76d586446807   lscr.io/linuxserver/transmission   "/init"                  3 months ago   Up 13 days   0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 0.0.0.0:51413->51413/tcp, :::51413->51413/tcp, 0.0.0.0:51413->51413/udp, :::51413->51413/udp   transmission
a668280205ec   portainer/portainer-ce             "/portainer"             3 months ago   Up 13 days   0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 9443/tcp                                            portainer
                                                                           kasm_firefox_1
`

here is df -f : 

`
udev               7,8G       0  7,8G   0% /dev
tmpfs              1,6G    155M  1,4G  10% /run
/dev/sda2          227G    9,4G  206G   5% /
tmpfs              7,8G       0  7,8G   0% /dev/shm
tmpfs              5,0M       0  5,0M   0% /run/lock
tmpfs              7,8G       0  7,8G   0% /sys/fs/cgroup
tmpfs              7,8G    4,0K  7,8G   1% /tmp
/dev/sda1          511M    148K  511M   1% /boot/efi
/dev/md0           1,4T    863G  512G  63% /srv/dev-disk-by-uuid-28fe4c38-7eeb-4f8e-805b-624b890cb817
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/c9b6338b9a417c6d1a1dab46b96f12712e29bc51966e7350d8d9dcc77aa21dcd/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/04601b51734404800c0f710604d1c43969eb6be81e92e27fc0c4700befe62650/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/4ebd5a500e482a5dd55667038e35aa6e88c39d1c76e491c098f510e8fdc542ad/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/f2758e1b9c26f8b39c60f2bcb13229c06ea9194861d6f33258e6919ea3a87802/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/a6ad51cb5acae51f3802fd3c1c472d0d205658948f274889fefd5df88ca27551/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/fce12d6c15ec2f846dec8bb90414e4b5632b9a4995721bf2294b04fab59bc6cb/merged
overlay            227G    9,4G  206G   5% /var/lib/docker/overlay2/19d38aaa9d4f9d547a90b9162e86d80a9dc09346283be48edce1b9bb42fab580/merged
tmpfs              1,6G       0  1,6G   0% /run/user/0
root@openmediavault:/#
`

Thanks in advance for any answer.

**Comment by j-travis** [comment]
Hello.
We don't support running on a mediavault server, not do we publish a standalone docker-compose template for doing so.

Here are the OS distros/versions we support.
https://kasmweb.com/docs/latest/install/system_requirements.html

so, unfortunately we can't support this request. You'll need to ask the person who created the docker-compose file.
