### ISSUE TITLE
Azure AD Saml Error

### ISSUE THREAD

**Issue by evankruiselbergen** [kasmtech/workspaces-issues#131]
Hi, 
Just new to KASM and setting up a standalone server at first to serve the security team. 
However when setting up I the SSO on our Azure AD I get this error. 

**_Sorry, but we’re having trouble signing you in.
AADSTS75011: Authentication method 'X509, MultiFactor' by which the user authenticated with the service doesn't match requested authentication method 'Password, ProtectedTransport'. Contact the KASM SSO application owner._**

Could this be because we do not have a license for Professional installed yet?
Or is there a config part I missed on the documentation?

Regards
Erik

**Comment by j-travis** [comment]
Here is a writeup of the error from Microsoft. 
https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts75011-auth-method-mismatch

We have a temporary workaround that may solve this for you. Currently Kasm requires the `RequestedAuthnContext` and some IdPs treat it as optional. We have a ticket to make this a configurable options via the UI in the future.

https://kasmweb.com/docs/latest/guide/saml/requestedAuthnContext.html

Can you give this a shot and see if fixes your issue?

**Comment by evankruiselbergen** [comment]
Thank you for the reply.. However when I change the context for the API.. I get the next error. 
Starting Kasm Services
yaml: line 46: mapping values are not allowed in this context

**Comment by j-travis** [comment]
It looks like your `docker-compose.yaml` is malformed after making the edits.

When you are making the edits, find the part of the file that starts with `kasm_api:`

Then underneath add the 2 lines that represent the environment variable that are requested in the doc:. Be sure to keep the spacing and indentation as its important for yaml.

```
    environment:
         KASM_SAML_REQUESTED_AUTHN_CONTEXT: 'false'
```


So the section should look like this when you are done

```
kasm_api:
   environment:
       KASM_SAML_REQUESTED_AUTHN_CONTEXT: 'false'
   container_name: kasm_api
   user: "${KASM_UID?}:${KASM_GID?}"


```

**Comment by evankruiselbergen** [comment]
Cool.. that did the trick.. But now I get another error.. 

services.proxy.volumes array items[1,2] must be unique

**Comment by evankruiselbergen** [comment]
Cool that did the trick.. got the other errors I recieved afterwards too.

**Comment by evankruiselbergen** [comment]
Or at least I thought I did.. back to the drawing board. Think I messed up the whole thing now my users are gone and all settings are gone too.

**Comment by j-travis** [comment]
It sounds like you many have accidentally made additional modifications to the yaml.

**Comment by evankruiselbergen** [comment]
Thanks for the help anyways.. I rebuild the VM and then redeployed Kasm and the SSO.. now it works like a charm.
