### ISSUE TITLE
Credentials for OS inside KASM

### ISSUE THREAD

**Issue by ionescurobert** [kasmtech/workspaces-issues#132]
Hi all,

After launching a session like Kali, the terminal will start with "default". Is there a way to setup any user for the OS so it is possible to run also commands as admin?

![image](https://user-images.githubusercontent.com/11048144/151324100-d95f767a-5dfc-474c-96cb-be773831ccf2.png)

**Comment by j-travis** [comment]
Yes:
- https://kasmweb.com/docs/latest/how_to/running_as_root.html
- https://youtu.be/U7e-mcJdZok?t=830

**Comment by ionescurobert** [comment]
Thank you
