### ISSUE TITLE
Do not display time inside the session

### ISSUE THREAD

**Issue by ionescurobert** [kasmtech/workspaces-issues#133]
The default time limit for a workspace is set to 60min. I need on specific Images to be able to keep them longer alive like 24h.

I have changed the Session Lifetime for the Image I want

![image](https://user-images.githubusercontent.com/11048144/151355329-2ff32dcd-194f-4607-ba60-a69fccea6a9a.png)

But why is this change displaying me the remaining time inside the workspace. This timer costs space and can be annoying. Is there a setting to remove it in general and keep only the time in the active session overview?

![image](https://user-images.githubusercontent.com/11048144/151355254-919b7ffd-ee03-41a5-8461-54c9bb43d7e5.png)

**Comment by j-travis** [comment]
Hi, I believe this is covered here:
https://github.com/kasmtech/workspaces-issues/issues/108

**Comment by ionescurobert** [comment]
Ok, looks good.
Seems like it is not possible to make it different for every Image.
