### ISSUE TITLE
Install script didn't show the admin login credentials

### ISSUE THREAD

**Issue by CristianEduardMihai** [kasmtech/workspaces-issues#134]
Hi ! I just installed kasm on a pc with ubuntu server and lubuntu desktop env.

This is the last thing that my installer gave me : 
```
a0ada5636317: Already exists
497109a96f39: Pull complete
3a49ee24157f: Pull complete
2b08385ed646: Pull complete
d9225b8bebfd: Pull complete
7841096e9c3d: Pull complete
8b8a23db5082: Pull complete
df5162f55714: Pull complete
af9912fec408: Pull complete
1ae3dff95767: Pull complete
Digest: sha256:ceb58f00018d291796b333bff668a01e272ddd4d92787e26ec384b802f695322
Status: Downloaded newer image for kasmweb/telegram:1.10.0
docker.io/kasmweb/telegram:1.10.0
mihai@ubuntu-server:~$
```

What now ? How can i get my login credentials ?

**Comment by mmcclaskey** [comment]
Duplicated by #118

Please provide the output of 
sudo docker info
sudo docker ps
sudo docker images | grep kasm
uname -a
cat /etc/os-release
df -h

**Comment by gautam-sudo** [comment]
I encountered the same issue.

I didn't get any output for this command:
sudo docker images | grep kasm

Please find the output for the commands requested.
sudo docker info--
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.18.0-15-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4.33GiB
 Name: gautam-VirtualBox
 ID: IN2K:3KVN:MXPD:J34B:4KBV:CHUU:RA7I:WJQI:MUHD:R5TX:P2AI:NIFU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support


sudo docker ps

<pre>CONTAINER ID   IMAGE                    COMMAND                  CREATED             STATUS                       PORTS                                           NAMES
1f9ba9332303   kasmweb/nginx:latest     &quot;/docker-entrypoint.…&quot;   About an hour ago   Up About an hour             80/tcp, 0.0.0.0:443-&gt;443/tcp, :::443-&gt;443/tcp   kasm_proxy
eed712cd1e0d   kasmweb/share:1.10.0     &quot;/bin/sh -c &apos;/usr/bi…&quot;   About an hour ago   Up About an hour             8182/tcp                                        kasm_share
b66e73f3b02b   kasmweb/agent:1.10.0     &quot;/bin/sh -c &apos;/usr/bi…&quot;   About an hour ago   Up About an hour             4444/tcp                                        kasm_agent
aa7742b194b3   redis:5-alpine           &quot;docker-entrypoint.s…&quot;   About an hour ago   Up About an hour             6379/tcp                                        kasm_redis
70ab24ad5ab4   kasmweb/manager:1.10.0   &quot;/bin/sh -c &apos;/usr/bi…&quot;   About an hour ago   Up About an hour             8181/tcp                                        kasm_manager
968fc9f22b46   kasmweb/api:1.10.0       &quot;/bin/sh -c &apos;/usr/bi…&quot;   About an hour ago   Up About an hour (healthy)   8080/tcp                                        kasm_api
d2bfa8e291be   postgres:12-alpine       &quot;docker-entrypoint.s…&quot;   About an hour ago   Up About an hour             5432/tcp                                        kasm_db
</pre>

<pre>Linux gautam-VirtualBox 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
</pre>

<pre>Filesystem      Size  Used Avail Use% Mounted on
udev            2.2G     0  2.2G   0% /dev
tmpfs           444M  2.0M  442M   1% /run
/dev/sda1        51G   24G   25G  49% /
tmpfs           2.2G   19M  2.2G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           2.2G     0  2.2G   0% /sys/fs/cgroup
/dev/loop0       91M   91M     0 100% /snap/core/6350
/dev/loop1       35M   35M     0 100% /snap/gtk-common-themes/818
tmpfs           444M   28K  444M   1% /run/user/121
/dev/loop2      141M  141M     0 100% /snap/gnome-3-26-1604/74
/dev/loop3      2.3M  2.3M     0 100% /snap/gnome-calculator/260
tmpfs           444M   52K  444M   1% /run/user/1000
/dev/loop4       13M   13M     0 100% /snap/gnome-characters/139
/dev/loop5       15M   15M     0 100% /snap/gnome-logs/45
/dev/loop6      3.8M  3.8M     0 100% /snap/gnome-system-monitor/57
</pre>

<pre>NAME=&quot;Ubuntu&quot;
VERSION=&quot;18.04.2 LTS (Bionic Beaver)&quot;
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME=&quot;Ubuntu 18.04.2 LTS&quot;
VERSION_ID=&quot;18.04&quot;
HOME_URL=&quot;https://www.ubuntu.com/&quot;
SUPPORT_URL=&quot;https://help.ubuntu.com/&quot;
BUG_REPORT_URL=&quot;https://bugs.launchpad.net/ubuntu/&quot;
PRIVACY_POLICY_URL=&quot;https://www.ubuntu.com/legal/terms-and-policies/privacy-policy&quot;
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
</pre>

**Comment by j-travis** [comment]
@gautam-sudo ,
Thank you for the info. 
Can you run one more command for me and pated the output

```
sudo swapon --show
```

**Comment by CristianEduardMihai** [comment]
Thanks for all the responses, but I ended up switching to another server distro, and thus reinstalling kasm. This time it didn't give me that error.
