### ISSUE TITLE
Install Fail Ubuntu 18.04

### ISSUE THREAD

**Issue by alex12342** [kasmtech/workspaces-issues#138]
Checking if docker and docker compose are installed.
WARNING: No swap limit support
Docker is installed
20.10.12 is a supported version of docker.
Commands docker and docker compose detected.
Skipping Dependency Installation.
Installing All Services
Updating configurations with custom DEFAULT_PROXY_LISTENING_PORT (8443)
Docker network kasm_default_network already exists. Will not create
Initializing Database
Setting Seed file as /opt/kasm/1.10.0/conf/database/seed_data/default_properties.yaml
Error response from daemon: Cannot kill container: kasm_db: No such container: kasm_db
Error: No such container: kasm_db
kasm_db_1.10.0
kasm_db_1.10.0
[+] Running 0/0
 ⠋ db Pulling                                                                  0.0s
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`

**Comment by j-travis** [comment]
This looks like an underlying docker issue.  A quick google of the error suggests that you docker install is configured to use a custom credential helper that requires a GUI to pop.

I'd expect if you did a `docker login` or `docker pull <image>` you'd get a similar message

**Comment by alex12342** [comment]
I do get a similar message when I try to do a docker login. Docker pull works fine.

**Comment by alex12342** [comment]
[https://github.com/docker/compose/issues/6023#issuecomment-419792269](url)
Followed the steps listed in that post and now I am able to install
