### ISSUE TITLE
Question: Run website along side Kasm

### ISSUE THREAD

**Issue by myxxmikeyxx** [kasmtech/workspaces-issues#141]
Would it be possible to run Kasm along side a pre-existing website. For example I have docker already installed on a server. I also have portainer installed. Portainer run on port 9000. I also have a website running, using ports 80, & 443. Could I configure Kasm to run on port 8080 or something like that? If so could you point me in the direction or to the documentation. I had no luck finding it.

**Comment by j-travis** [comment]
- When you install Kasm you can have it run on a different port by passing the `-L` flag. e.g  `-L 8443` . Its at the top of the install guide. https://kasmweb.com/docs/latest/index.html#installation-guide
- You may also consider using a reverse proxy to server multiple sites. If you place Kasm behind a reverse proxy like nginx, we have a guide for that. https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#multiple-server-names

**Comment by myxxmikeyxx** [comment]
Thank you so much. I will have to look into it more. I'm new to this and just kinda doing it for fun and to learn something new.
