### ISSUE TITLE
Kasm Sign Out

### ISSUE THREAD

**Issue by sha1024zz** [kasmtech/workspaces-issues#142]
Hi,

How can I extend the time when Kasm signs out? 

At present it signs me out after a short period of time when idle.  I then have to log back in using 2fa every time.

thanks

**Comment by j-travis** [comment]
I believe you are looking for the group setting named `idle_disconnect` : Ref: https://kasmweb.com/docs/latest/guide/groups/group_settings.html?highlight=idle_disconnect

Recommend you watch this video to get an understanding of how group settings work:
https://www.youtube.com/watch?v=teJSUxKEbfE&t=140s

Then set the `idle_disconnect` in the **All Users** group and remove the setting for the **Administrators** group if its present
