### ISSUE TITLE
Local Network browsing

### ISSUE THREAD

**Issue by Brittgoran** [kasmtech/workspaces-issues#145]
When using "Ubuntu Bionic" and selecting network "Bridge" we still not ping internal resources.
How can we configure it so we can access local resources?

**Comment by j-travis** [comment]
What error do you get?

The default Ubuntu image doesnt include the ping command so you would have had to create your own custom image with that command or run the container as root and install it.

Generally speaking though , this is going to be a local host or network firewall issue and not something that specific to Kasm.

**Comment by Brittgoran** [comment]
Ok, is it possible to modify the images and save the changes or do i need to set one up myself from scratch?

Failed to open "/ on ".

when I click on "Browse Network".

**Comment by j-travis** [comment]
While we do support Persistent Profiles: https://kasmweb.com/docs/latest/how_to/persistent_profiles.html , there is not currently a way to save back a running session as an image to base future sessions on.

You'll need to build your own custom image with the software and configurations you desire. Here are some resources to help:
- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://www.youtube.com/watch?v=BGP69_f1wq0

The Browse Network feature in the Thunar File manager can be enabled by installing additional packages in your image:

```
apt-get install -y cifs-utils gvfs-backends
```
