### ISSUE TITLE
Auth0 IDP invalid_response

### ISSUE THREAD

**Issue by jsargent8789** [kasmtech/workspaces-issues#147]
I tried to configure saml with my idp auth0 and no matter what I do I get invalid_response: Invalid issuer in the Assertion/Response (expected GOSRASs9ubrhuQrKXMq1j5UOZEQZtL9u, got urn:sso-dozecloud.auth0.com)

**Comment by jsargent8789** [comment]
![image](https://user-images.githubusercontent.com/74645469/152652907-0f386ee1-ea51-4ec2-844d-d8e2d3ead805.png)

**Comment by jsargent8789** [comment]
![image](https://user-images.githubusercontent.com/74645469/152652941-17c6c10f-18fc-4500-b2a9-58260adb0389.png)

**Comment by jsargent8789** [comment]
![image](https://user-images.githubusercontent.com/74645469/152652988-11e1cdd4-5901-47b7-9079-7d3b59f2779d.png)

**Comment by jsargent8789** [comment]
![image](https://user-images.githubusercontent.com/74645469/152652996-02f8aacd-6796-4a85-9d89-11951a2e59aa.png)

**Comment by zsinba** [comment]
the same issue.
