### ISSUE TITLE
500 Internal Server Error when signing in with saml

### ISSUE THREAD

**Issue by jsargent8789** [kasmtech/workspaces-issues#149]
I had saml working for about a day and all of sudden I get 500 Internal Server Error when I login now.

**Comment by mmcclaskey** [comment]
Can you open up devtools in your browser and see if there are any additional details in the console tab and provide the output. When you login via SAML, can you tail the logs on the kasm api container and provide those as well?

`sudo docker logs -f --tail 30 kasm_api`

**Comment by jsargent8789** [comment]
My Ubuntu server got stuck in read only mode had to use fsck to fix the file system
