### ISSUE TITLE
apache2 as reverse proxy

### ISSUE THREAD

**Issue by PrincessPi3** [kasmtech/workspaces-issues#151]
I have my kasm installed and listening on localhost:8443, and the following config in apache2, but it throws a 500
  GNU nano 4.8                                    kasm_princesspi_io.conf                                               <VirtualHost 192.3.204.9:80>
        ServerName kasm.princesspi.io
        Redirect permanent / https://kasm.princesspi.io
</VirtualHost>
<VirtualHost 192.3.204.9:443>
        ServerName kasm.princesspi.io
        SSLEngine on
        SSLCertificateFile      /etc/letsencrypt/live/kasm.princesspi.io/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/kasm.princesspi.io/privkey.pem

#this is what I've already tried
        RequestHeader set SSL_CLIENT_S_DN "Off"
        RequestHeader set SSL_CLIENT_I_DN "Off"
        RequestHeader set SSL_SERVER_S_DN_OU "Off"
        RequestHeader set SSL_CLIENT_VERIFY "Off"
        SSLProxyCheckPeerCN Off
        SSLProxyCheckPeerName Off

        ProxyPass / https://localhost:8443/
</VirtualHost>

tail /var/log/apache2/error.log shows this
`[proxy:error] [pid 13259] AH00961: HTTPS: failed to enable ssl support for [::1]:8443 (localhost)`

**Comment by j-travis** [comment]
At least for this initial error I suspect you are looking for `SSLProxyEngine`
https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslproxyengine

You'll also need to make sure that Apache is configured to support websockets.  We don't have a guide on apache, but we do have guides for Nginx that you may be able to map over to apache
https://kasmweb.com/docs/latest/how_to/reverse_proxy.html
