### ISSUE TITLE
Internal Error: cannot create temporary directory 

### ISSUE THREAD

**Issue by GeorgeGelis** [kasmtech/workspaces-issues#153]
Hello, I install Ubuntu 20.04 in Virtual Box and successfully install kasm. But, I cannot log in with the default credentials where provide me.
I run the command `sudo docker logs -f --tail 20 kasm_api` and it show the following error;

Internal Error: cannot create temporary directory , is it related with the issue ?

Thank you

**Comment by j-travis** [comment]
You are likely out of disk space.
Run the following command:

```
df
```

**Comment by j-travis** [comment]
Closed due to lack of response
