### ISSUE TITLE
I am getting this error when running install.sh: Error response from daemon: path /opt/kasm/1.10.0/conf/database/ is mounted on / but it is not a shared mount.

### ISSUE THREAD

**Issue by thomashutze** [kasmtech/workspaces-issues#154]

**Comment by mmcclaskey** [comment]
A quick search seems to indicate something unique on your host with regards to that location, /opt. 

https://forums.docker.com/t/make-mount-point-accesible-from-container-to-host-rshared-not-working/108759/2

Can you provide the output of the following two commands.

df -h

cat /etc/fstab

**Comment by thomashutze** [comment]
Filesystem      Size  Used Avail Use% Mounted on
none            7.8G  365M  7.5G   5% /mnt/wsl
drivers         466G  403G   63G  87% /usr/lib/wsl/drivers
lib             466G  403G   63G  87% /usr/lib/wsl/lib
/dev/sde        251G  2.9G  236G   2% /
none            7.8G   28K  7.8G   1% /mnt/wslg
tools           466G  403G   63G  87% /init
none            7.8G     0  7.8G   0% /dev
none            7.8G  8.0K  7.8G   1% /run
none            7.8G     0  7.8G   0% /run/lock
none            7.8G     0  7.8G   0% /run/shm
none            7.8G     0  7.8G   0% /run/user
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
none            7.8G   76K  7.8G   1% /mnt/wslg/versions.txt
none            7.8G   76K  7.8G   1% /mnt/wslg/doc
drvfs           466G  403G   63G  87% /mnt/c
drvfs           780G   88G  693G  12% /mnt/d
drvfs           2.9T  944M  2.9T   1% /mnt/e
/dev/sdd        251G  916M  238G   1% /mnt/wsl/docker-desktop-data/isocache
none            7.8G   12K  7.8G   1% /mnt/wsl/docker-desktop/shared-sockets/host-services
/dev/sdc        251G  123M  239G   1% /mnt/wsl/docker-desktop/docker-desktop-proxy
/dev/loop0      334M  334M     0 100% /mnt/wsl/docker-desktop/cli-tools
tmpfs           7.8G  484K  7.8G   1% /mnt/wsl/docker-desktop-data/tarcache/entries/docker.tar/173a93e315bf540748aab8f21f7a850c13d73d6d7d5c1cc23acaf83fcfcaf6b1/containers/services/docker/tmp
overlay         7.8G  484K  7.8G   1% /mnt/wsl/docker-desktop-data/tarcache/entries/docker.tar/173a93e315bf540748aab8f21f7a850c13d73d6d7d5c1cc23acaf83fcfcaf6b1/containers/services/docker/rootfs



LABEL=cloudimg-rootfs   /        ext4   defaults        0 1
/mnt/1GiB.swap swap swap defaults 0 0

**Comment by thomashutze** [comment]
there

**Comment by mmcclaskey** [comment]
From your output, I assume you are running a Windows Subsystem for Linux (WSL). We don't officially support that, but in our quick testing it worked for us.

Windows 10 21H1 (19043.1526)
- Installed WSL2 - rebooted
- Installed Docker Desktop  (Enable WSL 2 Windows Features Checked) - Its checked by default - rebooted
- When launching docker desktop It warned that HyperV was not installed but WSL2 was, Asked me to confirm I wanted to use WSL2 engine. I confirmed
- Launched Windows terminal into ubuntu
- Installed Kasm
- Cconnected to Kasm via localhost in browser
- Launched session

Looks like you may be having an issue related to this..
https://forums.docker.com/t/make-mount-point-accesible-from-container-to-host-rshared-not-working/108759

**Comment by j-travis** [comment]
Closing ticket. WSL2 is not an officially supported configuration, however a workaround was provided. No response for reporter
