### ISSUE TITLE
can't run teamviewer app 

### ISSUE THREAD

**Issue by m986883511** [kasmtech/workspaces-issues#155]
![image](https://user-images.githubusercontent.com/34444109/153531098-e6905e7d-56ef-49f6-9b09-dd92ac1144de.png)

my dockerfile is :

`
FROM kasmweb/desktop:1.10.0-rolling
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

COPY teamviewer_15.26.4_amd64.deb .
RUN apt install libminizip1 libxcb-icccm4 libxkbcommon-x11-0 libxcb-xkb1 libxcb-xinerama0 libxcb-image0 libxcb-randr0 libxcb-keysyms1 libxcb-render-util0 -y
RUN dpkg -i *.deb
RUN apt install teamviewer

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
`

**Comment by m986883511** [comment]
I found it need root to execute teamviewer --daemon start, but docker only have default user.

**Comment by j-travis** [comment]
https://kasmweb.com/docs/latest/how_to/running_as_root.html

**Comment by m986883511** [comment]
> 

very thank you
