### ISSUE TITLE
support storage limit?

### ISSUE THREAD

**Issue by m986883511** [kasmtech/workspaces-issues#157]
can set storage limit to every container?

**Comment by j-travis** [comment]
You should be able to specify the following in the `Docker Run Config` of your Image

```
{"storage_opt":{"size":"10g"}}
```

It requires that you are running compatible storage underneath like XFS with `pquota`. See the docker reference docs for more information:

https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container

**Comment by m986883511** [comment]
thank you
