### ISSUE TITLE
 libdl.so.2: cannot open shared libraries

### ISSUE THREAD

**Issue by mjakubowskilkr** [kasmtech/workspaces-issues#160]
I'm trying to install KASM on Debian 10 VM but I'm stuck.
My error is `/usr/bin/kasm_server.so: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory`
'locate libdl.so.2` is finding:
`/usr/lib/x86_64-linux-gnu/libdl.so.2
/usr/lib64/libdl.so.2
/usr/x86_64-linux-gnu/lib/libdl.so.2
/var/lib/docker/overlay2/0a20820cd7c516a78a50974bff4499f95475d15eae2a927e9529b62ec2f20169/diff/lib/x86_64-linux-gnu/libdl.so.2`
What can I do?

**Comment by mmcclaskey** [comment]
Can you provide exact steps to reproduce, assuming we are starting from a fresh VM with nothin but Debian 10 installed. The error is odd considering kasm_server.so is always executed inside a container. So I want to be absolutely sure of the steps used to reproduce. Thank you

**Comment by mjakubowskilkr** [comment]
I've destroyed vm and created it again. There is no problem now. So the topic is out of date.
