### ISSUE TITLE
Typo on app.kasmweb.com

### ISSUE THREAD

**Issue by thrillho93** [kasmtech/workspaces-issues#162]
There's a typo on app.kasmweb.com. Instead of Need Help, it's Need Heelp.

![Screenshot 2022-02-17 184750](https://user-images.githubusercontent.com/5497773/154596306-a099c616-32e1-4ffe-9e2d-9450aeec7a96.png)

**Comment by mmcclaskey** [comment]
Thank you, we have this on our backlog to fix with the next release.

**Comment by j-travis** [comment]
Fixed on the website. This will be available in the next release (1.11.0)
