### ISSUE TITLE
Add the Ability to Modify Images on app.kasmweb.com

### ISSUE THREAD

**Issue by thrillho93** [kasmtech/workspaces-issues#163]
Please add the ability to add / remove images on your paid hosted offering. I'd like to see kali and REMnux by default. Your enterprise offering adds these images by default. 

On the flipside I'd love to remove DOOM, and a couple of other images.

**Comment by mmcclaskey** [comment]
Hello @thrillho93, thanks for the feedback. We are working on a "Teams" product that will provide a fully customizable SaaS per team. We are targeting team sizes of 10 and up, but an exact minimum has not been reached yet. Doing something like this on the Cloud Personal SaaS where it is a single SaaS for all users would definitely require significant development. It would have impacts on scalability, security, and cost of operations that makes it unlikely at this point.
