### ISSUE TITLE
kasm server unstable (fresh install)

### ISSUE THREAD

**Issue by raymond-itsec** [kasmtech/workspaces-issues#164]
I thought I'd give KASM a try to see it's a fit for our company. But even 1 user in 1 (all-in-one) server gets "confused" after I have logged on and started 2 applications (dockers). Symptoms

- Cannot logout of the Kasm Web-UI
- Cannot change anything in the Web-UI
- Cannot start up a new app from the Workspace

There is nothing in the logs. The only option is to reboot the server (and thereby restart all dockers).

I was running on a 4GB, 2Core VM (proxmox). I tried upping it to 8GB, 4Core but that did not help. So does anyone have any suggestions as to where to look for errors ? The log files don't have anything...

**Comment by mmcclaskey** [comment]
Can you provide output of the following commands?

`df -h`
`uname -a`
`cat /etc/os-release`
`free -h`
`docker system info`

**Comment by rzwarts74** [comment]
`@kasm01:~$ df -h
Filesystem                              Size  Used Avail Use% Mounted on
udev                                    3.9G     0  3.9G   0% /dev
tmpfs                                   796M  1.5M  795M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv        54G  7.5G   44G  15% /
tmpfs                                   3.9G     0  3.9G   0% /dev/shm
tmpfs                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                   3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2                               1.5G  321M  1.1G  24% /boot
/dev/mapper/ubuntu--vg-ubuntu--lv--var   24G   22G  657M  98% /var
/dev/loop0                               56M   56M     0 100% /snap/core18/2128
/dev/loop3                               71M   71M     0 100% /snap/lxd/21029
/dev/loop2                               62M   62M     0 100% /snap/core20/1361
/dev/loop1                               56M   56M     0 100% /snap/core18/2284
/dev/loop4                               44M   44M     0 100% /snap/snapd/14978
/dev/loop5                               62M   62M     0 100% /snap/core20/1328
/dev/loop6                               68M   68M     0 100% /snap/lxd/21835
tmpfs                                   796M     0  796M   0% /run/user/1000

@kasm01:~$ uname -a
Linux kasm01 5.14.0-1024-oem #26-Ubuntu SMP Thu Feb 17 14:35:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

@kasm01:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

@kasm01:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       683Mi       5.4Gi        33Mi       1.7Gi       6.8Gi
Swap:         3.8Gi          0B       3.8Gi

@kasm01:~$ sudo docker system info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1024-oem
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.77GiB
 Name: kasm01
 ID: A7ZR:ZSUL:KH36:GJZ7:6VHE:2LM5:J3XY:USEX:7HR7:BLVY:K7XQ:K4VN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

**Comment by raymond-itsec** [comment]
```
@kasm01:~$ df -h
Filesystem                              Size  Used Avail Use% Mounted on
udev                                    3.9G     0  3.9G   0% /dev
tmpfs                                   796M  1.5M  795M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv        54G  7.5G   44G  15% /
tmpfs                                   3.9G     0  3.9G   0% /dev/shm
tmpfs                                   5.0M     0  5.0M   0% /run/lock
tmpfs                                   3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda2                               1.5G  321M  1.1G  24% /boot
/dev/mapper/ubuntu--vg-ubuntu--lv--var   24G   22G  657M  98% /var
/dev/loop0                               56M   56M     0 100% /snap/core18/2128
/dev/loop3                               71M   71M     0 100% /snap/lxd/21029
/dev/loop2                               62M   62M     0 100% /snap/core20/1361
/dev/loop1                               56M   56M     0 100% /snap/core18/2284
/dev/loop4                               44M   44M     0 100% /snap/snapd/14978
/dev/loop5                               62M   62M     0 100% /snap/core20/1328
/dev/loop6                               68M   68M     0 100% /snap/lxd/21835
tmpfs                                   796M     0  796M   0% /run/user/1000

@kasm01:~$ uname -a
Linux kasm01 5.14.0-1024-oem #26-Ubuntu SMP Thu Feb 17 14:35:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

@kasm01:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

@kasm01:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       683Mi       5.4Gi        33Mi       1.7Gi       6.8Gi
Swap:         3.8Gi          0B       3.8Gi

@kasm01:~$ sudo docker system info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 31
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.14.0-1024-oem
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.77GiB
 Name: kasm01
 ID: A7ZR:ZSUL:KH36:GJZ7:6VHE:2LM5:J3XY:USEX:7HR7:BLVY:K7XQ:K4VN
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mmcclaskey** [comment]
Based on the output of docker system, docker's data directory is Docker Root Dir: /var/lib/docker

Based on the output of df, /var is full. This is what I expected to see. Please increase the volume size of /var
/dev/mapper/ubuntu--vg-ubuntu--lv--var   24G   22G  657M  98% /var
