### ISSUE TITLE
Is it possible to disable the session timer at the bottom of your screen?

### ISSUE THREAD

**Issue by ItsNiceCraft** [kasmtech/workspaces-issues#167]
![image](https://user-images.githubusercontent.com/74358857/155194598-12991b85-e33d-454f-ad8d-44929db60724.png)
When using the default session timer (60 Minutes) this doesn't show up. If i set it manually using the Admin Dashboard/Groups, it shows this. Any way to disable it? (Hiding the timer at the bottom)

**Comment by j-travis** [comment]
Hi, can you review this existing ticket. I believe it answers your question.
https://github.com/kasmtech/workspaces-issues/issues/108

**Comment by ItsNiceCraft** [comment]
Thanks! this worked!
