### ISSUE TITLE
Multiserver stuck on Creating a secure connection...

### ISSUE THREAD

**Issue by ManuelW77** [kasmtech/workspaces-issues#169]
Hey there,

i have a kasm setup with 2 servers installed on port 8444 behind a nginx proxy.
server 1 is running as the manager, server 2 has only the agent.
the proxy is routing from 443 -> 8444

On opening a kasm workspace on in the manager on server 1 a session is created on server 2 and the container comes up.
But, the browser stuck on Creating a secure connection... and after a while is falling back to the manager.
I cant found some error msg in the logs.

**Comment by j-travis** [comment]
Hi. I suggested walking through our troubleshooting guide:
 https://kasmweb.com/docs/latest/guide/troubleshooting.html


If you place Kasm behind a reverse proxy, you need to update the Zone settings.  This is likely your issue. https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones

And also reviewing the similar tickets opened by other users:
https://github.com/kasmtech/workspaces-issues/issues/152
https://github.com/kasmtech/workspaces-issues/issues/143
https://github.com/kasmtech/workspaces-issues/issues/140
https://github.com/kasmtech/workspaces-issues/issues/110

**Comment by ManuelW77** [comment]
I'm sorry, the solving hint... always test by creating new sessions after making changes. Resuming a session may not have the changes applied
