### ISSUE TITLE
KASM Extension not working properly

### ISSUE THREAD

**Issue by DanteLogan** [kasmtech/workspaces-issues#170]
So I am not sure if it is the extension or the installations thats not functioning well, but I installed Kasm on my unarid server. I am able to open sessions via the dashboard e.g brave, chrome etc. However when I attempt to open a link using the kasm browser I am continuously getting a timeout error.

**Comment by j-travis** [comment]
Can you confirm what the issue is and post a screenshot?

You can launch a session manually via the dashboard but does the browser within the session always produce a timeout error when navigating to a website, or is it only when you open a session using the extension?

If its the latter, can you provide an example URL you are opening with the extension.

Can you also provide the following information:
Your host's browser type and version (Eg. Google Chrome 98.0.4758.102)
Your host's OS type and OS version (E.g Windows 10)

On the Kasm Workspaces server please run the following and provide the output

```
cat /etc/os-release
uname -a
sudo docker system info
sudo docker ps
df
```

**Comment by DanteLogan** [comment]
I am running Windows 10 with latest update, my browser is brave [Version 1.35.103 Chromium: 98.0.4758.102 (Official Build) (64-bit)](https://brave.com/latest/). And yes I only get timeout error when launching a link using the extension. The screenshots attached show a session opened via the dashboard and also me attempting to open a link using the extension, note that i did set the correct IP address for the server in the extension settings. 

The following is the output of the command above:

cfett@kasm:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
cfett@kasm:~$ uname -a
Linux kasm 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
cfett@kasm:~$ sudo docker system info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 30
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-100-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4.292GiB
 Name: kasm
 ID: YTVA:J6I5:NIHJ:2N5E:DFRG:3CWT:Z7LV:KQTQ:WW5F:7BSB:VWFC:RZ55
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
cfett@kasm:~$ sudo docker ps
CONTAINER ID   IMAGE                    COMMAND                  CREATED      STATUS                 PORTS                                           NAMES
5cf438ee6ae5   kasmweb/nginx:latest     "/docker-entrypoint.…"   2 days ago   Up 8 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
1935a7e5bd81   kasmweb/share:1.10.0     "/bin/sh -c '/usr/bi…"   2 days ago   Up 8 hours             8182/tcp                                        kasm_share
663f64090c22   kasmweb/agent:1.10.0     "/bin/sh -c '/usr/bi…"   2 days ago   Up 8 hours             4444/tcp                                        kasm_agent
f7440e112799   redis:5-alpine           "docker-entrypoint.s…"   2 days ago   Up 8 hours             6379/tcp                                        kasm_redis
820481b7114d   kasmweb/api:1.10.0       "/bin/sh -c '/usr/bi…"   2 days ago   Up 8 hours (healthy)   8080/tcp                                        kasm_api
e5f92d187270   kasmweb/manager:1.10.0   "/bin/sh -c '/usr/bi…"   2 days ago   Up 8 hours             8181/tcp                                        kasm_manager
0c4e91276d01   postgres:12-alpine       "docker-entrypoint.s…"   2 days ago   Up 8 hours             5432/tcp                                        kasm_db
cfett@kasm:~$ df
Filesystem                        1K-blocks     Used Available Use% Mounted on
udev                                3253800        0   3253800   0% /dev
tmpfs                                603744     1600    602144   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  30058452 25562856   2945672  90% /
tmpfs                               2250200        0   2250200   0% /dev/shm
tmpfs                                  5120        0      5120   0% /run/lock
tmpfs                               2250200        0   2250200   0% /sys/fs/cgroup
/dev/vda2                            999320   111388    819120  12% /boot
/dev/vda1                            523248     5356    517892   2% /boot/efi
/dev/loop0                            56960    56960         0 100% /snap/core18/2284
/dev/loop4                            63488    63488         0 100% /snap/core20/1361
/dev/loop1                            68864    68864         0 100% /snap/lxd/21835
/dev/loop3                            56832    56832         0 100% /snap/core18/2128
/dev/loop2                            44672    44672         0 100% /snap/snapd/14978
/dev/loop6                            69632    69632         0 100% /snap/lxd/22526
tmpfs                                450040        0    450040   0% /run/user/1000
![c4](https://user-images.githubusercontent.com/97335578/155807742-b191ac50-3a78-4f3d-a6c5-581b3c3af82e.PNG)
![c5](https://user-images.githubusercontent.com/97335578/155807745-10d360b7-2194-45e0-8557-b5f8c959e61e.PNG)

**Comment by j-travis** [comment]
In your extension options can you ensure you have HTTPS defined in the URL and not http or missing

![image](https://user-images.githubusercontent.com/48762190/155809014-4e1a90ee-12c6-4427-ae82-ca44a99d03d6.png)

**Comment by DanteLogan** [comment]
Well i just rralized im an idiot and put 192.169.0.20 instead of 192.168.0.20. So it had the wrong ip address. Its working now my apologies for wasting your time, but thank you very much for helping me understand what i did wrong.

**Comment by DanteLogan** [comment]
However some things are loading too well now.

**Comment by DanteLogan** [comment]
![Uploading c7.PNG…]()

**Comment by DanteLogan** [comment]
![c7](https://user-images.githubusercontent.com/97335578/155812240-8a357fcd-ec78-4550-8f88-092ecaee3831.PNG)
