### ISSUE TITLE
How to watch an active session as admin?

### ISSUE THREAD

**Issue by absane** [kasmtech/workspaces-issues#171]
I have a specific use case to provide images to anonymous users. I want to watch active sessions without the anonymous users being cognizant that active monitoring is occurring. As an admin, I can see that sessions are open (via the Sessions window). So, if I choose to click "View," I will see a URL like this:

    https://[KasmDomain]/#/kasm/09659f

However, if I click on it, Kasm will throw this error:

![image](https://user-images.githubusercontent.com/4988545/155770201-34b330dc-862b-4032-9a5e-696fea82b0ff.png)

Is what I want available within Kasm already? If not, how could I go about implementing this?

**Comment by mmcclaskey** [comment]
Hello, Kasm Workspaces does not currently support this out of the box. However, all the wiring in the backend is there to support such a feature. This is closely related to session recording, which is also in our backlog. It is not currently on our schedule to implement in the next release. Getting those features into a future release will depend on demand from our customers and the community.

**Comment by j-travis** [comment]
It sounds like what you are looking for is shadowing.
Unfortunately that's not an existing feature.

We do have an overt session sharing feature: https://kasmweb.com/docs/latest/guide/session_sharing.html

**Comment by absane** [comment]
Thank you for looking into this. I did eventually find a way to do it through the API (`/api/request_cast`). So, I made a Bash script to generate the URLs that I can share, and that allows me to "hop on" to the session without notifying the user. So yes, it is possible. But, I hope in the future it'll be much easier to accomplish ;)

**Comment by j-travis** [comment]
Hello,
in as much detail as possible, can you explain your use-case. We would like to better understand the need for this feature. Both the experience from the end-user perspective and the admin
