### ISSUE TITLE
 Kodachi Linux Image request

### ISSUE THREAD

**Issue by jdpadro** [kasmtech/workspaces-issues#172]
I would like to ask if it is possible to create a KASMWeb Image of Kodachi Linux. This is a secure OS that provides for privacy, anonymity and non atribution. An ISO image is available on their site https://www.digi77.com/linux-kodachi/

Thank you
Jesus

**Comment by j-travis** [comment]
Thank you for the suggestion. We will gauge community feedback for this and other image requests.

It does look like its based on Ubuntu 18, so you should be able to add the customizations of this distro to a custom image.

It doesn't appear that this project offers docker image, or makes the source and instructions readily available. The author suggests you go pull the customizations out of the iso.  Thats likely a non-starter.
