### ISSUE TITLE
Unable to lauch workspace application after change the user:root

### ISSUE THREAD

**Issue by cevinov** [kasmtech/workspaces-issues#176]
Hello sir,

Could you help me troubleshoot this issue. I can't launch the app on my kasm workspace after changing the Docker Run Config Override.

![kasm error](https://user-images.githubusercontent.com/94840989/156916759-34f7d143-27bc-4038-9081-fe59a7f07385.png)

Video problem:
https://screenrec.com/share/HfbXM3Gmev

Thanks.

**Comment by j-travis** [comment]
It looks like you are double clicking the items in the launcher. That is not supported.

Single click them. Another dialogue will pop up asking you to launch

**Comment by cevinov** [comment]
> It looks like you are double clicking the items in the launcher. That is not supported.
> 
> Single click them. Another dialogue will pop up asking you to launch

Thanks sir for the replies. But i got some other issue :
https://screenrec.com/share/DkxMlnWBw4

I can't access the kasm workspaces sir. After i join the network on portainer. Need some guidance sir, thanks.
![image](https://user-images.githubusercontent.com/94840989/157105999-784d5278-f392-4214-8307-fa01819e8246.png)

**Comment by cevinov** [comment]
> It looks like you are double clicking the items in the launcher. That is not supported.
> 
> Single click them. Another dialogue will pop up asking you to launch

thanks, it's already solved
