### ISSUE TITLE
Can't install Kasm on RHEL

### ISSUE THREAD

**Issue by shahar2806** [kasmtech/workspaces-issues#177]
Hi
trying to install Kasm workspace in Rhel 7 and getting this error
![image](https://user-images.githubusercontent.com/50527865/157010679-05d1da51-152e-490b-af85-fde994f80b78.png)
Checking if docker and docker-compose are installed.
Docker is installed
20.10.12 is a supported version of docker.
Docker Compose is not installed.
Installation Not Supported for this Operating System. Exiting

Docker-compose is working fine :)

kindly help
Shahar

**Comment by j-travis** [comment]
Hi,
Yes, our installer doesnt directly support running on RHEL. You can see the supported Operating Systems here:
https://kasmweb.com/docs/latest/install/system_requirements.html#operating-system

However, if you can get the dependencies installed before hand our installer will continue. See here for example:
https://kasmweb.com/docs/latest/how_to/other_operating_systems.html
