### ISSUE TITLE
Cant login to Kasm Workspaces anymore

### ISSUE THREAD

**Issue by naziris** [kasmtech/workspaces-issues#179]
I had a quite stable system a few days ago. I haven't change anything lately, and just to be sure I restored my vm to a month ago which I'm 100% sure no changes were made back then.

The issue Im facing is, Im able to login, I see the dashboard for a couple of seconds and then im looping back to the login screen.
Under client_api_server.log I see the following:

2022-03-13 10:03:33,534 [INFO] client_api_server: Successful authentication attempt for user: (admin@kasm.local)
2022-03-13 10:03:33,626 [WARNING] client_api_server: Invalid token (abd4baaa-df8a-****-****-3581718****) for user (admin@kasm.local) at (192.168.X.YYY) for request (license_status)
2022-03-13 10:03:33,631 [WARNING] client_api_server: Invalid token (abd4baaa-df8a-****-****-3581718****) for user (admin@kasm.local) at (192.168.X.YYY) for request (get_client_settings)
2022-03-13 10:03:33,833 [WARNING] client_api_server: Authenticated request missing required username or token values from (192.168.X.YYY)

I tried restarting services, login from a different machine, still the same.

**Comment by j-travis** [comment]
Hello,
Can you open the developer console in your browser and see if any errors are reported?
The way it works is when you authenticate, you are given back a session token that is placed in local storage within your browser, then sent for all subsequent requests. If the server sees the token is invalid it will report that message and log you out.

Perhaps something is happening in your browser where those session tokens are not properly being updated in local storage.

You can try repeating the test with and without incognito mode, or with a different browser completely. Perhaps another browser extensions is also interfering so you may try disabling those too.

You can also try clearing the cookies and site data in your browser to see if that helps

**Comment by naziris** [comment]
I've tried on a new browser, and even on a fresh vm. still same issue.

The console output on edge is:
`Cannot parse user info. No user info stored
m @ Constants.js:33
./src/constants/Constants.js @ Constants.js:68
m @ bootstrap 4fb3041fc0ff22073775:678
n @ bootstrap 4fb3041fc0ff22073775:88
./src/components/Header/Header.js @ Header.js:19
m @ bootstrap 4fb3041fc0ff22073775:678
n @ bootstrap 4fb3041fc0ff22073775:88
./src/containers/Full/Full.js @ Full.js:4
m @ bootstrap 4fb3041fc0ff22073775:678
n @ bootstrap 4fb3041fc0ff22073775:88
./src/index.js @ index.js:25
m @ bootstrap 4fb3041fc0ff22073775:678
n @ bootstrap 4fb3041fc0ff22073775:88
0 @ index.bundle.js:240302
m @ bootstrap 4fb3041fc0ff22073775:678
(anonymous) @ bootstrap 4fb3041fc0ff22073775:724
(anonymous) @ bootstrap 4fb3041fc0ff22073775:724`

**Comment by j-travis** [comment]
I see,
Would you mind following this guide to produce detailed debugging output . Its an export of the console log and a HAR data file with the detailed network traffic.

https://kasmweb.com/docs/latest/how_to/client_debugging.html

Basically, configure the logging etc, conduct a few login attempts where you get kicked out etc, then save off the data.

Then upload the files to our support portal.
https://kasmweb.com/support.html

Do not post the files here. Change your password after you submit the files.

**Comment by j-travis** [comment]
Can you also please run the following command on your Kasm server and report them here.

```
cat /etc/os-release
sudo docker ps | grep kasm
df
```

**Comment by naziris** [comment]
I submitted the files. Thanks for your time and effort Travis. 

```
root@athena:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@athena:~# sudo docker ps | grep kasm
d04b11af1d96   kasmweb/nginx:latest     "/docker-entrypoint.…"   7 weeks ago   Up Less than a second             80/tcp, 0.0.0.0:443->443/tcp   kasm_proxy
b04fa2599a8c   kasmweb/agent:1.10.0     "/bin/sh -c '/usr/bi…"   7 weeks ago   Up Less than a second             4444/tcp                       kasm_agent
91b7a1fbfaf7   kasmweb/share:1.10.0     "/bin/sh -c '/usr/bi…"   7 weeks ago   Up Less than a second             8182/tcp                       kasm_share
d683f061eb0c   kasmweb/manager:1.10.0   "/bin/sh -c '/usr/bi…"   7 weeks ago   Up Less than a second             8181/tcp                       kasm_manager
463bc550ccff   redis:5-alpine           "docker-entrypoint.s…"   7 weeks ago   Up Less than a second             6379/tcp                       kasm_redis
84fbbdc704a9   postgres:12-alpine       "docker-entrypoint.s…"   7 weeks ago   Up Less than a second             5432/tcp                       kasm_db
ff319f90aea5   kasmweb/api:1.10.0       "/bin/sh -c '/usr/bi…"   7 weeks ago   Up Less than a second (healthy)   8080/tcp                       kasm_api
root@athena:~# df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             3025360        0   3025360   0% /dev
tmpfs             608344     1180    607164   1% /run
/dev/sda1       60624740 36434068  21078636  64% /
tmpfs            3041700        0   3041700   0% /dev/shm
tmpfs               5120        0      5120   0% /run/lock
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/f0fc6a1fa658ac4416796bbd27806a10e4c0aa896d282f750ea716bbc04dc053/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/483e3e2e91d0a791710216d7b994c33542b84a529567d931459f8b63642be495/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/f57f0c16ebe17aaa8415f2eed3120a98c5af96006fddd070e37eae491bfa679d/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/181db6fb5c54d3a696ce77ecf9c529745a4fb4ea179f9f2c278c700e3bed378d/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/d4412522170be37bba62cd7d2e36cb03752acca3eeeff6cb47c959f31ff260dc/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/5a61b2ff695932544a883151a8fcc97c6f63d335592273c496d34074e163fc0b/merged
overlay         60624740 36434068  21078636  64% /var/lib/docker/overlay2/73dbfe2af913a8067d4c3f59e1599a851d69645a2a25f9e74b52ea096906e2d0/merged
tmpfs             608340        0    608340   0% /run/user/0
root@athena:~#

```

**Comment by j-travis** [comment]
Thanks for the info,
From the client end, things look in order - but indeed you are getting rejected by the server. 

From the output above it looks like your kasm containers might be constantly restarting:

```
Up Less than a second
```

Can you check the logs of these containers to see if there are reporting any failure? Perhaps there is an issue with the VM Host - e.g disk is full?

**Comment by j-travis** [comment]
closed due to lack of response
