### ISSUE TITLE
Kasm workspace installation tweaks

### ISSUE THREAD

**Issue by thelamer** [kasmtech/workspaces-issues#180]
I see a couple sleeps and no dependencies for postgres being ready in your compose setup. This borks out installs and creates race conditions on workspace setups.

I cannot find the location of any of this code on Github, but here are the modifications I made to the workspace installer scripts to get through an install in a VM: 

Install compose at current release in `install_dependencies.sh`:
```
function install_docker_compose (){
   echo "Installing Docker Compose"
   mkdir -p /usr/local/lib/docker/cli-plugins
   COMPOSE_RELEASE=$(curl -sX GET "https://api.github.com/repos/docker/compose/releases/latest" \
   | awk '/tag_name/{print $4;exit}' FS='[""]');
   curl -L https://github.com/docker/compose/releases/download/${COMPOSE_RELEASE}/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/lib/docker/cli-plugins/docker-compose
   chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
```

add `--wait` to the following compose commands and pull out the sleeps: (`docker compose up -d --wait`)
bin/start: line 17
bin/utils/db_restore: line 100
bin/utils/db_init: line 89

Add a simple healthcheck to the following compose files(docker-compose-all.yaml docker-compose-db-redis.yaml docker-compose-db.yaml)  for the `db:` entry:
```
    healthcheck:
      test: "pg_isready --username=kasmapp && cat /proc/1/cmdline | grep -q '^postgres'"
      timeout: 10s
      retries: 20
```

Should fix some installation woes on systems with spinning disks.

**Comment by j-travis** [comment]
Thank you, this is great feedback. 
These scripts are managed internally, so we will have someone take a look and apply the fixes as appropriate.

**Comment by thelamer** [comment]
Also note the `--wait` option is new in the compose v2 go plugin. The old python compose has had this functionality for years with the service_healthy depends on and can be directly written into compose files.
