### ISSUE TITLE
vnc.html 500 errors on digitalocean

### ISSUE THREAD

**Issue by yassine-cc** [kasmtech/workspaces-issues#181]
I've installed kasm on a digitalocean droplet through their 'oneclick app install', (2vcpu, 4gb ram)
But i can't access any workspaces when i launch them because of nginx 500 errors on the vnc.html request, it retries few time to connect then just redirects back to the dashboard.

What i've tried so far:
- Disabled any adblocking/content altering extensions
- Tried multiple browsers

**Comment by Ian-Kasmweb** [comment]
Hi Yassine,

Do you have any firewall rules applied to the droplet through the digitalocean console?
Did you do any extra configuration on the system, or change any settings in the Kasm Admin UI?

**Comment by yassine-cc** [comment]
@Ian-Kasmweb sorry for the late response, no, i haven't changed anything on the droplet, i've also tried different things:
- Installing from the oneclick app install that digitalocean provides with no other modification of the system
- Installing by following the instructions on the website on a fresh ubuntu 18 droplet
- Installing by following the instructions on the website on a fresh ubuntu 20 droplet

**Comment by Ian-Kasmweb** [comment]
Yassine,

What happens when you try to curl the URL used to connect to the kasm agent? 
IE:  If connect to kasm through your browser with "kasm.yassine.com" then run `curl https://kasm.yassine.com`

**Comment by yassine-cc** [comment]
Same as on the browser, i'm getting the nginx 500 error

**Comment by Ian-Kasmweb** [comment]
Could you please try running the curl command to the address of your deployment from the server you installed it on?
So `curl https://kasm.yassine.com` from the Kasm server? Then post the output of the command here.
