### ISSUE TITLE
Archlinux OS enhancement

### ISSUE THREAD

**Issue by octave21** [kasmtech/workspaces-issues#182]
In order to run on Archlinux I only need to modify the ~/kasm_release/install.sh script with this line : 
ARCH="amd64" 

Is it possible to add Archlinux in your supported OS list ?

**Comment by mmcclaskey** [comment]
Hello, we are tracking this issue and hoping to get it in soon. Thank you
[https://github.com/kasmtech/workspaces-issues/issues/98](https://github.com/kasmtech/workspaces-issues/issues/98)
