### ISSUE TITLE
get_kasm_screenshot api request is not working

### ISSUE THREAD

**Issue by razapoonja** [kasmtech/workspaces-issues#187]
I'm following this documentation https://kasmweb.com/docs/latest/api/developer_api.html#screenshot but its not working.

I tried calling api with GET request also but it is returning 500 internal error

**Comment by mmcclaskey** [comment]
@razapoonja , per the Curl you sent via chat, you are missing the user_id field. The documentation is correct, it is a POST. I did get the same error when not providing the user_id. I confirmed it does work correctly when passing the user_id.

**Comment by razapoonja** [comment]
@mmcclaskey I have send you 2 curl requests the first one was missing user_id the second one has it but both are giving same results.

api_key
api_key_secret
kasm_id
user_id
width
height

I'm sending all of these parameters

**Comment by mmcclaskey** [comment]
Can you provide your curl with the api key and IP address sanitized?

**Comment by razapoonja** [comment]
Here's the curl command

`
curl https://**********/api/public/get_kasm_screenshot -X POST -H 'Content-Type: application/json' -k -d '{ "api_key": "gDwep4rd6Vxc", "api_key_secret": "secret", "kasm_id": "cf323132d2e94b2185834a4c6dda44f0", "user_id": "c29b2fff475b4210947d76e0d429b950", "width": 1000 }' -o image.jpg`

**Comment by mmcclaskey** [comment]
I've tested this and it works for me. Are you able to share the server side logs? You can either go to the logging tab in the UI or go to the server and run the following right before you run the curl...

`sudo docker logs --tail 10 -f kasm_api`
