### ISSUE TITLE
Firefox Image - Remove titlebar not working

### ISSUE THREAD

**Issue by jeditec** [kasmtech/workspaces-issues#191]
To improve the user experience hidding the title bar from the browser increases the viewable area and provide a cleaner browser image. 

As of today to manually execute this, we need to right click the title bar, go to customize toolbar and uncheck titlebar. This works OK on the desktop Image but on the standalone firefox image is NOT working, also as a nice to have feature it would be great to have the hide titlebar enabled by default to always have as much as posible viewable area in the browser.

**Comment by j-travis** [comment]
Thanks for the feedback.
If you find a way to change enforce this via a firefox configuration setting that can be applied at build time , please let us know

**Comment by jingerpie** [comment]
With Firefox image, you can right click on the title bar, and select fullscreen to have the best experience. How do we have this enable by default?
