### ISSUE TITLE
Slack workspace image contains version of app that is no longer supported

### ISSUE THREAD

**Issue by alexatfindesign** [kasmtech/workspaces-issues#192]
I've been trying to log into the Slack app in the Slack workspace and upon putting in the Slack confirmation code during the login process, I am presented with a prompt to update the Slack app.
I was able to log in with my Slack account in the Slack workspace around April 6 2022 before it stopped working.
I've updated the Slack Docker image with the most recently published image (kasmweb/slack:1.10.0-rolling published on April 10, 2022) and the issue persists.
I can log into Slack in the Chrome workspace, but the time zone is incorrect (defaulted to UTC + 00:00) and changing the time zone preferences in Slack does not seem to work.

**Comment by j-travis** [comment]
Hi,
It looks like there is a compatibility issue with slack running on our existing 1.10 images that are based on ubuntu 18.04.
To work around this for now, you can use our pre-release images that are based on ubuntu 20.04 which will be the default in the next 1.11.0 release.

```
kasmweb/slack:develop
```

Please note, this is a development image and will change over time and may or may not remain compatible with 1.10 in the long term.

As for timezone, you can configure the `TZ` environment variable in the `Docker Run Config` of the image.
```
 {"environment":{"TZ":"America/New_York"}}
 ```
 You could either define this on the image, or as a Group Setting so it applies to all sessions you create.
 
 You can learn more about group settings here:
 
 - https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s
 - https://kasmweb.com/docs/latest/guide/groups/group_settings.html?highlight=run_config

**Comment by jcg31587** [comment]
"Develop" did not work for me. 
Please note that the slack-desktop package that you are using is OLD! 
Version on the container: 4.3
Version on Slack website: 4.25
Can someone please rebuild the image as it is non-functional. 
*Also, the Slack app on the Ubuntu Desktop image is also out of date.

**Comment by CanisHelix** [comment]
```
# slack latest does not run with --no-sandbox, so we have to hard code to an older version.
version=4.12.2
```

You even state in your install script you have to use an older version. The fact is, Slack themselves now forbid such older versions. A fix is needed for to bring up a newer version.

**Comment by j-travis** [comment]
Unfortunately we've had to remove slack. There is a problem in the way they use electron that won't allow it to run properly in containers without opening up too many permissions. We reported this to them several months ago, but so far no traction has been made resolving the issue.

So, for now, the slack image and slack being installed in the desktop images will be removed for the next release.
If you want to build an image yourself with the latest version of slack you'll need to run with seccomp unconfined.

You can use this configuration in the Docker Run Config setting  in the Image within Workspaces
```
{"security_opt":["seccomp=unconfined"]}
```

**Comment by CanisHelix** [comment]
It's shame, but at least we have a potential workaround if required. Will try it and confirm.
