### ISSUE TITLE
Rootkit found on Kali image

### ISSUE THREAD

**Issue by AdamE87** [kasmtech/workspaces-issues#196]
Unsure whether Kasm requires this to operate but on a chkrootkit command we see a potentially infected file under `linux.xor.ddos`

![image](https://user-images.githubusercontent.com/3043949/165531105-ae857177-2596-4abb-bd5e-13e2e9eadc2b.png)

**Comment by j-travis** [comment]
All that `chkrootkit` script is doing for this signature is looking for executable files in `/tmp` . 
We have several services that run inside our containers that will extract themselves and run from `/tmp` - for example our microphone passthrough service.

That is what this script is flagging on. 

If you change your group settings to disable audio, microphone passthrough, and uploads, then recreate a session, the script wont report the signature as we wont start those services if they are disabled.


Thanks for reporting, but I believe this is a false positive.

```
   ## Linux/Xor.DDoS 
   if [ "${QUIET}" != "t" ]; then
      printn "Searching for Linux.Xor.DDoS ... "; fi
   files="`${find} ${ROOTDIR}tmp/ ${findargs} -executable -type f 2> /dev/null`"
   if [ "${files}" = "" ]; then
      files="`${ls} ${ROOTDIR}etc/cron.hourly/udev.sh 2> /dev/null`"
      files="$files $($ls ${ROOTDIR}etc/cron.hourly/gcc.sh 2> /dev/null)"
      if [ "${files}" = " " ]; then
         if [ "${QUIET}" != "t" ]; then echo "nothing found"; fi
      else
         echo "INFECTED: Possible Malicious Linux.Xor.DDoS installed"
      fi
   else
     echo "INFECTED: Possible Malicious Linux.Xor.DDoS installed"
     echo "${files}"
   fi
```

**Comment by AdamE87** [comment]
No problem, thanks for helping me understand. I'll close the issue.
