### ISSUE TITLE
Sessions hang on reverse proxy

### ISSUE THREAD

**Issue by DayneD89** [kasmtech/workspaces-issues#198]
I'm using a docker nginx as a reverse proxy. As kasm doesn't allow to run on a path I'm using multiple server blocks. Here is the relevant part:
server {
listen 443 ssl;
server_name xx.yy.com;
ssl_certificate /etc/nginx/ssl/cert.crt;
ssl_certificate_key /etc/nginx/ssl/cert.key;

location / {
proxy_set_header        Upgrade $http_upgrade;
proxy_set_header        Connection "upgrade";

proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;

proxy_http_version      1.1;
proxy_read_timeout      1800s;
proxy_send_timeout      1800s;
proxy_connect_timeout   1800s;
proxy_buffering         off;

client_max_body_size 10M;
proxy_pass https://172.17.0.1:8443;
}
}

With this I can access the webui either on https://xx.yy.com, https://localhost:443 (through nginx) or https://localhost:8443 (direct)

I have one deployment zone with one agent. If I leave the zone settings as default then I can create and access sessions from https://localhost:8443 but nowhere else. So far so good. 

If I change the proxy port to 443 for the zone then this swaps around, so that https://localhost:443 works now (and interestingly if I create a session from here I can resume it from xx.yy.com, though I cant make a session from there, it hangs on Creating a secure connection., but the opposite isn't true)

Finally, I change the Upstream Auth Address of the zone to xx.yy.com (or the ip address) and loose the ability to launch or connect to sessions at all.

I do see this error in my browsers console: https://xx.yy.com/desktop/9adf8871-a31d-420c-b37d-77cff812a5e9/vnc/vnc.html?video_quality=2&enable_webp=false&idle_disconnect=20&password=&autoconnect=1&path=desktop/9adf8871-a31d-420c-b37d-77cff812a5e9/vnc/websockify&cursor=true&resize=remote&clipboard_up=false&clipboard_down=false&clipboard_seamless=false&toggle_control_panel=false
[HTTP/2 500 Internal Server Error 13ms]

Any help will be greatly appreciated as I'm lost.

**Comment by j-travis** [comment]
Hi,
You'll have to choose one way to access the system. I'll assume you will want to use https://xx.yy.com:443 

In the zone settings set Proxy Port to 443 and upstream auth address to the local IP of your kasm server.

Create a new session and test access (do not resume existing sessions.)

If it continues to hang, try the troubleshooting guide, in particular the **Name Resolution and General Connectivity** section:
https://kasmweb.com/docs/latest/guide/troubleshooting.html#server-side-issues

**Comment by DayneD89** [comment]
Hi, thanks for helping :)
And yes, thats how I'm trying to access it, and 443 and the local IP are set in the zone. Creating a new session does not work.

I did find an issue with my certificate (I didn't have the issuers certificate included), but fixing this still hasn't solved my issue. 

sudo docker exec -it kasm_proxy wget https://<your.kasm.server>:443
sudo docker exec -it kasm_proxy wget https://<your.kasm.server.ip>:443
Both produce an index.html inside the kasm_proxy container.

**Comment by j-travis** [comment]
This was addressed in 1.11.0
If the Proxy Port is `0`, then we will utilize whatever port you are currently using to connect to the UI. This allows you to access the service internally via `443` and externally via `8443` for example.

Ref: https://kasmweb.com/docs/latest/guide/zones/deployment_zones.html?highlight=proxy%20port#id3
