### ISSUE TITLE
Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory [214:243:0504/041021.141643:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

### ISSUE THREAD

**Issue by EzrealerQAQ** [kasmtech/workspaces-issues#199]
when I execute "docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password  kasmweb/chrome:1.10.0-rolling"
I get some errors,but container seem normal,do i need to process there errors?

errors:
Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

**Comment by j-travis** [comment]
Hi @EzrealerQAQ , you should be able to safely ignore these items emitted by Chrome
