### ISSUE TITLE
Pass arguments with first_launch

### ISSUE THREAD

**Issue by OscarCy** [kasmtech/workspaces-issues#200]
I have this JSON Docker Exec Config:
`{"first_launch":{"cmd":"bash -c /home/kasm-user/Documents/run.sh ArgA ArgB ArgC ArgD"}}`

Unfortunately, none of those arguments are passed on that script on launch. Is there any specific way to achieve that?

**Comment by j-travis** [comment]
Hi,
In our testing, we find it best to wrap the command (and args) passed to bash in single quotes. Its hard to see but thats suggested in the docs. (adding extra space so its easier to see)
`{"first_launch":{"cmd":"bash -c  '   /home/kasm-user/Documents/run.sh ArgA ArgB ArgC ArgD  '   "}}`


Ref: https://kasmweb.com/docs/latest/guide/custom_images.html#docker-exec-config

**Comment by OscarCy** [comment]
Thank you j-travis! The solution was to use environment variables in the Docker Run config override, and use $VAR in my run.sh script.
