### ISSUE TITLE
kali persistant profile - error

### ISSUE THREAD

**Issue by MrAshRhodes** [kasmtech/workspaces-issues#201]
Howdy, up until about an hour ago Kali was working great.

This is not the pulseaudio error as i have that disabled.

Im using a custom docker image using the kasm kali image.

When i now go to launch this i get an error saying the following

> Create Kasm
> An unexpected error occurred.Please contact an admin.

After this i manually ran 
docker system prune -a 

Then rebuilt the image.
Rebooted the server.

Without a persistant profile Kali loads as expected.

Below are the error logs i see when i try to launch... I see it says please wait... but even after waiting Persistant profile still doesnt work.

`Error after container creation Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 953, in raise_for_status requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad/exec During handling of the above exception, another exception occurred: Traceback (most recent call last): File "ProvisionAgent/provision.py", line 564, in provision File "docker/models/containers.py", line 196, in exec_run File "docker/utils/decorators.py", line 19, in wrapped File "docker/api/exec_api.py", line 80, in exec_create File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad/exec: Conflict ("Container c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad is restarting, wait until the container is running")`

`An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(18429f72-cb28-4fba-9c6a-a93fec0b3fbe) : (Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 953, in raise_for_status requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad/exec During handling of the above exception, another exception occurred: Traceback (most recent call last): File "ProvisionAgent/__init__.py", line 319, in post File "ProvisionAgent/provision.py", line 564, in provision File "docker/models/containers.py", line 196, in exec_run File "docker/utils/decorators.py", line 19, in wrapped File "docker/api/exec_api.py", line 80, in exec_create File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad/exec: Conflict ("Container c6a38d3c98e5f716a61bab44b81f38eccd7c6a9339dc37971ef89846118268ad is restarting, wait until the container is running") )`

**Comment by jingerpie** [comment]
It looks like your firewall is blocking Python script. You might want to refer to this issue https://github.com/kasmtech/workspaces-issues/issues/195 if you are also using Cloudflare

**Comment by MrAshRhodes** [comment]
Disabled ufw on host, it's a single server installation
error still persists, 

I am not using cloudflare or any WAF.

ran the commands from linked issue.

`docker exec -it kasm_proxy wget https://$hostname:443/agent/api/v1/hello/`

I have the same in my logs as posted in #195 "method not allowed" and "405 get" in agent logs.

Ubuntu image works with persistent profile and the kali image works if persistent profile is disabled.

**Comment by jingerpie** [comment]
There are many firewall for my deployment:
1. Sever Firewall, check this from your sever provider 
2. System Firewall, iptables, ufw
3. DNS Provider, such as Cloudflare

**Comment by MrAshRhodes** [comment]
Checking configs... nothing has changed on the server at all. 
doing a Reset on the persistent profile and its all working again.

**Comment by j-travis** [comment]
Hello,
Please try the following

1. Stop the Kasm services

```
sudo /opt/kasm/bin/stop
```

2. Edit the agent config file (`/opt/kasm/current/conf/app/agent.app.config.yaml`). Change the setting `remove_failed_containers` to false

```
remove_failed_containers: false
```

3. Start the Kasm services

```
sudo /opt/kasm/bin/start
```

4. Run the new session. The agent won't automatically remove the failed container so capture the logs and review for errors. You can paste them here too if you'd like us to review. If you do paste the entire thing

```
# list the running containers and find the new one for you kali session
sudo docker ps

# Capture the logs
sudo docker logs <container id>

```

**Comment by jrparks** [comment]
The profile is messed up in the database. I configured a new profile folder and was able to use it again with profiles.
