### ISSUE TITLE
Custom Chrome Image

### ISSUE THREAD

**Issue by Masonjar13** [kasmtech/workspaces-issues#205]
I've been working on creating a demo for a table I'm hosting at a convention, using Kasm installed on Proxmox. It's 90% set up, I just need to specify bookmarks for the Chrome image. I used [this guide](https://kasmweb.com/docs/latest/how_to/chrome_managed_policies.html) with [this dockerfile](https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome), and built using [the guide](https://kasmweb.com/docs/latest/how_to/building_images.html). I didn't change the bookmarks, just used the default json on the page to test with. I added `COPY ./bookmarks.json /etc/opt/chrome/policies/managed/bookmarks.json` the line just before "End Customizations", as instructed. I then did `docker build -t chrome:product -f dockerfile-kasm-chrome .` On the "Get" line, "read" reported `i/o error`.

I added it as an image in the dashboard, but it won't pull. It keeps posting this error to the log:
```
Failed to pull image (chrome:product) : 404 Client Error for http+docker://localhost/v1.41/images/create?tag=product&fromImage=chrome: Not Found ("pull access denied for chrome, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```
How can I get kasm to see the image? If it's a permission issue, what files am I giving permissions to?

Thanks in advance!

**Comment by mmcclaskey** [comment]
Can you provide the full output, to include the command you ran to build. The error does not seem to make sense given the command you provided, so I'm hoping a full dump starting at the build command will provide more context. Also the dockerfile-kasm-chrome.

I tried your docker build command and did not have an issue.

**Comment by Masonjar13** [comment]
Build output
```
root@Kasm:/tmp# docker build -t chrome:codesters -f dockerfile-kasm-chrome .
Sending build context to Docker daemon  36.89MB
Step 1/25 : ARG BASE_TAG="develop"
Step 2/25 : ARG BASE_IMAGE="core-ubuntu-focal"
Step 3/25 : FROM kasmweb/$BASE_IMAGE:$BASE_TAG
develop: Pulling from kasmweb/core-ubuntu-focal
Get "https://registry-1.docker.io/v2/kasmweb/core-ubuntu-focal/manifests/sha256:20998281bda04dac6e06d728e2093c83b4c35d9330b88c52c7ba029d08e44a97": dial tcp: lookup registry-1.docker.io on 192.168.0.1:53: read udp 192.168.0.121:57507->192.168.0.1:53: i/o timeout
```
Build file
```
ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########


# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel

# Setup the custom startup script that will be invoked when the container starts
#ENV LAUNCH_URL  http://kasmweb.com

COPY ./src/ubuntu/install/chrome/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh

# Install Custom Certificate Authority
# COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
# RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/

ENV KASM_RESTRICTED_FILE_CHOOSER=1
COPY ./src/ubuntu/install/gtk/ $INST_SCRIPTS/gtk/
RUN bash $INST_SCRIPTS/gtk/install_restricted_file_chooser.sh

COPY ./bookmarks.json /etc/opt/chrome/policies/managed/bookmarks.json

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
```
I also disabled pruning, and the json and dockerfile are in the same folder.

**Comment by mmcclaskey** [comment]
That is a different error message than originally reported. This appears to be a DNS timeout on resolving registry-1.docker.io as it tries to pull the base image. That would be an issue with your environment.

**Comment by Masonjar13** [comment]
The original error posted is what Kasm reports in the logs.

I don't have any custom DNS setup on this network, so I'm unclear why it wouldn't be resolving. I'm using a consumer router with 1.1.1.1 and 1.0.0.1 set. Is there an issue with Cloudflare? I can swap the DNS in proxmox if needed.

**Comment by Masonjar13** [comment]
I tried building it again and it just connected that time, so not sure what occurred. I'm now receiving this error:
```
Step 9/25 : COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
COPY failed: file not found in build context or excluded by .dockerignore: stat src/ubuntu/install/chrome: file does not exist
```
I checked, and there are no files or folders within `/home`.

**Comment by mmcclaskey** [comment]
The dockerfile specifies that the directory ./src/ubuntu/install/chrome must exist relative to the dockerfile. So you are likely missing that directory and the files within it. There are other files and directories likely needed by the dockerfile which also must exist. They are all in this project. I would recommend doing a git clone, cd into the directory created by the git clone, and create your dockerfile there. That way you have all the files needed.

**Comment by Masonjar13** [comment]
Ah! I didn't realize the src folder was required. This is my first go at making an image.

Cloned the git and built again, I'm now able to start a new session with the image! Just need to modify the bookmarks and I should be ready for my demo.

Thank you for your patience and information, it's been very helpful and greatly appreciated.
