### ISSUE TITLE
Chrome docker for arm machines

### ISSUE THREAD

**Issue by rahul1996pp** [kasmtech/workspaces-issues#206]
can you please create dockerfile or image for arm to use

**Comment by j-travis** [comment]
Google does not publish an arm64 build of Chrome for desktop linux. So you'll have to use Chromium instead.

**Comment by rahul1996pp** [comment]
How to use chromium and connect to online

**Comment by j-travis** [comment]
You can follow our install guide and/or videos.

https://kasmweb.com/docs/latest/index.html
https://www.youtube.com/watch?v=QV6CcV9eNNs
