### ISSUE TITLE
recent self signed ssl cert replacement.

### ISSUE THREAD

**Issue by ghartrid** [kasmtech/workspaces-issues#209]
Hi , i recently replaced the original crt and key for my self hosted kasm server ,running on ubuntu ,now i have a domain for my server and it is put through cloudflare free plan , i kept the original crt and key in the same directory as my new crt and key is there any way that could be a problem, them being in the same directory ? I also ran the command for ufw in ubuntu to allow ssl through .....everything was working until i changed out the self signed crt and key for the cloudflare ones? How would i resolve this issue with the "creating a secure connection" and then the session cuts out to the admin dashboard? The root of this problem? Thanks 
![Screenshot_20220521-210001_Chrome](https://user-images.githubusercontent.com/100740652/169893618-3d871dbf-cdbd-4c53-a58b-8afa4ff1b7a2.jpg)

**Comment by j-travis** [comment]
You already have a ticket for this which I have replied to. (https://github.com/kasmtech/workspaces-issues/issues/208) . Please direct further correspondence to that ticket
