### ISSUE TITLE
Kasm Web Filter weird behaviour

### ISSUE THREAD

**Issue by tiaden** [kasmtech/workspaces-issues#210]
Hello,
I have been testing Kasm for the last couples of days and noticed that once a web filter policy is attached to a group, users cannot access internet no matter what additional settings has been set. 
Below you'll see a web filter policy which is supposed to allow all requests but once applied is blocking all requests instead and changing the whitelists/blacklists settings that not seem to have any effect.
I'm using Kasm 1.10

![Screen Shot 2022-06-03 at 9 28 59 PM](https://user-images.githubusercontent.com/33968665/171971319-81ebfeb0-4ea9-462b-abb7-96b3184c355b.png)

**Comment by j-travis** [comment]
Hi @tiaden ,
By chance did you install workspaces on a nonstandard port? If so, we have a known issue regarding the web filter

https://github.com/kasmtech/workspaces-issues/issues/34

**Comment by tiaden** [comment]
Hi @j-travis,
Yes I've been using port 8443. Thank you for the response. My standard https port is occupied by another application but I guess i can try this out on another server for testing and wait for this to be resolved. Thanks !
