### ISSUE TITLE
port in use 

### ISSUE THREAD

**Issue by QstTheDuck** [kasmtech/workspaces-issues#214]
first off all i want to say i am new to kasm so i could be making a very dumb mistake.

i am trying to install kasm with the use of [this guide](https://kasmweb.com/docs/latest/install/single_server_install.html#installation-guide) but every time i try to run `sudo bash kasm_release/install.sh` i get this error

`Port (443) is in use. Installation cannot continue.`

i have tried using the -L tag with a diffrent port(checked to make sure its open) but still getting that error

**Comment by j-travis** [comment]
Hello,
You must have another service running on port 443 which explains the first error. 
The flag to use a different port is `-L` 

https://kasmweb.com/docs/latest/index.html#installation-guide

**Comment by QstTheDuck** [comment]
> Hello,
> You must have another service running on port 443 which explains the first error. 
> The flag to use a different port is `-L` 
> 
> https://kasmweb.com/docs/latest/index.html#installation-guide

Looks like i made an error i ment that i tried `-L` with allot of ports that i checked are open and am still getting that error.

**Comment by j-travis** [comment]
What OS Distro/Version are you using.

In the installer we use the following command to see if the a port is in use? 
What is the output of this command when you specify the desired port

```
sudo lsof -Pi :443 -sTCP:LISTEN
```

**Comment by QstTheDuck** [comment]
> What OS Distro/Version are you using.

Maybe this is actually the problem i am using homeassistant os https://github.com/home-assistant/operating-system

> In the installer we use the following command to see if the a port is in use? 
> What is the output of this command when you specify the desired port
> 
> ```
> sudo lsof -Pi :443 -sTCP:LISTEN
> ```

So if i run that command with port 6000 i get this
`     /sbin/docker-init       0       /dev/null
1       /sbin/docker-init       1       pipe:[24880]
1       /sbin/docker-init       2       pipe:[24881]
8       /bin/s6-svscan  0       /dev/null
8       /bin/s6-svscan  1       pipe:[24880]
8       /bin/s6-svscan  2       pipe:[24881]
8       /bin/s6-svscan  3       /run/s6/services/.s6-svscan/lock
8       /bin/s6-svscan  4       /run/s6/services/.s6-svscan/control
8       /bin/s6-svscan  5       /run/s6/services/.s6-svscan/control
8       /bin/s6-svscan  6       anon_inode:[signalfd]
37      /bin/s6-supervise       0       /dev/null
37      /bin/s6-supervise       1       pipe:[24880]
37      /bin/s6-supervise       2       pipe:[24881]
37      /bin/s6-supervise       3       /run/s6/services/s6-fdholderd/supervise/
lock
37      /bin/s6-supervise       4       /run/s6/services/s6-fdholderd/supervise/
control
37      /bin/s6-supervise       5       /run/s6/services/s6-fdholderd/supervise/
control
37      /bin/s6-supervise       6       anon_inode:[signalfd]
758     /bin/s6-supervise       0       /dev/null
758     /bin/s6-supervise       1       pipe:[24880]
758     /bin/s6-supervise       2       pipe:[24881]
758     /bin/s6-supervise       3       /run/s6/services/sshd/supervise/lock
758     /bin/s6-supervise       4       /run/s6/services/sshd/supervise/control
758     /bin/s6-supervise       5       /run/s6/services/sshd/supervise/control
758     /bin/s6-supervise       6       anon_inode:[signalfd]
759     /bin/s6-supervise       0       /dev/null
759     /bin/s6-supervise       1       pipe:[24880]
759     /bin/s6-supervise       2       pipe:[24881]
759     /bin/s6-supervise       3       /run/s6/services/ttyd/supervise/lock
759     /bin/s6-supervise       4       /run/s6/services/ttyd/supervise/control
759     /bin/s6-supervise       5       /run/s6/services/ttyd/supervise/control
759     /bin/s6-supervise       6       anon_inode:[signalfd]
762     /usr/sbin/sshd  0       /dev/null
762     /usr/sbin/sshd  1       pipe:[24880]
762     /usr/sbin/sshd  2       pipe:[24881]
762     /usr/sbin/sshd  3       socket:[27554]
762     /usr/sbin/sshd  4       socket:[27555]
764     /usr/bin/ttyd   0       /dev/null
764     /usr/bin/ttyd   1       pipe:[24880]
764     /usr/bin/ttyd   2       pipe:[24881]
764     /usr/bin/ttyd   3       anon_inode:[eventpoll]
764     /usr/bin/ttyd   4       pipe:[29105]
764     /usr/bin/ttyd   5       pipe:[29105]
764     /usr/bin/ttyd   6       pipe:[29106]
764     /usr/bin/ttyd   7       pipe:[29106]
764     /usr/bin/ttyd   8       anon_inode:[eventfd]
764     /usr/bin/ttyd   9       /dev/urandom
764     /usr/bin/ttyd   10      anon_inode:[eventfd]
764     /usr/bin/ttyd   11      socket:[29107]
764     /usr/bin/ttyd   12      socket:[29109]
3952    /usr/sbin/sshd  0       /dev/null
3952    /usr/sbin/sshd  1       /dev/null
3952    /usr/sbin/sshd  2       pipe:[24881]
3952    /usr/sbin/sshd  3       /dev/ptmx
3952    /usr/sbin/sshd  4       socket:[437152]
3952    /usr/sbin/sshd  5       socket:[438341]
3952    /usr/sbin/sshd  6       socket:[438312]
3955    /bin/zsh        0       /dev/pts/0
3955    /bin/zsh        1       /dev/pts/0
3955    /bin/zsh        2       /dev/pts/0
3955    /bin/zsh        10      /dev/pts/0`

**Comment by j-travis** [comment]
Sorry, 
I don't think we will be able to help out with this. Our supported distros are listed here:
https://kasmweb.com/docs/latest/install/system_requirements.html#operating-system

You are welcome to try and install on others, but as you can imagine, there are practically endless options so we cant support them all
