### ISSUE TITLE
Alt Gr Android issue

### ISSUE THREAD

**Issue by octave21** [kasmtech/workspaces-issues#215]
Hi, I am using an AZERTY physical Rii mini keyboard connected on an Android phone. This Android phone  runs chrome and colornote.

When I am typing the key sequence x_8\x on colornote the result is ok. But when I am typing this sequence on your desktops demo the \ is not displayed. The keys combined with Alt Gr are not working. 

Nota 1 : this text has been written with the physical keyboard on chrome on Android showing that the key sequence is correctly displayed by chrome.

Nota 2 : if the Android phone is replaced by a PC with Chrome, the keys from the physical Rii keyboard are correctly handeled.

Nota 3 : I experienced the same issue on my own kasm infrastructure.

Key sequence :
x -> x
_ -> _
Shift + _ - > 8
Alt Gr + _ -> \

Any Idea for being able to use Alt Gr via Android ?

![Screenshot_20220608-192913](https://user-images.githubusercontent.com/25460917/172683943-bf2e6fc7-b5f0-4588-8fcf-c61b6903c666.png)
![Screenshot_20220608-192639](https://user-images.githubusercontent.com/25460917/172683980-a708b2a4-434b-49ff-ab5a-cc13e49f613b.png)

**Comment by mmcclaskey** [comment]
We use browserstack for testing all the different combinations of devices, operating systems, and browsers out there. If you are able to instruct us on how to configure a specific device, such as a Samsung Galaxy S21, to display a AZERTY keyboard with an Alt Gr key, then we can try to get to the bottom of the issue. Here is a screenshot of the supported Samsung devices and Android versions available. If this is not possible on a soft keyboard and we need a physical external keyboard, then it would be difficult for us to replicate, so hopefully that is something that can be configured in Android.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/5209269/173335362-4e0cffaa-5dc0-45e8-8603-6361990dee0c.png">

**Comment by octave21** [comment]
Hi, thanks for answering my post. 

Some comments  :

1 - I don't know how it is possible to display an AZERTY keyboard with Alt Gr on Android. I'll try to find ....

2 - I made the x_8\x test with some devices : 

a - Logitech usb keyboard -> OTG USB adaptor -> Samsung Galaxy tab7 (Android 11) -> Chrome -> my own Kasm infrastructure : test KO, (screenshot). 

b - Rii physical keyboard -> Bluetooth -> Google Pixel 4a (Android 12) - Chrome -> my own Kasm infrastructure : test KO.

c - Rii physical keyboard -> Bluetooth -> Google Pixel 4a (Android 12) - Firefox -> my own Kasm infrastructure : test KO.

d - Logitech usb keyboard -> OTG USB adaptor -> Samsung Galaxy tab7 (Android 11) -> Chrome -> Google search : test OK

e - Logitech usb keyboard -> PC (Archlinux) -> Chrome -> my own Kasm infrastructure : test OK. 

f - Soft keyboard (Onboard) -> PC (Archlinux) -> Chrome -> my own Kasm infrastructure : test OK. 

g - Rii physical keyboard -> Bluetooth -> PC (Archlinux) -> Chrome -> my own Kasm infrastructure : test OK. 

3 - So I think that a physical keyboard + Android + Kasm is going wrong somewhere. 

![altgr](https://user-images.githubusercontent.com/25460917/173363403-40bacef9-dbe8-49de-bb89-8f57fdfc2461.jpg)

**Comment by octave21** [comment]
Hi, I found a software way to reproduce the issue without using the usb port and a hardware keyboard. The solution is to transform my mobile phone in a bluetooth keyboard connected on an other Android device.

1. Install Bluetooth Keyboard & Mouse from Google Play on the Android phone.
2. Set up the bluetooth link between the mobile and a Samsung Android tablet. 
3. On the tablet configure the keyboard as AZERTY (French).
4. Execute chrome on the tablet and connect to Kasm.
5. Open an Ubuntu terminal.
6. Open the search bar of Chrome.
7. With the bluetooth keyboard on the mobile, type the sequence x_8\x in the terminal and in the search bar.
8. The sequence is correct within the search bar, and wrong within the terminal. See screenshot.

Would it be easier for you to reproduce the issue ?

![2022-06-14](https://user-images.githubusercontent.com/25460917/173626777-4074a2fd-89e6-4f95-8529-14fc4849541d.jpg)

**Comment by mmcclaskey** [comment]
I may have been able to duplicate on MacOS using the onscreen keyboard and changing it to AZERTY. But I'm not 100% sure. Would you be willing to test with our develop release https://kasmweb-build-artifacts.s3.amazonaws.com/kasm_backend/branches/develop/kasm_workspaces_develop.tar.gz

This will require a re-install, but the develop release has new changes to support foreign language inputs. Once you get that up and running, try it again with default settings. Then, go open up the control panel and disable IME and try again.

<img width="588" alt="image" src="https://user-images.githubusercontent.com/5209269/174305541-fff8b728-fc59-44bc-9ef3-07c6c33e5013.png">

**Comment by octave21** [comment]
Hi, thanks for your input.
Yes I'll re-install and I'll make the test, when ready I come back to you.

**Comment by octave21** [comment]
Hi Matt,
I did re-install your develop release, but unfortunately the test is still KO.
- Before launching the workspace, test is OK.
- Within workspace with IME on, test is KO.
- Within workspace with IME off, test is KO.

Hardware keyboard + Google pixel 4a + Android 12 + AZERTY config + kasm develop release

![Screenshot_20220618-000437](https://user-images.githubusercontent.com/25460917/174408257-c67a8659-21a3-4066-8238-54133a30df55.png)
![Screenshot_20220618-000315](https://user-images.githubusercontent.com/25460917/174408267-9b43d5a6-1c67-4a70-8d52-07571494f768.png)
![Screenshot_20220618-000218](https://user-images.githubusercontent.com/25460917/174408275-e4427160-aeb1-4d68-bcfe-46c65b4d8b61.png)

**Comment by octave21** [comment]
Hi Matt,
I found a solution based on the mapping of the keys. Thanks to xdotool I am able to simulate key press.
- I wrote the keyp script
- I wrote the shortcut within the xfce keyboard UI for all AltGr keys

Will you plan to develop a key mapping function ?

![Screenshot_20220626-194440](https://user-images.githubusercontent.com/25460917/175827681-7ea58d5b-8d72-4b76-a0c0-c2775c173601.png)
![Screenshot_20220626-194154](https://user-images.githubusercontent.com/25460917/175827685-a9005c0b-8298-4423-81d4-e0daa3e54a23.png)
