### ISSUE TITLE
Kasm not installing 

### ISSUE THREAD

**Issue by chiragnahata** [kasmtech/workspaces-issues#217]
Kasm got installed on my oracle free tier server successfully and i got my userid and password. But i am unable to open it. I mean when i entered the ip address in the web browser. I said no webpage found. Please help

**Comment by mmcclaskey** [comment]
You need to make sure that port 443 is open in the cloud networking settings in Oracle. Depending on what operating system you selected, you may also need to open the port up on the VM as well. What OS did you use?

**Comment by chiragnahata** [comment]
Ubuntu 20.04 is the os

**Comment by chiragnahata** [comment]
Ok now worked after adding port 443 but it is not https. How to enable SSL ?

**Comment by chiragnahata** [comment]
I am not getting all the default images in KASM. Only 8 images are available.

**Comment by chiragnahata** [comment]
Also is it time limited as because when I launched one of the 8 images it showed 1 hour left.

**Comment by chiragnahata** [comment]
> I am not getting all the default images in KASM. Only 8 images are available.

Usually around 26 images are available as much I saw on youtube.

**Comment by mmcclaskey** [comment]
HTTPS is the only option, Kasm does not work over http. I suspect that your local browser does not show the HTTPS in the url by default, chrome does that.

As for why you are seeing few images, I am also guessing that you installed on an Arm based system. We have adapted a number of our images to work on Arm and x86_64, but not all of them are working on Arm. In most cases it is because the underlying software is just not available on Arm.

**Comment by chiragnahata** [comment]
So can I add those images

Chirag Nahata

**Comment by mmcclaskey** [comment]
No, they will not work on an Arm based CPU.

**Comment by chiragnahata** [comment]
> 

Please help with this

**Comment by chiragnahata** [comment]
Also is it time limited as because when I launched one of the 8 images it showed 1 hour left.

**Comment by mmcclaskey** [comment]
Its a group setting called Keepalive Expiration. Add that setting to the All Users group and set to the desired limit.

https://kasmweb.com/docs/latest/guide/groups/group_settings.html?highlight=keepalive_expiration

**Comment by chiragnahata** [comment]
Can I set it to unlimited time ?

**Comment by mmcclaskey** [comment]
We don't currently have a way to set it to unlimited, however, that is a request in our backlog and we plan to implement in a future release.

**Comment by chiragnahata** [comment]
> We don't currently have a way to set it to unlimited, however, that is a request in our backlog and we plan to implement in a future release.

So what is the maximum time limit possible

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/173852321-646ac85f-c4d7-4efd-ad34-fdec9368bb4b.png)

I am getting this error. Please help

**Comment by chiragnahata** [comment]
![image](https://user-images.githubusercontent.com/63905783/173886054-1d49ff1d-e10c-4e4a-ae96-66c4833152c6.png)

Getting this error please help

**Comment by chiragnahata** [comment]
I have added 443 already. One of my KASM installation is working on arm but the amd one is showing this error. Please help as soon as possible

**Comment by mmcclaskey** [comment]
As the error page says, you navigated to the site using HTTP rather than HTTPS.

**Comment by chiragnahata** [comment]
> As the error page says, you navigated to the site using HTTP rather than HTTPS.

But I just entered ipaddress:443 i haven't put https or http.

**Comment by mmcclaskey** [comment]
If you don't specify http or https, your browser will guess. Some browsers default to https others http.
