### ISSUE TITLE
Unable to properly update environment when persistent profile is enabled

### ISSUE THREAD

**Issue by tiaden** [kasmtech/workspaces-issues#218]
Hello,
I found that when  persistent profile is enabled, updating the image with new applications (vscode for example) result in the desktop entry file not copied to the desktop. After investigation, I found that the process of copying contents from /home/kasm-default-profile to /home/kasm-user is based on the absence of .bashrc. For persistent profile .bashrc is always present, therefore any new updates to the docker images does not reflect in /home/kasm-user. Please let me know if you have questions since I feel like I have not explained myself well.

**Comment by j-travis** [comment]
Hi @tiaden ,
I understand your issue.

The challenge is , there really is no absolute way for the system to know what is new in your image vs what the user may have altered in their profile.  For example, if a chrome shortcut was in the first iteration of the image, maybe the user decided they didn't want that shortcut and removed it.  That second iteration of the image would still have the chrome shortcut, so if we always copied in different entries - it would add back in the shortcut that the user originally removed from their profile.

So, unfortunately, if you use the same profile but are making updates to the image, items that you place in the home directory in subsequent updates to the image (like desktop shortcuts ), wont appear in existing profiles. The user can drag the shortcuts for the new apps from the menu bar on to their desktop, or they can reset their profile and start from scratch.

**Comment by tiaden** [comment]
Hi @j-travis,
You make excellent points. For us, resetting the profile is not an option. As a side note I was wondering if it can be deactivated by the admin since a user can erase all his data by mistake. 

Back to the subject at hand, I agree with you that it's difficult to know what has changed in the new image vs what has been altered by the user. So I was thinking maybe we should have a hook script where the admin (image builder) can decide how he wants to merge the new content into the current home directory. An example hook can be a script that replaces obsolete shortcuts with new ones or a script that places new shortcuts into a custom folder on the desktop etc ...

Also maybe it would be better to use a custom hidden file (example: .kasm/.persistent-profile) to detect the presence of an existing profile instead of using the .bashrc file. Right now I have to manually delete the .bashrc file for each user and then copy the content back in order to force the copy from  /home/kasm-default-profile to /home/kasm-user when I update an image.
Since we are on the subject of hooks, what is the purpose of the following files:
- kasm_post_run_root.sh
- kasm_post_run_user.sh
- kasm_pre_shutdown_root.sh
- kasm_pre_shutdown_user.sh

**Comment by j-travis** [comment]
- In the future we may add an option for the admin to remove the reset option completely. In the upcoming release we have added a dialogue that requires the user to confirm and type in a message that they really want to reset the profile. This should hopefully reduce accidental deletions.

- I agree that using a file more overt would be more intuit for admins to understand. There is nothing special about .bashrc other than we expect it to be there. Really this logic could just be replaced with one that checked if the folder was empty or not.  You have control to modify this as you see fit.  You could either overwrite this file in your custom image, or modify it and rebuild our core image. https://github.com/kasmtech/workspaces-core-images/blob/develop/src/common/startup_scripts/kasm_default_profile.sh

- These scripts are called via docker exec. They may be removed in the future as we now have the Docker Exec Config within the Image (https://kasmweb.com/docs/latest/guide/custom_images.html?#docker-exec-config) . You may consider using these to run logic to updating your profiles

kasm_post_run_root.sh - run this script as root after the session starts
kasm_post_run_user.sh - run this script as the standard user context (typically UID 1000) when the session starts
kasm_pre_shutdown_root.sh - run this script right before the session is deleted as root
kasm_pre_shutdown_user.sh - run this script right before the session is deleted as the standard user context (typically UID 1000)

**Comment by tiaden** [comment]
@j-travis ,
Yes there is nothing special about .bashrc, only that some developers have custom bash scripts, functions or environment variables in it. Therefore like I said, I delete the .bashrc and copy the content back in order to force the sync.
Thank you for your answers. You know best ! I believe you can close this. I have no further questions
