### ISSUE TITLE
Packet Drops While Streaming

### ISSUE THREAD

**Issue by Masonjar13** [kasmtech/workspaces-issues#219]
I have an RPI 3 1GB RAM plugged into a projector, and Kasm hosted on a self-hosted Proxmox server (CT, not VM). On the RPI, I'm running Raspbian and connecting to my Kasm server over LAN. I'm giving it Chrome, with 2GB RAM, and 4 CPUs. The purpose was to stream content, such as YouTube, Plex, etc., offloading to Kasm due to the restrictions of the RPI. On the RPI itself, YouTube and Plex stream perfectly fine, but can crash with more than 1 tab, this is where Kasm comes in.

The only issue I'm encountering is stuttering. I'll get dropped frames, which also drops audio packets. Tested on my personal laptop, and desktop, and I still receive these drops, at any streaming quality. The server and desktop are hardwired, laptop and RPI are on WiFi. It really doesn't seem like a network issue, and the image should have plenty of power. My question is: does the streaming expect GPU acceleration? If so, this is where there is an issue in hosting Kasm virtualized. I can passthrough a GPU if I need to, I have 2 cards on the server, but it's a bit of effort to do, so I wanted to ask first.

If streaming wouldn't use the GPU, then I'm at a loss for what is causing these drops.

**Comment by j-travis** [comment]
No, the streaming does not expect GPU, in fact it only uses CPU at the moment.

I recommend testing the following

1. Rule out load related issues on the Kasm session container itself. 

Download an mp3 into the container and just play the file with vlc (its in the desktop image).  If you still hear stuttering of the audio, then its likely not load on the container. If you dont, then try the same thing with a low quality video file. 

2. Rule out issues with WIFI

The Kasm stream is real-time meaning it can't utilize buffering that normal video streams do to smooth out network congestion issues.  Try hooking your pi and/or laptop up via wired connection , or test from your desktop that you mentioned was wired.

**Comment by Masonjar13** [comment]
Before trying the VLC image, I tried on my desktop again, and I hardly get any drops, even at extreme quality. Setting webp compression decreases the drops everywhere, so now I'm thinking it's very likely the RPIs built-in WiFi card. I'll run some more tests with the RPI closer, and hardwired.

Ultimately, it seems this is not a good purpose for Kasm though and I may look into other options (VM with GPU pass-through + Parsec).

Edit: I forgot to mention, I was watching the resource usage in Proxmox. The allocated CPU usage spiked to 55% when making the container, then settled around 6-7%. When playing a video, it sits around 30%. RAM was fine, network is ~1MB during streaming. Desktop browser delta traffic was about 4.8MB on extreme, and 1.4MB on low. Idle was ~25KB.

**Comment by j-travis** [comment]
Ok, thank you. I will close this for now.

You are correct that if your primary purpose is for consuming media, Kasm likely isn't the right fit currently. We may be able to offer a more compelling offering in the coming months, as we are about to release 1.11 which comes with support for passing in and sharing a GPU among any number of sessions. This will allow graphics acceleration of programs that run inside the container (e.g webgl  in chrome)

This will be available in the Developer Preview builds in a few days. @mmcclaskey , can ping you when its ready if you'd like to try it out.

Later, we plan on improving the KasmVNC rendering tech (how the container is streamed to your browser) to better support high quality video  streaming use-cases like yours.
