### ISSUE TITLE
Agent not detecting NVIDIA container toolkit

### ISSUE THREAD

**Issue by osiriswrecks** [kasmtech/workspaces-issues#221]
My agent is reporting 0 GPUs in the Agents list, but it shows both NVIDIA GPUs in the detailed view. According to the docs this means that the agent can't find the container toolkit on my system.

Here's a breakdown of my system specs. Is there anything else I can do to troubleshoot this?

CentOS 7
NVIDIA Driver 515.48.07
CUDA 11.7
NVIDIA Container Toolkit 1.10.0

![image](https://user-images.githubusercontent.com/24221107/174834212-f6819e8a-5862-4d83-a7c6-16c7ebb62228.png)

![image](https://user-images.githubusercontent.com/24221107/174834357-279b0161-d241-459e-81c5-dbde89f9badb.png)

I can run it from the command line though.

![image](https://user-images.githubusercontent.com/24221107/174834714-7d2592ba-bc05-40ef-8683-675f2b4784f1.png)

**Comment by j-travis** [comment]
@osiriswrecks ,
It looks like our system will report zero if the nvidia runtime isnt detected. A common issue is that the docker daemon hasnt been restarted after it installtion.

Can you check ?
Ref: https://kasmweb.com/docs/latest/guide/troubleshooting.html?highlight=nvidia%20runtime#gpu-passthrough-support

**Comment by osiriswrecks** [comment]
@j-travis I tried restarting the daemon with `systemctl` as well as a full `yum update` and reboot just in case. Neither works.

**Comment by j-travis** [comment]
In the Agent view, can you expand the Docker Info section, and find **Runtimes**. Can you expand the options and post a screenshot ?

**Comment by osiriswrecks** [comment]
Sure thing!

![image](https://user-images.githubusercontent.com/24221107/174864863-3e61063e-3ed6-4733-8a65-a82a49889a9d.png)

**Comment by osiriswrecks** [comment]
!!!! I figured it out. I think I didn't do a full proper installation of the toolkit, so I uninstalled and reinstalled based on the official docs and after restarting a couple of times it looks like it sees my GPUs now!

Do I have to do anything special on the container side to get full GPU support or does it handle it under the hood?

**Comment by j-travis** [comment]
@osiriswrecks ,
We just pushed updates to our Developer Preview builds , that will allow you to easily share a GPU among any number of sessions. The update also allows for graphics accelerates of programs inside the session - beyond the existing support for AI/ML use cases.

Here is an example of multiple sessions running WebGL workloads in Chrome

![image](https://user-images.githubusercontent.com/48762190/175775373-5392075c-59d9-4ec0-b12a-6c0b6e17ba41.png)



If you'd like to try out the Developer Preview builds you can find more information here:

- https://kasmweb.com/docs/latest/developers/builds.html

Updated docs about GPU workloads can be found here:

- https://kasmweb.com/docs/develop/how_to/gpu.html

You'll also want to be using the `:develop` tag of our workpaces images (e.g `kasmweb/ubuntu-focal-desktop:develop` )

**Comment by osiriswrecks** [comment]
Thanks! I'll definitely check this out. Does this apply to all desktop images or just the Ubuntu ones? Right now I'm using the `kasmweb/core-nvidia-focal:develop-rolling` as a base so maybe it doesn't make a difference.
