### ISSUE TITLE
How to add the user "default" into sudo group?

### ISSUE THREAD

**Issue by Ir0nOx** [kasmtech/workspaces-issues#222]
To whom it may concern,

I have reviewed ticket #58 & #43; non provide a definitive answer on how to grant sudo privileges to the default user. If there is a solution, please provide or direct me to the answer.

If there is not a solution readily available, can a script run in either Docker Run Config Override or Docker Exec Config to create an account with sudo privileges or grant the "default" user sudo privileges?

Your reply is greatly appreciated. Thank you.

**Comment by j-travis** [comment]
Hello,
You can build a custom image with sudo enabled for the default user.  Instructions are here:
https://kasmweb.com/docs/latest/how_to/running_as_root.html#building-an-image-with-sudo


There is a general facility "Docker Exec" for running arbitrary commands. You could use this to add custom configurations- but in general its better to build an image with the configurations/ software you prefer.

https://kasmweb.com/docs/latest/guide/custom_images.html?#docker-exec-config

You can run those commands as root too if you wish. there is an example of running the exec as root in the vpn guide
https://kasmweb.com/docs/develop/how_to/vpn_sidecar.html#customizing-workspaces-images
```
{"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'ip route delete default && ip route add default via 172.20.0.2'"}}

```

**Comment by Ir0nOx** [comment]
Hi @j-travis,

Thank you for responding so quickly. I've tried different variations of the JSON command you provided from the VPN doc. Unfortunately, and I must admit, my declarative language skills are limited, did not work.

```json
{
    "first_launch":{
        "user":"root",
        "privileged":true,
        "cmd": "bash -c '*'"} <--Input wildcard
}
```

I did remove or left only the pulse audio command:

```json
    {"user":"root","environment":{"START_PULSEAUDIO":"0"}}
```

If you believe creating a custom image is the only resolve, I'll pursue that. I was hoping for an easier solution.

**Comment by j-travis** [comment]
You can user docker exec to install sudo and set up  the default kasm-user with permissions. This should work on the `:develop` ubuntu based images

Docker Exec Config

```
{
   "first_launch":{
      "user":"root",
      "cmd":"bash -c 'apt-get update && apt-get install -y sudo && echo \"kasm-user  ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers'"
   }
}
```

**Comment by Ir0nOx** [comment]
Hi @j-travis,

Thank you for your response. Unfortunately, the JSON command did not work. Also, apologize for not mentioning this earlier, the image I've been troubleshooting in, is Kali. Although, the command you provided, you mentioned it should work for Ubuntu images. I'd assume it would work in Kali, considering it's Debian base. Nonetheless, I appreciate your efforts.

One last attempt:

The reason for the default user to have sudo privileges; I am using a license Burp Suite in a Chromium browser. When proxying traffic, Burp uses the "Burp Browser," which is opened in the Chromium browser; however, when the attempt is made to open the bowser an error appears (..."refusing to start browsers your current configuration..."). Most likely the reason for the error, is because it is opening the browser in root. I did try the following and it did not work:

```json
{
    "first_launch": {
        "user":"kasm-user", <--Also "default"
        "cmd": "bash -c 'Chromium --start-maximized \"$KASM_URL\"'",
        "environment": {
            "LAUNCH_URL": ""
        }
    }
}
```

I tried the above command with, without and removed the root user using the command below:

```json
{"user":"root","environment":{"START_PULSEAUDIO":"0"}}
```

Thank you.

**Comment by j-travis** [comment]
Ensure you are using the `:develop` tag for Kali. e.g `kasmweb/core-kali-rolling:develop`

Then for Docker Run Config - leave it empty.

For Docker Exec Config enter the snippet I last posted

Disable persistent profiles if you have it set.


Once you start the Kali session, you'll be able to run sudo commands with no password after a few seconds ( the exec command needs some time to run - it also assumes you have internet connection to do the apt commands)


I cant comment on burpsuite, but if its using an embedded browser , it may not like running inside a container.

you can try disabling secomp by entering the following in Docker Run Config

```
{"security_opt":["seccomp=unconfined"]}
```

**Comment by Ir0nOx** [comment]
Hi @j-travis,

Thank you! Your solution worked and I am able to run Burp Suite inside Kasm. I believe you can close this ticket.
