### ISSUE TITLE
Kasm fails to install - fails at : Initializing Postgres Database

### ISSUE THREAD

**Issue by rkz9000** [kasmtech/workspaces-issues#225]
I am installing Kasm on a clean version of Ubuntu server 22.04
I have been receiving a failure during the script during a database initialization. 
I appreciate any help you can provide.
Was able to use Docker-compose to make a container for testing. 

Thanks

I have read and accept End User License Agreement (y/n)? y
Checking if docker and docker compose are installed.
Docker is installed
20.10.17 is a supported version of docker.
Commands docker and docker compose detected.
Skipping Dependency Installation.
Installing All Services
Updating configurations with custom DEFAULT_PROXY_LISTENING_PORT (30443)
Docker network kasm_default_network already exists. Will not create
Initializing Database
Setting Seed file as /opt/kasm/1.10.0/conf/database/seed_data/default_properties.yaml
[+] Running 1/1
 ⠿ Container kasm_db  Stopped                                                                                     0.4s
Error response from daemon: Cannot kill container: kasm_db: Container 7e533ebf32f3d843fd50b2475a0e7edf76a6f267e60d1c1318d80d57792b4b5f is not running
kasm_db
kasm_db_1.10.0
kasm_db_1.10.0
WARN[0000] Found orphan containers ([docker-redis-1 docker-web-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[+] Running 1/1
 ⠿ Container kasm_db  Started                                                                                     0.4s
2022-06-29 23:44:16,493 [INFO] root: Performing Database Connectivity Test
2022-06-29 23:44:16,508 [INFO] root: Initializing Postgres Database

**Comment by j-travis** [comment]
This line is concerning
```
WARN[0000] Found orphan containers ([docker-redis-1 docker-web-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
```

We don't name anything in this fashion. 

Have you made custom modification to the dockerfile and/or installer?

**Comment by rkz9000** [comment]
Thanks for the quick response.  Since I had just but the bare-metal server, I did a full reinstall and had no problems. I have sure I had compose setup incorrectly in some way.  Is there GPU support to improve performance?  I have an ATI 6700 I would like to use with this build. If I can get resonable performance from the browser containers, I would like to purchase a full system for my office. Thanks.

**Comment by j-travis** [comment]
A follow up about performance:

First thing is ensure you are running on SSDs and not mechanical disks.
Next , the more Core and Memory you can allocate to each session will improve performance. You can adjust this in the Image settings within the UI.

Regarding GPU support. We have new capabilities for GPU graphics acceleration in our developer preview builds.  It's Nvidia only though - so it may not help in your case.

https://github.com/kasmtech/workspaces-issues/issues/221#issuecomment-1166284266

**Comment by rkz9000** [comment]
Thanks much!  Noticed the core additions needed for web browsing.  Test box is working great and uses M.2 drives! It is only an 8 core processor but is doing well with 3 clients so far. I will increase this to five and try to see how this will scale. I will probably have around 200 concurrent users in the end. I think keeping this bare-metal is the best plan so far. Thanks again for all your help!
