### ISSUE TITLE
have to select zone, even when I limit the available zone for an image 

### ISSUE THREAD

**Issue by thegreymatter** [kasmtech/workspaces-issues#230]
I'm running a 2 zone setup, where for one of the images I've limited the allowed zone to one of the zones (let's call it zone A).
However, when I try to create a new workspace, if I don't select the zone A specifically (i.e. keep it on auto, even though the only other zone is zone A) i receive consistently the following error - 
```
"No Agent slots available. No Agent can be contacted with enough available resources to provision the image"
"No resources are available to create the requested Kasm. Please try again later or contact an Administrator"
```
when i choose zone A explicitly, I get the workspace working. 
any idea why? and how can I sort it out?

here is an example how the call to request_kasm looks like 0 

```
// this doesn't work
{image_id: "9b99b0607db248ad891d0728ab7a69e8"
network_id: ""
persistent_profile_mode: "Disabled"
point_of_presence: ""
token: "REDACTED"
username: "REDACTED"
x_res: 1349
y_res: 1290
zone_id: ""}
```

```
// this works
image_id: "9b99b0607db248ad891d0728ab7a69e8"
network_id: ""
persistent_profile_mode: "Disabled"
point_of_presence: ""
token: "REDACTED"
username: "REDACTED"
x_res: 1349
y_res: 1290
zone_id: "8d929e7f-164d-45dc-94cb-a3218fe01b0a"
```

**Comment by j-travis** [comment]
I think this can happen if:
1. You are connected to the deployment via Zone B
2. You choose Auto
3. The image is configured to only provision in Zone A
4. Search Alternate Zones , for Zone B is set to False.


Can you double check your zone settings for Zone B and ensure Search Alternate Zones is enabled:

Ref: https://kasmweb.com/docs/latest/guide/zones/deployment_zones.html?highlight=search%20alternate%20zones#id3

**Comment by thegreymatter** [comment]
🤦  when you put it like this it makes a lot of sense. 
double-checked, and it indeed fixed the issue.

Thanks.
