### ISSUE TITLE
Question - agent network security requirements. 

### ISSUE THREAD

**Issue by thegreymatter** [kasmtech/workspaces-issues#232]
I'm slightly confused regarding the security requirements of agents.  
I'm trying to set up an agent inside a private network in the most secure way possible. 

So I'm trying to understand what is required from an agent network-wise. 

1) Does the agent need to have a public IP, and public access from the internet?
2) Or is it enough it has access from the manager service?
3) Or even better,  is it enough it has access to the manager server (i.e. ngrok style reverse proxy)

**Comment by j-travis** [comment]
You can install Workspaces in a multi-server (role) fashion. This allows you to compartmentalize the different components according to your desires.

This page illustrates the different roles and the ports and protocols needed for the systems to communicate:

https://kasmweb.com/docs/latest/install/multi_server_install.html

You'll see that the users only communicate with the webapp roles - so thats the only component that needs to be external facing. 

They are proxied through the webapp role down to sessions that run on the agents.

So yes, if you desired, you could have the agents on a private network, and they only need to communicate with the webapp servers.
