### ISSUE TITLE
unable to type Chinese in apps , not even paste it.

### ISSUE THREAD

**Issue by changchichung** [kasmtech/workspaces-issues#233]
Host OS: ubuntu 22.04
input method : fcitx5
 I started a kasm instance , and launch a google-chrome session , then I find that I can't input any chinese words , chrome.
so I try brave browser , it's  the same situation.
then I try to paste the chinese words into clipboard
as you can see in this image
![](https://i.imgur.com/WJvPuFg.png)

in No.1 block , I can type/paste Chinese words ,  but browser can't recognize the words ( as block No.2 )

any suggestions to solve the issue ?

**Comment by j-travis** [comment]
Hello,
Can you try clicking "Advanced Settings" within that control panel and enabling IME input mode.  It should allow you to user your IME within the session.

Ref: https://kasmweb.com/docs/latest/how_to/ime.html
