### ISSUE TITLE
How do I login as root user in the container

### ISSUE THREAD

**Issue by baigod** [kasmtech/workspaces-issues#238]
How do I login as root user in the container？

Image:  kasmweb/centos-7-desktop:1.9.0-rolling

![image](https://user-images.githubusercontent.com/23446974/181712697-cba97203-1680-45f3-979e-a13350dc3af6.png)

**Comment by j-travis** [comment]
Hello, 
You can find the solution in the docs or existing issues in this repo.

https://kasmweb.com/docs/latest/how_to/running_as_root.html#running-whole-container-as-root
