### ISSUE TITLE
Kasm Images are not updating to latest versions.

### ISSUE THREAD

**Issue by rkz9000** [kasmtech/workspaces-issues#243]
How do you force an update to the Images on the Kasm server. 

The images with the install are a bit old and have not updated.

Thanks.

**Comment by j-travis** [comment]
Hi,
Please see our FAQ (https://kasmweb.com/docs/latest/FAQ.html?highlight=images)

We pushed "-rolling" tags of the images nightly. To use them, change the existing docker image from the  `:1.11.0` tag to `:1.11.0-rolling` . 

e.g `kasmweb/chrome:1.11.0-rolling`

https://kasmweb.com/docs/latest/guide/custom_images.html#rolling-images

**Comment by rkz9000** [comment]
Thanks
