### ISSUE TITLE
Why does Ubuntu Cloud Workspace (paid subscription) always expire after 19 mins?

### ISSUE THREAD

**Issue by HarrisKirk** [kasmtech/workspaces-issues#245]
I have a paid 10/month subscription and I thought it would give me 200 mins of dockerized services but the Ubuntu always expires after 19 mins.  
![Screenshot from 2022-08-17 16-10-01](https://user-images.githubusercontent.com/2710359/185266438-a2f26847-b33c-47f4-957f-984d8f1cb461.png)

**Comment by mmcclaskey** [comment]
The "expiring in" time is updated any time you interact with the desktop. This ensures that if you forget to delete your desktop, you will not burn through all your time, at most you would burn through 20 minutes. We definitely appreciate the feedback, we want to use a setting that is most appealing to the entire user base.

**Comment by HarrisKirk** [comment]
Hmmmm. Interesting. So the workspaces are not really intended to persist? I could not use a desktop for an hour on Monday and expect the SAME container (with the created files or processes) to be available on Tuesday?

If so, I see huge value in Kasm in the realm of training, testing, privacy and CI/CD which has ephemeral applications but not emulating a business desktop which needs to persist from one day to the next.

I very much appreciate your thoughts.

Harris

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by mmcclaskey** [comment]
Kasm Workspaces absolutely supports persistent profiles and it also supports desktops that have any admin configured timeout (keep-alive timer). But Kasm Cloud Personal, a SaaS powered by our server product Kasm Workspaces does not. Kasm Cloud Personal SaaS products are targeted to use cases that desire ephemeral desktops/apps. 

You could run your own VM in a cloud provider of your choosing and install Kasm Workspaces and configure and deploy as you see fit.
[Single Server Install](https://youtu.be/QV6CcV9eNNs)
[Configuration Overview](https://youtu.be/teJSUxKEbfE)

**Comment by HarrisKirk** [comment]
Very helpful reply.  Thanks - I look forward to continuing to use Kasm products.
