### ISSUE TITLE
Can’t connect to Kasm with domain and Nginx

### ISSUE THREAD

**Issue by raining237** [kasmtech/workspaces-issues#246]
I’ve been trying to use a domain in conjunction with Cloudflare and Nginx, but I just can’t seem to get it to work correctly. I’m not sure if I setup something wrong in Cloudflare but I just can’t get the domain to load Kasm.

**Comment by j-travis** [comment]
I'm not sure we can help with this unless you are having a specific issue related to Kasm. If so please explain in detail what the issue and details about your environment

**Comment by complot72** [comment]
Try this:
In Kasm "zones", edit the default zone to this:
Upstream Auth address = localhost and the Proxy Port = 443

Then in Nginx, make sure you turn ON the "websocks support" in your redirect and select the scheme = https

**Comment by j-travis** [comment]
No response from user, closing
