### ISSUE TITLE
FAIL TO EXCUTE DEFAULT TERMINAL KALI LINUX

### ISSUE THREAD

**Issue by khiempham06** [kasmtech/workspaces-issues#248]
![ff](https://user-images.githubusercontent.com/68492139/186451090-9713d7f0-f635-4bb3-88de-ee1a55c7026a.png)

**Comment by hsemes** [comment]
Same error here but with network. Cannot enable networking and start browser.

**Comment by thelamer** [comment]
Can you please add  `{"security_opt":["seccomp=unconfined"]}` to the Docker Run Config Override and see if that fixes this issue? 

That error indicates vte3 is unable to make the syscall close_range, which indicates you are running a newer version of seccomp in the container than your host supports.

**Comment by gaoljhy** [comment]
Use xfce Terminal

```sh
apt install xfce4-terminal
```

chose default terminal for xfce4-terminal
