### ISSUE TITLE
How to go to the Download Folder

### ISSUE THREAD

**Issue by HumzzCopper** [kasmtech/workspaces-issues#252]
Hey! I am trying to download something and I uploaded it but I do not know how to access it
![image](https://user-images.githubusercontent.com/108969580/188146995-e00d7357-d2a9-4f32-a660-bdf3c755eaf4.png)

**Comment by j-travis** [comment]
ON the left hand side of the screen there is a little tab. When clicked it opens a control panel and there is a downloads menu.

Items that are placed in the Downloads directory from within the session will appear in that menu to re-download to your computer.

You can see an example workflow here: https://youtu.be/nBv7GCAbCPA?t=162

**Comment by HumzzCopper** [comment]
i know that but when i download something how do I access it because on the starting menu it does not have this 
![image](https://user-images.githubusercontent.com/108969580/188154105-c9e1bc58-0b14-4fc3-aa5f-227d16017bb8.png)

**Comment by HumzzCopper** [comment]
see look im trying to download stuff on the virtual desktop but I upload/download them but I do not know how to access them

**Comment by j-travis** [comment]
Click this 
![image](https://user-images.githubusercontent.com/48762190/188154396-bffc6c4a-7edc-44f7-9c35-a7230dc19024.png)

**Comment by HumzzCopper** [comment]
alright now what

**Comment by HumzzCopper** [comment]
hellooo?

**Comment by j-travis** [comment]
If you are using a single application workspace like chrome, when you download the file from within chrome ensure you put it in the Downloads folder. It should be the default anyway. If you right click the file and save it, you can double check the location.

After the file is downloaded, open the control panel from the left hand side, There should be a download menu. If there is not show a screenshot of what you see. 

You should then be able to download the file to your local PC

**Comment by HumzzCopper** [comment]
I am not trying to put the download on my pc I am trying to put it on the virtual pc

**Comment by j-travis** [comment]
I see, In that case, you should use a desktop workspace (e.g Ubuntu, Centos)  so you can interact with downloaded files within the Kasm session. The single application (e.g Chrome ) workspaces do not provide a full interactive desktop environment.

You can see how that works by trying the interactive Desktop Workspaces demo on our website: 
https://kasmweb.com/

Please be aware, these are Linux desktop containers -not full VMs, and when using the Cloud Personal service, you do not have administrative privileges within the sessions to install software.

If you want administrative privileges, you will need to deploy Kasm Workspaces yourself. You can start using our free community edition.
https://kasmweb.com/community-edition
