### ISSUE TITLE
Can't type backtick ` in kasm.

### ISSUE THREAD

**Issue by qt-engin** [kasmtech/workspaces-issues#253]
Is there a way to type backtick ( ` )  except clipboard in kasm?

**Comment by mmcclaskey** [comment]
It seems to work for me on MacOS with Chrome, standard US keyboard. What is your keyboard layout, operating system, browser, and language?

**Comment by qt-engin** [comment]
> It seems to work for me on MacOS with Chrome, standard US keyboard. What is your keyboard layout, operating system, browser, and language?

OS: MacOS Monterey, 
Browser: Brave, 
Layout: Turkish layout, 
OS Language: English
When i change the layout to US i am able to type backtick but not in turkish layout.

On MacOS i am able to type backtick with Option + , (comma) but kasm don't recognize it.

**Comment by mmcclaskey** [comment]
Does it work with IME Input mode turned on? It is an option in the session control panel.

![image](https://user-images.githubusercontent.com/5209269/189116889-36b67e4c-0d56-4b1f-9086-87e11b4c8ee2.png)

**Comment by qt-engin** [comment]
Yes, it's working with IME Input Mode on.
Thank you @mmcclaskey

**Comment by sitolam** [comment]
I have the same issue I tried to enable IME Input Mode but it still doesn't work. I have a us keyboard with deadkeys. I also can't type `'`.
