### ISSUE TITLE
 Zone (default) is configured with dynamic property $request_host$ as the Upstream Auth Address or Allow Origin Domain. This is not compatible with session staging.

### ISSUE THREAD

**Issue by Luxosity** [kasmtech/workspaces-issues#254]
Hello! I set up a new Kasm server that is behind an NGINX proxy (on a different server). I set up Kali Linux to be staged using the default zone. I noticed many errors in the logs saying " Zone (default) is configured with dynamic property $request_host$ as the Upstream Auth Address or Allow Origin Domain. This is not compatible with session staging." What exactly should I put in place of "$request_host$" for the "Allow Origin Domain" field to stop these errors?

10.23.10.136 is my Kasm Server IP

![msedge_RbBsDraQgH](https://user-images.githubusercontent.com/48502385/188792457-e7400f6c-5e70-485d-95e8-ebafd9a56cbb.png)

Thank you!

**Comment by j-travis** [comment]
@Luxosity , `Allow Origin Domain` should be the **host** portion of the URL you access kasm via. 

So if you access it via it (e.g `https://192.168.1.2` ) then  it should  be `192.168.1.2` 

If you access it via domain name  (e.g `https://kasm.example.com`) then it should be `kasm.example.com`

`Upstream Auth Address` should be the ip of your Kasm server as it is currently configured

**Comment by Luxosity** [comment]
@j-travis It looks like that was it. I appreciate the quick response!

Thanks!
