### ISSUE TITLE
Slow downloads

### ISSUE THREAD

**Issue by ianengelbrecht** [kasmtech/workspaces-issues#255]
I'm using Kasm to access and make backups of a MySQL database on a remote server. I log into Kasm, make a backup of the database to the Downloads folder, and then download to my laptop. The backups are typically 500 MB to 1.2GB in size, but I'm experiencing excessively long download times for these files. A 500MB file takes about an hour to download (downloading similarly sized files from other online sources typically only takes a few minutes). Furthermore, it seems like the download places strain on my processor - the fan starts running, and doesn't stop even long after the download has completed. Is there a Kasm setting or something I need to change to get this working?

(Kasm was set up by our sysadmin, not myself, and so I will have to relay any information provided here to him)

**Comment by mmcclaskey** [comment]
In my testing, it took 43 seconds for me to download a 500MB file from a Kasm deployment to my local system. There is nothing special about the downloads in Kasm, from the browser's perspective, it is a link to a static file and the browser downloads it the same as it would any other file. That being said, there is no reason a download would cause excessive CPU utilization. If you using the Kasm session at the time and there was a lot of movement on the screen, this would cause high CPU utilization, especially on older or underpowered systems. 

I couldn't really guess as to why your downloads are slow, but I would say that has a lot more to do with either your local network, the network that Kasm server side is deployed on, or the server that Kasm is deployed on than it does with any Kasm specific software. Perhaps Kasm is deployed on a server with HDD spinning disks versus SSDs, just taking guesses.

**Comment by ianengelbrecht** [comment]
Thank you @mmcclaskey, I'll investigate further on the server then
