### ISSUE TITLE
Offline Installation 

### ISSUE THREAD

**Issue by ecsuae** [kasmtech/workspaces-issues#256]
I am trying to setup Kasm on privileged lxc container, Installation starts smoothly but when downloading workspace images it waits for hours, keeps on downloading again and again the same images until i get error no space left.My container has 75GB hdd 8GB Memory, 6 core cpu and 8 GB swap.
i see in documentation there is offline installation method but i cannot get kasm_release_workspace_images*.tar.gz file anywhere.Can some one guide me where i can download that file or is there any installation procedure to install Kasm with limited or selected workspace images?
In the end i would like to thank kasm team for such a remarkable project.

**Comment by j-travis** [comment]
1. The offline workspaces images tgz is available on our downloads page (https://kasmweb.com/downloads) in the **Other Downloads** section.
![image](https://user-images.githubusercontent.com/48762190/189500018-a5eb9b85-7f88-4b43-93c1-20e1c9331b6a.png)

2. You can choose to not install any images during the install by passing `-I` , or you can customize the list that is installed by modifying the seed file after extracting the installer but before running `install.sh` . The seed files are located at `kasm_release/conf/database/seed_data/default_images_amd64.yaml` and `kasm_release/conf/database/seed_data/default_images_arm64.yaml`


However , your main issue is almost certainly this: (https://github.com/kasmtech/workspaces-issues/issues/244) - Docker in LXC can be horribly inefficient with disk space depending on your storage driver configuration - causing your drive to fill up

**Comment by ecsuae** [comment]
Thank you for your support.I followed the your instructions and downloaded kasm_release_workspace_images_amd64_1.11.0.18142e.tar.gz file  and tried to install kasm offline with following command:

bash kasm_release/install.sh -w kasm_release_workspace_images_amd64_1.11.0.18142e.tar.gz -s /tmp/kasm_release_workspace_images_amd64_1.11.0.18142e.tar.gz

Installation starts and after some time it stopped with a error message :

Creating docker network kasm_default_network
8b700111fdcc7c8e5662446169de2cb0a810259fc5966b8624c8274f686ecf5b
kasm_release/install.sh: line 585: /tmp/kasm_release/service_images/images.txt: No such file or directory 
i tried to locate service_images folder but it is not there 
/tmp# ls -la /tmp/kasm_release/
total 43
drwxr-xr-x  9 root root    12 Sep 10 21:38 .
drwxrwxrwt 13 root root    15 Sep 10 21:38 ..
drwxr-xr-x  3 root root     5 Jul  8 03:25 bin
drwxr-xr-x  5 root root     5 Jul  8 03:25 conf
drwxr-xr-x  2 root root     9 Jul  8 03:25 docker
-rwxr-xr-x  1 root root 43536 Jul  8 03:25 install.sh
-rw-r--r--  1 root root  7254 Jul  8 03:25 install_dependencies.sh
drwxr-xr-x  2 root root    16 Jul  8 03:25 licenses
drwxr-xr-x  2 root root     4 Jul  8 03:25 profiles
-rwxr-xr-x  1 root root 11044 Jul  8 03:25 upgrade.sh
drwxr-xr-x  2 root root     8 Jul  8 03:20 workspace_images
drwxr-xr-x  5 root root    10 Jul  8 03:25 www

Can you please guide how to fix this problem?

**Comment by j-travis** [comment]
The offline services images are a different package and are also available on the same downloads page. 
The instructions for running the offline install are on our main install docs page : https://kasmweb.com/docs/latest/index.html

You don't need to use the offline install packages if you have internet access and/or want to modify the seed yaml.

In any event, you may still have storage issues if you are running docker in an LXC  if you are using VFS as your storage driver per my previous comment.  See https://github.com/kasmtech/workspaces-issues/issues/244
