### ISSUE TITLE
Image with "--add-host" option raise an error

### ISSUE THREAD

**Issue by octave21** [kasmtech/workspaces-issues#259]
A kasm-agent error is thrown when I try to use the "--add-host" option  within the "Docker Run Config Override (JSON)" of my DinD image.
{"environment":{"LANGUAGE":"fr_FR.UTF-8","LC_ALL":"fr_FR.UTF-8","LANG":"fr_FR.UTF-8"},"privileged":true,"hostname":"vpcjfc","add-host":"somehost:172.100.0.13"}

host: proxy
ingest_date: 202209191854
application: kasm_agent
levelname: ERROR
message: Exception creating Kasm: Traceback (most recent call last): File "__init__.py", line 481, in post File "provision.py", line 698, in provision File "docker/models/containers.py", line 811, in run File "docker/models/containers.py", line 869, in create File "docker/models/containers.py", line 1085, in _create_container_args TypeError: run() got an unexpected keyword argument 'add-host' Traceback (most recent call last): File "__init__.py", line 481, in post File "provision.py", line 698, in provision File "docker/models/containers.py", line 811, in run File "docker/models/containers.py", line 869, in create File "docker/models/containers.py", line 1085, in _create_container_args TypeError: run() got an unexpected keyword argument 'add-host'
process: __main__.handler

**Comment by mmcclaskey** [comment]
I believe what you are looking for is "extra_hosts" as opposed to "add-host". We use the [Python Docker SDK](https://docker-py.readthedocs.io/en/stable/containers.html), which doesn't necessarily match 1 to 1 with command line options.

**Comment by octave21** [comment]
You are right, the extra_hosts option adds entries to the /etc/hosts file. The issue is closd
Thanks
