### ISSUE TITLE
Why is the volume mounted on the container nested in the DinD image mounted as root?

### ISSUE THREAD

**Issue by octave21** [kasmtech/workspaces-issues#260]
When I run a container nested in a Kasm DinD image (available here #262), with a mounted volume, this volume is root within the container and kasm-user outside the container. My thought is that the volume should be kasm-user within the container.

## Dockerfile
FROM debian:bullseye-slim
MAINTAINER octave21@orange.fr
RUN useradd -u 1000 kasm-user
RUN mkdir -p /home/kasm-user/data
RUN chown -R kasm-user:kasm-user /home/kasm-user/data
WORKDIR /home/kasm-user
USER kasm-user
CMD sleep 3600

## Bash commande : 
docker build -t sandboxi . && docker run  --volume /home/kasm-user/data:/home/kasm-user/data  --name sandboxc -d sandboxi && docker exec -it -u$(id -u) sandboxc bash -c "ls -l" && ls -l ~ | grep data  && docker stop sandboxc && docker rm sandbox

## Output of the command executed from the DinD container : 
drwxrwxrwx 2 root root 4096 Sep 16 17:04 data
drwxrwxrwx 2 kasm-user kasm-user     4096 sept. 16 19:04 data

## Output of the command executed from the host running Kasm  : 
drwxr-xr-x 2 kasm-user kasm-user 4096 Sep 20 13:44 data
drwxr-xr-x 2 kasm-user kasm-user 4096 20 sept. 15:44 data

**Comment by j-travis** [comment]
It looks like you are running into a quirk in docker in that if you mount a volume into a container , and the path on the host does not already exist, docker will create it and chown it as root. AFAIK there is no way to change that behavior.

This is a general docker thing and isnt specific to Kasm or the fact that you are running docker in docker.

So, before you run the container, make sure you create the directory and ensure the ownership is what you desire.

```
default:~$ mkdir /home/kasm-user/data
default:~$ chown -R kasm-user:kasm-user /home/kasm-user/data
default:~$ docker run -it --rm  --volume /home/kasm-user/data:/home/kasm-user/data sandboxi bash
kasm-user@06fb82f63487:~$ ls -la /home/kasm-user/data/
total 8
drwxr-xr-x 2 kasm-user kasm-user 4096 Oct  2 19:36 .
drwxr-xr-x 3 root      root      4096 Oct  2 19:36 ..
kasm-user@06fb82f63487:~$ touch /home/kasm-user/data/foo
```

As a side note, if always plan on mounting in the directory you may consider removing the following lines from your Dockerfile as they arent applicable and may only serve to confuse you since you'll always be at the mercy of permissions on the folder as they exist on the containers host

```
RUN mkdir -p /home/kasm-user/data
RUN chown -R kasm-user:kasm-user /home/kasm-user/data
```

**Comment by octave21** [comment]
Thank you for your analysis. Unfortunately when I run exactly the commands you suggest, including the side note, the directory is mounted root instead of kasm-user. According to you what did I miss ?

Below is the console trace, knowing that the host is a custom Dind image #262  of the Kasm workspaces.

#### Build on the host
`kasm-user:~/Documents/docker$ docker build -t sandboxi .`
`Sending build context to Docker daemon  381.7MB`
`Step 1/6 : FROM debian:bullseye-slim`
`---> 6a8065e4ba13`
`Step 2/6 : MAINTAINER octave21@orange.fr`
`---> Using cache`
`---> 07f3a0ec3dcc`
`Step 3/6 : RUN useradd -u 1000 kasm-user`
`---> Using cache`
`---> 6e274f5ddbdf`
`Step 4/6 : WORKDIR /home/kasm-user`
`---> Using cache`
`---> 6e76d291c55d`
`Step 5/6 : USER kasm-user`
`---> Using cache`
`---> 498c95ec3e21`
`Step 6/6 : CMD sleep 3600`
`---> Using cache`
`---> 0e434b7766ba`
`Successfully built 0e434b7766ba`
`Successfully tagged sandboxi:latest`

#### Make a new directory on the host
`kasm-user:~/Documents/docker$ mkdir /home/kasm-user/data`
`kasm-user:~/Documents/docker$ ls -la /home/kasm-user/data`
`total 8`
`drwxr-xr-x  2 kasm-user kasm-user 4096 oct.   3 18:36 .`
`drwxrwxrwx 34 kasm-user kasm-user 4096 oct.   3 18:36 ..`
`kasm-user:~/Documents/docker$ id`
`uid=1000(kasm-user) gid=1000(kasm-user) groupes=1000(kasm-user),126(docker)`

#### Docker run
`kasm-user:~/Documents/docker$ docker run -it --rm  --volume /home/kasm-user/data:/home/kasm-user/data sandboxi bash`

####  Check owner within the container
`kasm-user@ea457e6daf06:~$ ls -la /home/kasm-user/data/`
`total 8`
`drwxr-xr-x 2 root root 4096 Oct  3 16:36 .`
`drwxr-xr-x 1 root root 4096 Oct  3 16:37 ..`
`kasm-user@ea457e6daf06:~$ touch /home/kasm-user/data/foo`
`touch: cannot touch '/home/kasm-user/data/foo': Permission denied`
`kasm-user@ea457e6daf06:~$ id`
`uid=1000(kasm-user) gid=1000(kasm-user) groups=1000(kasm-user)`
`kasm-user@ea457e6daf06:~$`

**Comment by j-travis** [comment]
I tested with this image: kasmweb/ubuntu-focal-dind:1.11.0

Can you try?

**Comment by octave21** [comment]
Yes I will

**Comment by octave21** [comment]
With the image kasmweb/ubuntu-focal-dind:1.11.0 the owner of the directory ~/data is correctly set to kasm-user :-)
But with the image kasmweb/ubuntu-focal-dind-rootless:1.11.0-rolling that I usually use, the owner of the directory ~/data is set to root :-(

**Comment by octave21** [comment]
For your information, I have noticed significant differences in behavior between the DinD root image and the DinD rootless image :

1. On the root image, the volumes are correctly mounted with a non-root owner, while on the rootless image the volumes are mounted with a root owner (subject of this post).
2. On the root image, the build time of an image is extremely important, many minutes, while on the rootless image few seconds are enough.
3. On the root image, the images are not persistent while they are on the rootless image.

**Comment by j-travis** [comment]
1. This has to do with docker rootless using namespace remapping : https://docs.docker.com/engine/security/rootless/
2. This is likely due to the versions using different storage drivers.
3. The default data directory for docker rootless is within the users home directory which is why the images persist when using persistent profiles. The default data directory for regular docker is /var/lib/docker which is not covered by the persistent profile feature

**Comment by octave21** [comment]
Thanks
