### ISSUE TITLE
Stream an image that supports the docker runtime?

### ISSUE THREAD

**Issue by HarrisKirk** [kasmtech/workspaces-issues#262]
I want to use kasm cloud workspace to launch an image that contains a docker runtime (ie, docker within docker) to run a docker container.   Is that possible?   Trying to use an OS (such as Ubuntu) does not have docker nor does it have sudo to install docker.

**Comment by octave21** [comment]
Please find the [custom](https://www.kasmweb.com/docs/latest/how_to/building_images.html) Kasm dockerfile I made that provides an Ubuntu desktop with xfce + docker + some usefull applications. The use case of this Kasm image is to provide a remote virtual PC reachable from a regular browser. 
- On the host that runs Kasm, build the dockerfile `docker build -t vpcdind:stable  .`
- Via Kasm admin add the image vpcdind and set Run Config `{"environment":{"LANGUAGE":"fr_FR.UTF-8","LC_ALL":"fr_FR.UTF-8","LANG":"fr_FR.UTF-8"},"privileged":true}` 
- If you are using an Android device with an external keyboard, you will have to manage key mapping within xfce (at the end of #215)

## Dockerfile
`# Création d'un PC virtuel Ubuntu avec docker intégré`
FROM kasmweb/ubuntu-focal-dind-rootless:1.11.0-rolling
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

`######### Customize Container Here ###########`


`# Applications`
RUN add-apt-repository ppa:libreoffice/libreoffice-6-4
RUN apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y language-pack-fr language-pack-fr-base language-pack-gnome-fr language-pack-gnome-fr-base gimp-help-fr \
    && apt-get install -y geany \
    && apt-get install -y gimp \
    && apt-get install -y default-jre \
    && apt-get install -y firefox \
    && apt-get install -y evince \
    && apt-get install -y vlc \
    && apt-get install -y eog \
    && apt-get install -y libreoffice libreoffice-l10n-fr openclipart*-libreoffice hyphen-fr libreoffice-help-fr mythes-fr fonts-crosextra-caladea \
    && apt-get install -y iputils-ping traceroute \
    && apt-get install -y galculator \
    && apt-get install -y locales \
    && apt-get install -y python3-pip \
    && apt-get install -y git \
    && apt-get install -y onboard \
    && apt-get install -y docker-compose \
    && apt-get install -y xfce4-systemload-plugin \
    && apt-get install -y sweethome3d \
    && apt-get install -y fail2ban

`# Time & Locales & langues`
RUN echo "fr_FR.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen fr_FR.UTF-8
RUN update-locale LANG=fr_FR.UTF-8 LANGUAGE=fr_FR LC_ALL=fr_FR.UTF-8  
ENV LC_ALL fr_FR.UTF-8
ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR.UTF-8
RUN cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

`# User`
RUN sed -i -e "s/KASM_USER:-default/KASM_USER:-kasm-user/" $STARTUPDIR/generate_container_user
RUN gpasswd -a kasm-user docker

`# Workarounds`
RUN echo "\nexport LD_LIBRARY_PATH=/usr/lib/libreoffice/program" >> $STARTUPDIR/generate_container_user

`# Tests & bidouilles`


`######### End Customizations ###########`

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME
ENV HOME /home/kasm-user
WORKDIR $HOME

USER 1000

`# Build :         docker build -t vpcdind:stable -f dockerFileVpcDind .`
`# Inside root :   docker exec -it -u0 nom_container bash`

![Screenshot_20220921-030236_Opera](https://user-images.githubusercontent.com/25460917/191391583-b053294c-44e5-4732-9334-00f4104e8d22.jpg)

**Comment by j-travis** [comment]
Thank you @octave21 .

@HarrisKirk , we also publish pre-built images to run Docker in Kasm sessions. Please see the documentation for how to configure it:
https://kasmweb.com/docs/latest/how_to/docker_in_kasm.html

**Comment by HarrisKirk** [comment]
@j-travis Does the approach you suggest work in the paid Cloud Workspaces (ie, https://app.kasmweb.com/#/userdashboard) ?

**Comment by j-travis** [comment]
> @j-travis Does the approach you suggest work in the paid Cloud Workspaces (ie, https://app.kasmweb.com/#/userdashboard) ?

No, you cannot add custom images or have root privs on app.kasmweb.com.  You'll need to self-host Workspaces in order to have that level of control.  You can start with our free community edition https://kasmweb.com/community-edition.
