### ISSUE TITLE
Feature suggestion: container naming with username

### ISSUE THREAD

**Issue by tiaden** [kasmtech/workspaces-issues#263]
I would like to suggest that kasm container names contains the username for easy identification in tools like portainer or with the command `docker ps`.
Right now when I want to troubleshoot with a user and need to access his container, there is no easy way for to identify the target user container. I usually inspect container one after the other which is not convenient

**Comment by j-travis** [comment]
Thank you for the feedback. 
This is coming in the next release ( Late October)

It is currently available in the developer preview builds if you'd like to test it out:

https://kasmweb.com/docs/latest/developers/builds.html

**Comment by tiaden** [comment]
Great ! thank you. I will try it out !

**Comment by tiaden** [comment]
@j-travis I'm sorry to reopen this but I have quick question. 
is the next release still planned for late October ? There are fixes in the next release regarding gpu and container naming that I want to deploy in our production environment. No pressure of course !

**Comment by j-travis** [comment]
Sorry, it looks like the release will slip a bit to mid November

**Comment by tiaden** [comment]
Thank you ! I will plan accordingly
