### ISSUE TITLE
Wish to create a Godot Engine Editor demo

### ISSUE THREAD

**Issue by fire** [kasmtech/workspaces-issues#264]
Hi,

I was thinking of creating a godot engine desktop editor image for fun.

What are the steps to do this?

Feel free to use this a reason to document making Kasm any game.

**Comment by j-travis** [comment]
Hello,
You will want to start by learning how to build custom images. Here are some resources to get you started:

- Docs: https://kasmweb.com/docs/latest/how_to/building_images.html
- Video Tutorial: https://youtu.be/BGP69_f1wq0

Due to the nature of your application, you almost certainly want to use GPU acceleration, you can do this with Kasm but it requires some additional setup. Here is a guide for configuring and testing GPU graphics acceleration. 

-  https://kasmweb.com/docs/latest/how_to/gpu.html


It looks like the linux install is very simple for Godot ( just extract and install) so it should be pretty straight forward to build an image once you get through the previous tutorials.  Unzipping and running in on our `kasmweb/ubuntu-focal-desktop:1.11.0`  image works fine when GPUs are enabled



![image](https://user-images.githubusercontent.com/48762190/191991392-c7bb65f0-9e01-46ac-a1bf-1234b71967b2.png)

**Comment by fire** [comment]
@j-travis I was able to get the workspace loaded but the ubuntu focus image appears to be lacking the vulkan sdk.

Edited:
https://github.com/NVIDIA/nvidia-docker/wiki/#is-vulkan-supported

Edited 2 Force install vulkan sdk:
https://gitlab.com/nvidia/container-images/vulkan/blob/ubuntu16.04/Dockerfile

**Comment by j-travis** [comment]
Ok,
In that case, it looks like you'll have to build a custom image that includes the Vulkan SDK

It may be helpful to know that we currently publish an image based on the nvidia cuda image (`nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04`) .  Taking a quick look at the latest dockerfile for the vulkan SDK it should be able to be wired in nicely. (https://gitlab.com/nvidia/container-images/vulkan/-/blob/master/docker/Dockerfile.ubuntu) 


- https://hub.docker.com/r/kasmweb/core-cuda-focal
- https://github.com/kasmtech/workspaces-core-images/blob/develop/.gitlab-ci.yml#L82


Please let us know if you get something working

**Comment by fire** [comment]
[core-cuda-focal](https://hub.docker.com/r/kasmweb/core-cuda-focal) based on `nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04` doesn't work. I think it's llvmpipe renderer or something. Don't have diagnostic tools and both the scene and the fox crash.

> Vulkan API 1.2.131 - Using Vulkan Device #1: Unknown - llvmpipe (LLVM 14.0.5, 256 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

![image](https://user-images.githubusercontent.com/32321/192328423-7e8db7e6-9a92-42e3-ba2f-9efcb9285a03.png)


I wish to have `firefox` and `vulkaninfo` programs installed. 

### References

1. https://www.intel.com/content/www/us/en/developer/topic-technology/graphics-research/samples.html
2. https://downloads.tuxfamily.org/godotengine/4.0/beta1/
3. https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Fox/glTF-Binary/Fox.glb

**Comment by fire** [comment]
Secondly, I don't know you if you oversubscribe gpus or tag gpus to be for specific images.

**Comment by j-travis** [comment]
I was able to get the basics working.

0. Ensure the host is running cuda / vulkan sdk and both nvidia-smi and vulkaninfo are reporting back discreet GPU support

1. Clone https://gitlab.com/nvidia/container-images/vulkan/-/tree/master and build the image making sure the cuda and vulkan sdk versions match the host.

```
sudo docker build --pull -t \
   nvidia/vulkan:1.3-470 \
   --build-arg BASE_DIST=ubuntu20.04 \
   --build-arg CUDA_VERSION=11.6.2 \
   --build-arg VULKAN_SDK_VERSION=`curl -sk https://vulkan.lunarg.com/sdk/latest/linux.txt` \
   --file docker/Dockerfile.ubuntu .
```

2. Clone https://github.com/kasmtech/workspaces-core-images and build an image using the vulkan image as the base

```
sudo docker build -t kasmweb/vulkan:dev --build-arg START_PULSEAUDIO=1 --build-arg BASE_IMAGE="nvidia/vulkan:1.3-470" --build-arg START_XFCE4=1 f dockerfile-kasm-core .
```

3. Load it up in workspaces with the following settings. These map to what is requested in the vulkan docs (https://gitlab.com/nvidia/container-images/vulkan/-/blob/master/README.md?plain=1#L46). My host is ubuntu 20 so some of the configs you have to map in get installed into a different location. There is a note that these mappings may not be needed in the future if/when the nvidia docker container runtime is updated

**Docker Run Config Override**
```
{
  "environment": {
    "NVIDIA_DISABLE_REQUIRE": "1",
    "NVIDIA_DRIVER_CAPABILITIES": "all"
  }
}
```

**Volume Mapping**

```
{
  "/usr/share/vulkan/icd.d/nvidia_icd.json": {
    "bind": "/etc/vulkan/icd.d/nvidia_icd.json",
    "mode": "ro",
    "uid": 1000,
    "gid": 1000,
    "required": true,
    "skip_check": true
  },
  "/usr/share/vulkan/implicit_layer.d/nvidia_layers.json": {
    "bind": "/etc/vulkan/implicit_layer.d/nvidia_layers.json",
    "mode": "ro",
    "uid": 1000,
    "gid": 1000,
    "required": true,
    "skip_check": true
  },
  "/usr/share/glvnd/egl_vendor.d/10_nvidia.json": {
    "bind": "/usr/share/glvnd/egl_vendor.d/10_nvidia.json",
    "mode": "ro",
    "uid": 1000,
    "gid": 1000,
    "required": true,
    "skip_check": true
  }
}
```

**GPUS**
`1`


4. For `vulkaninfo` to run, you must unset the DISPLAY environment variable `DISPLAY= vulkaninfo` . This seems to be a quirk with the nvidia driver. I believe some of it is discussed here . https://forums.developer.nvidia.com/t/headless-vulkan-with-multiple-gpus/222832 . It looks like the quirk also limits the use to a single GPU


The 4.x beta of Godot loads as well as the intel sponza scene as shown.  If you get this far and have a working "Core" image for Kasm, you can easily use that to build your custom image with godot / firefox etc.  Examples for firefox are in https://github.com/kasmtech/workspaces-images

![image](https://user-images.githubusercontent.com/48762190/192533499-a5a9611e-1362-4072-941e-0f65dc9b7c8f.png)

**Comment by fire** [comment]
Do you know if using wayland will bypass the xorg limitation listed earlier? I don't know the landscape of wayland - nvidia support. The last news was the code was opensourced, but the linux kernel needs to get updates in the current linux distro.

**Comment by j-travis** [comment]
Honestly I'm not sure, but KasmVNC is pretty heavily tied to X atm, so its not really a feasible path in the short term for us even if it did.  I also haven't personally validated the limitations claimed with multiple GPUs

What is your ultimate goal? 

I'd be interested to know if the solution, as is, provides a suitable development environment for your work.  As you may have seen from our recent updates, we are trying to provide a convenient, and cost-effective ways to conduct hardware accelerated work via remotely accessible containers. Getting feedback from folks like you is very valuable to that effort.

**Comment by fire** [comment]
I have an expensive rtx card, I wanted to know if I have to have one gpu per kasm guest.

This is a blocker for use due to cost.

**Comment by j-travis** [comment]
Yes, you can share a single GPU with multiple Kasm sessions.

This video and docs explains how resources management works:
- https://kasmweb.com/docs/latest/how_to/gpu.html#resource-management
- https://www.youtube.com/watch?v=lv85XZ8EdjY

but in short, set your image to require 1 GPU, then edit your Agent GPU Override setting to  say, 4.  All other things being equal you can share the single GPU with 4 simultaneous sessions. Adjust as you see fit.

**Comment by AxionQc** [comment]
> 1. Clone https://gitlab.com/nvidia/container-images/vulkan/-/tree/master and build the image making sure the cuda and vulkan sdk versions match the host.
> 
> ```
> sudo docker build --pull -t \
>    nvidia/vulkan:1.3-470 \
>    --build-arg BASE_DIST=ubuntu20.04 \
>    --build-arg CUDA_VERSION=11.6.2 \
>    --build-arg VULKAN_SDK_VERSION=`curl -sk https://vulkan.lunarg.com/sdk/latest/linux.txt` \
>    --file docker/Dockerfile.ubuntu .
> ```
This container is heavily outdated, is there any update for this that could make Vulkan work? i need it for Unity HDRP

@j-travis Just in case
