### ISSUE TITLE
Root access /Ubuntu & Kali 

### ISSUE THREAD

**Issue by popasquat** [kasmtech/workspaces-issues#267]
Trying to get educated and understand what I can and cannot do within each workspace. When running Ubuntu, why are you not able to run as root for installation of apps/commands etc.? Using Kali I'm able to add the JSON command {"user":"root"} in order to run as root. Curious as to why both instances you are not able to run root in the environment. 

Thank you in advance for the reply.

**Comment by j-travis** [comment]
Hi,
Hopefully our documentation answers your question.
https://kasmweb.com/docs/latest/how_to/running_as_root.html


You should be able to run any of the images as root, including the ubuntu ones. 
The only difference between Kali and the others, is that Kali include the sudo package by default whereas the others do not. There is no default sudo password so you still need to run the Kali container as root, or follow the docks to properly configure sudo to work in your image without a password.

**Comment by docsewell** [comment]
I'm testing Personal Cloud, OSINT edition.  I am able to do a `sudo -i` and get root from RemNux, but not Kali or Ubuntu.  On those, I'm prompted for the password for the kasm user.
