### ISSUE TITLE
how to disable kasm session idle logout after 20 minutes

### ISSUE THREAD

**Issue by jamieduk** [kasmtech/workspaces-issues#268]
how to disable kasm session idle logout after 20 minutes

**Comment by j-travis** [comment]
There is a group setting called `idle_disconnect`
https://kasmweb.com/docs/latest/guide/groups/group_settings.html?highlight=idle_disconnect

You can learn more about group settings here:
- https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s
