### ISSUE TITLE
Fixing the no internet from inside kasm desktop ubuntu issue!

### ISSUE THREAD

**Issue by jamieduk** [kasmtech/workspaces-issues#269]
Internet was working for me in a virtual machine only for the workspaces but wouldnt update or install without adding a second network adapter (nat) then after disabling the standard network adapter inside kasm vm settings i got the internet working for updating installing etc, before re-enabling the other default network and letting workspaces internet connection work again!

this is a bug / glitch that needs solving but this works as a walk around!

**Comment by j-travis** [comment]
I'm having a hard time understanding exactly what the issue is here.

This sounds like a general OS / Hypervisor issue which Kasm has no control over.
