### ISSUE TITLE
sound bug / glitch

### ISSUE THREAD

**Issue by jamieduk** [kasmtech/workspaces-issues#270]
using open with kasm link opens tor browser great and it works but there is no sound until i use the left hidden menu to disable and then re-enable thge sound to get it to work, that fixes the audio everytime!

this should be an easy bug to fix just make it auto disable audio then re-enable audio to save the user time and hassel!

**Comment by j-travis** [comment]
You may recall a time of the internet when webpages often blasted MIDI music as soon as you visited the page. This was very annoying so browser implemented controls such that a page cant play audio unless a user explicitly does an action on the page like clicking a button.

This prevents us from automatically playing audio when a user visits opens a session. For the record, some browsers have heuristics that will change how they behave based on how popular a site is or how often you visit / interact with it. So this can lead to inconsistent results.

However, what "should" happen when you visit a Kasm session, is that as soon as you click anywhere inside the session (not the control panel) we try and "unlock" and start the audio.

You can see these messages in the developer console.

![image](https://user-images.githubusercontent.com/48762190/193466131-2eaf03ab-a7f8-4186-a03e-5c8894c75bc8.png)

If you are not seeing this behavior please report the OS / Version and browser / version you are using

**Comment by j-travis** [comment]
No response from user, closing
