### ISSUE TITLE
the kasm window itself has no option in hidden side menu for full-screen

### ISSUE THREAD

**Issue by jamieduk** [kasmtech/workspaces-issues#271]
the kasm window itself has no option in hidden side menu for full-screen

for example watching yt via a tor browser kasm session works and full screens but kasm window itself does not have an option to aswell full screen so there are things visable while attempting to full screen.

**Comment by j-travis** [comment]
Thank you for the feedback,
We may add this in the future, but there are a number of quirks with how browsers behave when full screen is invoked from a webpage . For example, pressing esc may cause the browser to break you out of full screen which is often very annoying.  It's almost always a better experience for the user invoke full screen from the browser controls instead.

**Comment by j-travis** [comment]
@jamieduk , We've now introduced a fullscreen button to the control panel menu.  It will be in the next release, but it is also available now in the developer preview builds if you want to try it out.

https://kasmweb.com/docs/latest/developers/builds.html

https://kasmweb.com/docs/develop/user_guide/control_panel.html#fullscreen
