### ISSUE TITLE
[BUG] KasmWeb Discord ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by BlackYuzia** [kasmtech/workspaces-issues#276]
Hi there.
I try run a docker container with `kasmweb/discord:1.11.0-rolling` [**image**](https://hub.docker.com/r/kasmweb/discord).
Then I open `http://ip:6901` url, but I get **ERR_EMPTY_RESPONSE** error on this page.

**Did I do something wrong?**

Latest logs
![image](https://user-images.githubusercontent.com/25010528/195978662-87abe1bb-31cd-4885-a1e5-9ae6f90c831e.png)

Docs: https://hub.docker.com/r/kasmweb/discord

**Comment by j-travis** [comment]
Hi,
You need to try and  connect over HTTPS, not HTTP , e.g  `https://ip:6901`


Failing that, can you try running the container manually using the command referenced in the Stand-Alone Deployment Section

> ```
> sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/discord:1.11.0
> ```
> The container is now accessible via a browser : https://IP_OF_SERVER:6901
> 
> User : kasm_user
> Password: password

**Comment by BlackYuzia** [comment]
I try go to https://ip:6901 and get the same.
![image](https://user-images.githubusercontent.com/25010528/197352637-ba1e81e9-d281-4776-b02d-35ab500c064a.png)

After run
```bash
sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/discord:1.11.0
```
 I get this:
![image](https://user-images.githubusercontent.com/25010528/197352625-a7dabef0-0211-4f4a-a0e2-279892b241ad.png)
and the same on https://ip:6901
![image](https://user-images.githubusercontent.com/25010528/197352635-9fa9be78-6558-4a52-bc04-a88a2c0f8fbd.png)

**Comment by BlackYuzia** [comment]
I try go to https://ip:6901 and get the same.
![image](https://user-images.githubusercontent.com/25010528/197352637-ba1e81e9-d281-4776-b02d-35ab500c064a.png)

After run
```bash
sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/discord:1.11.0
```
 I get this:
![image](https://user-images.githubusercontent.com/25010528/197352625-a7dabef0-0211-4f4a-a0e2-279892b241ad.png)
and the same on https://ip:6901
![image](https://user-images.githubusercontent.com/25010528/197352635-9fa9be78-6558-4a52-bc04-a88a2c0f8fbd.png)


@j-travis

**Comment by j-travis** [comment]
Hm, I'm not completely sure, but it may be an issue with the TSL/SSL cipher supported by your browser and/or any networking devices in between.

What OS/Version and Browser/Version are you using. Can you try a different browser?

- Can you successfully connect to the demo session listed in the description here?: https://hub.docker.com/r/kasmweb/discord
- Can you try using the `:develop` tagged image:  `sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/discord:develop`

**Comment by BlackYuzia** [comment]
> Can you successfully connect to the demo session listed in the description here?: https://hub.docker.com/r/kasmweb/discord

Did you mean live demo?
![image](https://user-images.githubusercontent.com/25010528/197353627-c387da5f-ecb5-4fbb-92ac-a2837592ef4d.png)
Suppose is work's
![image](https://user-images.githubusercontent.com/25010528/197353647-931d6bcc-a4f1-44c3-b6da-d2da57787e40.png)

~~I also try use `:develop` currently~~

UPD:
`:develop` (branch?) result:
![image](https://user-images.githubusercontent.com/25010528/197353777-000a8f16-2271-4c76-9315-2cb01bfb6375.png)
![image](https://user-images.githubusercontent.com/25010528/197353780-e8156f87-108b-4a0c-955a-50caac0e5c6b.png)
also **ERR_EMPTY_RESPONSE** the same

**Comment by BlackYuzia** [comment]
Don't sure did this issue is completed.
