### ISSUE TITLE
Standard Installation script OpenSSL fail

### ISSUE THREAD

**Issue by diasdmhub** [kasmtech/workspaces-issues#277]
Test system used: **Oracle Linux 8 LXC**
```
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.6"
```
```
$ uname -rsm
Linux 5.15.60-1-pve x86_64
```

I have found what I believe is an issue with the `standard` installation script where it completely stops with no error message.

After starting the script, it installs all dependencies correctly and checks for Docker support followed by Swap existence, after which it stops completely, as shown at the output bellow.
> I have read and accept End User License Agreement (y/n)? y
> Checking if docker and docker compose are installed.
> Docker is installed
> 20.10.19 is a supported version of docker.
> Docker compose is installed
> 2.5.0 is a supported version of docker compose
> Commands docker and docker compose detected.
> Skipping Dependency Installation.
> Swap Exists

It stops right after that "`Swap Exists`" message and returns to the system prompt.

Upon inspecting the script, I found that an Openssl command was failing at line 917 since it was not installed.
```
openssl req -x509 -nodes -days 1825 -newkey rsa:2048 -keyout ${KASM_INSTALL_BASE}/certs/kasm_nginx.key -out ${KASM_INSTALL_BASE}/certs/kasm_nginx.crt -subj "/C=US/ST=VA/L=None/O=None/OU=DoFu/CN=$(hostname)/emailAddress=none@none.none" 2> /dev/null
```

Also, at line 248, it was not generating the DB certification.
```
openssl req -x509 -nodes -days 1825 -newkey rsa:2048 -keyout ${KASM_INSTALL_BASE}/certs/db_server.key -out ${KASM_INSTALL_BASE}/certs/db_server.crt -subj "/C=US/ST=VA/L=None/O=None/OU=DoFu/CN=$(hostname)/emailAddress=none@none.none" 2> /dev/null
```

To solve the issue, I installed OpenSSL and the installation went on again.

I believe OpenSSL should be included in the "`install_dependencies.sh`" script, or there should not be an error redirection to "`/dev/null`".

**Comment by j-travis** [comment]
I was unable to reproduce this on an 8.6 VM, so it must be the LXC that doesnt include openssl.

We do not test against LXCs

That being said, we could do a better job at checking for and installing that dependency. 

Thanks for reporting

**Comment by diasdmhub** [comment]
@j-travis thanks for the return.
I hope to that improvement some day.

**Comment by j-travis** [comment]
The 1.12.0 installer was updated to check for the existence of openssl.
