### ISSUE TITLE
Blender Image - dockerfile-kasm-blender - Issue

### ISSUE THREAD

**Issue by metamultiverse** [kasmtech/workspaces-issues#278]
Hello Team,
I tried to run Blender image into my local host on docker container with mentioned ports as well as other ports but its not running.

**Comment by j-travis** [comment]
Hello, this is not enough information here for us to help you.

Are you running the image standalone?

e.g
```
sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/blender:develop
```
The container is now accessible via a browser : https://IP_OF_SERVER:6901

User : kasm_user
Password: password


Or are you running it via Workspaces?


You'll need to provide us more details of what you've tried , screenshots, logs etc.

Also past the output of the following commands

```
sudo docker system info 
sudo df -h
cat /etc/os-release
uname -a
```

**Comment by metamultiverse** [comment]
Terminal log for running - Althoug its not working on localhost:6901

sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e
VNC_PW=password kasmweb/blender:develop




+ DEFAULT_PROFILE_HOME=/home/kasm-default-profile

+ PROFILE_SYNC_DIR=/kasm_profile_sync

+ '[' -f /home/kasm-user/.bashrc ']'

+ echo 'Profile Sync Directory Does Not Exist. No Sync will occur'

Profile Sync Directory Does Not Exist. No Sync will occur

+ copy_default_profile_to_home

+ echo 'Copying default profile to home directory'

Copying default profile to home directory

+ cp -rp /home/kasm-default-profile/. /home/kasm-user/

+ ls -la /home/kasm-user

total 32

drwxrwxrwx 1 kasm-user root      4096 Oct 20 18:53 .

drwxr-xr-x 1 root      root      4096 Oct 20 18:54 ..

-rw-r--r-- 1 kasm-user kasm-user   43 Oct 20 18:53 .bashrc

drwxrwxrwx 2 kasm-user kasm-user 4096 Oct 20 18:52 .cache

drwxrwxrwx 3 kasm-user kasm-user 4096 Oct 20 18:53 .config

drwxrwxrwx 2 kasm-user kasm-user 4096 Oct 20 18:49 Desktop

drwxrwxrwx 3 kasm-user kasm-user 4096 Oct 20 18:53 .pki

+ verify_profile_config

+ echo 'Verifying Uploads/Downloads Configurations'

Verifying Uploads/Downloads Configurations

+ mkdir -p /home/kasm-user/Uploads

+ '[' -d /home/kasm-user/Desktop/Uploads ']'

+ echo 'Creating Uploads Desktop Symlink'

Creating Uploads Desktop Symlink

+ ln -sf /home/kasm-user/Uploads /home/kasm-user/Desktop/Uploads

+ mkdir -p /home/kasm-user/Downloads

+ '[' -d /home/kasm-user/Desktop/Downloads ']'

+ echo 'Creating Download Desktop Symlink'

Creating Download Desktop Symlink

+ ln -sf /home/kasm-user/Downloads /home/kasm-user/Desktop/Downloads

+ '[' -d /usr/share/kasmvnc/Downloads/Downloads ']'

+ echo 'Creating Downloads RX Symlink'

Creating Downloads RX Symlink

+ ln -sf /home/kasm-user/Downloads
/usr/share/kasmvnc/www/Downloads/Downloads

+ ls -la /home/kasm-user/Desktop

total 8

drwxrwxrwx 2 kasm-user kasm-user 4096 Oct 27 10:30 .

drwxrwxrwx 1 kasm-user root      4096 Oct 27 10:30 ..

lrwxrwxrwx 1 kasm-user kasm-user   25 Oct 27 10:30 Downloads ->
/home/kasm-user/Downloads

lrwxrwxrwx 1 kasm-user kasm-user   23 Oct 27 10:30 Uploads ->
/home/kasm-user/Uploads

+ rm -rf /home/kasm-user/.config/pulse

+ echo 'Removing Default Profile Directory'

Removing Default Profile Directory

+ rm -rf /home/kasm-default-profile/Desktop

+ echo -e '\n\n------------------ EXECUTE COMMAND ------------------'



------------------ EXECUTE COMMAND ------------------

+ echo 'Executing command: '\''/dockerstartup/vnc_startup.sh'
/dockerstartup/kasm_startup.sh '--wait'\'''

Executing command: '/dockerstartup/vnc_startup.sh
/dockerstartup/kasm_startup.sh --wait'

+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait

Generating a RSA private key

.+++++

....................+++++

writing new private key to '/home/kasm-user/.vnc/self.pem'

-----

Creating default config /home/kasm-user/.vnc/kasmvnc.yaml

xauth:  file /home/kasm-user/.Xauthority does not exist


New '922ebb1404b0:1 (kasm-user)' desktop is 922ebb1404b0:1


Users configured:

kasm_viewer (can only view)

kasm_user (can use keyboard and mouse, add/remove users)


Log file is /home/kasm-user/.vnc/922ebb1404b0:1.log


Creating default startup script /home/kasm-user/.vnc/xstartup

Starting applications specified in /home/kasm-user/.vnc/xstartup


Paste this url in your browser:

https://172.17.0.2:6901


------------------ Xfce4 window manager startup------------------

Starting XFCE

Starting audio websocket server

Starting audio server

Starting Pulse

/usr/bin/startxfce4: X server already running on display :1

Starting audio service


------------------ Started Audio Out  ----------------------------

Kasm Audio Out PID: 114

Starting audio input server

Starting upload server

Starting gamepad server



------------------ KasmVNC environment started ------------------

+ USERXSESSIONRC=/home/kasm-user/.xsessionrc

+ ALTUSERXSESSION=/home/kasm-user/.Xsession

+ ERRFILE=/home/kasm-user/.xsession-errors

+ [ -w /home/kasm-user/.xsession-errors ]

+ [ ! -L /home/kasm-user/.xsession-errors ]

+ chmod 600 /home/kasm-user/.xsession-errors

+ stat -c%s /home/kasm-user/.xsession-errors

+ [ 0 -gt 500000 ]

+ exec

 2022-10-27 10:30:47,092 [DEBUG] Selection: Selection owner change for
_DBUS_SESSION_BUS_SELECTION_kasm-user_e0974dea4d6e4cd48a90b9eaf60612e9

Kasm User () started container id 922ebb1404b0 with local IP address
172.17.0.2

+ START_COMMAND=blender

+ PGREP=blender

+ export MAXIMIZE=true

+ MAXIMIZE=true

+ export MAXIMIZE_NAME=Blender

+ MAXIMIZE_NAME=Blender

+ MAXIMIZE_SCRIPT=/dockerstartup/maximize_window.sh

+ DEFAULT_ARGS=

+ ARGS=

++ getopt -o gau: -l go,assign,url: -n /dockerstartup/custom_startup.sh --

+ options=' --'

+ eval set -- ' --'

++ set -- --

+ [[ -- != -- ]]

+ shift

+ FORCE=

+ '[' -n '' ']'

+ '[' -n '' ']'

+ kasm_startup

+ '[' -n '' ']'

+ '[' -z '' ']'

+ URL=

+ '[' -z '' ']'

+ echo 'Entering process startup loop'

Entering process startup loop

+ set +x

filter is not configured

Starting Blender

Cannot get client list properties.

(_NET_CLIENT_LIST or _WIN_CLIENT_LIST)

_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be
created.

gpg-agent[193]: WARNING: "--write-env-file" is an obsolete option - it has
no effect

gpg-agent[193]: directory '/home/kasm-user/.gnupg' created

gpg-agent[193]: directory '/home/kasm-user/.gnupg/private-keys-v1.d' created


(xfce4-session:73): xfce4-session-*WARNING* **: 10:30:47.426: gpg-agent
returned no PID in the variables


(xfce4-session:73): xfce4-session-*WARNING* **: 10:30:47.428:
xfsm_manager_load_session: Something wrong with
/home/kasm-user/.cache/sessions/xfce4-session-922ebb1404b0:1, Does it
exist? Permissions issue?

gpg-agent[197]: gpg-agent (GnuPG) 2.2.19 started

Listening for incomming MPEG-TS Stream on https://127.0.0.1:8081/<secret>

Awaiting WebSocket connections on wss://127.0.0.1:4901/


(xfce4-session:73): xfce4-session-*WARNING* **: 10:30:47.698: Unable to
launch "xfce4-panel": Failed to execute child process “xfce4-panel” (No
such file or directory)


(xfsettingsd:222): libupower-glib-*WARNING* **: 10:30:47.750: Couldn't
connect to proxy: Could not connect: No such file or directory


(xfsettingsd:222): libupower-glib-*CRITICAL* **: 10:30:47.751:
up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed


(xfsettingsd:222): GLib-GObject-*WARNING* **: 10:30:47.751: invalid (NULL)
pointer instance


(xfsettingsd:222): GLib-GObject-*CRITICAL* **: 10:30:47.751:
g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

 2022-10-27 10:30:47,577 [DEBUG] Selection: Selection owner change for WM_S0

 2022-10-27 10:30:47,619 [DEBUG] Selection: Selection owner change for
XFWM4_COMPOSITING_MANAGER

 2022-10-27 10:30:47,740 [DEBUG] Selection: Selection owner change for
_XSETTINGS_S0

 2022-10-27 10:30:47,810 [DEBUG] WebUdp: UDP listening on port 6901

 2022-10-27 10:30:48,002 [DEBUG] Selection: Selection owner change for
CLIPBOARD_MANAGER

ERROR:KasmGamepadServer:Failed to connect input (/dev/input/event0) :
[Errno 2] No such file or directory: '/dev/input/event0'

ERROR:KasmGamepadServer:Failed to connect input (/dev/input/event1) :
[Errno 2] No such file or directory: '/dev/input/event1'

ERROR:KasmGamepadServer:Failed to connect input (/dev/input/event2) :
[Errno 2] No such file or directory: '/dev/input/event2'

ERROR:KasmGamepadServer:Failed to connect input (/dev/input/event3) :
[Errno 2] No such file or directory: '/dev/input/event3'

Failed to unload module: Module module-pipe-source not loaded

 * Serving Flask app 'kasm_upload_server' (lazy loading)

 * Environment: production

   WARNING: This is a development server. Do not use it in a production
deployment.

   Use a production WSGI server instead.

 * Debug mode: off

 * Running on all addresses.

   WARNING: This is a development server. Do not use it in a production
deployment.

 * Running on https://172.17.0.2:4902/ (Press CTRL+C to quit)

Stream Connected: ::ffff:127.0.0.1:52406


** (xfdesktop:252): *WARNING* **: 10:30:55.922: Failed to get system bus:
Could not connect: No such file or directory

 2022-10-27 10:30:55,910 [DEBUG] Selection: Selection owner change for
XFDESKTOP_SELECTION_0

 2022-10-27 10:30:55,910 [DEBUG] Selection: Selection owner change for
_NET_DESKTOP_MANAGER_S0


** (xiccd:263): *CRITICAL* **: 10:31:03.707: Failed to connect to colord:
Could not connect: No such file or directory


** (agent:264): *CRITICAL* **: 10:31:03.717: Failed to get connection to
system bus: Could not connect: No such file or directory


(xfce4-session:73): xfce4-session-*WARNING* **: 10:31:03.793: ICE
connection 0x55e0f4dbf4e0 rejected

Failure: Module initialization failed


(nm-applet:277): nm-applet-*WARNING* **: 10:31:03.985: Error connecting to
system D-Bus: Could not connect: No such file or directory


(nm-applet:277): nm-applet-*WARNING* **: 10:31:03.985: Could not connect:
No such file or directory


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.988:
((libnm/nm-client.c:3905)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.994:
((libnm/nm-client.c:3859)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.995:
((libnm/nm-client.c:3937)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.995:
((libnm/nm-client.c:3986)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.995:
((libnm/nm-client.c:4026)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.995:
((libnm/nm-client.c:4042)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.996:
((libnm/nm-client.c:4080)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:03.996:
((libnm/nm-client.c:4598)): assertion '<dropped>' failed


(nm-applet:277): libnm-*CRITICAL* **: 10:31:04.002:
((libnm/nm-client.c:4598)): assertion '<dropped>' failed

system-config-printer-applet: failed to connect to system D-Bus

 2022-10-27 10:31:39,617 [INFO] websocket 0: got client connection from
172.17.0.1

 2022-10-27 10:31:39,635 [DEBUG] websocket 0: non-SSL connection disallowed

 2022-10-27 10:31:39,635 [DEBUG] websocket 0: No connection after handshake

 2022-10-27 10:31:39,636 [DEBUG] websocket 0: handler exit

 2022-10-27 10:31:39,638 [INFO] websocket 1: got client connection from
172.17.0.1

 2022-10-27 10:31:39,638 [DEBUG] websocket 1: non-SSL connection disallowed

 2022-10-27 10:31:39,639 [DEBUG] websocket 1: No connection after handshake

 2022-10-27 10:31:39,639 [DEBUG] websocket 1: handler exit

 2022-10-27 10:31:39,641 [INFO] websocket 2: got client connection from
172.17.0.1

 2022-10-27 10:31:39,641 [DEBUG] websocket 2: non-SSL connection disallowed

 2022-10-27 10:31:39,641 [DEBUG] websocket 2: No connection after handshake

 2022-10-27 10:31:39,641 [DEBUG] websocket 2: handler exit



Here you go

sudo docker system info

Server:

 Containers: 1

  Running: 1

  Paused: 0

  Stopped: 0

 Images: 2

 Server Version: 20.10.16

 Storage Driver: overlay2

  Backing Filesystem: extfs

  Supports d_type: true

  Native Overlay Diff: true

  userxattr: false

 Logging Driver: json-file

 Cgroup Driver: cgroupfs

 Cgroup Version: 2

 Plugins:

  Volume: local

  Network: bridge host ipvlan macvlan null overlay

  Log: awslogs fluentd gcplogs gelf journald json-file local
logentries splunk syslog

 Swarm: inactive

 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc

 Default Runtime: runc

 Init Binary: docker-init

 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16

 runc version: v1.1.1-0-g52de29d

 init version: de40ad0

 Security Options:

  seccomp

   Profile: default

  cgroupns

 Kernel Version: 5.10.104-linuxkit

 Operating System: Docker Desktop

 OSType: linux

 Architecture: x86_64

 CPUs: 2

 Total Memory: 7.677GiB

 Name: docker-desktop

 ID: AI32:ZTPS:WHVB:HB6O:LDDL:4LCV:P3I5:Q4HO:ONZI:MM6X:HP3B:YCEY

 Docker Root Dir: /var/lib/docker

 Debug Mode: false

 HTTP Proxy: http.docker.internal:3128

 HTTPS Proxy: http.docker.internal:3128

 No Proxy: hubproxy.docker.internal

 Registry: https://index.docker.io/v1/

 Labels:

 Experimental: false

 Insecure Registries:

  hubproxy.docker.internal:5000

  127.0.0.0/8

 Live Restore Enabled: false

sudo df -h

Filesystem       Size   Used  Avail Capacity iused       ifree %iused
Mounted on

/dev/disk2s1s1  1.8Ti   14Gi  1.1Ti     2%  502068  4291801478    0%   /

devfs           193Ki  193Ki    0Bi   100%     670           0  100%   /dev

/dev/disk2s5    1.8Ti  1.0Gi  1.1Ti     1%       2 12222630840    0%
/System/Volumes/VM

/dev/disk2s3    1.8Ti  649Mi  1.1Ti     1%    4232 12222630840    0%
/System/Volumes/Preboot

/dev/disk2s6    1.8Ti  3.8Mi  1.1Ti     1%      16 12222630840    0%
/System/Volumes/Update

/dev/disk2s2    1.8Ti  680Gi  1.1Ti    37% 3385709 12222630840    0%
/System/Volumes/Data

/dev/disk1s2    113Gi   12Mi  113Gi     1%      92      923948    0%
/Volumes/Macintosh H

map auto_home     0Bi    0Bi    0Bi   100%       0           0  100%
/System/Volumes/Data/home


cat /etc/os-release

Command not working but I am using MacOS monterey 12.5


uname -a

21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022;
root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64




On 22 October 2022 at 5:54:23 PM, j-travis ***@***.***) wrote:

sudo docker system info

**Comment by j-travis** [comment]
> 
> ```
>  2022-10-27 10:31:39,617 [INFO] websocket 0: got client connection from
> 172.17.0.1
> 
>  2022-10-27 10:31:39,635 [DEBUG] websocket 0: non-SSL connection disallowed
> 
>  2022-10-27 10:31:39,635 [DEBUG] websocket 0: No connection after handshake
> 
>  2022-10-27 10:31:39,636 [DEBUG] websocket 0: handler exit
> ```
> 

Can you ensure you are connecting to the service using **HTTPS**

e.g https://localhost:6901 or https://[your ip]:6901

Also ensure you try connecting with Chrome or Firefox. Safari may not work
