### ISSUE TITLE
Reset Password button gone in 1.11

### ISSUE THREAD

**Issue by inspectorgadjet7** [kasmtech/workspaces-issues#279]
I have updated to 1.11 and I've had to do an admin account recovery, but the reset password button appears to be gone...
![820613C7-F92E-4F12-A644-652D518B489C](https://user-images.githubusercontent.com/36364123/197220263-05366e5f-e4f3-466c-a649-0c9e88dfb538.jpeg)

**Comment by j-travis** [comment]
Did this user auth with LDAP, SAML , or OpenID Connect? 
If so you cant reset the password from Workspaces, you must do so via the identity provider.

You can confirm by logging in as an admin, and select **Users**.  Find the user in the table an select **View** from the menu. If the realm is not `local` then you cant reset the password from Workspaces

**Comment by inspectorgadjet7** [comment]
My users are local....I did have the realm set to 'mydomain.net' though. Setting it back to local has brought back the password reset.
