### ISSUE TITLE
NVIDIA GPU unavailable to Agent

### ISSUE THREAD

**Issue by thechirospasm** [kasmtech/workspaces-issues#282]
Hello! Having a fun weekend of trying to figure this out, although I'm a bit stuck now. I'm using the Developer Preview release of Workspaces, running on Ubuntu 22.04.1 LTS. My Agent's reporting 0 GPUs in its status, but when I expand into the details, the GPU section displays the folllowing:

![image](https://user-images.githubusercontent.com/93797398/198903267-673e2083-44a2-4397-a281-03b0600d9fa6.png)

Looks good to me. Testing that the GPU's running and accessible in Docker using a base CUDA container via

`sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`

and I receive a valid output of nvidia-smi displaying the GPU, as well:

![image](https://user-images.githubusercontent.com/93797398/198903594-9271bb08-5108-4213-b41a-22e861a07081.png)

Which is encournaging. But: I'm stuck, y'all. The expected behavior would be Workspaces leveraging the container toolkit, which is being referenced by the Agent. Forcing the Agent to have _GPU 1_, and/or editing an image to have forced _GPU 1_, doesn't seem to have any effect, and a resource error diag hits on launch even if a[ compatible image](https://www.kasmweb.com/docs/latest/guide/agent_settings.html#gpu-accelerated-graphics) has GPU set to 1. Restarting Docker via systemctl and/or restarting the kasm_agent via Docker has no effect, either. Re-installations of the container toolkit -- from either the latest repo or experiemental repo -- have no effect, as well.

The documentation currently suggests, because I am able to get a valid output from nvidia-smi both inside Docker (the CUDA container) and on the host machine, I should start a ticket here.

Runtimes are currently showing:

![image](https://user-images.githubusercontent.com/93797398/198904467-a0b85c2c-aa86-483d-8f03-dc733774161f.png)

Reading through NVIDIA's documentation, I have attempted to change some settings in the toolkit container configuration, but seeing these either may not have direct bearing on the issue or, in some cases, may break the setup, I've reinstalled the container toolkit or reverted changes. 

Thanks! I really appreciate your help.

**Comment by j-travis** [comment]
> Runtimes are currently showing:

You need to be seeing a runtime named `nvidia`.  Please double check that you've installed the Nvidia Container Toolkit and that you've restarted docker and the kasm_agent. You many also have to restart your server if its not showing up in the docker info.

https://kasmweb.com/docs/latest/how_to/gpu.html?highlight=gpu#installing-container-toolkit

**Comment by thechirospasm** [comment]
Hi, thanks for getting back to me. I have installed the container toolkit and am able to validate it is installed correctly by running the command  `sudo docker run --rm --gpus all nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi`, which validates the container toolkit is accessible inside Docker. However, the runtime is not displaying after restart of the server and/or restart of the kasm_agent. This issue was started in reference to the GPU [troubleshooting documentation](https://kasmweb.com/docs/latest/guide/troubleshooting.html#gpu-passthrough-support) that says,

> If you are able to run nvidia-smi from the host directly and when manually running a container, then open a support issue with Kasm

as I was able to run nvidia-smi both inside and outside Docker.

I have also attempted fresh installs of Kasm, itself, with similar results. Any suggestions I might try? Thanks, @j-travis, for your help.

**Comment by j-travis** [comment]
Can you please paste the output of the following command.

```
sudo docker info | grep runtime
```

**Comment by thechirospasm** [comment]
Output is:

`Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2`

Also for comparison, what Kasm outputs as the current runtimes:

![image](https://user-images.githubusercontent.com/93797398/200224617-e752b6ca-4e0d-4a56-8d05-a06fcdab755f.png)

**Comment by j-travis** [comment]
It looks like you still dont have the nvidia container runtime installed. That is a requirement. When you get it installed you should see nvidia listed 

```
sudo docker info | grep runtime
 Runtimes: nvidia runc io.containerd.runc.v2 io.containerd.runtime.v1.linux

```

https://kasmweb.com/docs/latest/how_to/gpu.html?highlight=gpu#installing-container-toolkit

**Comment by thechirospasm** [comment]
Hi, @j-travis -- took me a bit, but I appreciate your direction. I realized I had not installed the runtime properly, as you were pointing out. For anyone in the future who has bumped into this:

Installing the runtime properly also means setting it as a default for Docker. That can be accomplished by validating that the runtime was installed:

`sudo apt-get install nvidia-container-runtime`

which, if it is with nvidia-docker2, will show it's at the latest. After that, it's just a matter of editing _/etc/docker/daemon.json_ to contain only the following:

```
{
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": []
         } 
    },
    "default-runtime": "nvidia" 
}
```

which will ensure nvidia is a default runtime for Docker. Then, just `sudo systemctl restart docker` and you should be good to go.

To validate all the above, running `sudo docker info | grep runtime` should now include **_nvidia_** and the GPU is showing as present, which is the purpose of this thread. 

Thanks again, @j-travis !
