### ISSUE TITLE
Reverse Proxy - Stuck on "Creating secure connection"

### ISSUE THREAD

**Issue by jl-678** [kasmtech/workspaces-issues#284]
I am running 1.11.0.ccc7a3 and am experiencing this issue with my reverse proxy setup.  I have read the docs and specifically [this article](https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones), but it is not working. I am not sure if it is user error or if there is something about my config.  Here is how it is setup.

Kasm is running on my LAN with a private fqdn call it kasm.priv.foo.com. I also have a letsencrypt wildcard cert and private DNS so https://kasm.priv.foo.com works fine and has a valid certificate.

I want to expose kasm publicly and so I configured a reverse proxy on Apache (using the Kasm reference configuration) that maps https://kasm.foo.com to https://kasm.priv.foo.com. This setup works perfectly for https://kasm.priv.foo.com, of course.  I can also access the GUI and settings at https://kasm.foo.com without an issue but when I try to open an app it gets stuck on "Creating secure connection." 

Per the article above and other help topics, I have tried numerous combinations of IP address (public and private), FQDN (public and private) and the word "proxy" in the "Upstream Auth Address" field and nothing has fixed the issue.  Oh and "Proxy Port" is set to 0, I tried 443 too and the problem persists. (On a side note, while it is not clearly stated, I also made sure to restart the proxy service after making each change listed in this paragraph just to be safe.)

In an ideal world, I would like to be able to access kasm from either https://kasm.priv.foo.com/ or https://kasm.foo.com.  But I have never gotten the second URL work. I appreciate any suggestions on what I can do to make this work.

TIA for any thoughts.

**Comment by j-travis** [comment]
Hello. Please read through this thread and see if it applies to you:
https://github.com/kasmtech/workspaces-issues/issues/175

**Comment by jl-678** [comment]
The proposed configuration in #175 works!  Thank you so much.  Can I suggest that you update the docs to reflect this config?  I previously used your provided config and it did not work.
