### ISSUE TITLE
KASM Agent is unable to pull custom image from self-hosted GitLab

### ISSUE THREAD

**Issue by antoniokaust** [kasmtech/workspaces-issues#285]
Hello,

I installed KASM and it's working great. I'm having issues with my custom image.
I built my custom image that we'll be delivering to our students here at KAUST for a training. I can't get the KASM Agent to pull my image. This is the error I get in the logs:

`Failed to pull image (arenaam/wep-2023:latest) : 500 Server Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=arenaam%2Fwep-2023: Internal Server Error ("Head "https://registry-1.docker.io/v2/arenaam/wep-2023/manifests/latest": unauthorized: incorrect username or password") Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 1021, in raise_for_status requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=arenaam%2Fwep-2023 During handling of the above exception, another exception occurred: Traceback (most recent call last): File "provision.py", line 959, in get_image File "docker/models/images.py", line 446, in pull File "docker/api/image.py", line 430, in pull File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=arenaam%2Fwep-2023: Internal Server Error ("Head "https://registry-1.docker.io/v2/arenaam/wep-2023/manifests/latest": unauthorized: incorrect username or password")`

Here are the main entries for my custom image:

- Docker image: arenaam/wep-2023:latest
- Docker registry: https://gitregistry.kaust.edu.sa/
- Docker registry username: smart
- Docker registry password: XXXXXXXXX

I'm able to `docker login` from the KASM server and `docker pull` the image. It won't work from the KASM Agent because it seems that it's hardcoded somewhere to check on URL `https://registry-1.docker.io/v2/`.

I also pulled the image from the KASM server hoping the agent would detect it but I didn't have luck.

Any help is greatly appreciated. Thanks!

Ciao,
Antonio

**Comment by antoniokaust** [comment]
Any chance ti=o get help on this?

**Comment by j-travis** [comment]
Some of this may depend on how your registry is set up, but here is an example configuration that uses gitlab cloud


**Docker Image**
```
registry.gitlab.com/acme/example-images/myimage:develop
```

**Docker Registry**
```
https://registry.gitlab.com
```

What i'm trying to highlight here is that you may need to fully qualify your image by including the registry path/location

**Comment by antoniokaust** [comment]
It worked! @j-travis thanks for your help!

I'm sorry I didn't read this from the docs. Could you send me a link to this example?
