### ISSUE TITLE
Custom Image Software/Apps Fail To Launch

### ISSUE THREAD

**Issue by sts64** [kasmtech/workspaces-issues#287]
I have been experimenting with creating custom images so I can have specific applications running within my workspaces. I have been using Ubuntu Focal as the base image for this and although my custom image launches and has the additional application, the apps fail to launch. I'm not sure if there is something I am missing or if the applications are incompatible with Kasm (even if they're fully compatible with Ubuntu).

Example of Dockerfile used:
```
FROM kasmweb/core-ubuntu-focal:1.11.0
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

RUN   wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg \
    && apt-get update \
    && apt-get install -y apt-transport-https \
    && echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | tee /etc/apt/sources.list.d/element-io.list \
    && apt-get update \
    && apt-get install -y element-desktop \
    && cp /usr/share/applications/element-desktop.desktop $HOME/Desktop/ \
    && chmod +x $HOME/Desktop/element-desktop.desktop \
    && chown 1000:1000 $HOME/Desktop/element-desktop.desktop


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000   `
```

![Screenshot 2022-11-22 103615](https://user-images.githubusercontent.com/116198027/203292523-2b6456a8-aa9c-4de6-abc1-1746c1632717.png)

In this example I have installed Element messaging applications desktop app, but after double-click nothing happens.

**Comment by sts64** [comment]
I have done some testing with adding Teamviewer with the following in Dockerfile:

`# Install Teamviewer
RUN wget -q https://download.teamviewer.com/download/linux/teamviewer_amd64.deb \
    && dpkg -i teamviewer*.deb \
    && teamviewer --daemon start \
    && apt-get update `

Teamviewer installs but will not start.

I got this to work by enabling root for the user and entering these commands in to workspace terminal:

`teamviewer --daemon start`
and
`teamviewer --allowRoot`


This obviously isnt ideal at all. 

It seems that alot of custom image applications are having issues with permissions. Is there anything I can add into the Dockerfile to add the relevant permission?

**Comment by mmcclaskey** [comment]
Anything in the dockerfile is executed only during the build of the image. So teamviewer --daemon start, presumably starts some process called teamviewer as a background process. This shouldn't be done in the dockerfile but rather during container start.

Kasm provides a few hooks for you to define actions to occur during the container start:

Use a custom startup script, which is executed prior to all Kasm built in service (KasmVNC, audio in, audio out, upload service, etc). This script will be ran as the user, not as root. Teamviewer requires root to install, but if it is already installed on the image, it is possible it does not need root to run. Please refer to Teamviewer support to answer that or just try it.
https://www.kasmweb.com/docs/latest/how_to/building_images.html#custom-startup

The next hook, which allows you to run commands at container start as an arbitrary user, including root, is in the Image definition in the Kasm Workspaces UI. See the docs here. What the docs don't show is that you can add a "user": "root" under "first_launch" to specify that the command should be ran as root. This allows you to specify container start scripts to be ran as root, while not giving the user root permissions.
https://www.kasmweb.com/docs/latest/guide/custom_images.html#docker-exec-config

See this dock on adding sudo to the image, which may be useful when trying to figure all of this out when creating your custom image.
https://www.kasmweb.com/docs/latest/how_to/running_as_root.html#building-an-image-with-sudo

**Comment by sts64** [comment]
@mmcclaskey thank you for your response. All of the above is very useful and I'm glad to have learnt something today.

I have tested the docker exec config method but the TeamViewer daemon is still failing to start automatically.

I am using the following config:

```
{
    "first_launch": {
        "cmd": "bash -c 'teamviewer --daemon start \"$KASM_URL\"'",
        "environment": {
            "LAUNCH_URL": ""
        }
    },
    "go": {
        "cmd": "bash -c 'teamviewer --daemon start \"$KASM_URL\"'"
    },
    "assign": {
        "cmd": "bash -c 'teamviewer --daemon start \"$KASM_URL\"'"
    }
}
```
Maybe this is just an incompatibility issue with TeamViewer on a container.

Thanks anyway

**Comment by sts64** [comment]
@mmcclaskey 

Thank you!

`{"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'teamviewer --daemon start'"}}`

This worked perfectly.

I imagine that there may be some sort of dependency issues with my other applications that do not launch at all. Is this something you have experienced before?

**Comment by sts64** [comment]
@mmcclaskey 

Is it possible to put in multiple first_launch commands?

I have tried

`{"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'ip route delete default && ip route add default via 172.21.0.2'","cmd":"bash" -c 'teamviewer --daemon start'"}}`

and

`{"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'ip route delete default && ip route add default via 172.21.0.2'"},"first_launch":{"user":"root","privileged":true,"cmd":"bash" -c 'teamviewer --daemon start'"}}`

but both have failed.

**Comment by mmcclaskey** [comment]
It is not possible. For complex things I would recommend baking a script into the image and merely executing the script which can do any number of things you want.

**Comment by sts64** [comment]
@mmcclaskey Thanks again.

I have noticed now some inconsistency with this.

Both scripts and docker exec configs seem to work only some of the time. 

For some reason this:

`{"first_launch":{"user":"root","privileged":true,"cmd":"bash -c 'teamviewer --daemon start'"}}`

was working yesterday but now does nothing.

My guess is it is to do with Teamviewer compatibility issues.

Thanks for the help!

**Comment by MrMEEE** [comment]
@mmcclaskey Just a quick question on the docker exec config..

I have built an image based on the information in https://kasmweb.com/docs/latest/how_to/building_images.html, but no matter what I put into first_launch, it doesn't seem to be run?...

How is the first_launch implemented? could there be something in the image that i'm missing?
