### ISSUE TITLE
Telegram and Persistent Profiles

### ISSUE THREAD

**Issue by sts64** [kasmtech/workspaces-issues#288]
I have set up a Telegram workspace with persistent profile enabled and keepalive expiration set to 31557600 seconds (1year), but my telegram account still keeps being signed out after a couple of new sessions. Is this expected behaviour? Is there a better way to enable application persistence with kasm?

**Comment by GadgetGeekNI** [comment]
Did you figure this out? 

I've just came across the same issue myself.
