### ISSUE TITLE
API request_kasm returns "Error Creating User"

### ISSUE THREAD

**Issue by Lingomat** [kasmtech/workspaces-issues#289]
I have a use case for querying Kasm Workspaces via the API so as to pre-emptively warn users of a lack of session resources. For this I'm using the Kasm API. The get_kasms endpoint is working fine. 

When posting a request to /api/public/request_kasm, Kasm Workspaces returns "error_message": "Error Creating User" and I can't see how to further debug the issue.

This is a request without a user_id provided which, according to the documentation, should create an anonymous user.  It makes no difference providing an image_id field or providing values for any of the other fields for this endpoint.

There are no entries in the log except for an 'info' which simply logs the API request.
A casting configuration is otherwise functional, which does indeed create anonymous users.

**Comment by j-travis** [comment]
We've been able to reproduce this issue. Thanks for reporting

**Comment by brangelbr** [comment]
@j-travis, I have this same problem, is there a deadline for the solution?

**Comment by j-travis** [comment]
We had someone take a look and have a MR ready for review and testing.  That should make it through in the next few weeks - so the update will be testable by you all in the [Developer Preview Builds](https://kasmweb.com/docs/latest/developers/builds.html) at that point. 

The next stable release (1.13) will be end of Q1 2023

**Comment by j-travis** [comment]
This issue is now resolved and available in the Develop Preview Builds for testing:

- https://kasmweb.com/docs/latest/developers/builds.html
- https://kasmweb.com/docs/develop/release_notes/1.13.0.html#bugfixes
