### ISSUE TITLE
How to change the expiry time on a container

### ISSUE THREAD

**Issue by 3kh0** [kasmtech/workspaces-issues#291]
I know this might be a easy answer, but I can not seem to figure it out, I am on the latest version hosted on Linode, I have tried using command line to edit the files, did not seem to work, I also edited the settings through the GUI, every time I would do this, I would stop all of the containers, and reboot the sever using `sudo reboot now`. Any help here?

![image](https://user-images.githubusercontent.com/58097612/205794611-526d9d33-d267-4c52-902f-532a81b90278.png)

**Comment by j-travis** [comment]
The setting you are looking for is called keepalive_expiration . Its a group setting.

https://github.com/kasmtech/workspaces-issues/issues/108#issuecomment-1017003931

https://kasmweb.com/docs/latest/guide/groups/group_settings.html?highlight=keepalive_expiration

https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s

**Comment by 3kh0** [comment]
Wow, Thank you so much! I love Kasm!!!
