### ISSUE TITLE
Adding Windows as a image

### ISSUE THREAD

**Issue by 3kh0** [kasmtech/workspaces-issues#293]
I want to add Windows as a image, how would I do that?

**Comment by j-travis** [comment]
Here is a guide on configuring workspaces to connect to existing Windows machines:
https://kasmweb.com/docs/latest/how_to/fixed_infrastructure.html

Please note these are existing desktops/vms/servers and not Windows based docker containers.

**Comment by 3kh0** [comment]
@j-travis Thanks for the guide, but I need a Windows Docker container, do those exist?

**Comment by j-travis** [comment]
No,
While Microsoft does publish windows docker images, you can't use them to run graphical applications or desktop environments.

**Comment by 3kh0** [comment]
Ahhh ok thanks!
