### ISSUE TITLE
2Fa - Documentation not clear

### ISSUE THREAD

**Issue by Pontiac76** [kasmtech/workspaces-issues#295]
https://www.kasmweb.com/docs/latest/guide/two_factor.html

According to the documentation:
    Navigate to the Groups tab in the Administrators Sidebar and select green view button for the group
    Select Add Settings from the Group Settings card
    Select the “enable_totp_two_factor” setting and select True to add to all of the users in the group

Under the Admin account, in the right pane, I see Dashboard, Users, and Groups etc.  But I don't specifically see "Add settings" when I click on Groups.  When I click on Groups I see the two groups (Administrators and All Users) but no "Add Settings".

**Comment by j-travis** [comment]
>  select green view button

This is no longer a green button. It has changed to an ellipse under the actions , then you select View.


Here is a video describing group settings https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s

**Comment by Pontiac76** [comment]
Alright, found it.  Something to tinker with after I figure out my other problem.  Closing ticket.
