### ISSUE TITLE
Web Proxy

### ISSUE THREAD

**Issue by ktb92677** [kasmtech/workspaces-issues#298]
Hi! I have been trying to figure out how to access the management panel from an online web proxy. But every time I use one it just redirects me to a blank page. The kasm log shows nothing either. Can anyone help?

**Comment by j-travis** [comment]
There is not enough information here to help you.

What proxy are you using (software and version)?
How is it installed and configured?
How is your local browser configured to use the proxy ?
What errors do you receive on the proxy logs?
What errors do you receive on the client browser  (Looking at any failed requests or errors from the Web console)?
What errors do you see on the Kasm application logs? 

- https://kasmweb.com/docs/latest/guide/reporting.html
- https://kasmweb.com/docs/latest/guide/troubleshooting.html
