### ISSUE TITLE
Find the password of an account or disable password changes

### ISSUE THREAD

**Issue by 3kh0** [kasmtech/workspaces-issues#299]
Is there a way to find the users password in plaintext? or just to disable the password reset?

**Comment by j-travis** [comment]
No, passwords are not stored in a reversable form, nor can you disable the password reset. 

Can you explain your use-case  - perhaps there is another way to achieve the end goal

**Comment by 3kh0** [comment]
I am trying to use a secure password, and the people using kasm keep on escaping by the bare minimum, so I am trying to make them use the randomly generated password that was given to them, and if they want to change it, they have to make a support ticket, but we also do not want to keep on resetting passwords, so being able to view it on the kasm dashboard is needed

**Comment by 3kh0** [comment]
If not we can just resort to hashcat

**Comment by j-travis** [comment]
There are probably better ways to solve this than trying to crack passwords.  In no particular order...

1. If its about better security, then enforce the TOTP 2fa that's built in.  https://kasmweb.com/docs/latest/guide/two_factor.html
2. Use an external identity provider that will allow you full control over your password complexity ,retention and reset policy. We support LDAP, SAML, and OIDC
3. Write a script to reset the password to whatever you want them to be.
4. Don't give the users login credentials at all-1: Use Casting links with anonymous users: https://kasmweb.com/docs/latest/guide/casting.html
5. Don't give the users login credentials at all-2: Create the sessions via API: https://kasmweb.com/docs/latest/developers/developer_api.html#request-kasm
6. Don't  give the user login credentials at all-3: Log the user in via API. https://kasmweb.com/docs/latest/developers/developer_api.html#get-login
7. Put Kasm behind a reverse proxy and block access to the reset_password endpoint

**Comment by 3kh0** [comment]
Alr thanks!
