### ISSUE TITLE
update to 1.12 - using automatic update (no workspaces post upgrade)

### ISSUE THREAD

**Issue by joggie721** [kasmtech/workspaces-issues#300]
After updating following the documentation for the automatic update using the option --upgrade-images. there are no default images.

Not sure if there is a clean way to reload them all at one time?

**Comment by j-travis** [comment]
Hi, can you please paste the command you ran and the full otuput?

**Comment by j-travis** [comment]
@joggie721 , do you have the ability to post the command you ran and the output you received. Its helpful for our team to be able to diagnose and correct the issue both for yourself and those that follow

**Comment by joggie721** [comment]
Sorry for the delay.  I did not have the output from the original run, however I ran the upgrade again and it produced the following output:

[kasm1-12-0-upgradeoutput.txt](https://github.com/kasmtech/workspaces-issues/files/10241025/kasm1-12-0-upgradeoutput.txt)

**Comment by joggie721** [comment]
@j-travis  looks like new ticket #311 is related as well. same thing.

**Comment by Fubister** [comment]
same thing happened to me, same command and same output, additionally this happened when I previously upgraded kasm and was forced to do a fresh install which is not ideal because I was unable to find a solution to pulling just workspace images

**Comment by j-travis** [comment]
The 1.13 upgrade handles this better now. You existing images are left alone. You can and the new images manually by visiting the Workplace Registry. https://kasmweb.com/docs/latest/guide/workspace_registry.html
