### ISSUE TITLE
Half of the images are disabled

### ISSUE THREAD

**Issue by Issam2204** [kasmtech/workspaces-issues#303]
Fresh community-edition of kasmweb installed on Ubuntu 22.04 server (x64). I'm not sure what I'm doing wrong but half of the images are disabled: [https://i.imgur.com/qWLK5f8.png](https://i.imgur.com/qWLK5f8.png)

Any help is really appreciated, thanks!

**Comment by 3kh0** [comment]
You need to enable them first, go to your admin dashboard, click on workspaces, go to the image you would like to enable, click on edit, find the checkbox that says Enabled? Check that. Make sure you scroll down and click on save

**Comment by Issam2204** [comment]
Thank you so much!
