### ISSUE TITLE
chrome play video have no sound

### ISSUE THREAD

**Issue by m986883511** [kasmtech/workspaces-issues#304]
I test kasmweb/chrome:1.12.0 and ubuntu-bionic-desktop, play video have no sound, is that normal?

environment:
kasmweb container run on ubuntu20.04, I use win11 to access the url:6901.
docker command:
sudo docker run --rm  -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/<image>:<tag>

**Comment by j-travis** [comment]
Hi, Audio is only available when using the Kasm Workspaces platform. It is not available when you run the comatiner manually outside the platform
