### ISSUE TITLE
[Bug] - Self Profile Data Inaccurate on view

### ISSUE THREAD

**Issue by cwulterkens** [kasmtech/workspaces-issues#308]
**Describe the bug**
On profile details, Organization and Phone are same value, even when profile edit screen reflects accurately.

**To Reproduce**
Update user profile to contain Organization and Phone
View your own profile when logged in, and both values match the "Organization" value

**Expected behavior**
Data should reflect that of the user profile.

**Screenshots**
Can provide to developers as needed, but would have personal information.

**Workspaces Version**
Version 1.12

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Microsoft Edge and Google Chrome

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a` - 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`
 - PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo
 - `sudo docker info`
 - Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-26-generic
 Operating System: Ubuntu 22.10
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 141.6GiB
 Name: wulterkenstech
 ID: KP6A:4UUU:GUWT:EACK:P34C:6NIS:UZZK:CBH7:TP2F:X4JV:J3SW:46NC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 - `sudo docker ps | grep kasm`
41ffdfa8c8b8   kasmweb/nginx:latest            "/docker-entrypoint.…"   3 hours ago   Up 3 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp                                                    kasm_proxy
6dd8e6383d79   kasmweb/agent:1.12.0            "/bin/sh -c '/usr/bi…"   3 hours ago   Up 3 hours (healthy)   4444/tcp                                                                                         kasm_agent
c1d291ea1781   kasmweb/share:1.12.0            "/bin/sh -c '/usr/bi…"   3 hours ago   Up 3 hours (healthy)   8182/tcp                                                                                         kasm_share
4be41281c31f   redis:5-alpine                  "docker-entrypoint.s…"   3 hours ago   Up 3 hours             6379/tcp                                                                                         kasm_redis
a8dffc47adab   kasmweb/kasm-guac:1.12.0        "/dockerentrypoint.sh"   3 hours ago   Up 3 hours (healthy)                                                                                                    kasm_guac
df86f173ea8e   kasmweb/api:1.12.0              "/bin/sh -c '/usr/bi…"   3 hours ago   Up 3 hours (healthy)   8080/tcp                                                                                         kasm_api
4cf172991e39   kasmweb/manager:1.12.0          "/bin/sh -c '/usr/bi…"   3 hours ago   Up 3 hours (healthy)   8181/tcp                                                                                         kasm_manager
fbae1babb88c   postgres:12-alpine              "docker-entrypoint.s…"   3 hours ago   Up 3 hours (healthy)   5432/tcp                                                                                         kasm_db

**Additional context**
This was after fresh single server install.

**Comment by j-travis** [comment]
Confirmed.
Thanks for reporting. Will update this ticket when its fixed

**Comment by KodeStar** [comment]
The fix should now be merged into developer preview builds.
