### ISSUE TITLE
This image is not currently available. Agent may be still downloading the image? 

### ISSUE THREAD

**Issue by electricwildflower** [kasmtech/workspaces-issues#309]
I am following the building custom images guide and I have an issue with building a custom image and i'm pretty sure i am doing it totally wrong or missing a step. This is where i have gotten so far. 

Step 1 - Create a document on my Linux desktop called Dockerfile and include the content from the guide
Step 2 - Copy the document to my Truenas Scale server which is where Kasm is installed into a dataset called Programs which is shared with Kasm.
Step 3 - Jump into Truenas gui and open up the shell in Kasm, navigate to the Programs dataset shared with Kasm and run the following command sudo docker build -t sublime-text:example -f Dockerfile .
step 4 - Once it's completed steps 1 to 12 then jump into the Kasm web gui. 
step 5 - Log into the Kasm UI as an administrator and register a new Workspace by selecting the Workspaces panel and clicking on Add Workspace, run through the details and save
Step 6 - From the Kasm Dashboard click Sublime Text Image and launch session (it has a small warning sign on the button)

And then i am greeted with the error This image is not currently available. Agent may be still downloading the image? 

I know i am doing something wrong or missing a step or two but it refuses to boot after i run through the steps?

**Comment by mmcclaskey** [comment]
Apologies for the delayed response. It can take up to a minute for new images to become recognized and available. I assume that time as long passed and it was still not working. Can you provide a screenshot of your workspace definition and the output of `sudo docker images`?
