### ISSUE TITLE
Kasmweb package/module for nixos

### ISSUE THREAD

**Issue by s1341** [kasmtech/workspaces-issues#310]
Hi,

I've packaged kasmweb 1.12.0 for nixpkgs, and provided a nixos module to allow one to easily spin up an instance of kasmweb. I figured you might be interested.

See https://github.com/NixOS/nixpkgs/pull/208196

s1341

**Comment by j-travis** [comment]
Thank you for this. 
Since there is no action on our part,  i will close this ticket. 

If you have a blog/writeup/video you'd like to share with the community, please consider posting on our subreddit:

https://www.reddit.com/r/kasmweb/
