### ISSUE TITLE
Upgrade wiped out default images

### ISSUE THREAD

**Issue by terrorpup** [kasmtech/workspaces-issues#311]
hi, 

So I just a upgrade from 1.11 to 1.12, using the following command 

cd /tmp
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.12.0.d4fd8a.tar.gz
tar -xf kasm_release*.tar.gz
sudo bash kasm_release/upgrade.sh --upgrade-images 

And seems successful, but it removed all my default images. I have no docker images now.  

Is there a way I an pull the default images again? 

I did file this error 

2022-12-30 18:29:36,543 [INFO] root: Performing Database Connectivity Test
Traceback (most recent call last):
  File "server.py", line 218, in <module>
IsADirectoryError: [Errno 21] Is a directory: '/tmp/default_images_unknown.yaml'

**Comment by j-travis** [comment]
We have resolved this style of issue in the 1.13 upgrade. The system now includes support for 1st and 3rd party registries allowing the admin to easy add new images to the deployment.
https://kasmweb.com/docs/latest/guide/workspace_registry.html
