### ISSUE TITLE
[Feature Request] - "Open In Isolation" Add-On should have the option to bypass needing a hyperlink

### ISSUE THREAD

**Issue by emilyastranova** [kasmtech/workspaces-issues#313]
### Existing Resources

- [X ] Please search the existing issues for related items
- [ X] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
We work in an environment where our URLs are not hyperlinks that we need to put in isolated containers (sandboxing). Instead the links are just text, but the extension does not support that in the context-menu.

**Describe the solution you'd like**
Add a setting that allows right-clicking any text and opening in Kasm as a URL

**Describe alternatives you've considered**
Dealing with it :disappointed: 

**Additional context**
Sometimes our URLs are also defanged (hxxp://google[.]com). It would be cool to allow parsing those for viewing in a Kasm Workspace

**Comment by j-travis** [comment]
Thanks for the recommendations.
I could see it being helpful have the extension work on highlighted text for example.

As far as the defanging- people do this in all sorts of ways that It would be challenging to come up with rules that work in all situations.  Maybe we could allow the user to add their own regex/parsing rules so that you could customize it.

**Comment by emilyastranova** [comment]
@j-travis Are there any plans of making the extension code open-source so I can help with the feature implementation?

**Comment by j-travis** [comment]
There are no plans at the moment, but honestly its probably just due to priorities. 

If you download the extension you'll see we dont obfuscate the code and its pretty simple. The main logic is <100 lines of code - so you should be able to pretty easily re-create your own.

**Comment by emilyastranova** [comment]
What is the copyright/licensing of the extension? Would I get in trouble for distributing the new feature

**Comment by j-travis** [comment]
We've published a new version of the extension `0.1.2` . It should be live in the next few days.
It includes the option to search text, and add a list of regex substitution rules for those who want to work with defanged urls etc.

Docs: https://kasmweb.com/docs/latest/how_to/kasm_extension.html#configuration-options
