### ISSUE TITLE
[Bug] - Disable GPU(s) on the docker agent

### ISSUE THREAD

**Issue by asapcatftw** [kasmtech/workspaces-issues#314]
**The bug**
KASM is not able to provision workspaces on a server with multiple Nvidia GPUs that are not supported under the same drivers. In my case, I have a Dell server with the following: 
- GPUs: 1x Nvidia A40, 1x Nvidia GTX 1060, 1x Nvidia K80 (1 physical card 2 GPUs)
- GPU driver: v525

**To Reproduce**
1. Install KASM on a server with 2 different GPUs that can not be supported under the same drivers. 
2. nvidia-smi should only show 1 GPU enabled.
3. Create workspaces with GPU enabled.
4. KASM will only provision 1 GPU workspace and fail on the 2nd. 

**Expected behavior**
KASM should ignore the GPUs without the drivers and should only use the ones listed under /dev/dri

**Screenshots**
![image](https://user-images.githubusercontent.com/31966895/210262035-3092e53b-ea2a-4a8a-b0e1-f46f42871b2c.png)
![5d4e9e79724527c7813ce59e79e14833](https://user-images.githubusercontent.com/31966895/210263707-0d8107f8-1837-441f-aa4c-73983e3d945c.gif)
![image](https://user-images.githubusercontent.com/31966895/210263231-cecc972d-43d0-4b29-b71d-ed24d8e703bc.png)

**Workspaces Version**
Version 1.12

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser Edge, firefox

Originally posted on Reddit: https://www.reddit.com/r/kasmweb/comments/zz83t5/is_it_possible_to_disable_gpus_on_the_docker_agent/

Let me know if you need to run any tests om the server.

**Comment by mmcclaskey** [comment]
@asapcatftw, we do have an open issue on this. There are two workarounds that may help. 

The kasm_agent container looks for an environmental variable `KASM_GPU_IDS`. If defined, it will only consider GPUs that are in this comma separated list of IDs. To get the ID, run `sudo lshw -C video`. 

```bash
  *-display                 
       description: VGA compatible controller
       product: GA107M [GeForce RTX 3050 Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       logical name: /dev/fb0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=nouveau latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       resources: iomemory:600-5ff iomemory:610-60f irq:144 memory:81000000-81ffffff memory:6000000000-60ffffffff memory:6100000000-6101ffffff ioport:4000(size=128) memory:82000000-8207ffff
```
From this output, find the card you want and get the ID from the **bus info** field. Remove the "pci@". So for my system, the target ID is "0000:01:00.0".

Now modify /opt/kasm/current/docker/docker-compose.yaml, add the environmental variable KASM_GPU_IDS with the value being the ID of the target card, as shown here. You will need to add the "environment" key to the kasm_agent service in the yaml.

```yaml
  kasm_agent:
    container_name: kasm_agent
    image: "kasmweb/agent:1.12.0"
    environment:
      KASM_GPU_IDS: "0000:01:00.0"
```

Next remove the container and bring things back up.

```bash
sudo docker rm -f kasm_agent
sudo /opt/kasm/bin/start
```

Check the logs and you should see the agent filter and select the appropriate GPU.

```bash
2023-01-19 13:27:14,971 [DEBUG] __main__.handler: Provisioner initialized with 1 GPU(s)
2023-01-19 13:27:15,469 [DEBUG] __main__.handler: GPU ID (0000:01:00.0) added per user defined filter
2023-01-19 13:27:15,477 [INFO] __main__.handler: Removed kasm_gpu_helper container.
2023-01-19 13:27:15,477 [INFO] __main__.handler: Running kasm_gpu_helper to collect GPU stats.
```

The second workaround is for non-Nvidia GPUs, but may work for this scenario as well.

https://www.kasmweb.com/docs/latest/how_to/manual_intel_amd.html

**Comment by asapcatftw** [comment]
I was able to only assign the A40 and 1060 GPUs by updating the docker-compose.yaml file.
