### ISSUE TITLE
[Feature Request] - Unable to Locate Kali Dockerfile 

### ISSUE THREAD

**Issue by PhasmaShell** [kasmtech/workspaces-issues#316]
To whom it may concern,

I would like to create a custom Kali image; however, under `kasmtech/workspaces-images`, Kali is nowhere to be found. Please provide correct path.

Thank you.

**Comment by j-travis** [comment]
Its a bit tricky to find but its in this repo:
https://github.com/kasmtech/workspaces-core-images/blob/develop/dockerfile-kasm-core

Notably if you look at our pipeline, Kali is built by passing in special build arguments: https://github.com/kasmtech/workspaces-core-images/blob/develop/.gitlab-ci.yml#L129

The important ones being:

```
--build-arg BASE_IMAGE="kalilinux/kali-rolling:latest" --build-arg START_PULSEAUDIO="1" --build-arg EXTRA_SH="kali.sh"  --build-arg DISTRO="kali"  --build-arg LANG="" --build-arg LANGUAGE=""  --build-arg LC_ALL=""   -f dockerfile-kasm-core .
```
