### ISSUE TITLE
[BUG] KasmWeb Discord requiring update - not working

### ISSUE THREAD

**Issue by rcortespr** [kasmtech/workspaces-issues#317]
Fresh install of KASM, default 1.12.0 discord workspace is requesting an update upon launch.
I got the same error on the Demo page https://app.kasmweb.com/#/cast/3644724874 

It does not allow me to move forward no matter what selection I make on the update request.
 
![image](https://user-images.githubusercontent.com/111906629/210468358-473de63a-921f-4238-8ee0-1763b4f2f10f.png)

**Comment by 3kh0** [comment]
I also get this problem

**Comment by j-travis** [comment]
Discord is very aggressive about requiring the client to be up to date, so its not surprising the version built into the `1.12.0` tag is already to old. You'll want to use our `rolling` tags that are built nightly.

e.g `kasmweb/discord:1.12.0-rolling`

Ref: https://kasmweb.com/docs/latest/guide/custom_images.html#rolling-docker-images

**Comment by 3kh0** [comment]
That should be done by default then but ok

**Comment by rcortespr** [comment]
> Discord is very aggressive about requiring the client to be up to date, so its not surprising the version built into the `1.12.0` tag is already to old. You'll want to use our `rolling` tags that are built nightly.
> 
> e.g `kasmweb/discord:1.12.0-rolling`
> 
> Ref: https://kasmweb.com/docs/latest/guide/custom_images.html#rolling-docker-images

Thanks, that solved it. It should be either the default image or noted in the documentation somewhere.
