### ISSUE TITLE
Windows RDP Domain login

### ISSUE THREAD

**Issue by Famku** [kasmtech/workspaces-issues#319]
Hi,

I am not able to login with domain\user on RDP.

It just work with username and password, even if I set the domain in the server settings.

The connection close immediately.

Is there another option?

**Comment by mmcclaskey** [comment]
Without more information, I couldn't say what the issue could be. We have this deployed for clients on domains and I have it setup in my lab and I've tried both domain\user and user@domain and they both work. 

Do you have any special characters in the username? 

Are you able to connect to the Windows server using a traditional RDP client using the same username and password?

If not, is the user allowed to have remote sessions by AD group policy?

**Comment by Famku** [comment]
I solved the issue by adding "domain"to the guac settings

Thanks for the response
