### ISSUE TITLE
[Bug] - 502 Gateway errors

### ISSUE THREAD

**Issue by 3kh0** [kasmtech/workspaces-issues#323]
### Existing Resources

- [X] Please search the existing issues for related problems
- [X] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [X] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [X] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [X] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**

**To Reproduce**
1. Go to login
2. Already get `login_settings` with a 502 error
3. Enter in login
4. 502 Error in `authenticate`

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/58097612/213443147-17cf60e4-3785-4a07-b4b4-6d18ff7fedcf.png)

![image](https://user-images.githubusercontent.com/58097612/213442495-b620b67b-e7c3-4691-b356-ae583b36770b.png)

**Workspaces Version**
1.20 I believe

**Workspaces Installation Method**
Single server on Linode

**Client Browser (please complete the following information):**
 - OS: Chrome OS
 - Browser Chrome
 - Version 109
 - 
[Chrome 109 on Chrome OS 15236](https://www.whatismybrowser.com/detect/what-version-of-chrome-do-i-have)

**Workspace Server Information (please provide the output of the following commands):**
 - Linux localhost 5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
 - `sudo docker info`

 Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 9
  Running: 5
  Paused: 0
  Stopped: 4
 Images: 34
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-57-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.763GiB
 Name: localhost
 ID: RRM4:OF3T:UR6H:SEY5:SEP3:36MC:EWDA:CE27:EJAB:B55V:42AU:KXDU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 - `sudo docker ps | grep kasm`

![image](https://user-images.githubusercontent.com/58097612/213442153-3f84b589-7d61-441f-9049-006ea484d10f.png)

**Additional context**

**Comment by mmcclaskey** [comment]
It looks like the kasm_db is in a restarting state. If the kasm_api and kasm_manager cannot talk to the database, they will also constantly restart due to failed healthchecks. First start by stopping and then starting the services

```bash
sudo /opt/kasm/bin/stop
sudo /opt/kasm/bin/start
```

If the containers still do not come up in a healthy state, start by looking at the logs of the kasm_db.

```bash
sudo docker logs --tail 50 kasm_db
```

Please provide the output of the kasm_db logs.

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/213453769-f7f91814-13e4-4b2b-8928-29d8e21798f5.png)

**Comment by mmcclaskey** [comment]
As indicated by the logs, it appears there is not enough disk space left on your system and thus postgres fails to start.

can you provide the output of

```bash
sudo df -h
```

When you install Kasm Workspaces, it automatically downloads a number of Workspace images, a number of which you may not need. I would recommend trying to clear out images you don't want, for example...

```bash
sudo docker images
REPOSITORY                     TAG              IMAGE ID       CREATED         SIZE
kasmweb/ubuntu-focal-desktop   1.12.0  6b72e0ecbc4a   29 hours ago    7.16GB
kasmweb/core-kali-rolling      1.12.0          bc0f2e8e7364   13 days ago     11.2GB
kasmweb/opensuse-15-desktop    1.12.0          aecc6cda8c7d   13 days ago     5.98GB
kasmweb/super-tux-kart         1.12.0          c046f018e38e   13 days ago     3.62GB
kasmweb/centos-7-desktop       1.12.0          bbc6aa6e33d9   13 days ago     3.66GB
kasmweb/doom                   1.12.0          ede24e778f71   13 days ago     2.32GB
kasmweb/retroarch              1.12.0          c8d5bcc7dc12   13 days ago     2.42GB
kasmweb/filezilla              1.12.0          14328ee56161   13 days ago     2.26GB
kasmweb/terminal               1.12.0          7eb6b8e36173   13 days ago     2.72GB
kasmweb/libre-office           1.12.0          474993a9255d   13 days ago     3.28GB
kasmweb/chromium               1.12.0          c368fcca5269   13 days ago     2.53GB
kasmweb/firefox                1.12.0          5d27daa2120c   13 days ago     2.48GB
kasmweb/vs-code                1.12.0          f748847de5c1   13 days ago     2.64GB
kasmweb/gimp                   1.12.0          7788374f20df   13 days ago     2.32GB
kasmweb/thunderbird            1.12.0          48d0a519723d   13 days ago     2.47GB
kasmweb/remmina                1.12.0          4ae4414395d5   13 days ago     2.24GB

sudo docker rmi kasmweb/remmina:1.12.0
sudo docker rmi kasmweb/doom

sudo /opt/kasm/bin/stop
sudo /opt/kasm/bin/start

# stop the agent to prevent it re-downloading the images
sudo docker stop kasm_agent
```

If you were able to remove the images to free up disk space, you should be able to log into kasm after running the above commands to restart the services and stop the kasm_agent. In the Kasm Admin UI, go to Workspaces and delete Workspace definitions for the docker images you removed. If you don't, the agent will start downloading them again.

Hopefully this clean up is all that is needed. Sometimes the disk space can be so full that `docker rmi` will not work. In that case, you will need to delete files from the full volume until you have enough space that `docker rmi` will work again.

Disclaimer: We don't know anything about your system and what may be using the disk space or how the volumes are defined, what file systems you are using, etc. Please take our advice and apply in the proper context for your system.

**Comment by 3kh0** [comment]
![image](https://user-images.githubusercontent.com/58097612/213462071-ae2bc57f-9d49-4e31-bbaf-d7bf381dc895.png)

I am only using this server for kasm, it is a linode server 8gb of ram and 160gb of storage

**Comment by 3kh0** [comment]
I followed the default install instructions

**Comment by 3kh0** [comment]
and when I try to run `sudo docker rmi` i do not have space, anything I should do

**Comment by 3kh0** [comment]
I was download some big files on a kasm so that might be the issue, is there like a cache or place where those are stored so i can delete them

**Comment by 3kh0** [comment]
OK, how would i just reset it all, like restore from factory settings, it is all screwed up

**Comment by 3kh0** [comment]
@mmcclaskey

**Comment by 3kh0** [comment]
Ok, im just doing a clean install of kasm, `sudo rm -rf / --no-preserve-root`

next time i need to be careful of my storage!
