### ISSUE TITLE
Default brave workspace config

### ISSUE THREAD

**Issue by 3kh0** [kasmtech/workspaces-issues#324]
So i had deleted the og images, so i need to readd brave, what are the default config for it? and how do i set that up

**Comment by 3kh0** [comment]
i found some info in https://kasmweb.com/docs/latest/guide/custom_images.html

**Comment by j-travis** [comment]
Admittedly, manually adding images from the standard library is a bit clunky at the moment. We recognize this and have a fix coming in the next release. It should hit the [developer preview](https://kasmweb.com/docs/latest/developers/builds.html) builds in the next week or so for beta testing. Basically it will allow you to add first and third party Workspaces registries to your deployment and provide an easy menu to kindof one click add them to your system.

Until then, you'll have to manually add all the fields yourself. The list of the default images and their configurations can be found in the installer package. After you extract the tarball, you'll find a file named: kasm_release/conf/database/seed_data/default_images_amd64.yaml . there is also one for arm64. This contains the data that gets mapped .

**Comment by 3kh0** [comment]
Thanks!
