### ISSUE TITLE
[Bug] - Enabling shipped with Kasm workspace does not trigger new image download

### ISSUE THREAD

**Issue by idchlife** [kasmtech/workspaces-issues#325]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Enabling workspace does not trigger download for agent.

**To Reproduce**
1. Clean install Single Server Kasm Workspaces, 1.12
2. In workspaces enable Kali Linux
3. See that within an hour no download of image occurs

**Expected behavior**
Kali Linux image downloaded and available in workspaces

**Screenshots**
-

**Workspaces Version**
Version 1.12

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: macOS
 - Browser Chromium
 - Version 

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**
WORKAROUND

1) Clone workspace
2) See that download complete within 10 minutes

**Comment by j-travis** [comment]
I can't think of a reason why this would occur and why cloning would fix it.  I think it was just happenstance.  The Kali image is over 10GB so its possible, that it simply took a long time to download.

**Comment by idchlife** [comment]
@j-travis I tend to agree in this case. Will close this issue. I don't have enough proof right now.
