### ISSUE TITLE
[Feature Request] - Export/Import Kasmweb and Workspace settings

### ISSUE THREAD

**Issue by jbarr** [kasmtech/workspaces-issues#327]
**Existing Resources**
None found.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to install a fresh, new Kasmweb instance and apply all Kasmweb and Workspace settings from another instance. Currently, when I install a new instance of Kasmweb, I have to manually apply a number of Kasmweb and Workspace settings to tailor the installation to my environment and to my liking. 

**Describe the solution you'd like**
I would like to export and save all Kasmweb and Workspace settings from my current instance and then import them into another Kasmweb instance. Ideally, I'd like to be able to review the settings and make changes prior to applying the import, but a straight import would work as well.

**Describe alternatives you've considered**
I've looked into database backups and scripting, but they proved to be difficult, unreliable, and very prone to error, especially when crossing versions.

**Additional context**
None.

**Comment by j-travis** [comment]
We have added the ability to export and import the entire Kasm Workspaces configuration via yaml configuration via the UI.  You can also use that same yaml to import into a second instance , or slipstream the config during install  - As long as they are running the same version for Workspaces.

This feature is no available for testing in the [Developer Preview builds.](https://kasmweb.com/docs/latest/developers/builds.html)

- Feature Documentation: https://kasmweb.com/docs/develop/guide/import_export.html
