### ISSUE TITLE
Allow Kasm Workspaces to remote into a Mac - Example

### ISSUE THREAD

**Issue by AllenSikorski** [kasmtech/workspaces-issues#329]
### Existing Resources

- [X ] Please search the existing issues for related items
- [X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
It's frustrating when you have to use multiple pieces of software to remote into either Windows or Mac. Having a single software built into the browser like Kasm would be awesome to be able to easily and quickly switch between RDP for windows and for VNC or a VNC equivalent for Mac.

**Describe the solution you'd like**
Create a Kasm-based VNC that allows one to remote into a Mac.

**Describe alternatives you've considered**
I tried the KasmVNC, but it does not appear to work for remoting into a Mac.

**Additional context**
N/A

**Comment by j-travis** [comment]
Thanks for the feedback,
We've now added the ability to connect to arbitrary machines over traditional VNC and SSH in addition to the RDP and KasmVNC connections we added in 1.12.

You can test this out in the developer preview builds. https://kasmweb.com/docs/latest/developers/builds.html
