### ISSUE TITLE
Installation Error when upgrading from 1.11.0 to 1.12.0

### ISSUE THREAD

**Issue by fanuelsen** [kasmtech/workspaces-issues#330]
### Existing Resources

- [ X ] Please search the existing issues for related problems
- [ X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
when im trying to update from 1.11.0 to 1.12.0 on my ubuntu 20.04 system in the upgrade process i get this error:
` ⠿ Container kasm_db  Started 0.4s
Container kasm_db  Running
Traceback (most recent call last):
  File "server.py", line 164, in <module>
PermissionError: [Errno 13] Permission denied: '/opt/kasm/current/conf/app/api.app.config.yaml'
[1] Failed to execute script 'server' due to unhandled exception!`

This results in the kasm_api and kasm_manager container to go in to a endless reboot. I also tried to change the permissions on the file after the upgrade but with no success. 

**To Reproduce**
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.12.0.d4fd8a.tar.gz
tar -xf kasm_release_1.12.0.d4fd8a.tar.gz
sudo bash kasm_release/upgrade.sh --add-images --proxy-port 443

**Expected behavior**
The upgrade to succeed without errors

**Screenshots**

**Workspaces Version**
Version 1.11.0 to 1.12.0

**Workspaces Installation Method**
Single Server docker

**Workspace Server Information (please provide the output of the following commands):**
```
 - `uname -a` 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`  NAME="Ubuntu" VERSION="20.04.5 LTS (Focal Fossa)"
 - `sudo docker info`  Server Version: 20.10.21
```

**Comment by thelamer** [comment]
Did you happen to record the permissions of `/opt/kasm/current/conf/app/api.app.config.yaml` before you swapped them post the failed upgrade?
The error would seem to indicate that during the upgrade the api server attempted a start and it could not run properly, thus the seeding did not run properly during the upgrade phase when we init a clean install to load your backup into.

There are two ways to proceed here we can salvage your existing installation using the backup created during upgrade in `/opt/kasm/backups/kasm_db_backup.tar` (make a copy of that just in case) or we can remove the existing installation and do a clean install. How you proceed depends on the level of customization to your install. 

If it is heavily customized you can restore your DB backup using the process laid out in: 
https://www.kasmweb.com/docs/latest/upgrade/single_server_upgrade.html#manual-upgrade
Skipping the backup step as one was created during the upgrade. 

If not heavily customized you can simply remove the existing installation in a bad state with https://www.kasmweb.com/docs/latest/install/uninstall.html and perform a clean install. 

In either case right now before performing any actions I would recommend  making a copy of the entire contents of `/opt/kasm` to ensure you have all your data. IE `sudo cp -ax /opt/kasm /home/user/kasmbackup` . Also ensure that database file does in fact exist `/opt/kasm/backups/kasm_db_backup.tar`. 

Let me know about the file perm and how you would like to proceed.

**Comment by fanuelsen** [comment]
I did a snapshot of the vm its running on before the upgrade and just rolled it back, i can reproduce the same behaviour. I will check the permissions of that file.

**Comment by j-travis** [comment]
Closing as OBE
