### ISSUE TITLE
[Bug] - database "kasmapp" does not exist

### ISSUE THREAD

**Issue by batkins2** [kasmtech/workspaces-issues#331]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Receive 'FATAL - database "kasmapp" does not exist' in postgres logs after clean offline and online install of 1.12.0 x86_64 kasmweb. 502 bad gateway when trying to log in.

**To Reproduce**
1. https://kasmweb.com/docs/latest/install/single_server_install.html

**Expected behavior**
Log into kasmweb.

**Screenshots**

**Workspaces Version**
Version 1.12

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [109.0.5414.121]

**Workspace Server Information (please provide the output of the following commands):**
 Linux debian 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 12
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.771GiB
 Name: debian
 ID: a7df77b1-22f9-4def-8e0b-9412e412b7b6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

d766ddff7149   kasmweb/nginx:latest       "/docker-entrypoint.ΓÇª"   2 hours ago   Up 8 minutes                       80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
7d4d69cdc540   kasmweb/agent:1.12.0       "/bin/sh -c '/usr/biΓÇª"   2 hours ago   Up 8 minutes (healthy)             4444/tcp
        kasm_agent
910daa372f90   kasmweb/share:1.12.0       "/bin/sh -c '/usr/biΓÇª"   2 hours ago   Restarting (143) 24 seconds ago
        kasm_share
07b26b7df9b4   kasmweb/manager:1.12.0     "/bin/sh -c '/usr/biΓÇª"   2 hours ago   Up 50 seconds (health: starting)   8181/tcp
        kasm_manager
054411bbb07f   redis:5-alpine             "docker-entrypoint.sΓÇª"   2 hours ago   Up 8 minutes                       6379/tcp
        kasm_redis
1d4896c20d7b   kasmweb/api:1.12.0         "/bin/sh -c '/usr/biΓÇª"   2 hours ago   Restarting (143) 24 seconds ago
        kasm_api
71925188e7ab   kasmweb/kasm-guac:1.12.0   "/dockerentrypoint.sh"   2 hours ago   Up 8 minutes (healthy)
      kasm_guac
5f23efe7c00f   postgres:12-alpine         "docker-entrypoint.sΓÇª"   2 hours ago   Up 8 minutes (healthy)             5432/tcp
        kasm_db

**Additional context**

**Comment by j-travis** [comment]
When you created this bug ticket, it asked you to provide the output of the following commands to help us help you. Can you please provide these:

 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`
 
 It sounds like the install failed. I recommend looking through the output of the install for errors

**Comment by batkins2** [comment]
Is there an install log? I watched what I could during the install and it seemed to succeed. I've added necessary info to OP.
