### ISSUE TITLE
[Help wanted] Help with creating an image

### ISSUE THREAD

**Issue by Pegoku** [kasmtech/workspaces-issues#333]
Hello,
I like using kasm, and sometimes I create docker images with aplications
I have creted some images, like: minecraft java, krita and kdenlive
and I would like to be able to create an image with DaVinci Resolve
would it be possible?
I ask help because, I think, isn't possible to install it without GUI

**Comment by j-travis** [comment]
Likely, try this:

Launch a normal ubuntu workspace via Workspaces. Install/configure your application.

Then open a terminal on your server and run `docker commit` on the running container to create an image from it.

See https://docs.docker.com/engine/reference/commandline/commit/ for more details

Then try to add that new image to Workspaces and see if it launches.

We have an experimental code branch that automates this process so admins can take images for running sessions from the GUI. So far it seems to work pretty well - but I wouldn't be surprised if there are some gotchas along the line somewhere.
