### ISSUE TITLE
[Bug] - Discord asks to upgrade the client, however it does nothing.

### ISSUE THREAD

**Issue by WickedDuck** [kasmtech/workspaces-issues#335]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When I launch Discord Workspace on Kasm, it will load then bring up a prompt saying "Must be your lucky day, there's a new update!". It gives me options to use .deb files or .tar.gz files and when I try both it just closes then reopens.
**To Reproduce**
1. Go to Kasm,
2. Click on Discord
3. Let it fully open
4. It'll show the prompt.

**Expected behavior**
Discord should've fully opened and brought a login screen up to me.
**Screenshots**
![image](https://user-images.githubusercontent.com/89361696/221017512-1a2b7838-e468-4492-bd38-581c95427dbe.png)

**Workspaces Version**
Version 1.12.0

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 108

**Workspace Server Information (please provide the output of the following commands):**
`root@vmi1195246:~# uname -a
Linux vmi1195246.contaboserver.net 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
root@vmi1195246:~#  cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
root@vmi1195246:~#  sudo docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 16
  Running: 15
  Paused: 0
  Stopped: 1
 Images: 43
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-139-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 29.39GiB
 Name: vmi1195246.contaboserver.net
 ID: 3f00ac14-5e6c-4b44-a9f5-74799cc822c2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
root@vmi1195246:~#  sudo docker ps | grep kasm
88650900a591   kasmweb/discord:1.12.0              "/dockerstartup/kasm…"   22 minutes ago   Up 22 minutes          4901/tcp, 5901/tcp, 6901/tcp                                     administrato_bd8f1678
b6f06e1c20d2   kasmweb/steam:1.12.0                "/dockerstartup/kasm…"   26 minutes ago   Up 26 minutes          4901/tcp, 5901/tcp, 6901/tcp                                     administrato_9641e04e
5e20db12d50a   kasmweb/nginx:latest                "/docker-entrypoint.…"   2 hours ago      Up 2 hours             80/tcp, 0.0.0.0:2134->2134/tcp                                   kasm_proxy
1dea28de13c0   kasmweb/share:1.12.0                "/bin/sh -c '/usr/bi…"   2 hours ago      Up 2 hours (healthy)   8182/tcp                                                         kasm_share
afe9558ed308   redis:5-alpine                      "docker-entrypoint.s…"   2 hours ago      Up 2 hours             6379/tcp                                                         kasm_redis
08389b89cadc   postgres:12-alpine                  "docker-entrypoint.s…"   2 hours ago      Up 2 hours (healthy)   5432/tcp                                                         kasm_db
21069eebd19c   kasmweb/agent:1.12.0                "/bin/sh -c '/usr/bi…"   2 hours ago      Up 2 hours (healthy)   4444/tcp                                                         kasm_agent
5caf93928929   kasmweb/api:1.12.0                  "/bin/sh -c '/usr/bi…"   2 hours ago      Up 2 hours (healthy)   8080/tcp                                                         kasm_api
9908d96c939e   kasmweb/kasm-guac:1.12.0            "/dockerentrypoint.sh"   2 hours ago      Up 2 hours (healthy)                                                                    kasm_guac
4d504ca09f40   kasmweb/manager:1.12.0              "/bin/sh -c '/usr/bi…"   2 hours ago      Up 2 hours (healthy)   8181/tcp                                                         kasm_manager`

**Additional context**
Running Community Edition. Workspace is latest version available.

**Comment by j-travis** [comment]
https://github.com/kasmtech/workspaces-issues/issues/317
