### ISSUE TITLE
unable to use web filter

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#34]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/34) by Benjamin Jacobs (Bitbucket: [Benjamin Jacobs](https://bitbucket.org/Benjamin Jacobs), ).**

----------------------------------------

I’d like to use the web filter functionality but I can’t get this to work. When I add the web filter to the group settings the browser kasms just fail to load \(empty background\) and in the desktop versions I get a proxy error and I can’t load any site. When I remove the policy from the group everything works fine.

I’m running version 1.8.0 on a different port then 443.

the test web filter is configured without any white or blacklists \(for testing purposes\) and Deny by default is set to False.

**Comment by imightbelosthere** [comment]
Having the same issue... So what's the solution here? is there any configuration file we need to change in order for web filter to work when we use a non-standard port during installation?

**Comment by imightbelosthere** [comment]
I guess no one cares... Ah well, back to using Qubes :)

**Comment by j-travis** [comment]
@imightbelosthere , its been less than 1 business day here in the US since your comment

**Comment by KogPop** [comment]
I have the same problem. I'm using the latest version of Kasm. The problem occurs if kasm is installed on oracle linux 9.
I used standard ports. Please check the problem - (works on Debian)

**Comment by j-travis** [comment]
This original issue was solved in version 1.11
Closing https://kasmweb.com/docs/latest/release_notes/1.11.0.html#bugfixes

**Comment by KogPop** [comment]
Nice reply! **I said, i'm using the latest version of Kasm and the standard ports.** So i pleas to check the problem on Oracle linux 9. (it's important for me to install this on oracle) but when i tried it on debian it works.
