### ISSUE TITLE
Help - Settings permissions

### ISSUE THREAD

**Issue by Nuemit** [kasmtech/workspaces-issues#342]
I want to have one Group for different Settings, i.e. 
> One Group should be able to create new Workspaces but should not be able, to edit the Group Settings. 

From the Documentation and the Group settings, I don't think this is Possible right now, but to be sure, I wanted to ask if. 

For me, especially the Workspace Creation is interesting, and I want to have not only the Administrator Group to Create Workspaces (not the Session, only the Workspace configuration).

**Comment by j-travis** [comment]
Hi,
I don't fully understand what you are asking, but Kasm Workspaces supports defining multiple groups and assigning any of the Group Settings or Workspaces and any of the groups. 

A member can be a part of multiple groups and the settings will layer.  If conflicts exist, the system will chose the setting defined on the group with lower priority number.

Here is a video guide on how groups  and group settings work: https://www.youtube.com/watch?v=teJSUxKEbfE&t=105s
