### ISSUE TITLE
[Help Wanted] Docker Networks Not Shown

### ISSUE THREAD

**Issue by shape-err** [kasmtech/workspaces-issues#344]
Following the [VPN Sidecar Container](https://kasmweb.com/docs/latest/how_to/vpn_sidecar.html#customizing-workspaces) guide, I have created a container and docker network for a VPN. However, when selecting "Restrict Image to Docker Network" within any Kasm Workspace, only bridge and kasm_default_network are listed.

![226776802-e92480c3-ed69-4690-aa3f-d9eaa5b5b5a5](https://user-images.githubusercontent.com/8568594/227050057-ed12b335-ebcf-41d7-8ec5-895000bcc46a.png)

**Comment by j-travis** [comment]
Can you please provide responses to the questions we ask when creating a bug ticket: 
https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D+-+Example

These help us get an idea of your environment so we can try and help you

**Comment by shape-err** [comment]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When editing a Kasm Workspace Image, restricting an image to a Docker network does not show the full list of networks that have been made within Docker. 

**To Reproduce**
Steps to reproduce the behavior:
1. Create a VPN container and Docker network following the VPN Sidecar Container guide.
2. Open Kasm Workspaces > Docker Ubuntu Jammy > Edit > Restrict Image to Docker Network.
3. The Docker network I made for the VPN sidecar, gluetun_network, does not appear in the list of Docker Networks.

**Expected behavior**
I should see gluetun_network within the list. Should also see other docker networks from different containers. 

**Screenshots**
See above

**Workspaces Version**
Version 1.12

**Workspaces Installation Method**
linuxserver.io

**Client Browser:**
 - OS: Linux (Ubuntu)
 - Browser: Firefox
 - Version: 111.01

**Workspace Server Information:**
 - Linux 5.15.0-67-generic # 74-Ubuntu SMP
 - Ubuntu 22.04.2 LTS Jammy Jellfish
 - Docker version 20.10.14, build a224086
 - lscr.io/linuxserver/kasm:latest

**Additional context**
For my VPN container I am running Gluetun, here is how I setup both the Docker network and container:

```
docker network create \
  --driver=bridge \
  --opt icc=true \
  --subnet=172.23.0.0/16 \
  gluetun_network
```
  
```
docker run -d \
  --cap-add NET_ADMIN \
  --cap-add NET_RAW \
  --name gluetun \
  --net gluetun_network \
  --ip 172.23.0.2 \
  -e VPN_SERVICE_PROVIDER=N/A \
  -e VPN_TYPE=N/A \
  -e WIREGUARD_PRIVATE_KEY=N/A \
  -e WIREGUARD_ADDRESSES=N/A \
  -e SERVER_CITIES=N/A \
  --restart unless-stopped \
  qmcgaw/gluetun
```

**Comment by j-travis** [comment]
Thank you. that helps.

The reason your docker networks aren't showing up in the list, is because Kasm cant see them.

The VPN sidecar instructions are written with the assumption you used the standard installation method of installing Kasm directly on the host,  not wrapped inside a DinD (Docker in Docker) container like the lsio build.

When you are creating the docker network on your host, Kasm can't see it because its running a different instance of docker inside that lsio container. 

You could try to exec into the kasm container and run through the instructions there, but I'm not sure it would work.

**Comment by shape-err** [comment]
Thanks for the help and explanation! I can see the docker networks listed after setting up Kasm directly on host. I've successfully connected a CentOS Kasm container to the gluetun_network, however, the internet traffic is not routing through the Gluetun VPN container. I can still see my ISP IP after running a test on ipleak.net, maybe this is more so a problem with the Gluetun container vs Kasm, but I'm not sure.
