### ISSUE TITLE
Bug - workspace opening in same windows, not in new window

### ISSUE THREAD

**Issue by onlineapps-cloud** [kasmtech/workspaces-issues#346]
hi, when i have existing workspace and click to resume, this workspace is oppened in same window, but when i create workspace i configure to open in new window.

https://user-images.githubusercontent.com/69077240/227571340-76cfc225-dd5a-414a-8177-7830a87a428b.mp4

**Comment by j-travis** [comment]
Thanks for the feedback, We just fixed this and its available in the latest developer preview builds.
https://kasmweb.com/docs/latest/developers/builds.html

It will remember your previous preference when resuming
