### ISSUE TITLE
docker build and run chrome ,access show black

### ISSUE THREAD

**Issue by andyoulovexy** [kasmtech/workspaces-issues#347]
After two hours or one hour, if you visit again, the screen will be black.like this:
![image](https://user-images.githubusercontent.com/38940994/227718352-8d7d2044-a385-4fc8-bbc4-d78c770628d2.png)

**Comment by j-travis** [comment]
That was a bug for a short time where the power management settings such as screensaver and screen disabling were not being applied. This should be fixed now, You'll need to make sure you pull in the latest "core" images to get the updates
