### ISSUE TITLE
[Bug] - Asian language (Thai) not displaying correctly

### ISSUE THREAD

**Issue by toonshouin** [kasmtech/workspaces-issues#358]
**Describe the bug**
Asian language (Thai) not displaying correctly on the Program or Website.

**To Reproduce**
1. Go to any browser that you can launch on your workspace.
2. Navigate to any Thai website. (Ex. beartai.com , pms.ac.th , dusitnon.ac.th) and you will see it can't display correctly.
(Some websites have their font embedded like beartai.com so the webpage is normal but on the title bar on the top will broken.) 
![image](https://user-images.githubusercontent.com/82090464/230843824-95170309-4034-41d8-aa19-a13d9acfea6d.png)

**Expected behavior**
Thai font should be working fine with no issues and without a blank screen or the rectangle fonts like this one.
![image](https://user-images.githubusercontent.com/82090464/230843395-e51069d1-0de9-4f29-8a55-1f1e3da81a30.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/82090464/230843524-7a7d6873-5ac4-4eaa-9724-2933201f312a.png)
![image](https://user-images.githubusercontent.com/82090464/230843635-fdf8979f-7e56-43c6-a57c-ca0ad29dd22c.png)

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Virtual Machine on Synology NAS

**Client Browser (please complete the following information):**
 - Browser : Firefox
 - Version : 111.0.1

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
`Linux sh-kasm 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - `cat /etc/os-release`
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

 - `sudo docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 20
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-146-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.834GiB
 Name: sh-kasm
 ID: 700f0218-58a0-4d84-b1ce-769872a1e394
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
 - `sudo docker ps | grep kasm`
```
29343eef8850   kasmweb/nginx:latest       "/docker-entrypoint.…"   38 hours ago   Up 38 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
8543575f7790   kasmweb/share:1.13.0       "/bin/sh -c '/usr/bi…"   38 hours ago   Up 38 hours (healthy)   8182/tcp                                        kasm_share
f0660479e7ad   kasmweb/agent:1.13.0       "/bin/sh -c '/usr/bi…"   38 hours ago   Up 38 hours (healthy)   4444/tcp                                        kasm_agent
b29051940ae2   redis:5-alpine             "docker-entrypoint.s…"   38 hours ago   Up 38 hours             6379/tcp                                        kasm_redis
77450b5390b2   kasmweb/api:1.13.0         "/bin/sh -c '/usr/bi…"   38 hours ago   Up 38 hours (healthy)   8080/tcp                                        kasm_api
9f35e480754c   kasmweb/kasm-guac:1.13.0   "/dockerentrypoint.sh"   38 hours ago   Up 38 hours (healthy)                                                   kasm_guac
cbfb160a435d   kasmweb/manager:1.13.0     "/bin/sh -c '/usr/bi…"   38 hours ago   Up 38 hours (healthy)   8181/tcp                                        kasm_manager
3a92cae08985   postgres:12-alpine         "docker-entrypoint.s…"   38 hours ago   Up 38 hours (healthy)   5432/tcp                                        kasm_db
```

**Comment by j-travis** [comment]
Can you please try using the "develop" tags of our images. We recently pushed an update that includes additional fonts.  It seems to resolve the issues you reported. (e.g `kasmweb/chromium:develop`)
![image](https://user-images.githubusercontent.com/48762190/231826080-88d9bf2e-7b13-47ea-9efd-4e3bce88d825.png)

**Comment by toonshouin** [comment]
Okay. After I tried develop tag. It's working fine now. Here is screenshot.

![image](https://user-images.githubusercontent.com/82090464/232195879-62ebc3d6-ccc7-444a-8294-45bb8feee3cc.png)
![image](https://user-images.githubusercontent.com/82090464/232195985-04978113-dbdb-4e7d-b4b2-b9a33dfa39ae.png)
![image](https://user-images.githubusercontent.com/82090464/232196119-e5426e2b-9f4d-4807-b0e8-74435e621910.png)
![image](https://user-images.githubusercontent.com/82090464/232196143-bd7ccb80-efe5-4d64-9025-77c38670ae06.png)
