### ISSUE TITLE
Error: After upgrading to latest update, kasm keeps redirecting to dashboard after creating session.

### ISSUE THREAD

**Issue by Isaac-Cooper** [kasmtech/workspaces-issues#359]
Able to fix this? It was working fine and then I upgraded it cause I saw there was a new update. After upgrading, I created a session to test it and it redirected me to dashboard after I launched the session.

Error I am getting:

`
host: [HOST]
ingest_date: 202304110234
application: kasm_api
levelname: ERROR
message: Unhandled exception occurred Traceback (most recent call last): File "cherrypy/_cprequest.py", line 628, in respond File "cherrypy/_cprequest.py", line 687, in _do_respond File "cherrypy/lib/encoding.py", line 219, in __call__ File "cherrypy/_cpdispatch.py", line 54, in __call__ File "client_api.py", line 1618, in kasm_connect KeyError: 'connection_type'
process: root
client_ip: 172.19.0.9
user_agent: [USER_AGENT]
`

You help is much appreciated.

**Comment by j-travis** [comment]
When reporting bug tickets, we ask a number of questions that help us get an idea of your environment. With these questions, the community doesnt have a good place to help you start troubleshooting.  Please fill out the information requested.

https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBug%5D+-+Example

please include what version you were at before upgrading

**Comment by Isaac-Cooper** [comment]
It was running 1.12 and now it is 1.13

**Comment by Isaac-Cooper** [comment]
I don't think this is a bug, but just an issue on my side.

**Comment by rickkoliser** [comment]
Hello,
    There is a setting called "Enable Kasm Authorization" under Auth in the Settings page of the Admin panel. https://kasmweb.com/docs/latest/security/workspaces.html#global-settings. Can you check if this setting is disabled? If it is disabled can you try enabling the setting, restarting Kasm and trying to launch a workspace again?
Thanks,
-Rick

**Comment by Isaac-Cooper** [comment]
It is already enabled and the Kasm Authorization Domain is set to $request_host$

**Comment by Isaac-Cooper** [comment]
I have restarted Kasm and it appears to be working fine, thanks for your help!
