### ISSUE TITLE
Install on Raspberry Pi4 fails with /tmp/kasm_release/bin/utils/yq_armv7l: No such file or directory

### ISSUE THREAD

**Issue by enzoweb** [kasmtech/workspaces-issues#363]
I followed the instructions here: https://kasmweb.com/docs/latest/install/single_server_install.html#installation-guide
Using the commands
cd /tmp
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.13.0.002947.tar.gz
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_service_images_arm64_1.13.0.002947.tar.gz
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_workspace_images_arm64_1.13.0.002947.tar.gz
tar -xf kasm_release_1.13.0.002947.tar.gz
sudo bash kasm_release/install.sh --offline-workspaces /tmp/kasm_release_workspace_images_arm64_1.13.0.002947.tar.gz --offline-service /tmp/kasm_release_service_images_arm64_1.13.0.002947.tar.gz
It returns this in the log
I have read and accept End User License Agreement (y/n)? Checking if docker and docker compose are installed.
WARNING: No memory limit support
WARNING: No swap limit support
Docker is installed
23.0.3 is a supported version of docker.
Docker compose is installed
2.17.2 is a supported version of docker compose
Commands docker and docker compose detected.
Skipping Dependency Installation.
Checking if DEFAULT_PROXY_LISTENING_PORT (443) is free
Port (443) is not in use.
Swap Exists
WARNING: No memory limit support
WARNING: No swap limit support
Installing All Services
kasm_release/install.sh: line 447: /tmp/kasm_release/bin/utils/yq_armv7l: No such file or directory

This is in the /tmp/kasm_release/bin/utils directory

activate_kasm  db_backup  db_init  db_restore  db_upgrade  pull  yq_aarch64  yq_x86_64

So it looks as if the yq_armv7l component isn't included in the tar file, and I can't find it on the kasm website or anywhere

**Comment by j-travis** [comment]
It looks like you are trying to install on armv7 which is 32bit. We don't support that. We support arm64.
https://kasmweb.com/docs/latest/install/system_requirements.html

**Comment by enzoweb** [comment]
Thanks. I will close this.
