### ISSUE TITLE
[Bug] - Unable to add a 3rd party workspace

### ISSUE THREAD

**Issue by kabaga** [kasmtech/workspaces-issues#364]
### Existing Resources

- [ x ] Please search the existing issues for related problems
- [ x ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ x ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ x ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ x ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
The version that I am running is 1.13.0.357896 Web UI and 1.13.0.002947 API Server build. When I try to add the "https://kasmregistry.linuxserver.io/" to the Workspaces registry. It seems to be stuck in spinning loading icon. Nothing is happening.

**To Reproduce**
1. Go to 'Workspaces'
2. Click on 'Workspace Registry'
3. Click on 'Add new'
4. Paste the "https://kasmregistry.linuxserver.io/" to the url box
5. Click on 'ADD REGISTRY'

**Expected behavior**
The expected behavior is to load the linuxserver.io containers to be an option 

**Screenshots**
n/a

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
Single Server on a Debian 11 VM.

**Client Browser (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox and Chrome
 - Version: 111 and 111.0.5563.146 

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
``` 
Linux kasm 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
```
 - `cat /etc/os-release`
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
 - `sudo docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 23.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-21-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.734GiB
 Name: kasm
 ID: 4f32ad6b-c38b-46d8-be6d-2dbbb2610a5a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
 - `sudo docker ps | grep kasm`
```
e1aff7813652   kasmweb/nginx:latest       "/docker-entrypoint.…"   27 hours ago   Up 4 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
716c30905887   kasmweb/share:1.13.0       "/bin/sh -c '/usr/bi…"   27 hours ago   Up 4 hours (healthy)   8182/tcp                                        kasm_share
a27cbb950b05   kasmweb/agent:1.13.0       "/bin/sh -c '/usr/bi…"   27 hours ago   Up 4 hours (healthy)   4444/tcp                                        kasm_agent
0b2a745918b2   redis:5-alpine             "docker-entrypoint.s…"   27 hours ago   Up 4 hours             6379/tcp                                        kasm_redis
646c7cf55a07   kasmweb/api:1.13.0         "/bin/sh -c '/usr/bi…"   27 hours ago   Up 4 hours (healthy)   8080/tcp                                        kasm_api
9a343a0dae3e   kasmweb/kasm-guac:1.13.0   "/dockerentrypoint.sh"   27 hours ago   Up 4 hours (healthy)                                                   kasm_guac
087fd5ac4d13   kasmweb/manager:1.13.0     "/bin/sh -c '/usr/bi…"   27 hours ago   Up 4 hours (healthy)   8181/tcp                                        kasm_manager
17bdac9e3d30   postgres:12-alpine         "docker-entrypoint.s…"   27 hours ago   Up 4 hours (healthy)   5432/tcp                                        kasm_db
```

**Additional context**

**Comment by j-travis** [comment]
Is this still an issue for you. 

Are there any warning/error messages in the Kasm application logs, or in your browsers dev console?

**Comment by kabaga** [comment]
> Is this still an issue for you.
> 
> Are there any warning/error messages in the Kasm application logs, or in your browsers dev console?

Yes, I still can't add a new workspace. When I checked the Logging, I don't see any logs related to the workspace issue. The latest logs are about the heartbeat and database log rotation.

This is what it looks like:
![Screenshot 2023-05-02 at 16-34-53 Kasm Workspaces](https://user-images.githubusercontent.com/44072579/235791442-4e856d2b-9b1b-434e-b0e6-ce5e72a0cb6e.png)

**Comment by kabaga** [comment]
I tried it again and this time it worked. There is no change to the Kasm config; however, when I enter the same URL, Kasm accepted it right away.

**Comment by j-travis** [comment]
Perhaps the registry was down for some short period of time during the original test
