### ISSUE TITLE
The problem has been unable to be resolved, the password for help!

### ISSUE THREAD

**Issue by ShangTianYa** [kasmtech/workspaces-issues#369]
Linux system, when I use docker to install kasmweb/kali-rolling-desktop, I find that the internal container cannot log in!
    first step:
       docker pull kasmweb/kali-rolling-desktop
    Part Two:
       docker run -itd --name KaliLastDesktop --restart unless-stopped --network FuckWorldNetworks --ip 172.254.254.254 --shm-size=1024m -p 36501:6901 -e VNC_PW=Linux kasmweb/kali-rolling-desktop:1.13 .0 After running, it is found that neither the root password nor the default user inside the container can log in without a password! ! !
    Follow-up: Try + '--user root' and find that the default user still does not know the password and cannot operate, and then su - can be used normally after switching to root, but is the biggest problem considered? The risk of running a docker container as root is too high. I mean, can you run docker with non-root privileges, and then enter the container to sudo to run related commands! And it can inform the default password inside the container to change the password by itself.

**Comment by getyouamonte** [comment]
Hey I am no means no expert ,but If I understand correctly maybe this will help?

in this video a timestamp 11:21 

https://www.youtube.com/watch?v=ir3QhZp8864&t=1009s

Add that code into your kali linux image under the docker run config override (JSON) hopefully that helps your issue!

**Comment by ShangTianYa** [comment]
> 嘿，我不是专家，但如果我理解正确，也许这会有所帮助？
> 
> 在此视频中，时间戳为 11:21
> 
> https://www.youtube.com/watch?v=ir3QhZp8864&t=1009s
> 
> 在 docker run config override (JSON) 下将该代码添加到您的 kali linux 映像中，希望对您的问题有所帮助！

okok.This video has been watched and it has been determined that root is required to run. I am grateful for your reply
So - user root can solve the problem .>v<.

**Comment by getyouamonte** [comment]
Thats dope, Happy I could help!
Best wishes with everything you are working on!
