### ISSUE TITLE
[Bug] - Invalid auth token for connection_proxy - api/guac_get_managers

### ISSUE THREAD

**Issue by asapcatftw** [kasmtech/workspaces-issues#374]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Connection proxy errors after upgrading from v1.12.0 -> v1.13.0. I used the automatic upgrade script to do it.
I checked with kasmguac.app.config.yaml and both the ID and Token were copied.

Not sure how to fix this or where to check if the token is valid.

**Screenshots**
![image](https://user-images.githubusercontent.com/31966895/235522231-1de155c1-d0e9-43e4-85aa-8d8137d29995.png)

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 112.0.1722.64 

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a` 
 ```
Linux kasm-pve-01 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
 - `cat /etc/os-release` 
 ```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
```
 - `sudo docker ps | grep kasm`
```
d8e28c8acf28   kasmweb/api:1.13.0                             "/bin/sh -c '/usr/bi…"   About an hour ago   Up About an hour (healthy)   8080/tcp                                                                   kasm_api
1e9b6688331c   kasmweb/nginx:latest                           "/docker-entrypoint.…"   2 weeks ago         Up About an hour             80/tcp, 443/tcp                                                            kasm_proxy
1238c22f06eb   kasmweb/agent:1.13.0                           "/bin/sh -c '/usr/bi…"   2 weeks ago         Up About an hour (healthy)   4444/tcp                                                                   kasm_agent
054674741fad   kasmweb/share:1.13.0                           "/bin/sh -c '/usr/bi…"   2 weeks ago         Up About an hour (healthy)   8182/tcp                                                                   kasm_share
e5b628a87c7e   kasmweb/manager:1.13.0                         "/bin/sh -c '/usr/bi…"   2 weeks ago         Up About an hour (healthy)   8181/tcp                                                                   kasm_manager
26b50327dd58   kasmweb/kasm-guac:1.13.0                       "/dockerentrypoint.sh"   2 weeks ago         Up About an hour (healthy)                                                                              kasm_guac
590b8b2a034d   redis:5-alpine                                 "docker-entrypoint.s…"   2 weeks ago         Up About an hour             6379/tcp                                                                   kasm_redis
4849620ca453   postgres:12-alpine                             "docker-entrypoint.s…"   2 weeks ago         Up About an hour (healthy)   5432/tcp                                                                   kasm_db
```

**Comment by rickkoliser** [comment]
Hi @asapcatftw,
    I just want to verify when you said that the id and token were copied over, does that mean that you checked the old configuration file: /opt/kasm/1.12.0/conf/app/kasmguac.app.config.yaml and the new configuration file /opt/kasm/1.13.0/conf/app/kasmguac.app.config.yaml to ensure that the same id and token (now auth_token in 1.13) are the same value? Also can you check in the admin interface that there is only one connection proxy listed.
    
    
![image](https://user-images.githubusercontent.com/113311145/235761844-4b13fff9-ca1a-473d-a551-3e20dbe03621.png)

Also from the admin interface on the system info screen can you provide the full version number that is there for `API Server Build`?

**Comment by asapcatftw** [comment]
When I check the files the ID and token were the same. 

![image](https://user-images.githubusercontent.com/31966895/235775381-2159b433-ff5a-48fb-bf72-bbb2e393f946.png)

API Server Build: 1.13.0.002947

**Comment by asapcatftw** [comment]
@rickkoliser 

We currently don't intend to use Guacamole for RDP/VNC proxy in KASM. If I delete the connection proxy would it stop the spam in the logs?

![image](https://user-images.githubusercontent.com/31966895/235951944-35a40bd9-4887-41be-9ef9-6ad9ca435924.png)

Thanks,

**Comment by rickkoliser** [comment]
@asapcatftw 
    If you delete the connection proxy from the admin UI that won't stop the kasm_guac service which will continue to run in the background. Unfortunately I'm still not sure how your installation got into this configuration, but I can give you some instructions that should correct the error.
    
Under the admin UI settings copy the component registration token:
    
![image](https://user-images.githubusercontent.com/113311145/236018327-b057c2c7-1df9-4be7-bd22-4a927b1e6da5.png)

Delete the connection proxy from the Admin UI:

![image](https://user-images.githubusercontent.com/113311145/236018644-cc29ac43-9fea-4d98-aabf-38da588b7fc5.png)

Then ssh into the Kasm server and stop the Kasm services: `sudo /opt/kasm/bin/stop`

Edit the kasmguac config file `sudo vim /opt/kasm/1.13.0/conf/app/kasmguac.app.config.yaml`

Add the copied component registration token as `registration_token: rbE1t0R6oh3stnVOSn6l` to the config file and save it.

![image](https://user-images.githubusercontent.com/113311145/236019555-53f04d95-951a-4f66-8bdc-359868d347fd.png)

Restart the Kasm services `sudo /opt/kasm/bin/start` and the connection proxy will re-register itself with the system, and you should no longer get the errors.

**Comment by asapcatftw** [comment]
Thanks for your help, this Fixed the issue. 
Let me know if you need any logs that can be helpful to track down this issue.

**Comment by rickkoliser** [comment]
Glad that got your installation running smoothly, I think most of the data that might have been helpful isn't available anymore, but we will keep our eye out if this happens to anyone else.

Thanks again.
