### ISSUE TITLE
[Bug] - OIDC/SAML Idp not showing up on logon page

### ISSUE THREAD

**Issue by brolifen** [kasmtech/workspaces-issues#377]
**Describe the bug**
New IdP does not show up on logon page after it has been added.

**To Reproduce**
1. Go to Authentication 
2. Create a new OpenId Idp and enable it

**Screenshots**
![image](https://user-images.githubusercontent.com/20615514/236630650-277928e9-25fc-4350-9d96-1a9f167cf442.png)

**Workspaces Version**
1.13.0.002947

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Debian 11 bullseye
 - Browser Edge, Chrome, firefox

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**
Stopping and restarting services don't help. Thought this had to do with the web cert being self signed but even after getting a valid cert it still doesn't show. Log shows Idp was succesfully added.

**Comment by j-travis** [comment]
Ensure you have the hostname field of the OIDC config set correctly. It needs to match the hostname in the URL you connect to workspaces with. You can also set it as default.

https://kasmweb.com/docs/latest/guide/oidc.html#configuration

**Comment by brolifen** [comment]
> Ensure you have the hostname field of the OIDC config set correctly. It needs to match the hostname in the URL you connect to workspaces with. You can also set it as default.
> 
> https://kasmweb.com/docs/latest/guide/oidc.html#configuration

Thanks for the quick reply, that did the trick!

I followed this doc btw which left the hostname empty: https://kasmweb.com/docs/latest/guide/oidc/microsoft_internal.html
