### ISSUE TITLE
[Bug] - ProxyConnect connection refused

### ISSUE THREAD

**Issue by shanehughes1990** [kasmtech/workspaces-issues#383]
### Existing Resources

- [*] Please search the existing issues for related problems
- [*] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [*] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [*] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [*] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
We are having a problem with docker rootless and web policies not allowing docker pulls to happen

I am getting an error where if I enable the web policy on the workspace I get a proxy error when trying to `docker pull nginx`

If I change the workspace to inherit/ForceDisabled It solves this issue but we do need that web filtering in the end to work
Inherit works I assume because no other policies apply to this workspace at the workspace level or group level.

This bug occurs on the official Docker Rootless Ubuntu Jammy container from you guys 1.13.0 version

**To Reproduce**
1. Go to 'Web Policies'
2. Click on 'Add Policy'
3. Give the policy a name
4. Click Save (leaving policy default)
5. Add Policy to rootless docker workspace
6. Load workspace and bring up terminal
7. docker pull nginx

**Expected behavior**
I would expect that it pulls the nginx container

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/31993465/68c2a231-ecee-467c-ad18-e994c3a10c70)

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Terraform DigitalOcean SingleServer

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 112.0.5615.138 (Official Build) (64-bit)

**Workspace Server Information (please provide the output of the following commands):**
 ```sh
 root@kasm-workspaces:~# uname -a
Linux kasm-workspaces 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

root@kasm-workspaces:~# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

root@kasm-workspaces:~# sudo docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 32
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-71-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.81GiB
 Name: kasm-workspaces
 ID: LCUU:QDEX:GWJN:ENH3:H4SX:EY47:R6XA:7BL3:PFS6:FFSF:KTVI:O6FH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@kasm-workspaces:~# docker ps | grep kasm
e101848d2a98   kasmweb/ubuntu-jammy-dind-rootless:1.13.0                              "/dockerstartup/kasm…"   6 minutes ago   Up 6 minutes            4901/tcp, 5901/tcp, 6901/tcp                    shanegoeasyc_7f8f17b9
872b2210131f   kasmweb/nginx:latest                                                   "/docker-entrypoint.…"   2 weeks ago     Up 31 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
496e32ec9809   kasmweb/agent:1.13.0                                                   "/bin/sh -c '/usr/bi…"   2 weeks ago     Up 31 hours (healthy)   4444/tcp                                        kasm_agent
fe37666737e6   kasmweb/manager:1.13.0                                                 "/bin/sh -c '/usr/bi…"   2 weeks ago     Up 31 hours (healthy)   8181/tcp                                        kasm_manager
757dda363b35   kasmweb/kasm-guac:1.13.0                                               "/dockerentrypoint.sh"   2 weeks ago     Up 31 hours (healthy)                                                   kasm_guac
a48e9dbd66e4   kasmweb/share:1.13.0                                                   "/bin/sh -c '/usr/bi…"   2 weeks ago     Up 31 hours (healthy)   8182/tcp                                        kasm_share
45e47f99b7f8   kasmweb/api:1.13.0                                                     "/bin/sh -c '/usr/bi…"   2 weeks ago     Up 31 hours (healthy)   8080/tcp                                        kasm_api
fa7dbd2381c0   redis:5-alpine                                                         "docker-entrypoint.s…"   2 weeks ago     Up 31 hours             6379/tcp                                        kasm_redis
30b5512b1694   postgres:12-alpine                                                     "docker-entrypoint.s…"   2 weeks ago     Up 31 hours (healthy)   5432/tcp                                        kasm_db
 ```

**Additional context**

**Comment by j-travis** [comment]
It looks like its trying to use the proxy. 

As a quick fix, you could try using the NO_PROXY environment variable in the [Docker Run Config](https://kasmweb.com/docs/latest/guide/workspaces.html#docker-run-config) to bypass the proxy for the docker domains.

An updated version of the Docker rootless images it might look like this:

```
{
  "hostname": "kasm",
  "privileged": true,
  "environment": {
    "NO_PROXY": "*.docker.io,*.docker.com"
  }
}
```

**Comment by shanehughes1990** [comment]
Is this the intended outcome though, does the zone have anything to do with how things get proxied?

**Comment by j-travis** [comment]
Zones is not applicable here.

The web filter proxy (squid) runs inside the session container. It's primarily meant for browser-isolation use cases where the end user is only presented a browser within the session - with standard (unprivileged) access. The browsers are automatically configured to use the proxy. We also set proxy environment variables which docker is clearly picking up but for some reason unable to connect. I'm not sure why this is and would warrant futher investigation. 

There are a number of ways outside environment variables to configure docker to use a proxy that could be explored:

- https://docs.docker.com/network/proxy/


Regardless, the webfilter as implemented may not be sufficient for your use-case if you also intend to give your users privileged access to the container and the ability to pull/build/run arbitrary docker containers as those present avenues for circumventing the filter as is.

You might consider putting Kasm behind a firewall and filter all outbound traffic with a transparent proxy

**Comment by shanehughes1990** [comment]
Okay I understand a bit better now where that proxy lies, makes sense and we will use this until  a better solution is available. Thank you for the timely response and we do realize the security implication to allowing docker commands running, this is more of an interm workspace while we get all the single application workspaces setup with all the backend stuff figured out, We use docker for local development of dependency services to "init" a local development experience.

**Comment by lbteam001** [comment]
Hi,
We encounter a persistent proxy error message stating, "There is something wrong with the proxy server, or the address is incorrect," when attaching the Web Filter to the Ubuntu Workspace. However, disabling the Web Filter resolves the issue and restores normal functionality.

Expected Behavior:
The Web Filter should function correctly when attached to the Ubuntu Workspace, allowing users to browse without encountering proxy errors.

Is there any Solution?

Thanks
