### ISSUE TITLE
Different CPU Usage

### ISSUE THREAD

**Issue by mmolaie** [kasmtech/workspaces-issues#394]
hello
i use kasm architect. i set max 2 core CPU in containers profile.
but docker stats show chrome container use 5 core.
why this different?

**Comment by j-travis** [comment]
Please review the following resources and referenced links:
 - https://kasmweb.com/docs/latest/how_to/sizing_operations.html#cpu-allocation-method
 - https://youtu.be/lv85XZ8EdjY
