### ISSUE TITLE
Swapped workspace descriptions

### ISSUE THREAD

**Issue by Averexs** [kasmtech/workspaces-issues#397]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
The listed descriptions are swapped.

**To Reproduce**
1. Go to the Workspaces section
2. Click on the description of Debian and see the description for Fedora
3. Click on the description of Fedora and see the description for Debian

**Expected behavior**
The descriptions need to be adjusted to the correct workspace.

**Screenshots**
Attached
![image](https://github.com/kasmtech/workspaces-issues/assets/108954427/96b10fad-5b6a-4095-bd24-926339cb9743)

**Workspaces Version**
Version 1.13.1.421524

**Workspaces Installation Method**
Single Server, Running on top of Debian

**Client Browser (please complete the following information):**
 - OS: Debian 11.7.0
 - Browser: Chrome
 - Version: 113.0.5672.127

**Comment by j-travis** [comment]
Thank you. This is now fixed.

The registry entries should auto update the next time you navigate to that page. If not you can manually trigger an update from ellipse widget on the entry at the top of the screen
