### ISSUE TITLE
[Feature Request] - DigitalOcean VPC selection on VM provider config

### ISSUE THREAD

**Issue by shanehughes1990** [kasmtech/workspaces-issues#401]
### Existing Resources

- [*] Please search the existing issues for related items
- [*] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [*] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [*] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [*] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
I am attempting to setup auto scaling in digital ocean using the terraform module for single server setup. During that setup it puts the manager on it's own isolated VPC

I have modified this script to include nfs setup for the profiles as workspaces won't run on this machine (manager)

During the init of the autoscaling (the user script) part of connecting to the nfs server is `mount server_ip:/mount /mount` that server_ip I have a dns record created in the digital ocean domain it creates pointed to the internal vpc IP of the manager machine so that nfs can connect to it via dns => local vpc ip

The creation of auto scaled droplets does not have a way to select which vpc to deploy that too, it just puts it on the default vpc for that region

**Describe the solution you'd like**
The ability to select which vpc the autoscaled droplet is deployed too (obvisously like the tag, firewall rule etc would need to exist already).

**Describe alternatives you've considered**
What is mentioned above in the problem works if I comment out the creation of the custom vpc and put the manager on the default vpc DO creates for you.

**Comment by j-travis** [comment]
For the longest time VPCs in digital ocean were second class citizens...and after thought.

if you are using autoscaling you have an enterprise license and can submit support requests via a different forum : https://kasmweb.com/support

For now I will close this ticket as OBE , otherise you can open another support request
