### ISSUE TITLE
[Bug] - Typo

### ISSUE THREAD

**Issue by Jcodeerd** [kasmtech/workspaces-issues#402]
### Existing Resources

- [x] Please search the existing issues for related problems
- [ n/a ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ n/a ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ n/a ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ n/a ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
There's a typo at https://kasmweb.com/docs/latest/install/single_server_install.html#installation-guide
The sentence misses a part at the end. 

**To Reproduce**
-Scroll to "The Default usernames are admin@kasm.local and user@kasm.local. The passwords will be randomly generated and presented at the end of the install unless the `--admin-password` or/and `--user-password`" 

**Expected behavior**
- A correct sentence: "The Default usernames are admin@kasm.local and user@kasm.local. The passwords will be randomly generated and presented at the end of the install unless the `--admin-password` or/and `--user-password` **are specified.**"

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/68161666/4b0917eb-8dc0-497c-8fce-4f5d80b6c860)

**Workspaces Version**
n/a

**Workspaces Installation Method**
n/a

**Client Browser (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Opera Gx
 - Version: (of Opera Gx?): LVL4 (core: 98.0.4759.82)

**Workspace Server Information (please provide the output of the following commands):**
n/a

**Additional context**
n/a

**Comment by j-travis** [comment]
Fixed. Thank you
