### ISSUE TITLE
how to assign specific ip address to container with kasm workspace ?

### ISSUE THREAD

**Issue by mfmasoudian** [kasmtech/workspaces-issues#411]
Hello
I am a computer science student who is interested in docker
I recently got acquainted with your product (kasm) And I am testing it
I have a question that I can't find any source for that

my question is how to assign specific ip address (ipv4) in container with kasm ?
can you help me please ?
![kasm](https://github.com/kasmtech/workspaces-issues/assets/136468250/f101ac54-8bfe-4585-ad22-3ce70a365d4f)

**Comment by j-travis** [comment]
By default, all Kasm sessions get created on a bridged network that are NATed out the default interface of your machine. So if your machine is on the 192.168.1.0/24, the container ip wont actually be on that subnet. It will be in a private docker network (likely 172.18.0.0/16) or similar. It will then engress out of your computers interface via NAT.

If ,for example, you had multiple interfaces on the computer, and you wanted the Kasm containers to egress out of that particular interface you could use a custom docker network to achieve that: See (https://kasmweb.com/docs/latest/how_to/bridged_network_source_nat.html) 

If you truly do require the container to be directly on the 192.168.1.0/24 network , you'll need to IPVlan docker networking: https://kasmweb.com/docs/latest/how_to/ipvlan.html

**Comment by mfmasoudian** [comment]
> By default, all Kasm sessions get created on a bridged network that are NATed out the default interface of your machine. So if your machine is on the 192.168.1.0/24, the container ip wont actually be on that subnet. It will be in a private docker network (likely 172.18.0.0/16) or similar. It will then engress out of your computers interface via NAT.
> 
> If ,for example, you had multiple interfaces on the computer, and you wanted the Kasm containers to egress out of that particular interface you could use a custom docker network to achieve that: See (https://kasmweb.com/docs/latest/how_to/bridged_network_source_nat.html)
> 
> If you truly do require the container to be directly on the 192.168.1.0/24 network , you'll need to IPVlan docker networking: https://kasmweb.com/docs/latest/how_to/ipvlan.html

--------------------------------------------------------------
Thank you for your response. I'm sorry I think I couldn't explain my issue.
I want to launch my container with an specific IPv4 address which one  I assign in workspace page at Docker Run Config Override (JSON)
![image](https://github.com/kasmtech/workspaces-issues/assets/136468250/ca4298e2-1bf2-46ab-9c4c-dfffb906c9ba)

After this configuration container does not run at all.

![image](https://github.com/kasmtech/workspaces-issues/assets/136468250/c47a2990-24e2-439f-bb49-665ee94f5b09)


My linux network configuration for docker is:

 docker network create \
  --driver=bridge \
  --subnet=172.20.119.0/24 \
  --ip-range=172.20.119.0/24 \
  --gateway=172.20.119.254 \
  my-network

-------------------------------------------
The machine works with default configuration in docker and i can change or assign any ip address I want with docker command:

docker run --network my-network --ip 172.20.119.20  my-container-name

but in KASM it does not works.


Thank you in advance for your kind.

**Comment by j-travis** [comment]
Sorry, it is not possible at this time to configure the container with a specific IP address.

Depending on your use-case you may be able to leverage hostnames instead.  If you utilize a specific hostname in the Docker Run Config, other machines on that same docker network should be able to access it via the hostname. Assuming this was your purpose for needing the IPs, this may work for you. For Example...

```
{
  "hostname": "machine-1"
}
```

and on a different Workspace, configure..

```
{
  "hostname": "machine-2"
}
```

**Comment by mfmasoudian** [comment]
> Sorry, it is not possible at this time to configure the container with a specific IP address.
> 
> Depending on your use-case you may be able to leverage hostnames instead. If you utilize a specific hostname in the Docker Run Config, other machines on that same docker network should be able to access it via the hostname. Assuming this was your purpose for needing the IPs, this may work for you. For Example...
> 
> ```
> {
>   "hostname": "machine-1"
> }
> ```
> 
> and on a different Workspace, configure..
> 
> ```
> {
>   "hostname": "machine-2"
> }
> ```

Thank you for your response 👍
