### ISSUE TITLE
KASM + Apache Reverse Proxy: Fails Establish WebSocket Connection [Fixed]

### ISSUE THREAD

**Issue by fcaussa** [kasmtech/workspaces-issues#412]
I set up a selfhosted Kasm workspace which works like s charm when I access it from LAN; 
Also I did set up an remote apache reverse proxy to access it remotely (Which I have done before for other services), Access/login works fine, but when attempting to open a workspace session, it just hungs and logs that it can not establish the WSS connection to server;

I did follow this documentation:

[https://kasmweb.com/docs/latest/how_to/reverse_proxy.html](https://kasmweb.com/docs/latest/how_to/reverse_proxy.html)

with the following apache reverse proxy configuration:
```
 <VirtualHost *:443>
   # Server and ssl
   ServerName kasm.example.com
   SSLEngine on
   SSLCertificateFile /etc/ssl/apache2/server.pem
   SSLCertificateKeyFile /etc/ssl/apache2/server.key
   # Websocket upgrade
   RewriteEngine on
   RewriteCond ${HTTP:Upgrade} websocket [NC]
   RewriteCond ${HTTP:Connection} upgrade [NC]
   RewriteRule .* "wss://**<my-server-ip>**:443/$1" [P,L]
   # Proxy
   SSLProxyEngine on
   SSLProxyVerify none
   SSLProxyCheckPeerCN off
   SSLProxyCheckPeerName off
   SSLProxyCheckPeerExpire off
   ProxyPreserveHost on
   ProxyPass / https://<my-server-ip>:443/
   ProxyPassReverse / https://<my-server-ip>:443/
   ProxyRequests off
 </VirtualHost>
```

I did edit Zones as follow:

![image](https://github.com/kasmtech/workspaces-issues/assets/68918444/92eaae16-8824-4b35-9c09-822b19eb0253)

After several attemps I wasn't able to succesfully open a workspace remotely;

I changed the apache conf sockets upgrade for this lines:

```
  RewriteEngine On
  RewriteCond %{HTTP:Upgrade}    =websocket [NC]
  RewriteRule /(.*)           wss://<my-server-ip>:443/$1 [P,L]
  RewriteCond %{HTTP:Upgrade}    !=websocket [NC]
  RewriteRule /(.*)           https://<my-server-ip>:443/$1 [P,L]
```

Now it works perfectly fine.

Hope it helps others on the same issue.

**Comment by ManuXD32** [comment]
Wow, you are a lifesaver. This fix should be included in the documentation. I've been looking for this for days.

THANKS.

**Comment by gleitoncampos** [comment]
Worked for me too. I'm using Cosmos Cloud and using the built in reverse proxy and had the same problem. Changing the "Proxy port" to "0" solved the problem!
