### ISSUE TITLE
[Bug] iframe doesn't resize above 1024px width or 768px height in canvas resolution

### ISSUE THREAD

**Issue by nikochiko** [kasmtech/workspaces-issues#414]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When embedded as an iframe, the kasm window does not resize to full screen height or full screen width. The canvas element created by it keeps resizing but maxes out at 1024px width and 768px height.
But when opened on its own without an iframe, it resizes as per the device resolution and stretches to fill it. Interestingly, the iframe issue stops once the independent kasm page has been visited, and the max height increases to 800 or 900px (on my device).

**To Reproduce**
1. Get the kasmweb/blender docker image (1.13.1)
2. Run it with docker, expose it with nginx with the [recommended setup](https://kasmweb.com/docs/latest/how_to/reverse_proxy.html). (say it's running on "https://kasm.example.com")
3. Embed it in another webpage as an iframe: `<iframe id="kasm-iframe" allow="fullscreen; autoplay; microphone; clipboard-read; clipboard-write; self; https://kasm.example.com"></iframe>`.
4. Open it in a browser. Then try to run it in full screen with `requestFullscreen` API: https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen

**Expected behavior**
It should resize to the full window size.

**Screenshots**

**Workspaces Version**
kasm-blender:1.13.1

**Workspaces Installation Method**
Docker

**Client Browser (please complete the following information):**
 - OS: macOS
 - Browser: Brave Browser
 - Version: 1.51.114, Chromium 113.0.5672.92

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

1. uname -a

`Linux <ip-retracted> #43~20.04.1-Ubuntu SMP Fri Jun 2 17:10:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

2. cat /etc/os-release
```
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

3. `sudo docker info`

```
[sudo] password for kaustubh:
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.15.0-1038-aws
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.886GiB
 Name: ip-<retracted>
 ID: e27974ba-edd4-417f-9bc6-3d592c296764
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

4. `sudo docker ps | grep kasm`

```
678706444ed7   kasmweb/blender:1.13.1   "/dockerstartup/kasm…"   47 minutes ago   Up 5 minutes   4901/tcp, 5901/tcp, 0.0.0.0:6901->6901/tcp, :::6901->6901/tcp   blender-docker_kasm-blender_1
```

**Additional context**

**Comment by j-travis** [comment]
You aren't using workspaces, but here are docs that we have about running in an iframe,
you'll often need to specify the desired width and height. I believe these are default browser behaviors.
https://kasmweb.com/docs/latest/how_to/embed_kasm_in_iframe.html#example-webpage-with-kasm-in-iframe
