### ISSUE TITLE
[Bug] - conversion between UTF8 and SQL_ASCII is not supported

### ISSUE THREAD

**Issue by fcarucci** [kasmtech/workspaces-issues#415]
### Existing Resources

**Describe the bug**
When importing a registry I get the following error: "conversion between UTF8 and SQL_ASCII is not supported"

**To Reproduce**

1. Import workspace registry https://kasmregistry.linuxserver.io/

**Expected behavior**
Workspace is imported.

**Screenshots**
https://imagebin.ca/v/7RCzekKkAMaH

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Single server, external PostgresSql, installation script created user/database.

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
Linux kasm 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
 - `sudo docker info`
 Client: Docker Engine - Community
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 24.0.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-75-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.751GiB
 Name: kasm
 ID: 94c7ea87-c601-4efd-9041-88b72479d157
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false 
 - `sudo docker ps | grep kasm`
922010e2969f   kasmweb/nginx:latest     "/docker-entrypoint.…"   40 hours ago   Up 4 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
3e24c70a0bc7   kasmweb/api:1.13.1       "/bin/sh -c '/usr/bi…"   40 hours ago   Up 4 hours (healthy)   8080/tcp                                        kasm_api
c870d4f505a9   kasmweb/share:1.13.1     "/bin/sh -c '/usr/bi…"   40 hours ago   Up 4 hours (healthy)   8182/tcp                                        kasm_share
44f86c909179   kasmweb/manager:1.13.1   "/bin/sh -c '/usr/bi…"   40 hours ago   Up 4 hours (healthy)   8181/tcp                                        kasm_manager

**Additional context**

**Comment by j-travis** [comment]
My guess is there was a temporary issue with the LSIO registry where they where using Unicode characters is some of the json fields. That would cause this issue. It no longer seems to be an issue. I will close this. Please re-open if you see this issue again. You'll want to report it to the LSIO team too

**Comment by fcarucci** [comment]
This is not a temporary issue. I worked around it by exporting the db, converting to UTF8 and re-importing it. The installation script should create the db as UTF8 in the first place.
