### ISSUE TITLE
can i login without inputting the domain name for a workspace or can i login with a domain name which is different from the ldap settings?

### ISSUE THREAD

**Issue by cia-aic** [kasmtech/workspaces-issues#416]
Hi,

Suppose I configured abc.local in the ldap settings. abc.local is the actual internal domain on my active directory.
So, now my users can login with xxx@abc.local (the system requires to login w/ an e-mail address)

However, most of the users will login w/ xxx@abc.com because this is the actual email address.
Anyway my users can login w/ xxx@abc.com instead of xxx@abc.local?
Or can they simply login with username and password without a full e-mail address?

Thanks.
VT

**Comment by j-travis** [comment]
That feature is coming in the next release of workspaces (1.14.0).
The user can login with a different domain , or none at all
https://kasmweb.com/docs/develop/guide/ldap.html#user-domain-name-matching

You are welcome to test it out of you'd like to run the dev preview build:
https://kasmweb.com/docs/latest/developers/builds.html
