### ISSUE TITLE
[Bug] - Manager and Associated Agents show -1 day Last Reported

### ISSUE THREAD

**Issue by frznfngrs** [kasmtech/workspaces-issues#417]
**Describe the bug**
Manager and Associated Agents show -1 day Last Reported

**To Reproduce**
Not sure how I got here.

**Expected behavior**
Normal report time

**Screenshots**
<img width="152" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/19555532/1074e23b-4922-493e-b950-b454bc2b3265">
<img width="299" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/19555532/10c5bf6a-4f30-4864-a729-7a2cbae2638a">

**Workspaces Version**
Version 1.13.1

**Workspaces Installation Method**
Multi-Server

**Client Browser (please complete the following information):**
Any

**Comment by j-travis** [comment]
The likely issue is that time on one or more of your webapp, db, or agent servers is out of sync.

**Comment by frznfngrs** [comment]
Solved, thank you

**Comment by frznfngrs** [comment]
I was incorrect about this being solved.   This issue persists.   Time changes synced now, as thought before to be the issue.   Additional behavior information.

Both managers are set to UTC timezone.
When viewing from the "master" app manager, the time shows negative for the other manager.
When viewing the manager with the supposed negative time, both managers show good last reported times.
When the manager with the bad time is stopped, the "master" manager reports a non-negative time.

I also am having problems with launching any apps with agents talking to the negative time master.   II fear this may be a result of the negative reported time but am unsure.    I can login to the "negative" master and it allows me to launch workspaces from either masters zone.  I have checked all zone configurations for errors and come up empty handed there.

**Comment by j-travis** [comment]
Its not just about the timezone.
Are you sure they are all of the servers (including the database) and your client are synchronized on time?

Once you make those adjustments, you may need to reboot your servers so the underlying services pick up the changes.

One common thing that gets people is when they run VMs on hypervisors that have time drift.  And/or they configure the VM to not use the hosts time and things can fall out of sync if they poweroff / snapshot VMs.

**Comment by frznfngrs** [comment]
I wish it were true that it was time synchronization.    I am familiar with the various issues you mention, but I have been staring at date and chronyd like a madman trying to insure it is not drifting.   It is not.  I also don't understand why viewing from the one manager would show fine for last sync, but viewing from the other shows it nearly 2 days off.    

So in short, database, web apps, and agents all have same time/time settings.   UI still reports last reported time way off for one of the managers when viewed from the other.
All servers have been rebooted.

Services have been restarted multiple times

**Comment by frznfngrs** [comment]
Anyway I could entice some assistance with this problem as it seems to be rendering the entire deployment for that zone unusable.

<img width="899" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/19555532/5ae95371-6001-4732-9b23-b5ef590689ab">

**View from manager 1**
<img width="574" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/19555532/1fb98055-2174-4cf4-942e-b6eb40567f13">

**View from manager 2**
<img width="542" alt="image" src="https://github.com/kasmtech/workspaces-issues/assets/19555532/8a671d57-768a-45e6-ad36-ef89cae2077f">

**Comment by j-travis** [comment]
If the `date` commands were executed at roughly the same time, it shows that time on the server on the bottom is 2 minutes adrift.  This accounts for the erroneous elapsed time you are seeing that is roughly 2 minutes off

Consider the following
```
Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> last_reported = datetime.datetime.utcnow()
>>> last_reported +=  datetime.timedelta(minutes=2)
>>> str(datetime.datetime.utcnow() - last_reported).split('.')[:-1][0]
'-1 day, 23:58:00'
```

So when one of the managers tries to calculate timestamps from the database, it can be off depending on where the original timestamp was generated.

**Comment by frznfngrs** [comment]
> If the `date` commands were executed at roughly the same time, it shows that time on the server on the bottom is 2 minutes adrift. This accounts for the erroneous elapsed time you are seeing that is roughly 2 minutes off
> 
> Consider the following
> 
> ```
> Python 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import datetime
> >>> last_reported = datetime.datetime.utcnow()
> >>> last_reported +=  datetime.timedelta(minutes=2)
> >>> str(datetime.datetime.utcnow() - last_reported).split('.')[:-1][0]
> '-1 day, 23:58:00'
> ```
> 
> So when one of the managers tries to calculate timestamps from the database, it can be off depending on where the original timestamp was generated.

But isn't this reading as a negative value?  I mean the way I read this is its off by negative 1 day 23 hours and 58 minutes, so its saying its off by 46hours 58 minutes right?     Even if I am somehow reading the that entry incorrectly, even with moving the server to within a second of the others, it still shows the same -1day 23 hours 58 minutes

**Comment by frznfngrs** [comment]
Thank you for the help
