### ISSUE TITLE
[Bug] - community edition .install.sh > docker-compose not installed, but docker-compose IS installed

### ISSUE THREAD

**Issue by hubbertsmith** [kasmtech/workspaces-issues#418]
### Existing Resources

download, untar the community edition
run ./install.sh

**Describe the bug**

**To Reproduce**
**# ./install.sh**
Checking if docker and docker compose are installed.
Docker is installed
20.10.21 is a supported version of docker.
Docker Compose is not installed.
Installation Not Supported for this Operating System. Exiting
An error has occurred please review the log at ./kasm_install_1688667838.log

**# docker-compose** 
Define and run multi-container applications with Docker.
Usage:
  docker-compose [-f <arg>...] [--profile <name>...] [options] [--] [COMMAND] [ARGS...]
  docker-compose -h|--help

**>>> your script references "docker compose"
it is actually "docker-compose"**

**Expected behavior**

**Screenshots**

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
e.g Single Server, Multi-Server, TrueNAS, linuxserver.io, terraform, ansible

**Client Browser (please complete the following information):**

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**

**Comment by j-travis** [comment]
Kasm requires `docker compose` which is docker compose v2 and is a docker plugin. Not the older `docker-compose` v1.

https://kasmweb.com/docs/latest/install/system_requirements.html#docker-and-docker-compose
https://docs.docker.com/compose/migrate/

**Comment by hubbertsmith** [comment]
that worked
are there docs or runbook on how CLI manage user accounts?
thanks a ton
