### ISSUE TITLE
[Bug] - cannot login to admin

### ISSUE THREAD

**Issue by hubbertsmith** [kasmtech/workspaces-issues#420]
### Existing Resources
ubuntu 23
successfully downloaded and installed
the install produced access credential list

I read the docs
https://www.kasmweb.com/docs/latest/install/single_server_install.html
in the instructions I see
Log into the Web Application running on port 443 at https://<WEBAPP_SERVER>

I tried localhost:443 --- result 404
I tried https://172.26.11.111:443   --- result 404

>>>>>>>>>>>>>my bad this is the fix >>>>>>>
the fix  https://localhost:443
<<<<<<<<<<it needed the https: --- fyi, neither the docs or the error message were help<<<<<<<<<<<<<<

**Describe the bug**

**To Reproduce**

**Expected behavior**
please let me know how to start the admin

**Screenshots**

**Workspaces Version**
e.g Version 1.13

**Workspaces Installation Method**

**Client Browser (please complete the following information):**

**Workspace Server Information (please provide the output of the following commands):**

**Additional context**

**Comment by j-travis** [comment]
When you created this bug ticket, it asked you to provide the output of several commands. This is so we can better help you. Please provide the requested data


**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`
 
 
 Generally speaking this is going to be an issue with a local firewall
