### ISSUE TITLE
Chrome not loading when Kasm is accessed through Cloudflare tunnel

### ISSUE THREAD

**Issue by heisenberg2980** [kasmtech/workspaces-issues#421]
Kasm is working when accessing locally using the private ip and Chrome sessions are open without any issue, but they don´t open when accesing Kasm through a Cloudflare tunnel, the screen gets stuck with the message "Creating a secure connection..."

![image](https://github.com/kasmtech/workspaces-images/assets/58039006/52c43791-8a45-47aa-93c3-39d24175dc88)

This is the log:
```
07/11/2023 2:03:10 PM
time="2023-07-11T13:03:10.923252394Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
07/11/2023 2:03:10 PM
time="2023-07-11T13:03:10.923296526Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
07/11/2023 2:03:10 PM
time="2023-07-11T13:03:10.923305603Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
07/11/2023 2:03:10 PM
time="2023-07-11T13:03:10.923410327Z" level=info msg="starting signal loop" namespace=moby path=/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/6747b06aeb4e4c6c6b56281b3d1ce602cad48dbc6fd13232c3d1953bd8d93aa7 pid=6088 runtime=io.containerd.runc.v2
```

Opening the dashboard it seems the session is created but not initialized:

![image](https://github.com/kasmtech/workspaces-images/assets/58039006/3fbeba80-974d-48ba-bd03-528234f4e552)

After accesing the same dashboard using Kasm local ip and resuming the session, the session is initialized and work as expected, but only when Kasm is accessed locally:

![image](https://github.com/kasmtech/workspaces-images/assets/58039006/e6e658a4-6574-4b88-be04-335a4eb44389)

**Comment by j-travis** [comment]
Here are a few resources for you to review that show how to properly configure Cloudflare tunnels to work with Kasm workspaces.
Can you review and test:
- https://youtu.be/jIKvxtOQaQI
-  https://youtu.be/pv43JiCUlyI

**Comment by heisenberg2980** [comment]
Thanks for the info, I have watched both videos and the only option I was missing was the "HTTP2 connection", but after enabling this option in Cloudflare the issue is still happening

**Comment by j-travis** [comment]
Can you ensure you are creating new sessions and not trying to resume existing ones that may have been created before you were behind cloudflare?

You can also take a look at the troubleshooting guide for common problems. You'll want to look in your browser developer console logs for errors:
https://kasmweb.com/docs/latest/guide/troubleshooting.html#session-hangs-at-creating-a-secure-connection

**Comment by heisenberg2980** [comment]
Thank you very much for pointing me in the right direction, finally I found and fixed the issue, and it was the port mentioned here: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones
For some reason my instance had the port set to 4443 (which is the port I use when I connect to kasm locally) and changing it to 0 fixed the problem.

**Comment by Cosmic-Empath** [comment]
> Thank you very much for pointing me in the right direction, finally I found and fixed the issue, and it was the port mentioned here: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones For some reason my instance had the port set to 4443 (which is the port I use when I connect to kasm locally) and changing it to 0 fixed the problem.

THIS was absolute gold! Thank you all for your hard work! I had the exact same issue, and changing the port to 0 fixed it for me too!
