### ISSUE TITLE
[Bug] - Multi-server, cannot install app role on same server with db role

### ISSUE THREAD

**Issue by jknyght9** [kasmtech/workspaces-issues#422]
**Describe the bug**
After installing the `db` role, the installation process cannot connect to the database upon installing the `app` role on the same server.

**To Reproduce**
1. Install the db role with `sudo bash kasm_release/install.sh --role db app` on server
2. Install the app role with `sudo bash kasm_release/install.sh --role app --db-hostname [DATABASE_HOSTNAME] --db-password [DATABASE_PASSWORD] --redis-password [REDIS_PASSWORD]` on same server
3. Replace db-hostname with `127.0.0.1` | `localhost` | `kasm_db`
4. Watch the log output fail in its attempts to connect to the db and redis.

**Expected behavior**
Expected the app role to install correctly

**Workspaces Version**
Version 1.13

**Workspaces Installation Method**
Multi-Server, AWS

**Client Browser (please complete the following information):**
 - OS: Mac OS 
 - Browser none
 - Version none

**Workspace Server Information (please provide the output of the following commands):**
Linux workspaces 5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

**Additional context**
Verified the DB was up and could connect to it with psql

**Comment by j-travis** [comment]
Sorry, this installation method is not supported. You cant install multiple roles individually on the same system at this time.
The supported options are to install all roles on a single server using the single-server install. Or install them all separately using the multi-server install

**Comment by jknyght9** [comment]
Understood. Went with a default (all) install on one system and gen'd agents to spread the load. Thank you again for your support
