### ISSUE TITLE
[Bug] - Brave Constantly Minimizing Session

### ISSUE THREAD

**Issue by j0nsgh** [kasmtech/workspaces-issues#431]
When using Brave Workspace kasmweb/brave:1.13.1, launching a session in any mode (new tab, current tab, new window), it starts and the browser is shown, then it auto minimizes.

https://imgur.com/a/BxW7ugL

To replicate, create a new container from Workspace Registry, select Brave from Kasmweb.

Also occurs with -rolling release as well.

Originally worked when first rolled Kasm out, no changes to system (literally just used it with 1 account), and randomly started occurring last week.

**Comment by j-travis** [comment]
Thats interesting.

Activity inside the session doesnt really have the ability to cause actions to occur within your host browser , like navigating back.
I recommend trying the following:

- Using an incognito tab in your browser
- Disabling any extensions you have on your host browser
- Trying a different web browser on your host.
- Looking for any logs in your host browser developer console

I also would expect this to occur on other images, not just brave.

**Comment by j0nsgh** [comment]
> Thats interesting.
> 
> Activity inside the session doesnt really have the ability to cause actions to occur within your host browser , like navigating back. I recommend trying the following:
> 
> * Using an incognito tab in your browser
> * Disabling any extensions you have on your host browser
> * Trying a different web browser on your host.
> * Looking for any logs in your host browser developer console
> 
> I also would expect this to occur on other images, not just brave.

Thanks for the response!  I've tried MS Edge, Brave, Chrome and Firefox browsers, all experience the same issue.  My Firefox local browser has zero extensions as I nuke it regularly for web testing.  Additionally, no other workspaces experience this issue.  I even deleted the workspace and recreated it, I also created a new test user to confirm it wasn't my main account.

I will look at developer tools to see if anything pops up again, but initial review didn't show anything specific from it vs say Firefox workspace.

**Comment by j0nsgh** [comment]
@j-travis just an update, I only found one item between the two workspaces (Brave and say, Firefox), the Brave one when it self closes shows this in the console (see image).

[https://imgur.com/tW7A4ew](url)

**Comment by j0nsgh** [comment]
I haven't been able to find a  resolution or reason why, going to nuke the box and try and see if something else is messed up, but its ONLY happening to BRAVE.

**Comment by j-travis** [comment]
Sorry, we cannot reproduce this issue, nor has it been reported by other users. Thus, this is likely a local environment issues.
