### ISSUE TITLE
[Bug] - Unable to access official registry via forward proxy

### ISSUE THREAD

**Issue by JmbFountain** [kasmtech/workspaces-issues#432]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
In our environment, all outbound traffic has to go via a forward proxy. Getting the images to use the forward proxy works, pulling docker images also works

**To Reproduce**
1. Install KASM behind forward proxy
2. set environment variables and daemon.json entries with the proxy address
3. test connection via CURL and docker pull
```
root@kasm:~# docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
719385e32844: Pull complete 
Digest: sha256:926fac19d22aa2d60f1a276b66a20eb765fbeea2db5dbdaafeb456ad8ce81598
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest
root@kasm:~# curl https://registry.kasmweb.com
<a href="/1.0/">Moved Permanently</a>.
```
4. Click "Install official Registry" in Admin web interface
5. get "There was a problem installing Registry" errors

**Expected behavior**

**Screenshots**

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
e.g Single Server, Multi-Server, TrueNAS, linuxserver.io, terraform, ansible

**Client Browser (please complete the following information):**
 - OS: [Debian/Windows]
 - Browser [Firefox/Chrome]
 - Version [various tested]

**Workspace Server Information (please provide the output of the following commands):**
uname -a:
 `Linux kasm 5.10.0-23-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27) x86_64 GNU/Linux`

/etc/os-relase: 
```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Docker info:
```
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-23-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.59GiB
 Name: GVMKASM01
 ID: 212c34d9-0530-4750-b104-90a76c201324
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://10.242.1.5:3128
 HTTPS Proxy: http://10.242.1.5:3128
 No Proxy: 127.0.0.0/8
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```
docker ps | grep kasm:

```
e90811051ccf   kasmweb/nginx:latest       "/docker-entrypoint.…"   18 hours ago   Up 17 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
3e466d084249   kasmweb/share:1.13.1       "/bin/sh -c '/usr/bi…"   18 hours ago   Up 17 hours (healthy)   8182/tcp                                        kasm_share
fe7f3c58b267   kasmweb/agent:1.13.1       "/bin/sh -c '/usr/bi…"   18 hours ago   Up 17 hours (healthy)   4444/tcp                                        kasm_agent
045dda677476   kasmweb/manager:1.13.1     "/bin/sh -c '/usr/bi…"   18 hours ago   Up 17 hours (healthy)   8181/tcp                                        kasm_manager
4621b8f46ddf   kasmweb/kasm-guac:1.13.1   "/dockerentrypoint.sh"   18 hours ago   Up 17 hours (healthy)                                                   kasm_guac
bd2832051b18   redis:5-alpine             "docker-entrypoint.s…"   18 hours ago   Up 17 hours             6379/tcp                                        kasm_redis
4b441604c001   kasmweb/api:1.13.1         "/bin/sh -c '/usr/bi…"   18 hours ago   Up 17 hours (healthy)   8080/tcp                                        kasm_api
a7ae6761b250   postgres:12-alpine         "docker-entrypoint.s…"   18 hours ago   Up 17 hours (healthy)   5432/tcp                                        kasm_db
```

**Additional context**
Relevant log entry:

```
/opt/kasm/current/log/api_server.log:2023-08-03 06:24:52,931 [DEBUG] admin_api_server: Successfully authenticated request (create_registry) for user (admin@kasm.local) at (10.x.x.x)
/opt/kasm/current/log/api_server.log:2023-08-03 06:25:08,941 [INFO] cherrypy.access.133864668473328: 172.18.0.9 - - [03/Aug/2023:06:25:08] "POST /api/admin/create_registry HTTP/1.1" 200 52 "https://kasm.domain/" "Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0"
/opt/kasm/current/log/api_server.log:2023-08-03 06:25:25,015 [ERROR] admin_api_server: https://registry.kasmweb.com/ - A valid url needs to be entered
```

**Comment by j-travis** [comment]
Thank you for reporting.
As you've seen, there is currently no way to specify proxy settings for this request within the app.

Aside from using a transparent proxy, a potential workaround is to update the kasm_api container with `http_proxy` , `https_proxy` and `no_proxy` environment variables in `/opt/kasm/current/docker/docker-compose.yaml` and restarting the services.  You'll for sure want the local subnets  on your machine and docker interfaces to be in `no_proxy` . Note this is untested and should only be attempted if you are comfortable with these types of custom configs within a testing environment.

Ref: https://docs.python.org/3/library/urllib.request.html

**Comment by JmbFountain** [comment]
Hello,

Thanks for the tip, it worked just fine!
We are exploring KASM as a way for our airgapped users to be able to browse the internet, so this is a really useful thing for us. 

Best regards,

Johannes
