### ISSUE TITLE
Kasm_agent and kasm_guac on the same server

### ISSUE THREAD

**Issue by szadan51** [kasmtech/workspaces-issues#435]
Hi! I know it's a bit of an odd use case but i want to install kasm_agent and kasm_guac on the same hardware. I'm only using 1 browser on each server as it only acts as a gateway to the internal network. I also want to do the same with the VNC accessable hardware behind it. I hope i could describe what i want to achieve well enough :) Thanks in advance.

**Comment by j-travis** [comment]
Sorry, its not possible to install the system this way. 
Every everything is on a single server, or you install the different roles per the Multi-Server guide:
https://kasmweb.com/docs/latest/install/multi_server_install.html

If you don't want to use the connection proxy (guac) to connect to your VNC infrastructure , you can use the remmina containr workspace which would then provision on the Agent(s)  While its a bit more work, you can set up individual remmina workspaces to auto connect to your VNC servers. See: https://www.reddit.com/r/kasmweb/comments/15ihh45/question_how_to_setup_kasm_to_use_remmina_docker/

**Comment by szadan51** [comment]
Thank you very much for your answer. It's a great solution to my problem. It will require a bit of elbow grease but should be fine. I think we might have found our choosen platform which we should implement :)

**Comment by szadan51** [comment]
One more thing. As i was setting it up i noticed that i can use $KASM_URL to pass as a server argument, but if i use it, it breaks the other arguments, such as viewmode and password. It's not the end of the world but it would be nice to use it dynamically as well. Here is my configuration file for it:

`{
  "environment": {
    "REMMINA_OPTIONS": "window_maximize=1,viewmode=4,server=$KASM_URL",
    "REMMINA_PROFILE": "/home/kasm-user/.local/share/remmina/defaults/default.vnc.remmina"
  }
}`

The only other "problem" with this approach is that i have to use URL's like this: ?kasm_url=vnc://x.x.x.x

**Comment by j-travis** [comment]
I'm not sure,
but at the end of the day you can replace the custom_startup.sh with something that suits your needs better by creating a custom image, or using a file mapping to replace it.

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://kasmweb.com/docs/latest/guide/file_mappings.html#file-mappings
