### ISSUE TITLE
[Bug] - Unable to contact settings server

### ISSUE THREAD

**Issue by jm1021** [kasmtech/workspaces-issues#437]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
At launch of image a dialog box appears "Unable to contact settings server:  Count not connect: connection refused".  We had one successful image that worked, so I spent time rebuild various paired down images.  

However, after multiple tries, and the nature of the error I am thinking it might be something to do with Nginx.   But I am stumped that one image works that was built on a different machine.

**To Reproduce**
1. Go to '...' Workspace and launch image
2. See error '...` Blocking error dialog occurs, it seems desktop flashes in background

**Expected behavior**
Regular launch

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/54686997/9603424d-80a7-4e06-b7fc-7e41e16dc279)

**Workspaces Version**
e.g Version 1.13

**Workspaces Installation Method**
e.g Single Server, Multi-Server, TrueNAS, linuxserver.io, terraform, ansible
Single Server

**Client Browser (please complete the following information):**

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`
Can't get there, but trying most recent jammy

**Additional context**

I can't find any information online.  Context of where error occurs would be helpful.

**Comment by j-travis** [comment]
Are you trying to run your own custom built images?
if so, can you paste your dockerfile and/or the exact build command you used

**Comment by jm1021** [comment]
# Docker File, 

### All the scripts except tools_install.sh  are from your published repo with a couple of mods top and end to stay in your  documented standards.  I am essentially trying to get Anaconda and a few tools into custom image from your example.

ARG BASE_TAG="1.13.1-rolling"
ARG BASE_IMAGE="core-ubuntu-jammy"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install

WORKDIR $HOME

######### Customize Container Here ###########

# Set Anaconda environment
ENV CONDA_DIR /opt/anconda3
ENV PATH $CONDA_DIR/bin:$PATH

# Install Anaconda
RUN cd /tmp/ && \
    wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh && \
    chmod +x Anaconda3-2023.07-1-Linux-x86_64.sh && \
    ./Anaconda3-2023.07-1-Linux-x86_64.sh -b -p ${CONDA_DIR} && \
    rm -r Anaconda3-2023.07-1-Linux-x86_64.sh

# Add Conda to Global Path
ENV PATH="$CONDA_BIN:$PATH"
RUN echo 'export PATH="$PATH"' >> /etc/bash.bashrc

### Envrionment config
ENV DEBUG=false \
    DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/chromium/install_chromium.sh \
                  /ubuntu/install/sublime_text/install_sublime_text.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR
# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT}; \
  done && \
  rm -f /etc/X11/xinit/Xclients && \
  rm -Rf ${INST_DIR}

########## End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

# Userspace Runtime
ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

CMD ["--tail-log"]

**Comment by jm1021** [comment]
# Tools Script

#!/usr/bin/env bash
apt-get update
apt-get install -y \
    curl \
    sudo \
    wget \
    nano \
    zip \
    build-essential \
    ruby-full

# Cleanup
if [ -z ${SKIP_CLEAN+x} ]; then
    apt-get autoclean
    rm -rf \
        /var/lib/apt/lists/* \
        /var/tmp/* \
        /tmp/*
fi

**Comment by jm1021** [comment]
# Build command and push commands

docker build --no-cache -t nighthawkcoders/kasm_workspaces:1.0  -f dockerfile-csse-ubuntu-jammy-desktop .

docker push nighthawkcoders/kasm_workspaces:1.0

**Comment by jm1021** [comment]
docker --version
Docker version 20.10.21, build baeda1f

**Comment by jm1021** [comment]
Dockerfile and commands are in Issue above.  A clue on where the error originates from would be helpful.  Anaconda config was published by others and I picked it up.  

There is a Redit where guy said he had error and changed from bash to zsh https://www.reddit.com/r/kasmweb/comments/13lk2rb/xfce_error_unable_to_contact_settings_server/.  Perhaps these lines are problem.

```bash
# Add Conda to Global Path
ENV PATH="$CONDA_BIN:$PATH"
RUN echo 'export PATH="$PATH"' >> /etc/bash.bashrc
```

 Here is online directory of files: https://github.com/nighthawkcoders/devOps/tree/main/kasm_workspaces

**Comment by j-travis** [comment]
Generally the best way to solve a problem with this is to back up to the base config, and add the custom sections bit by by bit to find the offending item. 

From the referenced reddit post it does seem like the same thing.

**Comment by jm1021** [comment]
Yes, I got Jammy 22.04 to work by removing Anaconda. 

Bur, this Anaconda setup was in about three places on the web, the Reddit guy did not share specifics except changing shell which is a pretty big deal to some, though MacOS did it.   To adapt it, it would be nice to know what the error is?

Right now I was say it is either.
1. The whole thing: ./Anaconda3-2023.07-1-Linux-x86_64.sh -b -p ${CONDA_DIR} &&
2. Or something to do with settings:  echo 'export PATH="$PATH"' >> /etc/bash.bashrc

Anaconda is a big deal, I would suggest Kasm support it.  For some reason, this config is working on 20.04:

######
# Set Anaconda environment
ENV CONDA_DIR /opt/anconda3
ENV PATH $CONDA_DIR/bin:$PATH

# Install Anaconda
RUN cd /tmp/ && \
    wget https://repo.anaconda.com/archive/Anaconda3-2023.07-1-Linux-x86_64.sh && \
    chmod +x Anaconda3-2023.07-1-Linux-x86_64.sh && \
    ./Anaconda3-2023.07-1-Linux-x86_64.sh -b -p ${CONDA_DIR} && \
    rm -r Anaconda3-2023.07-1-Linux-x86_64.sh

# Add Conda to Global Path
ENV PATH="$CONDA_BIN:$PATH"
RUN echo 'export PATH="$PATH"' >> /etc/bash.bashrc

# Setup Anaconda User profile
RUN conda update -n base conda && \
    conda update --all && \
    conda clean --all && \
    conda config --set ssl_verify /etc/ssl/certs/ca-certificates.crt && \
    conda install pip && \
    mkdir -p /home/kasm-user/.pip && \
    chown -R 1000:1000 ${CONDA_DIR} ${HOME}/.conda/ && \
    conda install -y jupyter
#######

**Comment by jm1021** [comment]
My next try, would be to take out this line: RUN echo 'export PATH="$PATH"' >> /etc/bash.bashrc
And run it to user  ~/.bashrc outsite of the image using Workspaces File Mapping.  

As conclusion, I got jupyter with:  apt-get jupyter-notebook.  This took a 8 hour build and push process down to about 2 hours.  But, conda is loved and has all the packages users want.   I would need to add them one by one with apt.

**Comment by jm1021** [comment]
By the way I do love flexibility of your product.  I am a Teacher and plan to use it in classroom using AWS and Terraform for setup.   

Here are some feature request, or things I can find published...

1. Terraform or system setup should have a way to update things like Compute Cores Override and Memory Override, additionally Zones proxy port from 8443 to 0 when putting server behind nginx reverse proxy.
2. The Workspace Registry should have  option to add File Manager information like PATH updates shown above for Anaconda.  I used it for Packages on 20.04 as I was developing feasibility.
3. Publication of server errors and cause like,  Unable to contact settings server
4. I like the feature to clone image from image but I could not find a way to get that to another machines, like upload it to dockerhub?

**Comment by echo-devnull** [comment]
I have the same error but it came from adding DIND installation to the Debian Bookworm XFCE image.

If I add these installation lines to the docker, I consistently break XFCE:
https://gitlab.com/maas-martin/kasm-workspaces/-/blob/c06301199616da6f3d97afe971bfc222a5cf5dde/bookworm/Dockerfile#L86

Docker rootless works, but is unable to work with K3d, so I wanted to use "normal" docker.

Still trying to find the technical cause, it something inside that docker installation script

**Comment by echo-devnull** [comment]
Ok, if I disable autostart in supervisor, the bug does not appear:
https://gitlab.com/maas-martin/kasm-workspaces/-/blob/56a0aeaf3bb924fea521d8ed933b4fbd123dc8fa/.gitlab-ci.yml#L10

"https://github.com/kasmtech/workspaces-images/blob/2e0bd0d678019f66d3077620beac48186c9ff58d/src/ubuntu/install/dind/dockerd.conf#L3"

If I then start the docker deamon using:
`sudo supervisorctl start dockerd`

The bug reappears. (As in, trying to open "session and startup" from the "settings" menu would result in the error.)

Stopping docker afterwards, does not solve it again unfortunately.

So something in the "https://kasm-ci.s3.amazonaws.com/dockerd-entrypoint.sh"  script?
