### ISSUE TITLE
Not able to Run the kasmweb/chrome in the mac arm architecture.

### ISSUE THREAD

**Issue by tarunmittal24** [kasmtech/workspaces-issues#439]
I have download the kasmweb/chrome from the docker hub and tries to run it on mac ma pro arm architecture, but getting blank screen, can you guys build the image on the arm based architecture as well.

Command Used to run the container:- 

sudo docker run --rm -it --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/chrome:1.13.0

and tried this as well.

sudo docker run --rm -it --platform=linux/amd64 --shm-size=512m -p 6901:6901 -e VNC_PW=password kasmweb/chrome:1.13.0

but no luck.

<img width="1728" alt="Screenshot 2023-08-25 at 11 31 51" src="https://github.com/kasmtech/workspaces-issues/assets/131644722/bf9133ad-39a2-40b5-b8cd-48a21cdd2519">

Error-logs:- 
[logs.txt](https://github.com/kasmtech/workspaces-issues/files/12436087/logs.txt)

**Comment by mmcclaskey** [comment]
You will have to use our kasmweb/chromium image instead of Chrome. Google does not publish an arm build of Chrome, therefore, the kasmweb/chrome container is x86 only.
