### ISSUE TITLE
[Bug] - LDAP authenticated users dropping out of group on login

### ISSUE THREAD

**Issue by judouk** [kasmtech/workspaces-issues#440]
**Describe the bug**
I have built a new KASM installation using 1.14.0
As part of the installation, I have configured an LDAP provider and am able to authenticate as a user.
I have removed all workspaces from the 'all users' group and have created a new group (ProjectX)
Once the user has initially connected, they are added as a member of All Users and then we can manually move them to the relevant Project
When the user logs out, they are removed from the ProjectX group and so an administrator must re-add them manually

**To Reproduce**
1. Login as an LDAP user
2. Admin adds them to the ProjectX group
3. User logs out
4. User logs back in and no longer has access to ProjectX

**Expected behavior**
Once added to the group, they should remain until they are removed

**Screenshots**
n/a

**Workspaces Version**
1.14.0

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
Tested using a MacOS with Google Chrome

**Workspace Server Information (please provide the output of the following commands):**
# uname -a
Linux kasm.projectx.example.com 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.20.3)

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.25
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.19.0-1025-aws
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.624GiB
 Name: kasm.projectx.example.com
 ID: RDBM:ZKJ5:WSPH:SDNU:CH72:ZEC5:FGU5:5UFF:H2X2:NWX4:NZ67:ZFAH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
# docker ps | grep kasm
149c39c1ae5e   kasmweb/nginx:1.25.1                                                        "/docker-entrypoint.…"   4 days ago       Up 4 days             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
7f683abf758d   kasmweb/agent:1.14.0                                                        "/bin/sh -c '/usr/bi…"   4 days ago       Up 4 days (healthy)   4444/tcp                                        kasm_agent
6da858142984   kasmweb/share:1.14.0                                                        "/bin/sh -c '/usr/bi…"   4 days ago       Up 4 days (healthy)   8182/tcp                                        kasm_share
8e68d8028a04   redis:5-alpine                                                              "docker-entrypoint.s…"   4 days ago       Up 4 days             6379/tcp                                        kasm_redis
20d0e4eea499   kasmweb/api:1.14.0                                                          "/bin/sh -c '/usr/bi…"   4 days ago       Up 4 days (healthy)   8080/tcp                                        kasm_api
42c5a6e17c7f   kasmweb/kasm-guac:1.14.0                                                    "/dockerentrypoint.sh"   4 days ago       Up 4 days (healthy)                                                   kasm_guac
b4e986ca2f66   kasmweb/manager:1.14.0                                                      "/bin/sh -c '/usr/bi…"   4 days ago       Up 4 days (healthy)   8181/tcp                                        kasm_manager
8c5de36aeb99   postgres:12-alpine                                                          "docker-entrypoint.s…"   4 days ago       Up 4 days (healthy)   5432/tcp                                        kasm_db

**Additional context**
Nothing to add

**Comment by j-travis** [comment]
The user should only be pulled from the manually assigned group, if there is an SSO group mapping defined on that group and the user doesnt match. Can you double check?

If you still see the issue, please post the logs from the `kasm_api` container.
- Manually assign the user to the group
-  start a tail of the logs `sudo docker logs -f kasm_api`
- Log in as the user. 

You should see debugging information about the login attempt and group assignment / Un-assignment.

**Comment by judouk** [comment]
Thank you @j-travis 
Your debug allowed me to see exactly what you were describing.

For some reason, when the user logs in, the client_api_server believes that the user is not in the correct group.
We have setup SSO group mappings and I thought we had done so correctly.

ProjectX group SSO mappings are linked to the only SSO provider (LDAP). We have unticked 'assign all users' as we only want people who are members of the particular group to be associated with this group and then have listed the group attributes as
CN=kasm-access,OU=Group,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com

The user in question is a member of the group but the logs suggest differently
2023-08-30 09:03:56,182 [DEBUG] client_api_server: Found User (testuser) : Data ({'attributes': {'accountExpires': ['9999-12-31 23:59:59.999999'], 'badPasswordTime': ['2023-08-18 11:54:22.024374+00:00'], 'badPwdCount': [0], 'cn': ['Test User'], 'codePage': [0], 'countryCode': [0], 'dSCorePropagationData': ['1601-01-01 00:00:00+00:00'], 'displayName': ['Test User'], 'distinguishedName': ['CN=Test User,OU=People,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com'], 'gecos': ['Test User'], 'gidNumber': [1699], 'givenName': ['Test'], 'homeDirectory': ['/users/testuser'], 'instanceType': [4], 'lastLogon': ['2023-08-18 11:54:31.136875+00:00'], 'lastLogonTimestamp': ['2023-08-29 10:29:39.796104+00:00'], 'loginShell': ['/bin/bash'], 'logonCount': [0], 'mail': ['test.user@example.com'], 'memberOf': ['CN=kasm-access,OU=Group,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com'], 'name': ['Test User'], 'objectCategory': ['CN=Person,CN=Schema,CN=Configuration,DC=msad,DC=aws,DC=example,DC=com'], 'objectClass': ['top', 'posixAccount', 'person', 'organizationalPerson', 'user'], 'objectGUID': ['{f0a041c5-6408-4855-9650-180e6e04c7e9}'], 'objectSid': ['S-1-5-21-308591162-4168765019-1924608669-1738'], 'primaryGroupID': [513], 'pwdLastSet': ['2023-06-09 09:35:53.189743+00:00'], 'sAMAccountName': ['testuser'], 'sAMAccountType': [805306368], 'sn': ['Waterhouse'], 'uSNChanged': [137005], 'uSNCreated': [12905], 'uid': ['testuser'], 'uidNumber': [599], 'userAccountControl': [66048], 'userPrincipalName': ['testuser@msad.aws.example.com'], 'whenChanged': ['2023-08-29 10:29:39+00:00'], 'whenCreated': ['2023-06-09 08:05:24+00:00']}, 'dn': 'CN=Test User,OU=People,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com'})
2023-08-30 09:03:56,187 [DEBUG] client_api_server: No Groups found for User (testuser)
2023-08-30 09:03:56,313 [DEBUG] client_api_server: LDAP login successful for user (testuser)
2023-08-30 09:03:56,319 [DEBUG] client_api_server: Processing Group (ProjectX) with (1) sso_mappings for sso type ldap, id: (16b1c828-83ad-4e9d-b065-d2822c782421)
2023-08-30 09:03:56,320 [DEBUG] client_api_server: Removing User (testuser) from Group (ProjectX)
2023-08-30 09:03:56,345 [INFO] client_api_server: Successful authentication attempt for user: (testuser)

**Comment by judouk** [comment]
hmmm, I'm thinking that the problem here is with the setup of ,my LDAP providers (Group Membership Filter) and/or the SSO group mappings

Do you know if there is a way to output what the ldapsearch parameters are?

**Comment by mmcclaskey** [comment]
Can you check that your group mapping definition does not have any extra spaces before or after the value.

Can you provide your LDAP Group Membership Filter value?

**Comment by judouk** [comment]
Hi @mmcclaskey 

Access Management -> Authentication -> LDAP
Search Base : OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com
Search Filter : sAMAccountName={0}
Group Filter :  (&(objectCategory=person)(objectClass=user)(memberOf=OU=Groups,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com))

The SSO Group mapping doesnt have any leading or trailing spaces. It is
CN=kasm-access,OU=Project-X,OU=Group,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com


Hope that helps

**Comment by judouk** [comment]
AAARRRRGGHHHHH - I've just seen it
A typo - Group and not Groups!

**Comment by judouk** [comment]
OK, so even after fixing up the typo, I still get the same behaviour

When I login, the logs do show that I am a member of the group
 'memberOf': ['CN=kasm-access,OU=Group,OU=EXAMPLE,DC=msad,DC=aws,DC=example,DC=com'], 'name':

I then see
Processing Group (ProjectX) with (1) sso_mappings for sso type ldap, id: (16b1c828-83ad-4e9d-b065-d2822c782421)

Before it confirms that my user is not a member of the ProjectX group

**Comment by j-travis** [comment]
If you look at our examples in the docs: https://kasmweb.com/docs/latest/guide/ldap/active_directory.html

You'll see that there is a `{0}` that indicates what field we should be matching in the **Group Membership Filter**. Make sure yours is doing something like this too

- `(&(objectClass=groupOfNames)(member={0}))`
- `&(objectClass=group)(member:1.2.840.113556.1.4.1941:={0})`


You'll see the same kindof thing for the **Search Filter**

- `&(objectClass=user)(sAMAccountName={0})(memberof:1.2.840.113556.1.4.1941:=CN=all_kasm_app_users,OU=MyOrg,DC=kasm,DC=core)`
- `(&(objectClass=posixAccount)(uid={0})`

**Comment by judouk** [comment]
Thank you @j-travis 
This is _exactly_ what I was looking for.
I can confirm that this change resolves my issue entirely.
Thank you once again
