### ISSUE TITLE
Cannot use custom images from Docker Hub anymore

### ISSUE THREAD

**Issue by kernelkraut** [kasmtech/workspaces-issues#444]
There seems to be an issue pulling custom images (non-KASM) from Docker hub. This was working in previouse versions but after updating to the latest version it no longer works. 

I can create the custom workspaces and I can see them successfully pulling in the logs but the front-end continues to show "Installing"
![image](https://github.com/kasmtech/workspaces-issues/assets/23164186/f4b00931-1768-4204-838e-3cbb5e0b334e)

Image can be listed:
![image](https://github.com/kasmtech/workspaces-issues/assets/23164186/819a761e-ebe0-4ff2-9f20-49d054beecd7)

Successfully pulled image in logs:
![image](https://github.com/kasmtech/workspaces-issues/assets/23164186/898ba9ae-b5e2-4b48-8752-78b6a52520dc)

I have tested further by deploying two new KASM (single-host) servers. One on x64 and another on Arm64. Both seem to do exactly the same. KASM images work fine. Custom images do not.

**Comment by j-travis** [comment]
Can you ensure that within the Workspace definitiion you are actually defining the `latest` tag.  So ensure your docker image section put `kernelkraut/custom:latest`

**Comment by kernelkraut** [comment]
Thanks, that seems to sort out the "Installing" issue. Unfortunately all of my custom images fail to start. These are all images that worked fine before on previous versions of Kasm. 

All I can find in the logs is the error below:

An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(47fd28c0-a944-4ab2-a96b-19f3e8b0bd72) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1615, in provision
  File "provision.py", line 1780, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (487c8f57bc66273db79b45146870b627ee634e7e7b64d055e0beced87b583a86)
)

**Comment by j-travis** [comment]
I'd first try to run your containers manually and see if they start.

Failing that.

0. Delete all kasm sessions from the UI
1. remove any excess auto generated nginx confs `rm -f /opt/kasm/current/conf/nginx/containers.d/*`
2. Stop the Kasm Services `sudo /opt/kasm/bin/stop`
3. Modify `/opt/kasm/current/conf/app/agent.app.config.yaml` set `remove_failed_containers` to `false`
4. Start the services: `sudo /opt/kasm/bin/start`
5. Launch the session
6. If it fails tail the logs on the services and post them here:
```
sudo docker logs tail -1000 kasm_agent
sudo docker ps
sudo docker logs <container is of your user session>
```

**Comment by kernelkraut** [comment]
Thanks for the responses and apologies for the delayed response. I was able to sort this out by building customimages bases on the existing images from KASM and then making my modifications.
