### ISSUE TITLE
VSCode Command Line Launch [Bug] - Example

### ISSUE THREAD

**Issue by jm1021** [kasmtech/workspaces-issues#445]
### Existing Resources

- [ X] Please search the existing issues for related problems
I saw something from 2022 below but it seemed specific to an arch that was not mine.

**Describe the bug**
I want to run "code" or "code projectname" from terminal.  

**To Reproduce**
1. Using Ubuntu 22.04
2. Install VSCode using: https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/vs_code/install_vs_code.sh
3. launch workspace
4. open terminal
5. code

**Expected behavior**
You expect desktop to open;  it returns to prompt.

**Screenshots**
Digging in VSCode "code "scripts it can be reduced to...
default:~$ /usr/share/code/code /usr/share/code/resources/app/out/cli.js --ms-enable-electron-run-as-node
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: MacOS, Windows
 - Browser Chrome

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 Linux kasm 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 
- `cat /etc/os-release`default:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
 
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**

ChatGPT tells me the below.  But, I think I may need your assistance to achieve this.

This error is often encountered when running graphical applications or Electron-based applications like Visual Studio Code within certain containerized or restricted environments, such as Docker containers or certain configurations of Linux namespaces.

Share the X11 Socket: When running VS Code inside a Docker container, you need to share the X11 socket from your host machine. This allows the container to display graphical applications on your host's X server. 

docker run -it --rm \
    --net=host \  # Allows the container to use the host's network stack
    --env="DISPLAY" \  # Passes the DISPLAY environment variable
    --volume="$HOME/.Xauthority:/root/.Xauthority:rw" \  # Grants X11 access
    --name vscode-container \
    vscode-container

**Comment by j-travis** [comment]
You need `code --no-sandbox` 
https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/vs_code/install_vs_code.sh#L10
