### ISSUE TITLE
[Bug] - A tiny ime-hidden-input element is blocking the screen in RDP session

### ISSUE THREAD

**Issue by ryan-ma** [kasmtech/workspaces-issues#446]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
In RDP session, there is a tiny < input type="text" id="ime-hidden-input" > element blocking the mouse control. 
The mouse cursor will become a text edit cursor if hovering on it. 
Clicking the text box would trigger the password autofill dropdown.

**To Reproduce**
Start RDP session. Try to hover the mouse cursor in the middle of the windows.
Could also use browser developer tool to find this element

**Expected behavior**
That blocking element should be hidden or not exsit.

**Screenshots**
![Screenshot 2023-09-12 004223](https://github.com/kasmtech/workspaces-issues/assets/12838712/e11d85bf-b3a7-4729-89fc-e7996e037ffb)
![Screenshot 2023-09-12 0051352](https://github.com/kasmtech/workspaces-issues/assets/12838712/692f81fb-a786-41c3-a768-a82aff20cf05)

**Workspaces Version**
Version 1.14

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116.0.5845.180 

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
   - Linux debian 6.1.0-12-amd64
 - `cat /etc/os-release`
   - PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Comment by j-travis** [comment]
Please use the following steps on your Kasm server, (or the Connection Proxy role if using multi-server) in your ecosystem to receive the hidden IME input fix. 

1. Open a terminal on your Connection Proxy (Guac) Server

2. Open the docker-compose.yaml file in an editor

```
sudo nano /opt/kasm/current/docker/docker-compose.yaml
```

3. In the kasm_guac section, adjust the tag for the kasm-guac container to 1.14.0-rolling in the image section and save the file
 
```
image: "kasmweb/kasm-guac:1.14.0-rolling"
```

It should look similar to this:

![image](https://github.com/kasmtech/workspaces-issues/assets/48762190/c17d1393-52cc-4a97-94f1-888feaf3d130)

 

4. Stop the Kasm services

```
sudo /opt/kasm/bin/stop
```

5. Remove the exiting kasm_guac container

```
sudo docker rm -f kasm_guac
```

6. Start the services

```
sudo /opt/kasm/bin/start
```

 

You should notice the system pull the new 1.14.0-rolling container. 
Reconnection to a Windows session and verify the fix.
