### ISSUE TITLE
[Bug] - Audio problem while remote desktop (use RDP) to window server 2019

### ISSUE THREAD

**Issue by Donam0408** [kasmtech/workspaces-issues#448]
### Existing Resources

- [ ] Please search the existing issues for related problems
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Audio Problems while remote desktop (using RDP) to Windows Server 2019. Sound and Micro remote devices are found but do not work ( Dont have sound output in local machine and cant use micro from local machine)

**To Reproduce**
1. Connect to Windows server 2019 from Kasm Workspace
2. Open sounds setting 

**Expected behavior**

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/95564727/32c290a6-485f-41fd-ba7c-41d5c627a2fb)
![image](https://github.com/kasmtech/workspaces-issues/assets/95564727/9ac4369c-52b5-4be3-9ef4-cb22349003f3)
![image](https://github.com/kasmtech/workspaces-issues/assets/95564727/34651107-8841-4e13-a4fc-322b45aa32a7)

**Workspaces Version**
 Version 1.14

**Workspaces Installation Method**
 Singe.g Single Server

**Client Browser (please complete the following information):**
 - OS: Ubuntu

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`: 5.15.0-83-generic 92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`: 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
 - `sudo docker ps | grep kasm`:
![image](https://github.com/kasmtech/workspaces-issues/assets/95564727/d1916e50-d09e-435a-9799-ff29842221c5)

**Additional context**

**Comment by j-travis** [comment]
Is the audio service enabled?

Powershell:
```
Start-Service -Name "Audiosrv"
```

**Comment by MrTronMan** [comment]
Hi! I am following up because I think it is stupid to open a new issue, when there is the same one happening here. I have the exact same issue. Is the Kasm Window Agent required for sound?

**Comment by j-travis** [comment]
No, the Kasm Windows Agent is not required for sound.

**Comment by MrTronMan** [comment]
Oh okay, well then I am having the same issue, the remote audio appears and shows that audio is playing but Kasm won't output any audio itself through the tab.

**Comment by j-travis** [comment]
Thank you for reporting, we've identified a bug and will have a workaround shortly

**Comment by MrTronMan** [comment]
Sounds good, keep me updated!

**Comment by MrTronMan** [comment]
Any updates?

> Sounds good, keep me updated!

**Comment by j-travis** [comment]
Please use the following steps on your Kasm server, (or the Connection Proxy role if using multi-server) in your ecosystem to receive the hidden IME input fix. 

1. Open a terminal on your Connection Proxy (Guac) Server

2. Open the docker-compose.yaml file in an editor

```
sudo nano /opt/kasm/current/docker/docker-compose.yaml
```

3. In the kasm_guac section, adjust the tag for the kasm-guac container to 1.14.0-rolling in the image section and save the file
 
```
image: "kasmweb/kasm-guac:1.14.0-rolling"
```

It should look similar to this:

![image](https://github.com/kasmtech/workspaces-issues/assets/48762190/c17d1393-52cc-4a97-94f1-888feaf3d130)

 

4. Stop the Kasm services

```
sudo /opt/kasm/bin/stop
```

5. Remove the exiting kasm_guac container

```
sudo docker rm -f kasm_guac
```

6. Start the services

```
sudo /opt/kasm/bin/start
```

 

You should notice the system pull the new 1.14.0-rolling container. 
Reconnection to a Windows session and verify the fix.


This fix is also available in the developer preview builds: https://kasmweb.com/docs/latest/developers/builds.html

**Comment by MrTronMan** [comment]
Hi! I have done all the following steps, and the audio is now working properly. Thank you very much for your help. I am not the owner of the issue so I cannot close it. But much appreciated!
