### ISSUE TITLE
when installing kasm(I'm using the offline Single Server Installation), I got no space left on device error

### ISSUE THREAD

**Issue by asmwarrior** [kasmtech/workspaces-issues#450]
Hi, one a CentOS7(The total harddisk is 1T, and automatic partitioning during the CentOS install), I have followed the way to install the kasm, here is a simple steps:

1, I run the commands mentioned here to prepare the packages and dockers in https://kasmweb.com/docs/latest/how_to/other_operating_systems.html#redhat-7

2, I then followed the way mentioned here: Single Server Installation — Kasm 1.14.0 documentation — https://kasmweb.com/docs/latest/install/single_server_install.html, note I'm using the offline x64 mode, so mainly I need to download about 5G bytes files in the `/tmp`(actually 3 files) from the server, and finally run the command:
~~~~
sudo bash kasm_release/install.sh --offline-workspaces /tmp/kasm_release_workspace_images_amd64_1.14.0.3a7abb.tar.gz --offline-service /tmp/kasm_release_service_images_amd64_1.14.0.3a7abb.tar.gz
~~~~

After wait for a while, I got the error that "no space left on device", and the installation get exit.

I'm not sure this is the correct place to ask such question, but can you give me some directions?

Thanks.

**Comment by j-travis** [comment]
Can you please provide the output of these commands:

- `df`
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`


Basically you should check out how your disk was divvied up on your system. Its common for only a small subset to actually be partitioned/allocated.

The install will extract those image to /tmp which need 10s of GBs to do correctly. They will then be loaded into the default "Docker Root Dir" which is `/var/lib/docker` . So you need to ensure your partition/volume layout can accommodate that

Also more context on the install log would help

**Comment by asmwarrior** [comment]
> The install will extract those image to /tmp which need 10s of GBs to do correctly. They will then be loaded into the default "Docker Root Dir" which is /var/lib/docker . So you need to ensure your partition/volume layout can accommodate that


Thanks for the reply.

I think in the document, put the image to the `/tmp` is really not a good idea, I just moved the images to other folder, such as `/home/myusername/kasm`, and basically the `/home` folder/partition has the enough space to hold those extracted files, and after that, I can run the install scripts, and finally start the program.

I think those information should be put in the document, and maybe others will meet the same issue as mine.

Thanks.
