### ISSUE TITLE
kasmweb/kali-rolling-desktop  passwd: Authentication token manipulation error

### ISSUE THREAD

**Issue by ghost** [kasmtech/workspaces-issues#451]
default:~$ passwd kasm-user
Changing password for kasm-user.                                                                                                                                                          
Current password:                                                                                                                                                                         
passwd: Authentication token manipulation error                                                                                                                                           
passwd: password unchanged                                                                                                                                                                
default:~$ 
default:~$ 
default:~$ passwd                                                                                                                                                                         
Changing password for kasm-user.                                                                                                                                                          
Current password:                                                                                                                                                                         
passwd: Authentication token manipulation error                                                                                                                                           
passwd: password unchanged                                                                                                                                                                
default:~$

**Comment by j-travis** [comment]
The standard users don't have a password.
If you want to run the session with elevated privs, you can run the session as root or install and configure sudo via docker exec

- https://kasmweb.com/docs/latest/how_to/running_as_root.html
