### ISSUE TITLE
[Bug] - Persistant profiles not working

### ISSUE THREAD

**Issue by jamess60** [kasmtech/workspaces-issues#452]
### Existing Resources

- [ ] Please search the existing issues for related problems
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When attempting to start a workspace with persistant profile enabled, it is unable to start and produces the following error: 

An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(2a7cd62f-3780-4551-8272-d2feacd4ee5f) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1615, in provision
  File "provision.py", line 1780, in generate_nginx_config
Exception: Nginx failed to reload after generating config for container (65653383f83ca78d085f85a108524cc2349dc0565877020420012dbcb6e50c0c)
)

**To Reproduce**
1. Install Debian 12
2. Install Kasm and import Debian bookworm or Fedora 37 workspace from default registry
3. On Kasm server, mkdir -p /user-data/{multiple,usernames} && chmod -R 777 /user-data
4. Set persistent path to /user-data/{username}
5. Attempt to start the workspace with persistent enabled 

**Expected behavior**
The container would start with persistent on 

**Screenshots**
![Screenshot 2023-09-23 at 21 48 26](https://github.com/kasmtech/workspaces-issues/assets/126415249/892a8c48-d3ae-4dec-86b5-8e523b6840c6)
![Screenshot 2023-09-23 at 21 48 17](https://github.com/kasmtech/workspaces-issues/assets/126415249/dd6477c8-0949-40a7-8bd9-42e8f17a58b9)
![Screenshot 2023-09-23 at 21 48 17](https://github.com/kasmtech/workspaces-issues/assets/126415249/5d626947-0508-45c5-879e-d83403463621)

**Workspaces Version**
Latest (installed 23/9/23)

**Workspaces Installation Method**
Single server, bare metal debian 12 

**Client Browser (please complete the following information):**
 - OS: macOS Ventura
 - Browser Firefox
 - Version Latest (23/9/23)

**Workspace Server Information (please provide the output of the following commands):**
netadmin@V-KASM-01:~$ uname -a
Linux V-KASM-01 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
netadmin@V-KASM-01:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
netadmin@V-KASM-01:~$ sudo docker info
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 22
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-12-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.34GiB
 Name: V-KASM-01
 ID: 6ee10713-7031-4a1b-9677-7e80b7e5126b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

netadmin@V-KASM-01:~$ sudo docker ps | grep kasm
9940f89d0425   kasmweb/nginx:1.25.1       "/docker-entrypoint.…"   7 hours ago   Up 28 minutes             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
769de2dc95fc   kasmweb/agent:1.14.0       "/bin/sh -c '/usr/bi…"   7 hours ago   Up 28 minutes (healthy)   4444/tcp                                        kasm_agent
31a3891072c0   kasmweb/share:1.14.0       "/bin/sh -c '/usr/bi…"   7 hours ago   Up 28 minutes (healthy)   8182/tcp                                        kasm_share
9a8bc63e75eb   kasmweb/kasm-guac:1.14.0   "/dockerentrypoint.sh"   7 hours ago   Up 28 minutes (healthy)                                                   kasm_guac
43dca57fdf3f   kasmweb/api:1.14.0         "/bin/sh -c '/usr/bi…"   7 hours ago   Up 28 minutes (healthy)   8080/tcp                                        kasm_api
8553bf03c06b   redis:5-alpine             "docker-entrypoint.s…"   7 hours ago   Up 28 minutes             6379/tcp                                        kasm_redis
fd9cc39ba1d0   kasmweb/manager:1.14.0     "/bin/sh -c '/usr/bi…"   7 hours ago   Up 28 minutes (healthy)   8181/tcp                                        kasm_manager
b6fdcd909ea8   postgres:12-alpine         "docker-entrypoint.s…"   7 hours ago   Up 28 minutes (healthy)   5432/tcp                                        kasm_db
netadmin@V-KASM-01:~$

**Comment by jamess60** [comment]
Edit: Only seems to impact network volumes, works on local disk

**Comment by j-travis** [comment]
Here is a guide on using persistent data on a remote file system via NFS:
https://kasmweb.com/docs/latest/guide/persistent_data/host_guides.html

You'll see there are very specific requirements for ensuring that the container can read and write from the filesystem as UID/GID 1000

**Comment by FlorianHeigl** [comment]
@j-travis the examples for the persistent profile and persistent data shares don't match up as far as paths go.
this could really need a bit more substance :-)
