### ISSUE TITLE
No access

### ISSUE THREAD

**Issue by Vitlyr** [kasmtech/workspaces-issues#458]
When attempting to access Kasm within my local network, it functions correctly on the server but encounters issues on other devices. The server is indeed connected to the appropriate network, and Ubuntu's terminal is hosted on my Windows 11 computer. To enable access on other devices, should I modify the hostname, and if necessary, how can this be accomplished?

**Comment by ToxicMonster** [comment]
Are you using Ubuntu in a virtual machine or WSL?

**Comment by Vitlyr** [comment]
WSL

**Comment by Vitlyr** [comment]
> Are you using Ubuntu in a virtual machine or WSL?

Using the latest version of WSL, after that, downloaded Ubuntu on it.

**Comment by Vitlyr** [comment]
Can somebody help out?

**Comment by j-travis** [comment]
This doesnt sound like an issue with Kasm, but a general networking issue with your host/WSL/network.  My guess is you's have the same issue if you spun up a simple nginx container . 
I recommend looking for generic solutions to accessing services created in docker via WSL over the LAN

**Comment by Vitlyr** [comment]
I'll try that! Is there a way to change the SSL certificate, since I'm tunneling this, it wont allow it, since this is a self assigned certificate? (Replace it with Cloudflares Certificate)

Edit: I've read [this issue](https://github.com/kasmtech/workspaces-issues/issues/77), when I followed and found the files, I edited them with my SSL keys, when done so, it still says that its insecure.

![Screenshot 2023-11-01 10 42 12 AM](https://github.com/kasmtech/workspaces-issues/assets/103600474/4f62ec6e-e3de-43e1-bd86-956e1098fa76)

**Comment by j-travis** [comment]
Per the docs you can replace kasm autogenerated self signed certs with trusted certs:
https://kasmweb.com/docs/latest/how_to/certificates.html

If you are using cloudflare tunnels you may want to look at this. There is a way to disable TLS verification if for some reason cloudflare doesnt trust your certs.
https://kasmweb.com/docs/latest/how_to/cloudflare_tunnels.html
