### ISSUE TITLE
Customizable LDAP login domain and related feedback

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#47]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/47) by Lev Elupirl (Bitbucket: [Lev Elupirl](https://bitbucket.org/Lev Elupirl), ).**

----------------------------------------

**LDAP login domain**

There’s no way to customize the login domain when LDAP authentication is enabled. This is especially important when using cloud LDAP services. For example, my _Search Base_ when using [JumpCloud](https://www.jumpcloud.com) is:

```
ou=Users,o=<organization_id>,dc=jumpcloud,dc=com
```

This forces the user to use an email login like so: `kuser@jumpcloud.com`. Preferably there should be some way to use a custom domain, or read from the user’s `mail` LDAP attribute for login.

**LDAP auto-populated fields**

When an LDAP user logs in for the first time, and their user is created within Kasm from _Auto Create App User_, there should be an option to additionally auto-populate certain attributes into the user profile. At the very least, this should the first name and last name fields.

**LDAP user interface**

When creating a new LDAP configuration, typing the _Service Account Password_ should use a password form field instead of a regular text form field.

Additionally, in the same creation interface, the _Group Membership Filter_ example provided in grey when there’s no text, shows the example as:

```
&(objectClass=group)(member:1.2.840.113556.1.4.1941:={})
```

Note that the example incorrectly gives the `{}` placeholder, when it should be `{0}`. Also, mentioned in [Valid LDAP query filters fail as "malformed"](https://bitbucket.org/kasmtech/kasm_release/issues/9/valid-ldap-query-filters-fail-as-malformed) the filter confusingly omits the outer parenthesis. I ran into this same issue, and the errors I got made it initially difficult to troubleshoot. The current way the filter needs to be inputted technically doesn’t conform to the proper notation, i.e. the user should be required to input the outer parenthesis.

**Comment by j-travis** [comment]
Customizable ldap domains will be available in the next release of workspaces (1.14.0)
