### ISSUE TITLE
[Bug] - Steam Launcher disappearing after sign in

### ISSUE THREAD

**Issue by swoopingasaservice** [kasmtech/workspaces-issues#471]
**Describe the bug**
Steam launcher disappears after signing in

**To Reproduce**
Sign into Steam via the launcher.
**Expected behavior**
Steam brings up the library, community, etc tabs to select installed games

**Screenshots**

**Workspaces Version**
Latest

**Workspaces Installation Method**
Docker

**Client Browser (please complete the following information):**
 - OS: Debian 12 and Ubuntu 22.04

**Comment by j-travis** [comment]
This doesn't totally help but potentially a tiny step forward.

Setting the following in Docker Run Config Override 
```
{
  "security_opt": [
    "seccomp=unconfined"
  ]
}
```

In my brief testing , no GPU, no persistent profiles, `kasmweb/steam:1.14.0-rolling`. The steam updater runs and  I'm able to login via the QR code with steam. The friends bar is displayed and what looks to be the steam browser which is fully black. You can right click and see certain menu options.

Obviously not a working setup though.

The steam image stopped working when the new steam client was released. This image has always been experimental. If a working solution isn't found we may pull it in the next release.

![image](https://github.com/kasmtech/workspaces-issues/assets/48762190/a0d01b2d-2d77-4782-90c8-f24647ce0eaf)


![image](https://github.com/kasmtech/workspaces-issues/assets/48762190/89adad6f-1200-453f-91fa-7fd943c1dae1)

**Comment by swoopingasaservice** [comment]
I have found the solution. After signing into Steam, the menus will no longer be visible. Click the Steam icon in the bottom right corner in the toolbar and enter "settings". Once there, disable GPU acceleration for the web client. Restart Steam. The menus will be visible again. Currently, I have figured this out without a dedicated GPU attached. Hope this helps others.

**Comment by j-travis** [comment]
Nice @swoopingasaservice !,
It looks like you can pass an argument to steam to get it to disable the GPU acceleration, so now the Docker Run would look like this:

```
{
  "security_opt": [
    "seccomp=unconfined"
  ],
  "environment": {
    "APP_ARGS": "-cef-disable-gpu-compositing"
  }
}
```

That should avoid having to manually disable when you first launch the session.

If found this page with a list of arguments. Note there are multiple GPU flags and sandbox/seccomp flags so those might be interesting to experiment with:
https://gist.github.com/davispuh/6600880?permalink_comment_id=2311617

**Comment by swoopingasaservice** [comment]
Awesome. Thanks!
