### ISSUE TITLE
Launch menu disable

### ISSUE THREAD

**Issue by KogPop** [kasmtech/workspaces-issues#472]
Hello !

Can I disable this menu ? I want set default "persistent profile" - enable and "Open session in" - current tab. I would like to hide menu from the users. 
![image](https://github.com/kasmtech/workspaces-issues/assets/129720507/d80dca92-5f11-4db1-b369-f21fe2627d6d)

**Comment by j-travis** [comment]
Sorry,
It is not possible to disable this menu. 

Kasm does have the ability for system integrators to launch sessions programmatically via low-code/no-code integrations or via full API access. If you are looking for a more turnkey custom workflow that may be an option.

- https://kasmweb.com/docs/latest/guide/casting.html
- https://kasmweb.com/docs/latest/developers/developer_api.html

There is also the ability to auto-launch a session when the user logs in. You can use a combination of the `auto_login_to_kasm` and `default_image` group settings  https://kasmweb.com/docs/latest/guide/groups.html#group-settings
