### ISSUE TITLE
[Bug] - Unrar/7z missing in kasmweb/qbittorrent docker image

### ISSUE THREAD

**Issue by Bortus-AI** [kasmtech/workspaces-issues#486]
Unrar/7z missing in kasmweb/qbittorrent docker image so I am unable to unrar multipart files from qbittorent. There only seems to be unzip available which won't work for rar files. 

If it is there an this is a bug let me know. If there is a way to get this added that would be appreciated. 

Thanks

**Comment by j-travis** [comment]
You can build a custom image with the additional tools you want inside:

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://youtu.be/BGP69_f1wq0?si=_YIqCoJ9czGxzEut
