### ISSUE TITLE
[Bug] - Cannot add proxy setting for kasm admin to gather registry

### ISSUE THREAD

**Issue by tperrindell** [kasmtech/workspaces-issues#489]
### Existing Resources

- [ X ] Please search the existing issues for related problems
- [ X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Cannot add registry behind proxy

**To Reproduce**
1. Setup kasm in a corp environment running behind a proxy
2. Try to add a registry

**Expected behavior**
Have a setting in the admin panel to setup a global http proxy

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/103429802/7d9cbae6-083b-4d3e-adff-36507f6e40c1)

**Workspaces Version**
1.14.0

**Workspaces Installation Method**
Single-server

**Client Browser (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome / Firefox
 - Version  irrelevant

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
`Linux -redacted- 4.18.0-513.9.1.el8_9.x86_64 #1 SMP Thu Nov 16 10:29:04 EST 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - `cat /etc/os-release`
```
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```
 - `sudo docker info`
```
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-513.9.1.el8_9.x86_64
 Operating System: Red Hat Enterprise Linux 8.9 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 15.29GiB
 Name: ssh.mtp.supportlabs.dell
 ID: 70e9f1f6-fab0-4817-a12a-373e0b7262ca
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://externalproxy:80/
 HTTPS Proxy: http://externalproxy:80/
 No Proxy: .internal.domains
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
 - `sudo docker ps | grep kasm`
```
a0215f78bb9a   kasmweb/nginx:1.25.1       "/docker-entrypoint.…"   3 hours ago      Up 2 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
8d5d2278695d   kasmweb/share:1.14.0       "/bin/sh -c '/usr/bi…"   3 hours ago      Up 2 hours (healthy)   8182/tcp                                        kasm_share
1389fc85cfd3   kasmweb/agent:1.14.0       "/bin/sh -c '/usr/bi…"   3 hours ago      Up 2 hours (healthy)   4444/tcp                                        kasm_agent
718663ed271c   kasmweb/kasm-guac:1.14.0   "/dockerentrypoint.sh"   3 hours ago      Up 2 hours (healthy)                                                   kasm_guac
04095250265d   kasmweb/api:1.14.0         "/bin/sh -c '/usr/bi…"   3 hours ago      Up 2 hours (healthy)   8080/tcp                                        kasm_api
2d13bfac2c8b   kasmweb/manager:1.14.0     "/bin/sh -c '/usr/bi…"   3 hours ago      Up 2 hours (healthy)   8181/tcp                                        kasm_manager
5ed05385596e   redis:5-alpine             "docker-entrypoint.s…"   3 hours ago      Up 2 hours             6379/tcp                                        kasm_redis
b37e9bb9c58b   postgres:12-alpine         "docker-entrypoint.s…"   3 hours ago      Up 2 hours (healthy)   5432/tcp                                        kasm_db
```

**Additional context**

**Comment by tperrindell** [comment]
Or maybe I could write a docker compose override to include the proxy values to some containers and see if that helps?

If I wanted to do so, which containers are polling the registry URLs ? 

Otherwise I might have to rebuild the image to include them. Can you confirm if doing so works (not for workspaces, but for the actual Kasm application) ?

**Comment by j-travis** [comment]
You should be able to:

- Get the CIDR of the `kasm_default_network`
```
sudo docker network inspect kasm_default_network | grep Subnet
                    "Subnet": "172.18.0.0/16",
```
- Modify the docker-compose.yaml file: `sudo nano /opt/kasm/current/docker/docker-compose.yaml`
- Add `http_proxy`, `https_proxy` , and `no_proxy` environment variables to the `kasm_api` section - adding the docker network cidr and the other service hostnames to the `no_proxy` entry.

```
kasm_api:
    container_name: kasm_api
    user: "${KASM_UID?}:${KASM_GID?}"
    image: "kasmweb/api:develop"
    read_only: true
    environment:
      https_proxy: https://my.proxy.com
      http_proxy: http://my.proxy.com
      no_proxy: "172.18.0.0/16,localhost,127.0.0.1,proxy,kasm_agent,kasm_manager,kasm_guac"
    networks:
      - kasm_default_network
```
- Remove the kasm_api container and restart the services
```
sudo docker rm -f kasm_api
sudo /opt/kasm/bin/stop && sudo /opt/kasm/bin/start
```

**Comment by tperrindell** [comment]
Thank you :)

I didn't assume it was the api container that was doing that !

I created a docker-compose.override.yaml in the /opt/kasm/current/docker with the following content, which seems like a less invasive and more "documentable" way of doing the customization:
```
services:
  kasm_api:
    environment:
      HTTP_PROXY: 'http://mysuperproxy:80'
      HTTPS_PROXY: 'http://mysuperproxy:80'
      no_proxy: "172.18.0.0/16,localhost,127.0.0.1,proxy,kasm_agent,kasm_manager,kasm_guac"
```
![image](https://github.com/kasmtech/workspaces-issues/assets/103429802/0059874c-e38d-4c72-8cc6-2e974351c983)

**Comment by tperrindell** [comment]
Closing as per previous comment, thanks.
