### ISSUE TITLE
[Feature Request] - DooD

### ISSUE THREAD

**Issue by octave21** [kasmtech/workspaces-issues#491]
Hello, 

I would like to run docker within a kasm container via mounting the socket /var/run/docker.sock (DooD). That is to say relying on the docker from the host and not relying on a full docker within the container (Dind).

When I try to mount the /var/run/docker.sock via the "Mappings de volume (JSON)" Kasm raise and error.

Is it possible with Kasm to mount a socket like /var/run/docker.sock ?

**** Volumes mapping (JSON) 
{
  "/home/jfc": {
    "bind": "/home/jfc",
    "mode": "rw",
    "uid": 1000,
    "gid": 1000,
    "required": true,
    "skip_check": false
  },
  "/var/run/docker.sock": {
    "bind": "/var/run/docker.sock",
    "mode": "rw",
    "uid": 0,
    "gid": 0,
    "required": true,
    "skip_check": false
  }
}

**** Execution configuration substitution Docker (JSON) 
{
  "environment": {
    "HW3D": true,
    "DRINODE": "/dev/dri/renderD128",
    "KASM_USER": "kasm-user"
  },
  "devices": [
    "/dev/dri/card0:/dev/dri/card0:rwm",
    "/dev/dri/renderD128:/dev/dri/renderD128:rwm"
  ]
}

**** Error log :
host: Portable-JFC
ingest_date: 202312052019
application: kasm_api
levelname: ERROR
kasm_user_name: admin
process: client_api_server
client_ip: 192.168.8.17
user_agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
message
An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(c7095ddc-c8b4-46a9-807e-d48fb449d545) : (Exception creating Kasm: Traceback (most recent call last):
  File "__init__.py", line 539, in post
  File "provision.py", line 1351, in provision
Exception: Failed to process container volume (/var/run/docker.sock)
)

### Existing Resources

- [ ] Please search the existing issues for related items
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by j-travis** [comment]
I was able to use the Docker Ubuntu Jammy image with a volume mapping of
```
{
  "/var/run/docker.sock": {
    "bind": "/var/run/docker.sock",
    "mode": "rw",
    "uid": 0,
    "gid": 0,
    "required": true,
    "skip_check": false
  }
}
```
(which is what you have above)

and docker was able to interact with the hosts' docker.

Maybe try backing out some of your other settings?

You can also try following these steps to look at the session container logs for the failure case
https://github.com/kasmtech/workspaces-issues/issues/444#issuecomment-1736460285

**Comment by octave21** [comment]
Thanks for your reply. The good new is that the function is available. I'll check my configuration.
