### ISSUE TITLE
Resize Remaining Space

### ISSUE THREAD

**Issue by ccigas** [kasmtech/workspaces-issues#493]
Not sure if this is a bug but I am running Kasm in a VM on Proxmox. I originally gave it the 55GB of storage that the docs mention but I quickly ran out of space. So I resized my storage to give the VM an additional 100GB and booted up Kasm. I expected that Kasm would see it but it doesnt. 

How do I resize my storage in Kasm to utilize the newly free 100GB+ of storage?

**Comment by mmcclaskey** [comment]
This is not a Kasm issue but a Linux partition issue. You have adjusted the size of the disk on the VM, but whatever Linux distro you are using does not automatically detect and make assumptions about what to do with the extra space, you have to use utilities in Linux to expand the partition. Here is a link for Ubuntu, but you may want to search for a guide that covers your specific disto of Linux. 
https://raspberrytips.com/resize-partition-ubuntu/
