### ISSUE TITLE
[Bug] - Storage size

### ISSUE THREAD

**Issue by rcarvalho2clicks** [kasmtech/workspaces-issues#496]
Guys, I just installed kasm on a vmware with 4GB and 100GB of storage. I only installed one workspace and it appears that I only have 7.8 of space left. What happened to kasm only having 32GB of storage?
![2023-12-06_17-06](https://github.com/kasmtech/workspaces-issues/assets/135126750/80c5639c-7294-4446-9f28-4d5aa28a3f6e)

**Comment by j-travis** [comment]
- https://github.com/kasmtech/workspaces-issues/issues/466#issuecomment-1779228658
- https://github.com/kasmtech/workspaces-issues/issues/493
