### ISSUE TITLE
[Feature Request] - grab keys - enable switching applications by pressing alt+tab without virtual keyboard

### ISSUE THREAD

**Issue by prahal** [kasmtech/workspaces-issues#497]
### Existing Resources

- [ x ] Please search the existing issues for related items
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ x ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
I cannot switch the foreground application (Xorg). I do open a book with a viewer. Then I want to switch between the calibre library manager and the ebook viewer.
I tried with the "keys" menu, press "Alt" virtual button then either "Tab" virtual button of the keyboard button. The openbox applications menu displays, I can move from one application icon to the other but cannot validate my selection with enter or a mouse click. Still, I can cancel the application switcher menu with Esc.

Either way I would like to be able to do like with my old RDP client (when the docker calibre container was based on xrdp), that is grab the inputs inside the "window"(here browser document) with a button so I do not have to use virtual keyboard.

bug report for the above issue with the virtual keyboard #498 

The docker container code:
https://github.com/linuxserver/docker-calibre
The container images:
https://hub.docker.com/r/linuxserver/calibre

**Describe the solution you'd like**
I would like to be able to do like with my old RDP client (when the docker calibre container was based on xrdp), that is grab the inputs inside the "window"(here browser document) with a button so I do not have to use virtual keyboard.

**Describe alternatives you've considered**
Keep it as is but at least fix fix the above bug.

**Comment by j-travis** [comment]
This image is maintained by linuxserver.io, not Kasm Technologies.  You will need to report this via their support channels.

**Comment by prahal** [comment]
By the way, this feature request has nothing to do with any packaging. You do not provide the feature. How could anybody else be at fault for this feature missing?00

But the bug has nothing to do with the image from linuxserver. It will happen with any openbox setup. Please reopen.

It is as if you told me if I install your software on Debian I should only report your bug to Debian. It's your call but in that case, you only accept bug reports for the firmwares you provide (as you provide none ...).
