### ISSUE TITLE
[Bug] - cannot validate openbox application switcher menu selection - virtual keys menu

### ISSUE THREAD

**Issue by prahal** [kasmtech/workspaces-issues#498]
### Existing Resources

- [ x ] Please search the existing issues for related problems
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ x ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
I cannot switch the foreground application (openbox Xorg). I do open a book with a viewer. Then I want to switch between the calibre library manager and the ebook viewer.
I tried with the "keys" menu, press "Alt" virtual button then either "Tab" virtual button of the keyboard button. The openbox applications menu displays, I can move from one application icon to the other but cannot validate my selection with enter or a mouse click. Still, I can cancel the application switcher menu with Esc.

**To Reproduce**
1. Connect to the calibre docker image running openbox
2. Left lick on the minimize on the calibre title bar
3. Right click on the openbox background and select xterm 
4. Open the Kasmvnc Keys menu and click on "Alt", then press the "Tab" key
5. On the openbox application switcher menu select the application currently in the background (switching with more "Tab" key press and then try to validate and get this application to the foreground with Enter or Left mouse click.
6. Nothing happens.

**Expected behavior**
When I click "Alt" n the kasmvnc virtual keys menu, then press "Alt" and openbox shows its application switcher menu, when pressing the Enter key or left clicking with the mouse I should have the openbox application switcher currently selected application getting to the foreground.

**Screenshots**

**Workspaces Version**
1.3.0

**Workspaces Installation Method**
linuxserver.io

The docker container code:
https://github.com/linuxserver/docker-calibre
The container images:
https://hub.docker.com/r/linuxserver/calibre

**Client Browser (please complete the following information):**
 - OS: Linux Debian Trixie
 - Browser Firefox
 - Version 120.0.1 (64 bits)

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**

**Comment by j-travis** [comment]
This image is maintained by linuxserver.io, not Kasm Technologies.  You will need to report this via their support channels.

**Comment by prahal** [comment]
But the bug has nothing to do with the image from linuxserver. It will happen with any openbox setup. Please reopen.

It is as if you told me if I install your software on Debian I should only report your bug to Debian. It's your call but in that case, you only accept bug reports for the firmwares you provide (as you provide none ...).

Or do you mean openbox is not supported as a window manager for kasmvnc?

**Comment by j-travis** [comment]
Perhaps I don't understand your question. 

This issue tracker is for the Kasm Workspaces platform (https://kasmweb.com/) (https://kasmweb.com/docs/latest/index.html)  .  The platform and the official images don't use openbox in any capacity. KasmVNC is used within our official images, but we don't use openbox.


I do believe some of the linuxserver images leverage openbox  My guess at what you are asking for is just down to key-mappings that may need to be defined in those images , bug I'm not sure. If thats the case, its something the linuxserver image maintainers will have to do.

If you think there is a problem with KasmVNC in general,  Please open a ticket in that repo (https://github.com/kasmtech/KasmVNC/issues)

I encourage you to put as much detail as possible to include a video recording.

**Comment by prahal** [comment]
Indeed I was aiming for https://github.com/kasmtech/KasmVNC/issues, I misunderstood your support page and thought this issue tracker was home for both. I will open the issue in the proper tracker asap.
