### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by carldavis** [kasmtech/workspaces-issues#501]
I can log into the dashboard but cannot connect to any instance and instead receive a 500 internal server error. I have tested with curl from within the Kasm container and still get a 500 server error so I do not believe this is related to Cloudflare or the swag instance I have in front of Kasm. The Firefox instance seems to be running and the logs show the following in a loop.

```
docker logs userkasm.loc_acc84331
/dockerstartup/vnc_startup.sh: line 395: kill: (75) - No such process
...
```
 
At this point I am not sure what to look at because I *think* I have verified things are working and cannot find the source of the 500 error.

**Comment by j-travis** [comment]
When creating bug/troubleshooting tickets, please include the requested information as defined in the ticket. https://github.com/kasmtech/workspaces-issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBug%5D+-+Example

You'll also want to include details about your setup , OS, what image you are using etc

You may also find the following troubleshooting guides helpful.
- https://kasmweb.com/docs/latest/guide/troubleshooting.html
- https://kasmweb.com/docs/develop/guide/troubleshooting/advanced_connection_troubleshooting.html#connectivity-troubleshooting
