### ISSUE TITLE
[Feature Request] - Data Persistence Cross Sessions for Kasm Cloud Personal

### ISSUE THREAD

**Issue by Albatraoz189** [kasmtech/workspaces-issues#506]
Hello, 

I am looking for an option to enable data persistence cross sessions for KasmWeb Cloud. Is this feature currently being looked into by the developers? It would be nice to be able to option it on or off.

### Existing Resources

- [ ] Please search the existing issues for related items
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by j-travis** [comment]
Hello, 
I encourage you to reach out to our team via the contact form at the bottom of our homepage
https://kasmweb.com/

They can walk you through the options for a setup with persistence for your developers
