### ISSUE TITLE
[Bug] - Error performing upgrade to 1.15.0

### ISSUE THREAD

**Issue by marcogiorgio** [kasmtech/workspaces-issues#517]
Hi
I tried to perform the upgrade to Kasm 1.15 from 1.14 using the upgrade script, but it fails with this log:

<details>
  <summary>error log</summary>
  
  ```bash
  marco@srvkasm:/tmp$ cat kasm_install_1708127493.log

Setting Default Database Password from stdin -Q
Setting Default Manager Token as <TOKEN>
Setting Default Listening Port as 8443
Hit:1 http://deb.debian.org/debian bookworm InRelease
Get:2 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:3 https://download.docker.com/linux/debian bookworm InRelease [43.3 kB]
Get:4 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:5 http://security.debian.org/debian-security bookworm-security/main Sources
[80.9 kB]
Get:6 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [139 kB]
Get:7 http://security.debian.org/debian-security bookworm-security/main Translation-en [82.9 kB]
Get:8 http://deb.debian.org/debian bookworm-updates/non-free-firmware Sources [2,076 B]
Get:9 http://deb.debian.org/debian bookworm-updates/non-free-firmware amd64 Packages [616 B]
Get:10 http://deb.debian.org/debian bookworm-updates/non-free-firmware Translation-en [384 B]
Fetched 452 kB in 1s (691 kB/s)
Reading package lists...
W: https://download.docker.com/linux/debian/dists/bookworm/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34992  100 34992    0     0  40367      0 --:--:-- --:--:-- --:--:-- 40359
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  v4l2loopback-utils
The following packages will be DOWNGRADED:
  v4l2loopback-dkms
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
E: Packages were downgraded and -y was used without --allow-downgrades.
An error has occurred please review the log at ./kasm_install_1708127493.log
  ```
  
</details>

**To Reproduce**
cd /tmp
curl -O https://kasm-static-content.s3.amazonaws.com/kasm_release_1.15.0.06fdc8.tar.gz
tar -xf kasm_release_1.15.0.06fdc8.tar.gz
sudo bash kasm_release/upgrade.sh --proxy-port 443

**Workspaces Version**
1.14

**Workspaces Installation Method**
Single Server

**Workspace Server Information:**

<details>
  <summary>uname -r</summary>

 Linux srvkasm 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
 </details>

 <details>
  <summary>cat /etc/os-release</summary>

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
</details>

<details>
  <summary>sudo docker ps</summary>

 Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
 Containers: 19
  Running: 19
  Paused: 0
  Stopped: 0
 Images: 18
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-18-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 7.753GiB
 Name: srvkasm
 ID: f590a1aa-5f09-4ebc-9274-d28ccab30e2a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
</details>

<details>
  <summary>sudo docker ps | grep kasm</summary>

 987526df1dbd   kasmweb/nginx:1.25.1                           "/docker-entrypoint.…"   6 weeks ago   Up 5 days             80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp   kasm_proxy
ccd6d346bc25   kasmweb/share:1.14.0                           "/bin/sh -c '/usr/bi…"   6 weeks ago   Up 5 days (healthy)   8182/tcp
               kasm_share
ccc5604c2be1   kasmweb/agent:1.14.0                           "/bin/sh -c '/usr/bi…"   6 weeks ago   Up 5 days (healthy)   4444/tcp
               kasm_agent
ef5a0f1c7eb3   kasmweb/api:1.14.0                             "/bin/sh -c '/usr/bi…"   6 weeks ago   Up 5 days (healthy)   8080/tcp
               kasm_api
1eff15ba966f   kasmweb/kasm-guac:1.14.0                       "/dockerentrypoint.sh"   6 weeks ago   Up 5 days (healthy)
               kasm_guac
f128da874054   redis:5-alpine                                 "docker-entrypoint.s…"   6 weeks ago   Up 5 days             6379/tcp
               kasm_redis
93a33867cfc4   kasmweb/manager:1.14.0                         "/bin/sh -c '/usr/bi…"   6 weeks ago   Up 5 days (healthy)   8181/tcp
               kasm_manager
9bcee36f4db3   postgres:12-alpine                             "docker-entrypoint.s…"   6 weeks ago   Up 5 days (healthy)   5432/tcp
               kasm_db
</details>

**Comment by thelamer** [comment]
I cannot replicate this in bookworm, the deb we ingest is built by us with specific patches to allow up to 128 virtual cameras. We build this deb constantly to ensure it is not out of sync with what is in Debian's Bookworm repo, which is currently `0.12.7-2` even up to backports and sid.
We have logic to completely block the install if `/var/lib/dkms/v4l2loopback` exists so I need help understanding what might be custom about your bookworm setup. Did you add any repos that may have ingested v4l2loopback-dkms or manually installed a deb previous to this upgrade? 

As for an actual solution to your problem you can: 

```
sudo apt-get remove --purge v4l2loopback-dkms
wget https://kasmweb-build-artifacts.s3.amazonaws.com/v4l2loopback-ubuntu/debian_12-v4l2loopback-dkms.deb
sudo dpkg -i debian_12-v4l2loopback-dkms.deb
```
Previous to the upgrade if you want webcam support, or you can make a fake folder to block the install attempt: 

```
sudo mkdir -p /var/lib/dkms/v4l2loopback
```
If you don't want it installed at all on top of whatever is your current setup.

**Comment by marcogiorgio** [comment]
Hi @thelamer and thanks for your support!

> Did you add any repos that may have ingested v4l2loopback-dkms or manually installed a deb previous to this upgrade?

I didn't, in facts I use this server just for Kasm. This is the output of  `apt policy v4l2loopback-dkms`:

```bash

v4l2loopback-dkms:
  Installed: 0.12.7-2
  Candidate: 0.12.7-2
  Version table:
 *** 0.12.7-2 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status

```
You can see that the package comes from the standard Debian Bookworm repo 


> As for an actual solution to your problem you can...previous to the upgrade:

Thanks to this I managed to complete the upgrade but I got this in the error logs after the upgrade:

```bash
Failed to create virtual webcam devices. modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/6.1.0-18-amd64
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/6.1.0-18-amd64
```

**Comment by thelamer** [comment]
You need to do some digging here. Can you modprobe that manually on the host ?
Is the kernel module videodev present on your system?
I run bookworm on my personal laptop and many remote machines this is new to me.
Did you modify the kernel on your system in any way (vanilla install etc).
Also just to confirm you are actually running your head kernel right 6.1.0-18-amd64? `uname -a` or does the system need to be rebooted.
None of this should matter as it should dkms all kernels present on the system, but I am at a loss here, Debian is one of the most straight forward when it comes to stuff like this, if you installed the Deb it should be on your system as it has hooks that run and compile/enable it during the install.

**Comment by marcogiorgio** [comment]
I found the issue. I didn't have the kernel headers installed. However, I don't think that by default Debian installs them, but I am not sure..
Does the install script make sure that they are installed?
Thanks

**Comment by thelamer** [comment]
Yes I believe so unless using a min network install. But regardless we should check for their presence in the installation logic before attempting to install a dkms module.
Thanks for getting to the bottom of this.

**Comment by marcogiorgio** [comment]
No worries, thank you for the support!
