### ISSUE TITLE
Kasm is full of bullshit.

### ISSUE THREAD

**Issue by uhidontkno** [kasmtech/workspaces-issues#520]
You heard me, Kasm is full of bullshit. I am absolutely fed up with the direction Kasm is going towards. This is not good for people that FOSS is (usually) aimed for... Hobbyist developers.

----

1. **Anti open source and false claims**:
First and foremost, Kasm seems to be advertised as an "open-source" DaaS or  desktop-as-a-service solution. I am here to tell you that their claims are absolute bullshit, as they are only open sourcing the BARE MINIMUM of enough to be called "open source" so they can rub it into your face. They are dockerizing their core containers to make it extremely hard to reverse engineer  the backend and as a side effect makes it hard to backup the db, and their sourcemaps are extremely large and have an incomprehensible amount of files in said sourcemap to (probably) steer you away from trying to reverse engineer the frontend. Additionally their bold claims of "infinite customizability" is lacking, especially for the free version as it is 600 DOLLARS to just get customizability and the same amount of concurrent sessions as the FREE version. What a scam.

2. **Incorrect target audience and bad user-friendliness**
Next, Kasm seems to be targeted to businesses with loads of money to blow. There is no clear distinction on the Kasm website that Kasm Workspaces is targeted for people or for corporate businesses. No wonder why Kasm Workspaces licenses are OVER 600 DOLLARS?! This is absolutely diabolical for the average "Joe"[1] as they do not have enough money to afford the most basic license for Kasm Workspaces... Public Kasm Workspaces instances on the Community (aka free) version will be doomed because of ever-growing userbases regardless of how many resources they have for Kasm. I, or the average "Joe" do not have enough money to afford to get a basic suite of customization, extra features not a lot of people really don't care about, and it is another 600 DOLLARS TO INCREASE CONCURRENT SESSIONS???!?! These horrible practices and hefty pricetags may be for corporate, but NOT for the CORRECT target audience, which is for the consumer. This proves that Kasm and Kasm Workspaces are both FAR from being user friendly, especially for the FOSS audience that seems to be discovering Kasm Workspaces which is almost always hobbyist developers, which these developers will probably be trying to make a public and free Kasm Workspaces instance. 

3. **KasmVNC and Kasm containers are hard to use outside of Kasm Workspaces**
I am absolutely fed up with the anti-consumer things Kasm is doing so what if I want to make something similar. That's where my trip with Kasm's containers ends and the journey of making the entire thing from scratch myself starts because Kasm containers are notoriously hard to use, deploy, and proxy outside of Kasm Workspaces. The webserver baked in of KasmVNC seems to refuse legitimate WebSocket connections forcing you to either modify the client/server or ditch using Kasm's absolutely amazing innovation (sarcasm) and painstakingly create your own base Docker containers and to use noVNC, so you can finally proxy your Docker containers using Nginx. Great, Kasm isn't even doing shit that is good for developers. Seems like all of the open source resources from Kasm that you DO get (which is not a lot) isn't being useful even when trying to develop using it, you can only use their stuff with Kasm Workspaces only, so it's essentially useless. Bad CONSUMER experience AND bad DEVELOPER experience? What the fuck are you guys doing? Seems like jacking off and making a mediocre DaaS (or what us proxy devs call a really good "proxy") that only just works on your shit and nobody else's. Why can't we integrate your software into other shit? (Basically anything can do better at integration) Seems like all of this dumbass work is only for the fatass paycheck and not even for a good developer experience filled with vague, hard to fix errors and unhelpful responses from Kasm employees that the COMMUNITY has to answer two weeks after you already found a workaround, which is ditch Kasm entirely and go for the more work intensive route which is remake Kasm to actually be GOOD and not a corporate piece of shit whose goal is solely to make money and have a shitty free version. Fucking piece of shit. 

4. **What should I do?**
### Ditch Kasm. 
Sadly ditching Kasm is really hard if you are looking for something that offers similar functionality. I am currently working on an alternative to Kasm Workspaces. Currently called NewDeblok as "Old Deblok" is a (forcefully
) rebranded instance of Kasm Workspaces but I had to reevaluate due to reaching above shitty limits very frequently (this is why I ranted earlier)
*  [NewDeblok's GitHub](https://github.com/Deblok-Workshop/NewDeblok), NewDeblok is licensed under GPL-3.0.
* There are virtually zero alternatives to Kasm Workspaces that offer similar functionality. [n.eko](https://neko.m1k1o.net/) is an option but I couldn't get it working outside my LAN and N.eko Rooms doesn't provide sufficient functionality that Kasm does.

### Footnotes
[1]: The average "Joe" is the average consumer
[2]: A lot of this is based off of MY OWN experience running my own public and free instance of Kasm Workspaces for 4 months.

**Do NOT reply with "i ain't reading allat" 😭**

**Comment by ProgrammerIn-wonderland** [comment]
Lmao why are you whining in their GitHub issues 😭

**Comment by uhidontkno** [comment]
> Lmao why are you whining in their GitHub issues 😭

Because I can 🗣️🗣️

**Comment by ProgrammerIn-wonderland** [comment]
> Because I can 🗣️🗣️
> Now read the rest of the issue because I bash on people on GitHub. Cry about it.

I think you misunderstand, you're the whole whining about a free product, I believe in this instance, you're the one "crying about it"

**Comment by uhidontkno** [comment]
> > Because I can 🗣️🗣️
> > Now read the rest of the issue because I bash on people on GitHub. Cry about it.
> 
> I think you misunderstand, you're the whole whining about a free product, I believe in this instance, you're the one "crying about it"

Kasm advertises itself as having a free version, while it does, but it's limited when you're trying to use it in prod.

**Comment by ProgrammerIn-wonderland** [comment]
> Kasm advertises itself as having a free version, while it does, but it's limited when you're trying to use it in prod.

Yeah, most free versions of things are more limited than their paid versions, that's usually how that works.

**Comment by uhidontkno** [comment]
> Yeah, most free versions of things are more limited than their paid versions, that's usually how that works.

I know, but it is hard to even use the free version apart from a private instance with like 6 friends, but even then its limiting. The feature set I'm not complaining about but the license pricing and concurrent session limits are unacceptable.

**Comment by wearrrrr** [comment]
smorenitez v2 anyone?

**Comment by alfonsop123** [comment]
what

> smorenitez v2 anyone?

**Comment by CoolElectronics** [comment]
don't make me summon crystals

**Comment by proudparrot2** [comment]
> what
> 
> > smorenitez v2 anyone?

oh hi

**Comment by ProgrammerIn-wonderland** [comment]
> I know, but it is hard to even use the free version apart from a private instance with like 6 friends, but even then its limiting. The feature set I'm not complaining about (apart from modifying kasms `/www/img` folder to get some customization for free) but the license pricing and concurrent session limits are unacceptable.

You aren't supposed to customize the free version lol, I'm not even sure if the license allows it

**Comment by loool999** [comment]
Dam this issue is active af

**Comment by certifiedfoolio** [comment]
this is so true frfr

**Comment by j-travis** [comment]
Feedback , constructive criticism and complaints are welcome. Disrespecting  our team,  cursing , ranting an insulting other users of the community , especially on unrelated tickets, is not. For that reason, I am shutting this down.

I'm sorry you were not able to get KasmVNC or our Workspace Image containers working for your use-case. I assure you it doesn't only work in our platform. Both our org and linuxserver.io publish dozens if not 100+ container images that leverage KasmVNC outside the platform.  While we try to make it look and feel easy, under the hood it can be quite complex and require an command several  disciplines including networking, security, systems administration, and development at multiple levels of the stack, etc

When you choose to use these tools for your own projects, we have limited ability to help you integrate / customize - much like every other open source project.
