### ISSUE TITLE
Browser crashes when users load multiple tabs

### ISSUE THREAD

**Issue by Shab-sam** [kasmtech/workspaces-issues#522]
In  the kasm workspace(google chrome/firefox) session when users loads multiple tabs the application crashes with the error "Can't open this page with error code 9" and sometimes they get "Aw! Snap  with error code 9".

**Comment by j-travis** [comment]
- Ensure you have a proper swap partition created on your kasm servers.  A minimum of 2GB per simultanous session you want to run.: https://kasmweb.com/docs/latest/install/system_requirements.html#swap-partition
- Give the workspace more ram/cpu resources.
- Try increasing the `shm_size` of the workspace. : https://kasmweb.com/docs/latest/guide/troubleshooting/sigtrap.html

**Comment by Shab-sam** [comment]
Hi,

Initially then CPU core was set to 2 and ram was 2 GB which we have increased to 4 cores and 4 GB also we set the shm_size to 4g. Still we are facing the issue. 

The kasm server has 128 GB ram out of which only 39 GB being used.

Please find the details below:

 free -g
               total        used        free      shared  buff/cache   available
Mem:             125          39          51           1          34          83
Swap:              1           1           0

**Comment by j-travis** [comment]
And how about that swap recommendation?

**Comment by Shab-sam** [comment]
The OS swap is 2 GB
swapon --show
NAME      TYPE SIZE USED PRIO
/swapfile file   2G   2G   -2

Just wanted to confirm if kasm will create a separate swap space while installing ?

**Comment by j-travis** [comment]
Kasm can create a swap partition when installing , but you can create and modify one after the fact too.  The main point is that when a container has a memory limit set, when it hits that limit it will use swap no matter how much other free ram you have. Thats why its imperative to have a healthy swap partition. When swap is exceeded the kernel will start killing processes . its called an OOM error (Out of Memory) . You can check your kern.log to see if you've been experiencing these. 

I recommend reviewing this guide that was referenced in the docs: https://docs.docker.com/config/containers/resource_constraints/

**Comment by Shab-sam** [comment]
Thanks for the information. I will update the swap memory to 100 GB and check if it resolve the issue .

**Comment by Shab-sam** [comment]
Now, we are getting the error "No Resources are available to create the requested Kasm. Please try again or contact an Administrator kasm".

Total Memory:125.78 GB
Used Memory:30.38 GB
Available Memory:91.74 GB
Disk Capacity:467.33 GB
Used Disk Space:134.98 GB
Available Disk Space:308.54 GB

**Comment by j-travis** [comment]
We have a guide on this issue. Can you please review it and see if  you can resolve your issues: https://kasmweb.com/docs/latest/guide/troubleshooting/no_resources_available.html#no-resources-available

**Comment by Shab-sam** [comment]
Hi 

Now for some users when they login to gmail and start the google meet web cam, headphone works fine once they switchover to another meeting their camera freezes and some time the headphone doesn't work. When they delete the session and start the meeting everything works fine again.

Also when they login for the first time webcam does not appear and after refreshing the web page it appears.

**Comment by Shab-sam** [comment]
Any idea on how to fix this issue?

**Comment by j-travis** [comment]
I believe the original issue is resolved. Please open a new issue for new topics.
When  creating bug tickets please provide all the requested information as it helps us understand your operating environment to start the triage process.
