### ISSUE TITLE
[Bug] - Session Recorder

### ISSUE THREAD

**Issue by johncadengo** [kasmtech/workspaces-issues#525]
### Existing Resources

- [X] Please search the existing issues for related problems
- [X] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [X] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [X] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [X] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
I am trying out the new Sessions Recording feature (https://kasmweb.com/docs/latest/guide/session_recording.html).

I configured the settings as described in the documentation (https://kasmweb.com/docs/latest/guide/session_recording.html#configuration)

**To Reproduce**
1. I have one window open as the Admin
2. I have another window open as a user who is in a group with the `record_sessions` setting set to `true`.
3. I perform work as expected and eventually delete the session
4. Back in the Admin window, I see no error logs that indicate it is not working. I see 0 recordings under the session history. And I only get an error later, after the session has been deleted, but I'm not sure what information it is telling me.

**Expected behavior**
I'm hoping to be able to get a more detailed error log so I can troubleshoot what's going on.

Is it failing on the client side? 

Is it failing on the server side?

Is it failing to upload to my s3 bucket?

Did I misconfigure the s3 bucket?

Do I need to make the folders in advance inside of the s3 bucket?

I'm not really sure where to troubleshoot.

**Screenshots**
This is the only warning/error I can find in the logs related to session recording.
![Screenshot 2024-03-08 at 5 52 03 PM](https://github.com/kasmtech/workspaces-issues/assets/561587/7142a496-7474-4efa-afd3-9bf488bc3e0c)

**Workspaces Version**
Version 1.15

**Workspaces Installation Method**
Single Server, linuxserver.io

**Client Browser (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 122.0.6261.112 (Official Build) (arm64)

**Additional context**
I am using a custom S3 endpoint on a machine on my local network. 

I have a feeling it has to do with my S3 setting but I don't know how to confirm if that's the case since I don't know how to see where the error is occurring. Is there a way to find more detailed logs about this? And is there a way to confirm that my S3 settings are correct?

My s3 endpoint is following the convention from the documentation (i.e. `s3://kasm@storage.googleapis.com/recordings/{user_id}/{image_friendly_name}-{start_date}.mp4`)

It looks like this (changed IP and port, just using an example):

`s3://Kasm@192.168.1.100:8888/recordings/{user_id}/{image_friendly_name}-{start_date}.mp4`

In this case `Kasm` is my bucket name and `8888` is my port.

In my custom s3 compatible server, when I ask for the URL, it shows `https://`. I'm not sure if I need to specify that it's `https` vs `http` or not when it comes to the `s3` protocol.

**Comment by johncadengo** [comment]
More additional context on the client side, when I look at my javascript console, I see something like this:

```
Failure:  DOMException: Failed to register a ServiceWorker for scope ('https://192.168.1.101/') with script ('https://192.168.1.101/serviceworker.js'): An SSL certificate error occurred when fetching the script.
```

I'm not sure if it's an SSL error that's preventing the sessions recording script to start. Not sure if it uses the serviceworker to do anything or not.

**Comment by johncadengo** [comment]
After some troubleshooting, I have an error now. This is the first time finding an error in my logs about s3:

```
host: 878796c05cdd
ingest_date: 202403100119
application: kasm_api
levelname: ERROR
process: root
client_ip: 172.18.0.1
user_agent: python-requests/2.31.0
message
Unhandled exception occurred
Traceback (most recent call last):
  File "cherrypy/_cprequest.py", line 628, in respond
  File "cherrypy/_cprequest.py", line 687, in _do_respond
  File "cherrypy/lib/encoding.py", line 219, in __call__
  File "cherrypy/lib/jsontools.py", line 59, in json_handler
  File "cherrypy/_cpdispatch.py", line 54, in __call__
  File "utils.py", line 370, in wrapper
  File "client_api.py", line 6463, in request_session_recording_upload_url
  File "providers/aws_provider.py", line 747, in request_upload_file
  File "providers/aws_provider.py", line 439, in set_endpoint
  File "providers/aws_provider.py", line 498, in get_bucket_region_name
  File "botocore/client.py", line 530, in _api_call
  File "botocore/client.py", line 915, in _make_api_call
  File "botocore/client.py", line 1027, in _emit_api_params
  File "botocore/hooks.py", line 412, in emit
  File "botocore/hooks.py", line 256, in emit
  File "botocore/hooks.py", line 239, in _emit
  File "botocore/handlers.py", line 285, in validate_bucket_name
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "kasm:192.168.1.100": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

Edit: Actually, I was changing the s3 endpoint and made a typo. I used a `:` instead of a `@` which resulted in this error. I've fixed the typo and now I'll test if the new endpoint configuration gives me a new error or works.

**Comment by johncadengo** [comment]
After some more troubleshooting, I was able to get recordings to save, but only for one of the two workspaces I had set up.

For a workspace I downloaded from the registry (i.e. Ubuntu) it works.

For a workspace I forked from the registry, it does not. Specifically that workspace was forked from `kasmweb/ubuntu-jammy-desktop:develop-2024-01-17.15.22`

Is this because it was forked earlier than the new changes were made that were necessary to support recordings? 

> Session recording is supported on container based workspaces as well as RDP, VNC, and SSH server based workspaces. Containers must be either 1st party Kasm published images, or built upon the 1st party images with 1.15.0 tags or newer.

At this point I'll look into it, but it appears that this is the reason.

**Comment by j-travis** [comment]
Hello,
yes, we made changes to the recording capability regularly throughout the release cycle , so nothing before the official `:1.15.0` tags isnt guaranteed to be compatible.

In fact I recommend you use the `:1.15.0-rolling` tags, as we've made a few updates since the release that may improve stability

**Comment by johncadengo** [comment]
Got it. This is likely the source of my issue. Thank you.
