### ISSUE TITLE
Need help with Kasm behind Authentik (openID)

### ISSUE THREAD

**Issue by morskipas** [kasmtech/workspaces-issues#536]
Hello together,

I've been trying to use Kasm authentication OpenID in conjunction with Authentik for a few days now. Unfortunately, I always get the following error.

 
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/704eece7-bb24-420f-9312-410f68073a29)

I hope that someone already has Kasm and Authentik via openID running and can give me some tips. I really don't know what to do.
It may be important to know that everything runs behind an "Nginx Proxy Manager".
As a quick info: I've already connected wiki.js via openID, so Authentik basically works.

In Authentik (version 2024.2.2) I have set up Kasm as an application and provider.
In Kasm (version 1.15.0) I set up OpenID like this:
 
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/ad252c0c-7ff0-4763-893d-9414790ae567)
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/94ac7ee4-b317-4844-bcfe-3f27b026653f)

 
Then I assigned the SSO type OpenID to the group "All Users", in which all users are assigned, under SSO group assignment. The mapping applies to all users without a group attribute.
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/7a9a0d45-13c2-4b02-8d5b-02419c7209b6)
 

Now I call kasm, it shows me the login screen and I click on "Continue with Authentik". 
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/cbe26131-ae48-4fb0-87f0-f34238f5e490)
 

Here I enter my email address and click on "Use security key".
 
![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/87f24d11-d597-468a-84b0-8b7744f04acd)

Then the message "Successfully logged in" comes up briefly and I end up on this screen with an error message.

![image](https://github.com/kasmtech/workspaces-issues/assets/6042276/257295d3-8653-4a7c-9258-4f36268842b6)

Any help or tips?

**Comment by j-travis** [comment]
It looks like you may already have a user defined in the system with the same name as the one you are trying to login with authentic. 

Delete that user from the Kasm app, then try to sign on again. It will re-create the account in Kasm

**Comment by morskipas** [comment]
> It looks like you may already have a user defined in the system with the same name as the one you are trying to login with authentic.
> 
> Delete that user from the Kasm app, then try to sign on again. It will re-create the account in Kasm

Oh my goodness, that's exactly what it was! 
Thank you so much for the help :-) 
I thought that existing users would also work if they have the same username.

Thanks for your help :-) and have a nice Sunday

**Comment by morskipas** [comment]
Solved by a hint from j-travis :-) thx
