### ISSUE TITLE
[Bug] - Rename a download files

### ISSUE THREAD

**Issue by KogPop** [kasmtech/workspaces-issues#546]
Hello !
I have problem. I can't rename the file when I try to download it. I can select name and delete but after that the name window only catches 1 character.

Can anyone help me? Thanks!

**Comment by j-travis** [comment]
There is not enough information to go off of to help you.
When you entered the ticket there was a list of items we asked you to provide to help orient us to your environment. Please reenter your ticket with that data , to include any helpful screenshots / videos of the issue
