### ISSUE TITLE
[Bug] - Unable to launch containers

### ISSUE THREAD

**Issue by brommeltje** [kasmtech/workspaces-issues#551]
**Describe the bug**
All containers fail to start after a fresh install

**To Reproduce**
Add container from registery (example remmina)
Try to launch after it is loaded, 

**Expected behavior**
App launched 

**Screenshots**
Log shows following:
2024-05-06T16:41:10Z DEBUG (vnc_startup.sh): Starting printer service
INFO:KasmPrintingService:Watching for PDF documents at /home/kasm-user/PDF
Traceback (most recent call last):
  File "service.py", line 83, in <module>
  File "watchdog/observers/api.py", line 261, in start
  File "watchdog/utils/__init__.py", line 92, in start
  File "watchdog/observers/inotify.py", line 119, in on_thread_start
  File "watchdog/observers/inotify_buffer.py", line 37, in __init__
  File "watchdog/observers/inotify_c.py", line 167, in __init__
  File "watchdog/observers/inotify_c.py", line 430, in _raise_error
OSError: [Errno 24] inotify instance limit reached
[920] Failed to execute script 'service' due to unhandled exception!
/dockerstartup/vnc_startup.sh: line 473: kill: (917) - No such process

**Workspaces Version**
Version 1.15

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 124

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
     Linux gandalf 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux
 - `cat /etc/os-release`
     PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 - `sudo docker info`
 Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 36
  Running: 33
  Paused: 1
  Stopped: 2
 Images: 35
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-28-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.35GiB
 Name: gandalf
 ID: 366d0c3d-d7b5-46a9-8d4f-5a4c5845d7b3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 - `sudo docker ps | grep kasm`
d717ed5bbbd9   kasmweb/remmina:1.15.0                          "/dockerstartup/kasm…"   11 minutes ago   Up 11 minutes (Paused)    4901/tcp, 5901/tcp, 6901/tcp                                                                                                                                                           adminkasm.lo_e7ad7582
725848a3ef20   kasmweb/nginx:1.25.3                            "/docker-entrypoint.…"   29 minutes ago   Up 29 minutes             80/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp                                                                                                                                      kasm_proxy
edfd33c18026   kasmweb/share:1.15.0                            "/bin/sh -c '/usr/bi…"   29 minutes ago   Up 29 minutes (healthy)   8182/tcp                                                                                                                                                                               kasm_share
2e101a808170   kasmweb/agent:1.15.0                            "/bin/sh -c '/usr/bi…"   29 minutes ago   Up 29 minutes (healthy)   4444/tcp                                                                                                                                                                               kasm_agent
259c297d1bd1   kasmweb/kasm-guac:1.15.0                        "/dockerentrypoint.sh"   29 minutes ago   Up 29 minutes (healthy)                                                                                                                                                                                          kasm_guac
a7d1633f01e4   kasmweb/api:1.15.0                              "/bin/sh -c '/usr/bi…"   29 minutes ago   Up 29 minutes (healthy)   8080/tcp                                                                                                                                                                               kasm_api
fd4faaf67afc   redis:5-alpine                                  "docker-entrypoint.s…"   29 minutes ago   Up 29 minutes             6379/tcp                                                                                                                                                                               kasm_redis
45473c9568c9   kasmweb/manager:1.15.0                          "/bin/sh -c '/usr/bi…"   29 minutes ago   Up 29 minutes (healthy)   8181/tcp                                                                                                                                                                               kasm_manager
a04a0b407c2f   postgres:12-alpine                              "docker-entrypoint.s…"   30 minutes ago   Up 29 minutes (healthy)   5432/tcp                                                                                                                                                                               kasm_db

**Additional context**

**Comment by j-travis** [comment]
You are bumping into an operating system configured limit guarding the maximum number of filesystem events.
You will likely need to increase:
`fs.inotify.max_user_instances` and/or `fs.inotify.max_user_watches` in `/etc/sysctl.conf` . You can find guides on this.

If you don't need the printer redirection, you can disable it via the group settings. Turn `allow_kasm_printing` to `false`. This may temporarily relieve the problem.

You may also just have too many containers (33) running on the same host. You may consider moving kasm to its own host.

**Comment by brommeltje** [comment]
Some more logs.... after disabling printer....  (log is of the remmina container trying to start)
+ DEFAULT_PROFILE_HOME=/home/kasm-default-profile
+ PROFILE_SYNC_DIR=/kasm_profile_sync
+ '[' -f /home/kasm-user/.bashrc ']'
+ echo 'Profile Sync Directory Does Not Exist. No Sync will occur'
+ copy_default_profile_to_home
Profile Sync Directory Does Not Exist. No Sync will occur
Copying default profile to home directory
+ echo 'Copying default profile to home directory'
+ cp -rp /home/kasm-default-profile/. /home/kasm-user/
+ ls -la /home/kasm-user
total 32
drwxrwxrwx 1 kasm-user root      4096 Mar 23 16:02 .
drwxr-xr-x 1 root      root      4096 Mar 23 06:13 ..
-rw-r--r-- 1 kasm-user kasm-user   43 Mar 23 06:12 .bashrc
drwxrwxrwx 4 kasm-user kasm-user 4096 Mar 23 16:02 .config
drwxrwxrwx 2 kasm-user kasm-user 4096 Mar 23 16:02 Desktop
drwxr-xr-x 3 kasm-user kasm-user 4096 Mar 23 16:02 .local
drwxrwxrwx 3 kasm-user kasm-user 4096 Mar 23 06:12 .pki
+ verify_profile_config
+ echo 'Verifying Uploads/Downloads Configurations'
+ mkdir -p /home/kasm-user/Uploads
Verifying Uploads/Downloads Configurations
+ '[' -d /home/kasm-user/Desktop/Uploads ']'
+ echo 'Creating Uploads Desktop Symlink'
+ ln -sf /home/kasm-user/Uploads /home/kasm-user/Desktop/Uploads
Creating Uploads Desktop Symlink
+ mkdir -p /home/kasm-user/Downloads
+ '[' -d /home/kasm-user/Desktop/Downloads ']'
+ echo 'Creating Download Desktop Symlink'
+ ln -sf /home/kasm-user/Downloads /home/kasm-user/Desktop/Downloads
Creating Download Desktop Symlink
+ '[' -d /usr/share/kasmvnc/Downloads/Downloads ']'
+ echo 'Creating Downloads RX Symlink'
+ ln -sf /home/kasm-user/Downloads /usr/share/kasmvnc/www/Downloads/Downloads
Creating Downloads RX Symlink
+ ls -la /home/kasm-user/Desktop
total 16
drwxrwxrwx 2 kasm-user kasm-user 4096 May  9 09:52 .
drwxrwxrwx 1 kasm-user root      4096 May  9 09:52 ..
lrwxrwxrwx 1 kasm-user kasm-user   25 May  9 09:52 Downloads -> /home/kasm-user/Downloads
-rwxr-xr-x 1 kasm-user kasm-user 6034 Mar 23 16:02 org.remmina.Remmina.desktop
lrwxrwxrwx 1 kasm-user kasm-user   23 May  9 09:52 Uploads -> /home/kasm-user/Uploads
+ rm -rf /home/kasm-user/.config/pulse


------------------ EXECUTE COMMAND ------------------
+ echo -e '\n\n------------------ EXECUTE COMMAND ------------------'
+ echo 'Executing command: '\''/dockerstartup/vnc_startup.sh' /dockerstartup/kasm_startup.sh '--wait'\'''
+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
Executing command: '/dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait'
Generating a RSA private key
...........+++++
................+++++
writing new private key to '/home/kasm-user/.vnc/self.pem'
-----
2024-05-09T07:52:21Z DEBUG (vnc_startup.sh): Starting KasmVNC
Creating default config /home/kasm-user/.vnc/kasmvnc.yaml
xauth:  file /home/kasm-user/.Xauthority does not exist

New '47cc5bc102e0:1 (kasm-user)' desktop is 47cc5bc102e0:1

Users configured:
kasm_user (can use keyboard and mouse, add/remove users)
kasm_viewer (can only view)

Log file is /home/kasm-user/.vnc/47cc5bc102e0:1.log

Starting applications specified in /home/kasm-user/.vnc/xstartup

Paste this url in your browser:
https://172.19.0.11:6901
Disabling X Screensaver Functionality
server does not have extension for -dpms option
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000000
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  660    repeat rate:  25
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  2/1    threshold:  4
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  600
Colors:
  default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11//misc,/usr/share/fonts/X11//Type1,built-ins
DPMS (Energy Star):
  Server does not have the DPMS Extension
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Starting Window Manager
Starting XFCE
/usr/bin/startxfce4: X server already running on display :1
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Starting audio websocket server
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Starting audio server
Starting Pulse
Starting audio service

------------------ Started Audio Out  ----------------------------
Kasm Audio Out PID: 130
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Starting audio input server
Listening for incomming MPEG-TS Stream on https://127.0.0.1:8081/<secret>
Awaiting WebSocket connections on wss://127.0.0.1:4901/
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Starting upload server


------------------ KasmVNC environment started ------------------
 2024-05-09 09:52:22,601 [DEBUG] VNCServerST: creating single-threaded server 47cc5bc102e0:1 (kasm-user)
 2024-05-09 09:52:22,601 [INFO] VNCServerST: CPU capability: SSE2 yes, AVX512f no
 2024-05-09 09:52:22,601 [PRIO] VNCServerST: Failed to init inotify
 2024-05-09 09:52:22,601 [PRIO] VNCServerST: Failed to set watch
 2024-05-09 09:52:22,601 [INFO] vncext: created VNC server for screen 0
 2024-05-09 09:52:22,623 [DEBUG] WebUdp: UDP listening on port 6901
 2024-05-09 09:52:22,628 [INFO] Input: Mouse horizonatl scroll factor: 50.000000
 2024-05-09 09:52:22,628 [INFO] Input: Mouse vertical scroll factor: 50.000000
Running /home/kasm-user/.vnc/xstartup
 2024-05-09 09:52:22,752 [DEBUG] Selection: Selection owner change for _DBUS_SESSION_BUS_SELECTION_kasm-user_e51a0ae43cbf40c2810d2719376325c4
2024-05-09T07:52:22Z INFO (vnc_startup.sh): Kasm User () started container id 47cc5bc102e0 with local IP address 172.19.0.11
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
failed to load driver: zink
2024-05-09T07:52:22Z DEBUG (vnc_startup.sh): Executed custom startup script.
+ START_COMMAND=remmina
+ PGREP=remmina
+ DEFAULT_ARGS=
+ export MAXIMIZE=false
+ MAXIMIZE=false
+ MAXIMIZE_SCRIPT=/dockerstartup/maximize_window.sh
+ ARGS=
++ getopt -o gau: -l go,assign,url: -n /dockerstartup/custom_startup.sh --
+ options=' --'
+ eval set -- ' --'
++ set -- --
+ [[ -- != -- ]]
+ shift
+ FORCE=
+ '[' -n '' ']'
+ '[' -n '' ']'
+ kasm_startup
+ '[' -n '' ']'
+ '[' -z '' ']'
+ URL=
+ '[' -z '' ']'
+ echo 'Entering process startup loop'
+ set +x
Entering process startup loop
filter is not configured
remmina-Message: 09:52:22.865: Remmina does not log all output statements. Turn on more verbose output by using "G_MESSAGES_DEBUG=remmina" as an environment variable.
More info available on the Remmina wiki at:
https://gitlab.com/Remmina/Remmina/-/wikis/Usage/Remmina-debugging
_IceTransmkdir: ERROR: euid != 0,directory /tmp/.ICE-unix will not be created.
gpg-agent[189]: WARNING: "--write-env-file" is an obsolete option - it has no effect
gpg-agent[189]: directory '/home/kasm-user/.gnupg' created
gpg-agent[189]: directory '/home/kasm-user/.gnupg/private-keys-v1.d' created
gpg-agent[190]: gpg-agent (GnuPG) 2.2.19 started
gpg-agent[190]: error enabling daemon termination by socket removal: Too many open files

(xfce4-session:96): xfce4-session-WARNING **: 09:52:22.884: gpg-agent returned no PID in the variables
gpg-agent[190]: error enabling daemon termination by homedir removal: Too many open files

(xfce4-session:96): xfce4-session-WARNING **: 09:52:22.885: xfsm_manager_load_session: Something wrong with /home/kasm-user/.cache/sessions/xfce4-session-47cc5bc102e0:1, Does it exist? Permissions issue?
[glibsecret] unable to get secret service: Error calling StartServiceByName for org.freedesktop.secrets: Failed to execute program org.freedesktop.secrets: Operation not permitted

(org.remmina.Remmina:158): GLib-CRITICAL **: 09:52:22.919: g_ascii_strdown: assertion 'str != NULL' failed

(org.remmina.Remmina:158): GLib-CRITICAL **: 09:52:22.920: g_strrstr: assertion 'haystack != NULL' failed

(org.remmina.Remmina:158): GLib-CRITICAL **: 09:52:22.920: g_strrstr: assertion 'haystack != NULL' failed

(org.remmina.Remmina:158): GLib-CRITICAL **: 09:52:22.920: g_strrstr: assertion 'haystack != NULL' failed

(org.remmina.Remmina:158): GLib-CRITICAL **: 09:52:22.920: g_strrstr: assertion 'haystack != NULL' failed
Warning: Remmina is running without a secret plugin. Passwords will be saved in a less secure way.

(xfce4-session:96): xfce4-session-WARNING **: 09:52:23.146: Unable to launch "xfce4-panel": Failed to execute child process “xfce4-panel” (No such file or directory)

(xfsettingsd:212): libupower-glib-WARNING **: 09:52:23.154: Couldn't connect to proxy: Could not connect: No such file or directory

(xfsettingsd:212): libupower-glib-CRITICAL **: 09:52:23.155: up_client_get_lid_is_closed: assertion 'UP_IS_CLIENT (client)' failed

(xfsettingsd:212): GLib-GObject-WARNING **: 09:52:23.155: invalid (NULL) pointer instance

(xfsettingsd:212): GLib-GObject-CRITICAL **: 09:52:23.155: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Failed to unload module: Module module-pipe-source not loaded

(org.remmina.Remmina:158): Gtk-WARNING **: 09:52:23.229: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
 * Serving Flask app 'kasm_upload_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:4902
 * Running on https://172.19.0.11:4902
Press CTRL+C to quit
 2024-05-09 09:52:23,118 [DEBUG] Selection: Selection owner change for WM_S0
 2024-05-09 09:52:23,133 [DEBUG] Selection: Selection owner change for XFWM4_COMPOSITING_MANAGER
 2024-05-09 09:52:23,153 [DEBUG] Selection: Selection owner change for _XSETTINGS_S0
 2024-05-09 09:52:23,198 [DEBUG] Selection: Selection owner change for CLIPBOARD_MANAGER
Stream Connected: ::ffff:127.0.0.1:37682

(xfdesktop:264): GLib-GObject-WARNING **: 09:52:31.269: invalid (NULL) pointer instance

(xfdesktop:264): GLib-GObject-CRITICAL **: 09:52:31.269: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

** (xfdesktop:264): WARNING **: 09:52:31.269: Failed to get system bus: Could not connect: No such file or directory
 2024-05-09 09:52:31,265 [DEBUG] Selection: Selection owner change for XFDESKTOP_SELECTION_0
 2024-05-09 09:52:31,265 [DEBUG] Selection: Selection owner change for _NET_DESKTOP_MANAGER_S0

** (xiccd:289): CRITICAL **: 09:52:39.157: Failed to connect to colord: Could not connect: No such file or directory

(nm-applet:293): nm-applet-WARNING **: 09:52:39.200: Error connecting to system D-Bus: Could not connect: No such file or directory

(nm-applet:293): nm-applet-WARNING **: 09:52:39.200: Could not connect: No such file or directory

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:3905)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:3859)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:3937)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:3986)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:4026)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:4042)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:4080)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.201: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed

(nm-applet:293): libnm-CRITICAL **: 09:52:39.202: ((libnm/nm-client.c:4598)): assertion '<dropped>' failed
system-config-printer-applet: failed to connect to system D-Bus
 2024-05-09 09:52:43,305 [INFO] websocket 0: got client connection from 172.19.0.9
 2024-05-09 09:52:43,308 [DEBUG] websocket 0: using SSL socket
 2024-05-09 09:52:43,308 [DEBUG] websocket 0: X-Forwarded-For ip '172.19.0.5'
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: BasicAuth matched
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: Invalid WS request, maybe a HTTP one
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: HTTP request under /api/
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: Requested owner api '/api/get_screenshot' with args 'width=1000&height=1000'
 2024-05-09 09:52:43,310 [PRIO] GetAPIMessager: Screenshot requested but no screenshot exists (screen hasn't been viewed)
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: Invalid params to screenshot
 2024-05-09 09:52:43,310 [INFO] websocket 0: 172.19.0.9 172.19.0.5 kasm_user "GET /api/get_screenshot?width=1000&height=1000 HTTP/1.1" 400 194
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: No connection after handshake
 2024-05-09 09:52:43,310 [DEBUG] websocket 0: handler exit

**Comment by j-travis** [comment]
`gpg-agent[190]: error enabling daemon termination by homedir removal: Too many open files`

Its likely the same problem. 

Try adjusting those OS settings or move Kasm to a new host

**Comment by brommeltje** [comment]
Moving to another host worked
