### ISSUE TITLE
Windows CE

### ISSUE THREAD

**Issue by NXGF-43** [kasmtech/workspaces-issues#553]
Hello, i apologize but i need an information:
to install Windows Service and PWA on Android and IOS i need a Kasm desktop installation before. But i can install it if the only Server installation (fixed or auto-scaled), are based on Linux? Windows Service is only a supply. I need Windows CE. If i use Azure, anyway i need a precedent installation before. Last question: can i use WLS instead of Azure?
Thank you.

**Comment by j-travis** [comment]
Kasm Workspaces is a platform that installs on linux system.
See here:
- https://kasmweb.com/docs/latest/index.html
- https://www.youtube.com/watch?v=BYJ0M04cD18

After it is installed, you can configure the platform to launch container based sessions, or connect to existing virtual machines / hardware like Windows systems over RDP
- https://www.youtube.com/watch?v=_WCee4-E4vA
- https://kasmweb.com/docs/latest/how_to/fixed_infrastructure.html
- https://www.youtube.com/watch?v=JkYF20Kq4G8
- https://kasmweb.com/docs/latest/guide/windows.html#windows


WSL is not supported

**Comment by NXGF-43** [comment]
Ok. Thank you. Last question please: so Kasm Windows Service can be used only on Windows Virtual Machines? Is there someone better than the other i can use? But why in the YouTube video they use Azure on a Mac computer? And which are the best RDP methods?
I apologize.
