### ISSUE TITLE
Kasm only half loads when using reverse-proxy URL

### ISSUE THREAD

**Issue by ZuluPilgrim** [kasmtech/workspaces-issues#558]
When I browse directly to the local IP, everything works as expected.

When I try going through the url which is redirect to the IP using Nginx Reverse Proxy Manager, I can log on but when I click on my resource i.e. try open Brave, I get stuck at the following screen.

![image](https://github.com/kasmtech/workspaces-issues/assets/111164245/fec55e40-45ee-4b2a-b7c5-b1e58aa0bffc)

I am not sure how to troubleshoot or what could be causing this.

I installed using https://kasmweb.com/docs/latest/install/single_server_install.html

**Comment by j-travis** [comment]
Make sure your reverse proxy supports websockets. 

Aside from that here is a connectivity troubleshooting guide: https://kasmweb.com/docs/latest/guide/troubleshooting/advanced_connection_troubleshooting.html

**Comment by ZuluPilgrim** [comment]
Thanks @j-travis, that was it I had not enabled websockets.

All good now :)

![image](https://github.com/kasmtech/workspaces-issues/assets/111164245/96a95004-809f-4f09-bb6a-0f25b4d9e47b)
