### ISSUE TITLE
Copying and Pasting Text and Images

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#57]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/57) by Shay Duek (Bitbucket: [Shay Duek](https://bitbucket.org/Shay Duek), ).**

----------------------------------------

Hello,

I am not sure whether this is possible or not at the moment, but I thought I would ask.

Copying and Pasting from the Remote to Kasm work BUT Copying and Pasting Images dont !!!

for example:  
open whatsapp web or slack on KASM and paste the Photo directly on it.

Any help would be greatly appreciated.

Duek

**Comment by mmcclaskey** [comment]
Binary clipboard was added to Kasm Workspaces as of 1.10.0. You must use a Chromium based browser, such as Chrome, Chromium, Edge, Brave, etc. Chromium is the browser type that fully implements the clipboard API to allow for this feature to work.
