### ISSUE TITLE
[Bug] - Kasm Workspaces does not work behind a web proxy when set proxy variables

### ISSUE THREAD

**Issue by ldklikm** [kasmtech/workspaces-issues#573]
**Describe the bug**
I am not able to run Kasm behind a web proxy. 

If I set the proxy variables in ~/.docker/config.json or /etc/docker/config.json, then all kasm_* Docker containers constantly restart after one minute. The logs show that the proxy (kasm_proxy) is not accessible.

If I now deactivate the proxy variables, Kasm Workspace starts and I can log in via admin@kasm.local but I cannot install Docker images or add registry. I then tried to solve it via /opt/kasm/current/docker/docker-compose.yaml. In the /opt/kasm/current/docker/docker-compose.yaml I added the following in the kasm_api section:

    environment:
      - HTTP_PROXY=http://xxx.xxx.xxx.xxx:3128
      - HTTPS_PROXY=http://xxx.xxx.xxx.xxx:3128
      - http_proxy=http://xxx.xxx.xxx.xxx:3128
      - https_proxy=http://xxx.xxx.xxx.xxx:3128
      - NO_PROXY=proxy
      - no_proxy=proxy

With these options I can install Docker images and add registry but now the Docker container kasm_api restarts every 60 seconds.

**Workspaces Version**
Version 1.15.0.06fdc8

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Windows 11, Kubuntu 22.04 LTS
 - Browser: Google Chrome
 - Version 126.0.6478.55

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
> Linux sv90016 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
 - `cat /etc/os-release`
> PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
 - `sudo docker info`
> Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
Server:
 Containers: 10
  Running: 9
  Paused: 0
  Stopped: 1
 Images: 18
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-112-generic
 Operating System: Ubuntu 22.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.751GiB
 Name: sv90016
 ID: 6c9bd1c6-717d-44d9-aab0-d4c82c61bf52
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://xxx.xxx.xxx.xxx:3128
 HTTPS Proxy: http://xxx.xxx.xxx.xxx:3128
 No Proxy: localhost,127.0.0.1,.xxx-xxxxx.de,proxy,sv90016
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false 
 - `sudo docker ps | grep kasm`
> 8210f1219928   kasmweb/nginx:1.25.3            "/docker-entrypoint.…"   42 hours ago   Up 42 hours               80/tcp, 0.0.0.0:443-443/tcp                 kasm_proxy
b412676d6169   kasmweb/api:1.15.0              "/bin/sh -c '/usr/bi…"   42 hours ago   Up 42 hours (healthy)     8080/tcp                                     kasm_api
c4aed577ca85   kasmweb/agent:1.15.0            "/bin/sh -c '/usr/bi…"   2 days ago     Up 42 hours (healthy)     4444/tcp                                     kasm_agent
a3b5166b003c   kasmweb/share:1.15.0            "/bin/sh -c '/usr/bi…"   2 days ago     Up 42 hours (healthy)     8182/tcp                                     kasm_share
e15d101d7049   kasmweb/manager:1.15.0          "/bin/sh -c '/usr/bi…"   2 days ago     Up 42 hours (healthy)     8181/tcp                                     kasm_manager
581b137c8572   postgres:12-alpine              "docker-entrypoint.s…"   2 days ago     Up 42 hours (healthy)     5432/tcp                                     kasm_db
794d4e32611f   kasmweb/kasm-guac:1.15.0        "/dockerentrypoint.sh"   2 days ago     Up 42 hours (unhealthy)                                                kasm_guac
1bbcb25fc09d   redis:5-alpine                  "docker-entrypoint.s…"   2 days ago     Up 42 hours               6379/tcp                                     kasm_redis

**Comment by j-travis** [comment]
Can you see if these instructions work for you: https://kasmweb.atlassian.net/servicedesk/customer/kb/view/3047638

**Comment by ldklikm** [comment]
Thank you very much, that's the solution. I didn't know that page yet. Sorry for the wrong bug report.
