### ISSUE TITLE
[Bug] - Brave browser "-rolling" release over a month old

### ISSUE THREAD

**Issue by Taomyn** [kasmtech/workspaces-issues#574]
**Describe the bug**
First time installation of Kasm for testing and successfully installed. Downloaded first workspace, Brave browser, but saw it was incredibly out of date. After some research saw that there is a "-rolling" release which should be a nightly build, tried that and it's still out of date by a month.

**To Reproduce**
1. Install Kasm
2. Install Brave workspace
3. Help, About

**Expected behavior**
At least the very latest "release" from Brave

**Screenshots**
![image](https://github.com/kasmtech/workspaces-issues/assets/4365929/d8b4ff94-b304-4d03-871d-ce6569e89762)

![image](https://github.com/kasmtech/workspaces-issues/assets/4365929/4b7cdafd-0ac6-4955-a352-c65c88012540)

![image](https://github.com/kasmtech/workspaces-issues/assets/4365929/efdcafbb-96ed-48ba-b09b-ddae8361eb7d)

**Workspaces Version**
Version 1.15

**Workspaces Installation Method**
Single Server, Debian 12

**Additional context**

**Comment by j-travis** [comment]
Thank you for reporting. 
This should be corrected now

**Comment by Taomyn** [comment]
@j-travis hello, this has happened again, only now with 1.16.0-rolling-daily, in fact any 1.16.0 tag
