### ISSUE TITLE
[Question] - Is it possible to map storage provider to browser

### ISSUE THREAD

**Issue by dshortppe** [kasmtech/workspaces-issues#577]
We are looking to map some SMB/NFS shares to a browser for our users so that they can work with files on our network shares. I can get the storage to map for everything **BUT** browser containers.

**Comment by j-travis** [comment]
You will need to disable the restricted file chooser. This module is only enabled by default on browser based container images. 
See here: https://kasmweb.com/docs/latest/guide/storage_mappings.html#id3

**Comment by dshortppe** [comment]
That's exactly what I was looking for. Thank you so much!


[cid:321bf3dc-7d6c-4d0c-b1b7-6b2aafebeff1]

Dan Short

Manager, Information Technology



Physicians’ Practice Enhancement, LLC

66 West Gilbert Street, Suite 100

Red Bank, NJ 07701

E: ***@***.***

T: 732-515-4551

***@***.***?anonymous&ep=signature>               Book time to meet with ***@***.***?anonymous&ep=signature>
________________________________
