### ISSUE TITLE
[Bug?] - OIDC login not working (error: non OIDC user) -> change user realm? how?

### ISSUE THREAD

**Issue by gitwittidbit** [kasmtech/workspaces-issues#587]
**Describe the bug**
This may or may not be a bug. Could also be attributable to my incompetence...
I can't login with SSO for an existing user.
Authentication via Keycloak seems to work but upon redirection, I get an error message that the user is a non OIDC user.
While I can't find anything on this particular error, I am suspecting that it has to do with the user's realm "local".
But I can't seem to find a way to change this to "OIDC".

**To Reproduce**
1. Create a local user in KASM
2. Set up Keycloak OIDC
3. Authenticate to KASM via Keycloak as this local user
4. See error message
5. Try to find a way to change user realm to OIDC

**Expected behavior**
Either login should work immediately or there should be a way to change the user realm (if this is what is causing my error)

**Screenshots**

**Workspaces Version**
e.g Version 1.15

**Workspaces Installation Method**
e.g Linuxserver docker compose

**Client Browser (please complete the following information):**
 - OS: MacOS 13.6.6
 - Browser [Firefox
 - Version 127

Does anyone know how to change the realm?
Or do I have to remove the user and create it again as an "OIDC" user?

Thanks!

**Comment by j-travis** [comment]
You need to remove the user  and allow it to be re-created again when the user logs in via OIDC
