### ISSUE TITLE
[Bug] - Using the Example for custom image using the core image fails

### ISSUE THREAD

**Issue by stijndhondt** [kasmtech/workspaces-issues#588]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
When trying to create a custom image from an core ubuntu image. build process failed with root user not found exception

**To Reproduce**
1. Windows 10 pc
2. Create a docker file
3. Copy the example from installing software
4. Wait a bit until it comes to the 'run wget ' step and 
5. See error: unable to find user root: no matching entries in passwd file

**Expected behavior**
To have an image as described in the manual

**Screenshots**

**Workspaces Version**
1.15

**Workspaces Installation Method**
Single Server, 

**Client Browser (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 126.0.6478.127

**Workspace Server Information (please provide the output of the following commands):**
 - RUN wget
 - RUN bash

**Additional context**
I also tried to rebuild the vscode one from the repo same issue. It just complained about the bash command with the same error.

**Comment by j-travis** [comment]
Hi, 
We don't really support building or running the containers on Windows machines. Recommend you try and build from a linux machine. (e.g Ubuntu 24.04 LTS)
