### ISSUE TITLE
Pulling usage reports

### ISSUE THREAD

**Issue by sdcoil** [kasmtech/workspaces-issues#589]
I'm evaluating serving a custom Kasm workspace to a small number of users at my university and need to pull usage reports (who used a session, what session, when it was created, when it was destroyed, etc.).

The "Reporting and Logging" section of the docs don't delve deeply into the subject.

I've been digging through the log files and writing some bash and python scripts to pull the data. Before I go much farther, has someone else created scripts for this or does anyone have some insight?

**Comment by j-travis** [comment]
If you are using Kasm Workspace 1.15 there is the Sessions-> History page that includes all the data you are looking for.

You could pull this via the get_session_history API if you wanted. 

Please review the following:
- https://kasmweb.com/docs/latest/developers/developer_api.html
- https://kasmweb.atlassian.net/servicedesk/customer/kb/view/10682377

**Comment by sdcoil** [comment]
Thank you!
