### ISSUE TITLE
Need help how to link to internal servers

### ISSUE THREAD

**Issue by brettthomson** [kasmtech/workspaces-issues#590]
I have just installed kasm and have it working through my reverse proxy with all the inbuilt applications.

I have some internal web pages and and the like. Which when on the home network everyone in the house would access using http://192.168.1.20:1234 or http://192.168.1.20:1235 etc etc. 

If I setup a workspace with a link it works perfectly internally as you would expect, but when outside of the house and accessing the workspace link via the reverse proxy it doesn't work as you would expect.

How would I set this scenario up in kasm.

Thanks for the help in advance.

**Comment by j-travis** [comment]
Hi,
The "link" type workspace just opens up a new tab to the link you provided. Its not actually proxied through Kasm etc.

What you are looking for is something like this: https://kasmweb.com/docs/latest/how_to/protected_web_apps.html#protected-web-apps

Basically create a chrome container based workspace that launches your internal web apps

**Comment by brettthomson** [comment]
Amazing, thank you for that. I will give it a go.
