### ISSUE TITLE
Multiple users for using one browser instance issue

### ISSUE THREAD

**Issue by abdilea** [kasmtech/workspaces-issues#594]
I am new to kasm and run into issues when more than two users try and use same docker container(browser instance). I am getting this error message 

"No resources are available to create the requested Kasm. Please try again later or contact an Administrator : No Agent slots available. No Agent can be contacted with enough available resources to provision the image" 

I have seen suggestions to edit CPU and RAM override but this didn't help 

Is it possible for multiple users to access the same browser instance simultaneously using different accounts? up to two users seem to be fine but 3rd user gets the above error. 

Any help would be greatly appreciated.

**Comment by abdilea** [comment]
Just to add docker agent usage looks like this 
Core Utilization: 8.4%
Core Allocation: 100% (4 of 4 Cores)
Memory Utilization: 20.4%
Memory Allocation: 37% (5.16 GB of 14.00 GB)
Disk Usage: 36.9%

It looks like each session(per user) is getting 2 cores

**Comment by j-travis** [comment]
This should help you understand how the system works: https://kasmweb.com/docs/latest/guide/troubleshooting/no_resources_available.html

**Comment by abdilea** [comment]
Thanks j-travis, this is KB I used to configure the override of the CPU and RAM which I think is not working at less I am doing something wrong. At the moment, I have 2 browser instances one with 1 CPU and one with 2 CPU and I have two sessions running right now. Based on this for 10 concurrent sessions I will need 10 cores is that right?

Core Utilization: 30.5%
Core Allocation: 75% (3 of 4 Cores)
Memory Utilization: 18.7%
Memory Allocation: 37% (5.16 GB of 14.00 GB)
Disk Usage: 37%

**Comment by j-travis** [comment]
Yes
