### ISSUE TITLE
[Bug] - No browser access within vscode image prevents login for sync

### ISSUE THREAD

**Issue by bencmeyer** [kasmtech/workspaces-issues#595]
### Existing Resources

- [ X ] Please search the existing issues for related problems
- [ X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
Attempting to sign in to Visual Studio Code workspace returns a "Failed to execute default Web Browser." Making it impossible to sign in for syncing.

**To Reproduce**
1. Launch Visual Studio Code workspace
2. Click on settings, then Backup and Sync Settings...
3. Choose either Sign in with GitHub or Sign in with Microsoft, both return same error.

**Expected behavior**
A browser window should open allowing to sign in with credentials.

**Screenshots**
![image](https://github.com/user-attachments/assets/e5c3d4d0-4187-4610-8699-e7f607b17fa8)

**Workspaces Version**
1.15.0.577587

**Workspaces Installation Method**
Single Server, unRAID Docker
lscr.io/linuxserver/kasm

**Client Browser (please complete the following information):**
 - OS: Windows 11 v23H2 (10.0.22631) 
 - Browser: Edge 
 - Version: 127.0.2651.74 (Official build) (64-bit)

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
```shell
Linux c4b45ab26a1a 6.1.74-Unraid #1 SMP PREEMPT_DYNAMIC Fri Feb  2 11:06:32 PST 2024 x86_64 x86_64 x86_64 GNU/Linux
```
 - `cat /etc/os-release`
```shell
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
``` 
 - `sudo docker info`
```shell
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.74-Unraid
 Operating System: Ubuntu 22.04.4 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 27.47GiB
 Name: c4b45ab26a1a
 ID: 73736c88-6555-4ed9-9307-b87fc6381a7d
 Docker Root Dir: /opt/docker
 Debug Mode: false
 Username: bencmeyer
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
 - `sudo docker ps | grep kasm`
```shell
ff2c4e2bb837   kasmweb/vs-code:1.15.0     "/dockerstartup/kasm…"   7 minutes ago   Up 7 minutes           4901/tcp, 5901/tcp, 6901/tcp     adminkasm.lo_1c2036fb
f8d87216973f   kasmweb/nginx:1.25.3       "/docker-entrypoint.…"   43 hours ago    Up 5 hours             80/tcp, 0.0.0.0:6333->6333/tcp   kasm_proxy
1c6ca6afbb80   kasmweb/share:1.15.0       "/bin/sh -c '/usr/bi…"   43 hours ago    Up 5 hours (healthy)   8182/tcp                         kasm_share
d695bc4fbf6a   kasmweb/agent:1.15.0       "/bin/sh -c '/usr/bi…"   43 hours ago    Up 5 hours (healthy)   4444/tcp                         kasm_agent
b62d21cdb7c1   kasmweb/manager:1.15.0     "/bin/sh -c '/usr/bi…"   43 hours ago    Up 5 hours (healthy)   8181/tcp                         kasm_manager
02798675baac   kasmweb/api:1.15.0         "/bin/sh -c '/usr/bi…"   43 hours ago    Up 5 hours (healthy)   8080/tcp                         kasm_api
6f2c67f6bc8a   redis:5-alpine             "docker-entrypoint.s…"   43 hours ago    Up 5 hours             6379/tcp                         kasm_redis
a7113da0a196   kasmweb/kasm-guac:1.15.0   "/dockerentrypoint.sh"   43 hours ago    Up 5 hours (healthy)                                    kasm_guac
70acda288c25   postgres:12-alpine         "docker-entrypoint.s…"   44 hours ago    Up 5 hours (healthy)   5432/tcp                         kasm_db
```

**Comment by lindi200000** [comment]
I have the same problem, any solution?

**Comment by j-travis** [comment]
In all cases you are free to build a custom image with the software and configurations as you wish. You do not need to wait on updates from our team.

- https://kasmweb.com/docs/latest/how_to/building_images.html

An updated version of this image has been pushed to the `develop` tag with chrome pre-installed if you'd like to try it out

`kasmweb/vs-code:develop`
