### ISSUE TITLE
[Feature Request] - Ability to configure the workspace persistent profiles using an API or deployment configuration

### ISSUE THREAD

**Issue by varunrai** [kasmtech/workspaces-issues#596]
### Existing Resources

- [X] Please search the existing issues for related items
- [X] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [X] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [X] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [X] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Is your feature request related to a problem? Please describe.**
To automate the deployment/setup of kasm workspaces, it is frustrating to go to each workspace and setting the persistent profile location. 

**Describe the solution you'd like**
Looking for the ability to download the workspaces and setting the persistent profiles using automation/scripting instead of manually setting them through the UI. Either the ability to set for each workspace or global setting that can automatically be inherited by the workspaces.

**Comment by j-travis** [comment]
For automating deployment configuration , you can define the entire configuration as YAML, which allows you to version control the configuration of the initial deployment.

https://kasmweb.com/docs/develop/guide/import_export/slipstream_install.html

Second , we have a developer API https://kasmweb.com/docs/develop/developers/developer_api.html
While not every API is documented here, basically anything  you can do via the UI, you can do via API. Heres a guide for using any undocumented APIs.
https://kasmweb.atlassian.net/servicedesk/customer/kb/view/10682377

**Comment by j-travis** [comment]
Also as an FYI for the specific persistent profile,
Coming in 1.16 , you'll be able to configure the profile path right from the table if you add the column. This will hopefully make manual configuration a bit easier
![image](https://github.com/user-attachments/assets/c5beec60-e819-4900-b26e-700aa059ccc0)

**Comment by varunrai** [comment]
> Also as an FYI for the specific persistent profile,
> Coming in 1.16 , you'll be able to configure the profile path right from the table if you add the column. This will hopefully make manual configuration a bit easier
> ![image](https://github.com/user-attachments/assets/c5beec60-e819-4900-b26e-700aa059ccc0)
> 

This is definitely a good option but for fully automated setup I will look at the developer documentation and yaml based deployment.
