### ISSUE TITLE
[Bug] - Exec Config doesn't seem to be working

### ISSUE THREAD

**Issue by MrMEEE** [kasmtech/workspaces-issues#597]
### Existing Resources

- [ X ] Please search the existing issues for related problems
- [ X ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ X ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ X ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ X ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
I can't Exec config to launch anything..

I have create a custom image from kasmweb/core-ubuntu-focal:1.15.0.. but I can't get anything to launch with exec config:

```
{
  "first_launch": {
    "cmd": "/usr/bin/bash -c '/usr/bin/xterm'"
  },
  "go": {
    "cmd": "/usr/bin/bash -c '/usr/bin/xterm'"
  },
  "assign": {
    "cmd": "/usr/bin/bash -c '/usr/bin/xterm'"
}
``` 

I have also tried with just "xterm"... but nothing spawns.. just the background (menubar is disabled)

If I run the docker exec command on the command line, the program spawns fine...

**Comment by j-travis** [comment]
You're probably running into a race condition where xterm is trying to launch before the desktop environment is ready , thus its failing to either be visible or doesnt have a display to attach to.

Try this

```
{
  "first_launch": {
    "cmd": "/usr/bin/bash -c '/usr/bin/desktop_ready && /usr/bin/xterm'"
  }
}
```

There is a helper util `/usr/bin/desktop_ready`  that blocks until the XFCE DE is running.
