### ISSUE TITLE
[Bug] - Chrome Workspace clear text requests to google https://edgedl.me.gvt1.com

### ISSUE THREAD

**Issue by c0decave** [kasmtech/workspaces-issues#600]
### Existing Resources

**Describe the bug**
Starting a Chrome Browser instance, shortly after usage the browser is connecting in clear text to google ip and downloads several extensions. The host seems to be legit, but the connection should be done with https, no? Or is this necessary bootstrap behavior at a clean chrome?
 
**To Reproduce**
1. Login to KASM Community
2. Workspaces, Run Chrome
3. Start tcpdump/wireshark
4. See connections and downloads in clear text to specified host

**Expected behavior**
If those downloads are legit and necessary for running chrome, using verified https instead.

**Screenshots**
![image](https://github.com/user-attachments/assets/e2c2ebd9-06ca-4d34-9c95-33641ee471cf)

**Workspaces Version**
Version API Server Build 1.15.0.06fdc8

**Workspaces Installation Method**
Single Server

**Client Browser (please complete the following information):**
 - OS: Unix
 - Browser Chrome
 - Version 127

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
  - `Linux kasm 6.8.0-39-generic #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux` 
 - `cat /etc/os-release`
```cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo```
 - `sudo docker info`
 ```Client:                                                                         
 Version:    24.0.7                                                             
 Context:    default                                                            
 Debug Mode: false                                                              
 Plugins:                                                                       
  compose: Docker Compose (Docker Inc.)                                         
    Version:  2.24.6+ds1-0ubuntu2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
```
 - `sudo docker ps | grep kasm`
 ``` bf9553c9d275   kasmweb/nginx:1.25.3       "/docker-entrypoint.…"   4 days ago   Up 2 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
331b6d5a5ef1   kasmweb/share:1.15.0       "/bin/sh -c '/usr/bi…"   4 days ago   Up 2 hours (healthy)   8182/tcp                                        kasm_share
e3addc9be03d   kasmweb/agent:1.15.0       "/bin/sh -c '/usr/bi…"   4 days ago   Up 2 hours (healthy)   4444/tcp                                        kasm_agent
55339491293d   kasmweb/api:1.15.0         "/bin/sh -c '/usr/bi…"   4 days ago   Up 2 hours (healthy)   8080/tcp                                        kasm_api
e382666a4d98   kasmweb/manager:1.15.0     "/bin/sh -c '/usr/bi…"   4 days ago   Up 2 hours (healthy)   8181/tcp                                        kasm_manager
e871736c788b   redis:5-alpine             "docker-entrypoint.s…"   4 days ago   Up 2 hours             6379/tcp                                        kasm_redis
f5f82dd5b4d0   kasmweb/kasm-guac:1.15.0   "/dockerentrypoint.sh"   4 days ago   Up 2 hours (healthy)                                                   kasm_guac
cd0c9f59228f   postgres:12-alpine         "docker-entrypoint.s…"   4 days ago   Up 2 hours (healthy)   5432/tcp                                        kasm_db
```

**Comment by j-travis** [comment]
We use stock chrome with only a few minor configuration mods for compatibility.  You can see them here:

- https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-chrome
- https://github.com/kasmtech/workspaces-images/blob/develop/src/ubuntu/install/chrome/install_chrome.sh

We don't preload any extensions by default so this behavior is coming from chrome itself.
