### ISSUE TITLE
[Bug] - lscr.io/linuxserver/kasm image not working

### ISSUE THREAD

**Issue by jsanchezm87** [kasmtech/workspaces-issues#606]
I'm triying to start a kasm server from a lscr.io/linuxserver/kasm container but at this moment /version didn't work,...

Some time ago i did it succesfully, i supose wass with other version of the container,...

Runing this docker command, the container is started but i can't acces to 3000 or 443 port, the container close the comunication or didnt send any data,...

> docker run -d \
>   --name=kasm \
>   --privileged \
>   -e KASM_PORT=443 \
>   -e DOCKER_HUB_USERNAME=USER `#optional` \
>   -e DOCKER_HUB_PASSWORD=PASS `#optional` \
>   -e DOCKER_MTU=1500 `#optional` \
>   -p 3000:3000 \
>   -p 443:443 \
>   -v /path/to/data:/opt \
>   -v /path/to/profiles:/profiles `#optional` \
>   -v /dev/input:/dev/input `#optional` \
>   -v /run/udev/data:/run/udev/data `#optional` \
>   --restart unless-stopped \
>   lscr.io/linuxserver/kasm:latest

Please, i need start kasm using this way to run it on a Nomad cluster,...

Can anybody tell me,...

How to start it?
What's happened in this new version?
There is other Kasm images to use like this-one?

I wait for your response, thanks and kind regards, 
Javier.

**Comment by j-travis** [comment]
Hi, This project is not maintained by us but instead by the folks at linuxserver.io . You'll want to ask this question to them
