### ISSUE TITLE
How to store a Firefox Session on kasmweb cloud browswer

### ISSUE THREAD

**Issue by josephbenfeld** [kasmtech/workspaces-issues#607]
Every time I log out from my account , my Firefox session expires aftre 20  minutes. Is there an option to save it and relaunch it when I log in again?

**Comment by j-travis** [comment]
Hi,
Persistance is not offered on the Kasm Cloud Personal (https://kasmweb.com/cloud-personal) offering at this time.

However, if you install Kasm Workspaces in your environment (to include the free community edition), or we host a business SaaS offering for your team there are several mechanisms for persistence including persistent profiles which is likely what will work for you in this situation .

- https://kasmweb.com/docs/latest/guide/persistent_data.html
- https://kasmweb.com/community-edition
