### ISSUE TITLE
[Bug] - Persistent Profiles are not remembered when using PWAS

### ISSUE THREAD

**Issue by bruman** [kasmtech/workspaces-issues#632]
### Existing Resources

- [ ] Please search the existing issues for related problems
- [ ] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [ ] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [ ] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [ ] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
After installing 1.16.174001 i tried creating some PWA using chrome on a mac. I initially created the app by starting a container, say slack trough the UI then

**To Reproduce**
1. Start an application say slack from the webui with persistent profiles enabled
2. Create a PWA using the menu in control pannel 
3. close the window in the browser and start the app, you get connected to the session with the persistent profile
4. delete the session, then open a new 'slack' session using the PWA button, and it creates a new session without a persistent profile, so you would have to log into slack and set up all your slack workspaces again. 

**Expected behavior**
When you click on a PWA if should have remembered that it has a persistent profile and use that. 

**Screenshots**
N/A

**Workspaces Version**
1.16.174001

**Workspaces Installation Method**
Single Server 

**Client Browser (please complete the following information):**
 - OS: macos 14
 - Browser chrome
 - Version 129

**Workspace Server Information (please provide the output of the following commands):**
N/A

**Additional context**
N/A

**Comment by j-travis** [comment]
Thank you for reporting

**Comment by j-travis** [comment]
This is fixed in the developer preview builds. It will be available in 1.16.1 which will be out in a few days
