### ISSUE TITLE
[Bug] - KASM containers ignore the hosts file and request the machine's own host name from the DNS Server

### ISSUE THREAD

**Issue by hox-hub** [kasmtech/workspaces-issues#649]
### Existing Resources

- [x] Please search the existing issues for related problems
- [x] Consult the product documentation : [Docs](https://kasmweb.com/docs/latest/index.html)
- [x] Consult the FAQ : [FAQ](https://kasmweb.com/docs/latest/FAQ.html)
- [x] Consult the Troubleshooting Guide : [Guide](https://kasmweb.com/docs/latest/guide/troubleshooting.html)
- [x] Reviewed existing training videos: [Youtube](https://www.youtube.com/@KasmWorkspaces )

**Describe the bug**
I have noticed a DNS phenomenon that does not seem correct to me.
The KASM containers ignore the hosts file and request the machine's own host name from the DNS server.

If I do an NS lookup on the host itself, I get the response 127.0.0.1 - i.e. the entry from the hosts file (which is correct). However, while KASM is active I see a lot of requests (about one per second) to my own host. “kasm.mydomain” and ‘kasm’. Normally, these queries should be answered by the host file on the host itself and therefore not appear or arrive on my DNS server.

Is this a technical necessity or is there a problem here?

**Expected behavior**
The own host name is resolved by “/etc/hosts” and is not queried once per second at the DNS server.

**Workspaces Version**
Version 1.16

**Workspaces Installation Method**
Single Server

**Workspace Server Information (please provide the output of the following commands):**
 - `uname -a`
 Linux portal 6.1.0-25-amd64{hashtag}1  SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
----------

 - `cat /etc/os-release`
 PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
----------

 - `sudo docker info`
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.5.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 52
  Running: 10
  Paused: 0
  Stopped: 42
 Images: 26
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan kasmweb/sidecar:1.0 macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-25-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 11.68GiB
 Name: portal
 ID: 277076b5-2a46-490c-ae77-2bdf6e707d2c
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
----------

 - `sudo docker ps | grep kasm`
003220c67f42   kasmweb/proxy:1.16.0               "/docker-entrypoint.…"   5 weeks ago   Up 37 hours             80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   kasm_proxy
d2ad99b1bf63   kasmweb/rdp-https-gateway:1.16.0   "/opt/rdpgw/rdpgw"       5 weeks ago   Up 37 hours (healthy)   0.0.0.0:9443->9443/tcp, :::9443->9443/tcp       kasm_rdp_https_gateway
89e827e5aad0   kasmweb/agent:1.16.0               "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 37 hours (healthy)   4444/tcp                                        kasm_agent
45216750d9c3   kasmweb/share:1.16.0               "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 37 hours (healthy)   8182/tcp                                        kasm_share
5302737e30a6   kasmweb/rdp-gateway:1.16.0         "/start.sh"              5 weeks ago   Up 37 hours (healthy)   0.0.0.0:3389->3389/tcp, :::3389->3389/tcp       kasm_rdp_gateway
6af226d46dd7   kasmweb/kasm-guac:1.16.0           "/dockerentrypoint.sh"   5 weeks ago   Up 37 hours (healthy)                                                   kasm_guac
dd8bd910a572   kasmweb/manager:1.16.0             "/usr/bin/startup.sh…"   5 weeks ago   Up 37 hours (healthy)   8181/tcp                                        kasm_manager
5e2fe0732700   redis:5-alpine                     "docker-entrypoint.s…"   5 weeks ago   Up 37 hours             6379/tcp                                        kasm_redis
578e2192cb59   kasmweb/api:1.16.0                 "/bin/sh -c '/usr/bi…"   5 weeks ago   Up 37 hours (healthy)   8080/tcp                                        kasm_api
65e62c78fdbb   postgres:14-alpine                 "docker-entrypoint.s…"   5 weeks ago   Up 37 hours (healthy)   5432/tcp                                        kasm_db

**Comment by mmcclaskey** [comment]
Kasm is containerized and this seems like the expected behavior of containers. Entries in /etc/hosts on the host would not be relevant to containers running on the host. If you need to add host entries to containers, you would need to edit /opt/kasm/current/docker/docker-compose.yaml with extra hosts in the yaml for each container you need it on.

https://github.com/compose-spec/compose-spec/blob/main/spec.md#extra_hosts

**Comment by hox-hub** [comment]
Hello mmcclaskey,
that was a very good tip, thank you. I have entered the hostname of the machine in the Compose-YAML using the method you suggested and it seems that no more queries are arriving at the DNS.
On my own research at the time it said COntainers using the host network would also access the hosts file, so I thought it was a bug, but then it actually seems to be intentional. Well, I'll be happy when PiHole's statistics no longer show 50,000 hits per day on the hostname of my KASM VM :D 

Translated with DeepL.com (free version)

**Comment by hox-hub** [comment]
> Kasm is containerized and this seems like the expected behavior of containers. Entries in /etc/hosts on the host would not be relevant to containers running on the host. If you need to add host entries to containers, you would need to edit /opt/kasm/current/docker/docker-compose.yaml with extra hosts in the yaml for each container you need it on.
> 
> https://github.com/compose-spec/compose-spec/blob/main/spec.md#extra_hosts

Hello mmcclaskey,
that was a very good tip, thank you. I have entered the hostname of the machine in the Compose-YAML using the method you suggested and it seems that no more queries are arriving at the DNS.
On my own research at the time it said COntainers using the host network would also access the hosts file, so I thought it was a bug, but then it actually seems to be intentional. Well, I'll be happy when PiHole's statistics no longer show 50,000 hits per day on the hostname of my KASM VM :D
