### ISSUE TITLE
Persistence of application data (installed apps, docker, etc)

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#69]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/69) by reesevader NA (Bitbucket: [reesevader](https://bitbucket.org/reesevader), ).**

----------------------------------------

After running Ubuntu Desktop \(Bionic\) I found that I needed to install docker and a whole bunch of other apps, that perhaps needed a custom image, but I didn’t necessarily want to to that right out of the gate.

‌

After installing, ending the session, apps were not saved. I’d like an option to save app data for installed programs.

‌

I should also note that I couldn’t get Docker to install with: 

 apt-get update && apt install [docker.io](http://docker.io/) -y

I can’t run docker build .

Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

‌systemctl start docker - not working - dockered - I can’t start docker… 

systemctl start docker gives me an error that the system isn’t using systemd….

**Comment by j-travis** [comment]
Being that Kasm sessions are containers, by default, any changes you make inside the session will be lost when the container is destroyed.
We do support Persistent Profiles that saves the user's home directory outside of the session so things like documents, application settings etc are remembered https://kasmweb.com/docs/latest/how_to/persistent_profiles.html

We also support generic Volume Mapping in case you wanted to mount an persistent shared folder https://kasmweb.com/docs/latest/how_to/volume_mapping.html

However in both cases if you were to install an application while running a session, that program wouldnt be saved after the container is destroyed.  We recommend creating a custom image with the software you need pre-installed inside the image.  Here are some guides on doing this: 
- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://www.youtube.com/watch?v=BGP69_f1wq0


We also have a guide for allowing docker to run inside a Kasm session: https://kasmweb.com/docs/latest/how_to/docker_in_kasm.html
