### ISSUE TITLE
Docker Compose not detected in Pop_OS! 

### ISSUE THREAD

**Issue by kokomo123** [kasmtech/workspaces-issues#79]
Hello there, I'm inquiring about the install_dependencies.sh not properly detecting docker-compose while it's clearly installed in /usr/local/bin/docker-compose and it's verified to be working. It also exits out because it's unsupported though it should work. I'm running Pop_OS! 20.10 x64 and the latest version of docker-compose is 1.29.2, docker version is 20.10.8. Is there any problems that make the installer not detect docker-compose, or is it just the command inside install_dependencies.sh that isn't working in PopOS, else I may find somewhere else to install it, just wanted to try it out on this computer. Thank you!

**Comment by mmcclaskey** [comment]
Hello. If you are installing the latest release, 1.10.0, we updated to using docker-compose version 2.x, which is a proper docker plugin versus a script. Please see the documentation that covers installing Kasm on unsupported Linux distros. 

https://kasmweb.com/docs/latest/how_to/other_operating_systems.html

**Comment by kokomo123** [comment]
It seems then that's what I must do. Thank you so much! :)
