### ISSUE TITLE
Chrome image Env Vars

### ISSUE THREAD

**Issue by WarriorXK** [kasmtech/workspaces-issues#81]
Hi there,

We are currently exploring Kasm as an option to expose certain websites in our intranet to all of our customers. One of the requirements for this is to have the Chrome browser in a specific language.

I've managed to create a custom image using the `kasmweb/chrome:1.10.0` base image, but setting the LANGUAGE envvar doesn't seem to work when using the default `custom_startup.sh` script that the default images uses:
```
{
    "assign": {
        "cmd": "bash -c '/dockerstartup/custom_startup.sh --assign --url \"$KASM_URL\"'",
        "environment": {
            "LANGUAGE": "nl"
        }
    },
    "go": {
        "cmd": "bash -c '/dockerstartup/custom_startup.sh --go --url \"$KASM_URL\"'",
        "environment": {
            "LANGUAGE": "nl"
        }
    }
}
```

However, doing the following DOES work:
```
{
    "assign": {
        "cmd": "bash -c 'LANGUAGE=nl ; google-chrome --start-maximized \"$KASM_URL\"'"
    },
    "go": {
        "cmd": "bash -c 'LANGUAGE=nl ; google-chrome --start-maximized' \"$KASM_URL\""
    }
}
```

Unfortunately this causes chrome to have a top border (Which allows the user to minimize chrome, this breaks Kasm a bit) and the `$KASM_URL` env var doesn't seem to work this way.

Apologizes if this is a known issue, let me know if you need more info.

**Comment by j-travis** [comment]
Hello,
I recommend putting the language environment variable in the Docker Run Config Override section:
`{"environment":{"LANGUAGE":"nl"}}`

 and then utilize the default Docker Exec Config
 
 Let me know if that works for you.

**Comment by WarriorXK** [comment]
Thanks a lot, that works perfectly.
