### ISSUE TITLE
More Default Images fro ARM version

### ISSUE THREAD

**Issue by pcpaulh** [kasmtech/workspaces-issues#84]
Hi amazing product, I ran the x64 version and then tested the ARM version in OCI. It works perfectly! Is there any likelehood that the images that come in the x64 version will be ported over and made available for ARM too? 
Thanks

**Comment by ghost** [comment]
Good idea, to make from raspberry (8GB RAM) personal mini PC

**Comment by mmcclaskey** [comment]
It really depends on what apps are available for Arm. As more software becomes available for Arm we will update our pipelines to do multi architecture builds. For example, there is no Chrome or Brave binaries for Arm so we can’t do anything about that.

**Comment by alemens** [comment]
By imagining Kasm on Raspberry Pi would be amazing. I see @pcpaulh tried in OCI, does anyone already tried physically in a Pi on steroids?

**Comment by j-travis** [comment]
Yes you can run Kasm Workspaces on a pi4 using either raspberry pi OS (ARM64 version) or ubuntu 20.04 LTS (ARM64). I believe the raspberry pi OS ARM64 builds are still beta, but you can double check.

https://downloads.raspberrypi.org/raspios_arm64/images/

**Comment by alemens** [comment]
My headless Pi model B boot this Kali [image](https://www.kali.org/get-kali/#kali-arm) at moment @j-travis on this storage `32 GB UHS Speed Class 3 (U3) Bus Interface UHS-I`

> Yes you can run Kasm Workspaces on a pi4 using either raspberry pi OS (ARM64 version) or ubuntu 20.04 LTS (ARM64). I believe the raspberry pi OS ARM64 builds are still beta, but you can double check.
> 
> https://downloads.raspberrypi.org/raspios_arm64/images/

**Comment by j-travis** [comment]
Ok.
As an FYI, we don't have an ARM64 version of our Kali image. Just AMD64 at the moment: https://hub.docker.com/r/kasmweb/core-kali-rolling

We do have a few other images like Chromium, Ubuntu etc

**Comment by alemens** [comment]
Remaining on ARM64 if I follow [Kasm installation-guide](https://www.kasmweb.com/docs/latest/install/single_server_install.html#installation-guide) to create a swap partition. Then when I will `sudo bash` this two packages [Workspace arm64](https://kasm-static-content.s3.amazonaws.com/kasm_release_workspace_images_arm64_1.10.0.238225.tar.gz), and [Kasm Service arm64](https://kasm-static-content.s3.amazonaws.com/kasm_release_service_images_arm64_1.10.0.238225.tar.gz) ... from a `raspios_arm64` it will work, but from a `kali-arm` it will not work? 
> @j-travis

**Comment by j-travis** [comment]
I'm not sure if you will be able to install directly on a Kali OS as we don't test that. 

Our installer only targets supported distros/versions which can be found here:  https://kasmweb.com/docs/latest/install/system_requirements.html#id1

However, if you are installing on an unsupported distro the installer will continue as long as you have supported versions of docker-ce and docker compose v2 installed.

See https://kasmweb.com/docs/latest/how_to/other_operating_systems.html  and https://kasmweb.com/docs/latest/install/system_requirements.html#docker-and-docker-compose for reference information

**Comment by alemens** [comment]
I will try this _Frankenstein_ and if you are interested I will let you know my experience @j-travis

**Comment by alemens** [comment]
I hope Kasm will fully support ARM64 Raspberry Pi OS

**Comment by j-travis** [comment]
We have published an ARM64 version of Kali. You can use the `develop` tag e.g (`kasmweb/core-kali-rolling:develop`)

We will make this official in the next release (1.11.0) and create a version tag accordingly

For now, you can manually add this to your deployments via the Admin->Images page if you desire.

Please note the `develop` tags are meant of experimentation/testing and provides no expectation of compatibility with current release of Kasm Workspaces.

**Comment by alemens** [comment]
Dope!

**Comment by KamilPacanek** [comment]
> Good idea, to make from raspberry (8GB RAM) personal mini PC

I've just published a first guide on RPi 4 running Kasm - I'm going to publish more of them in incoming days because in my opinion it is lit idea!
https://blog.cyberethical.me/run-kasm-workspaces-on-raspberry-pi

**Comment by j-travis** [comment]
@KamilPacanek , that's excellent!  I'm sure folks will appreciate that. Consider posting it to our subreddit as well:
https://www.reddit.com/r/kasmweb/

**Comment by j-travis** [comment]
We went through our existing image set and added compatibility where its supported by the app vendor. We also have several new images available  under the `develop` tags. You are free to test them if you like:

- kasmweb/core-kali-rolling:develop
- kasmweb/doom:develop
- kasmweb/sublime-text:develop
- kasmweb/tor-browser:develop
- kasmweb/java-dev:develop
- kasmweb/telegram:develop
- kasmweb/opensuse-15-desktop:develop
- kasmweb/oracle-8-desktop:develop
- kasmweb/libre-office:develop
- kasmweb/ubuntu-focal-desktop:develop
