### ISSUE TITLE
Kasm does not load sessions.

### ISSUE THREAD

**Issue by paul10510** [kasmtech/workspaces-issues#89]
Every time I try to open a kasm session, either from the workspaces tab, or the extension, it will say "Creating secure connection" for a minute or two, then just go back to the admin page. When I go back to the workspaces page, it says the session is running, but when I try to resume the session, it will do the same go back to admin page thing it does when I first opened the session. I do not receive any errors. Any suggestions on how to fix?

**Comment by j-travis** [comment]
Can you please run through the client and server-side troubleshooting steps found here:
https://kasmweb.com/docs/latest/guide/troubleshooting.html

A quick way to test client-side issues is to try loading up a demo session on our homepage. 

https://kasmweb.com

**Comment by paul10510** [comment]
would you guys happen to have an updated Caddyfile for V2? I believe that is where I am having trouble.

**Comment by j-travis** [comment]
I'm sorry we don't. If you get a working version it would be great to share.

It sounds like you found our reverse proxy guide (https://kasmweb.com/docs/latest/how_to/reverse_proxy.html)

If you are already able to connect to the web app, you probably just need to make sure your caddyfile proxies websockets correctly, and that you've updated your Zone settings: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones

**Comment by paul10510** [comment]
I have updated my zone settings, just need to figure out the web sockets. Will definitely share when I find a working version.

**Comment by paul10510** [comment]
I am no longer getting websocket errors. I am now getting ERR_CONNECTION_TIMED_OUT, with the admin logs saying that they had a "Error requesting screenshot from kasm". Is this still an issue with my Caddyfile? I have been able to translate your Caddy V1  file to V2, but I am still getting these errors.

**Comment by j-travis** [comment]
I'll need some more information:

1. What port is Kasm Workspaces running on. e.g did you pass the `-L` flag during the install to specify a non standard port?
2. Is caddy on the same server or different server?
3. What port is caddy running on?

**Comment by paul10510** [comment]
Kasm is currently running on port 900. Caddy is running on the same server. Caddy is running on either port 443 or port 80.

**Comment by paul10510** [comment]
Caddy is running on the default 443 port.

**Comment by j-travis** [comment]
Ok,

- Please share the URL that you use to access the deployment (you can obfuscate it for privacy) 
- Please share the IP of you Kasm server (you can obfuscate it for privacy)
- Log into the workspaces webapp as an admin
- Select Zones. Edit your default zone. Share what you have for upstream auth address (you can obfuscate it for privacy)
- Destroy any sessions you may already have created
- Create a new session
- SSH into your Kasm server (or login via console)
- Run the following command and paste the output : `sudo grep internal_auth /opt/kasm/current/conf/nginx/containers.d/*`
- Exec into the kasm_proxy container: `sudo docker exec_it kasm_proxy sh`
- Curl the URL you got in the previous grep command ` curl -ik  https://my.kasm.server:443/api/internal_auth/`  paste the output. You should get a 403 Forbidden - If it errors in any other way you'll need to solve that

**Comment by paul10510** [comment]
I use kasm.mydomain.com
For upstream auth address I use kasm.mydomain.com
For the output of the first command I get `proxy_pass https://kasmserverip:900/api/internal_auth/`
The second command throws an error. `docker: 'exec_it' is not a docker command.`
The third command outputs 
`HTTP/1.1 403 Forbidden                                                                                                                                                  
Server: nginx/1.21.3                                                                                                                                                    
Date: Tue, 18 Jan 2022 00:52:35 GMT                                                                                                                                     
Content-Type: text/html;charset=utf-8                                                                                                                                   
Content-Length: 0                                                                                                                                                       
Connection: keep-alive`

**Comment by paul10510** [comment]
I am able to launch kasm sessions only when I connect to the webapp from https://kasmserverip:900 if that helps

**Comment by j-travis** [comment]
For upstream auth enter your kasm server ip.
In that same zone form, what do you have for proxy port. It needs to be 443.

Make those changes then destroy and recreate a new session...do not resume the existing one

**Comment by paul10510** [comment]
Now the websocket connections are failing
![Screenshot 2022-01-17 200816](https://user-images.githubusercontent.com/76189635/149853537-382641d5-8b8b-41e8-a5a7-58eca36c1a13.png)

**Comment by j-travis** [comment]
Ok, I think now the issue is with the caddy config.

**Comment by paul10510** [comment]
![Screenshot 2022-01-17 200816](https://user-images.githubusercontent.com/76189635/149854198-a705b599-e8d8-4de6-abd2-fae3ba290fd3.png)
![Screenshot 2022-01-17 201700](https://user-images.githubusercontent.com/76189635/149854201-a91cbd5a-f53b-4d0c-8675-84ae14042cbc.png)

Here are the full errors and my Caddy config.

**Comment by j-travis** [comment]
Can you see if the websocket connection is making it to the session?

1. Find the session container via `sudo docker ps`
2. Tail the logs while you are making a connection. `sudo docker logs -f <container id>`

**Comment by paul10510** [comment]
![image](https://user-images.githubusercontent.com/76189635/149855484-cb4b928f-b613-4eb0-9351-933477256ded.png)
this is what I am seeing

**Comment by j-travis** [comment]
It's possible We just dont work with Caddy 2. Sometimes systems handle websockets in quirky ways.
We've seen it before: https://github.com/kasmtech/KasmVNC/issues/38

I don't think there is much more I can do at the moment.  We will have to have someone set things up and debug.

**Comment by paul10510** [comment]
Thank you so much for your time.

**Comment by mgeorgy** [comment]
I am also having issues with Kasm loading sessions.  My install is behind Cloudflare, however I have the same experience when attempting to launch a session using my server IP.  I am able to log into and work within the admin interface without issue.  When I attempt to launch a session the page remains at "Creating a secure connection..." for while before reloading the main dashboard.  When I click back to the workspaces I can see a session appears to have been launched but I am unable to resume.

![image](https://user-images.githubusercontent.com/1755116/150045667-26111896-d349-4a90-ae41-7602f1a56d5f.png)

I have successfully tested the client using the demo session on the Kasm web site.  I have also tried updating some images to the -rolling versions per https://github.com/kasmtech/KasmVNC/issues/38#issuecomment-881318819.

The client console reports 500 errors as Kasm is attempting to launch the session:
`
Kasm.js:262 GET https://<kasm>/desktop/2054c06b-87a4-4829-9952-868e03417eac/vnc/vnc.html?video_quality=2&enable_webp=false&idle_disconnect=20&password=&autoconnect=1&path=desktop/2054c06b-87a4-4829-9952-868e03417eac/vnc/websockify&cursor=true&resize=remote&clipboard_up=true&clipboard_down=true&clipboard_seamless=true&toggle_control_panel=false 500`

Any suggestions?

**Comment by j-travis** [comment]
@mgeorgy .
Consider walking through the server side troubleshooting guide: https://kasmweb.com/docs/latest/guide/troubleshooting.html#server-side-issues

When you put Kasm behind a proxy system like cloudflare you need to update the zone settings. More info can be found here

https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#update-zones

When you change and test your settings destroy and create a new session for the changes to take effect. Do not try and resume an existing session

**Comment by mgeorgy** [comment]
@j-travis thank you.  I'd skimmed over the zone update, but after a more thorough reading I realized I'd made a mistake.  Everything works as expect.

Thank you!

**Comment by j-travis** [comment]
@paul10510 ,
The Caddy V2 docs say that :

```
Websocket proxying "just works" in v2; there is no need to "enable" websockets like in v1.
```
https://caddyserver.com/docs/v2-upgrade#proxy

Indeed that seems to be the case, at least with some quick testing with Kasm.

In your Caddyfile try removing the websocket header lines
```
header_up Connection {>Connection}
header_up Upgrade {>Upgrade}
```

With those removed it should work. When they are present it will not.

For example
```
{
   local_certs
   default_sni kasm.example.local
}
https://kasm.example.local:443 {

        reverse_proxy https://127.0.0.1:8443 {
                transport http {
                        tls_insecure_skip_verify
                }

            header_up Host {host}
            header_up X-Real-IP {remote}
            header_up X-Forwarded-For {remote}
            header_up X-Forwarded-Port {server_port}
            header_up X-Forwarded-Proto {scheme}

        }
}

```

**Comment by mayrink85** [comment]
I've been also having issues with this. I've deployed it and am publishing through cloudflare, I've updated the zones to reflect the upstream auth Address to my kasm.example.com domain and still getting internal error 500.
At some stage I was able to access the applications via the internal IP address but even through that I am getting errors. 

![image](https://user-images.githubusercontent.com/85237105/150647955-823b1bf0-1748-4fb7-9603-fffc1090545d.png)

![image](https://user-images.githubusercontent.com/85237105/150647982-822d0ee1-741d-482b-bb08-463d36016f59.png)

Checking the nginx container.d conf file I can see that the proxy_pass is pointing to the correct domain address
I can also see some parameters inside location /<SOME ID>/ which there is this options below
![image](https://user-images.githubusercontent.com/85237105/150648092-36cd3454-4e69-4b54-bbb2-2c7d13458ad2.png)

This is pointing to the internal local IP address. And this is the same for a lot of other ids.

Looking for some help and clarification.

**Comment by j-travis** [comment]
@mayrink85 ,
Please try changing the upstream auth to the internal IP of your kasm server:
https://github.com/kasmtech/workspaces-issues/issues/110#issuecomment-1017853184

**Comment by mayrink85** [comment]
> @mayrink85 , Please try changing the upstream auth to the internal IP of your kasm server: [#110 (comment)](https://github.com/kasmtech/workspaces-issues/issues/110#issuecomment-1017853184)

Thank you @j-travis That seems to have actually fixed my issue. Much appreciated.

**Comment by urbanswelt** [comment]
CloudFlare - Linode - Kasm
I have not seen a Setup for CloudFlare, here the picture ;-)
Thank you very much @j-travis !

![image](https://user-images.githubusercontent.com/2138928/150651567-edc850cb-bf27-406f-b0e0-9cd686209f2b.png)

![image](https://user-images.githubusercontent.com/2138928/150651647-bab888c7-9e55-42a5-b1ce-0cbe2b2e88e9.png)

![image](https://user-images.githubusercontent.com/2138928/150651701-67cf3142-6da8-46b4-a667-1e26127f83be.png)

**Comment by j-travis** [comment]
@urbanswelt ,
please walk through the troubleshooting guide. and see if you can resolve the issue
https://kasmweb.com/docs/latest/guide/troubleshooting.html#connection-to-session-hangs-requesting-kasm

**Comment by urbanswelt** [comment]
Hi @j-travis,

it was already solved with your link back to the comment 110 ;-)
My pictures are the results, sorry for my bad feedback text. !

**Comment by j-travis** [comment]
@urbanswelt ,
 I initially misunderstood. Thank you for the update and screenshots 👍
