### ISSUE TITLE
Valid LDAP query filters fail as "malformed"

### ISSUE THREAD

**Issue by Ian-Kasmweb** [kasmtech/workspaces-issues#9]
**[Original report](https://bitbucket.org/kasmtech/kasm_release/issue/9) by Zack W (Bitbucket: [Zack W](https://bitbucket.org/Zack W), ).**

----------------------------------------

I’m attempting to set up LDAP authentication. I’ve crafted search and group filters that I know to work and return the expected entries with the `ladpsearch` shell command, but the same filters when entered into the LDAP configuration for Kasm cause the authentication test to fail with the following error landing in the log:

```
message: Authentication Error : malformed filter
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
host: my_host.my.domain.com
client_ip: my_hosts_ip
process: client_api_server
user_agent: Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0
ingest_date: 202004301844
```

Here is my LDAP configuration:

```
Ldap Id:                    c6d8aa1a98df47808dfd480c6644b3eb
Name:                       Mollontinaxial
Url:                        ldap://ma-lin-ds01.internal.mollontinaxial.net
Search Base:                dc=internal,dc=mollontinaxial,dc=net?
Search Filter:              (&(objectclass=inetorgperson)(memberof=cn=kasm,cn=groups,cn=accounts,dc=internal,dc=mollontinaxial,dc=net))
Group Membership Filter:    (&(objectclass=ipausergroup)(cn=kasm))
Email attribute:            NA
Service Account DN:         uid=somebody,cn=users,cn=accounts,dc=internal,dc=mollontinaxial,dc=net
Search Subtree:             true
Auto Create App User:       true
Enabled:                    true
```

Removing the parentheses wrapping the filters causes Kasm to make a successful query against my LDAP server, but, because the filter doesn’t work anymore, authentication fails. I’ve tried putting them in quotes, as well. Am I doing something wrong, or is this a bug?

‌

I’m using version 1.6.0.a6b662 on Ubuntu 18.04, authenticating against FreeIPA LDAP

‌

‌

UPDATE:

‌

It seems like Kasm is taking my inputted search filter, and then adding the required parentheses before sending it off to LDAP. I _guess_ this works, but I can absolutely see it confusing other administrators who are trying to submit a valid search filter, not expecting Kasm to do some other formatting on it after they’ve configured LDAP. Might be something to consider changing.

‌

After fiddling around, It seems like I’ve got LDAP working now.

‌

**Comment by mmcclaskey** [comment]
This was fixed with the release of 1.10.0. Kasm will support proper and improper ldap syntax (with or without wrapping parentheses.
