### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by proars** [kasmtech/workspaces-issues#90]
Cant login with admin and user 
Fresh installed Kasm on Ubunti 20.04
Error: Login Failed 

![Untitled](https://user-images.githubusercontent.com/96272922/149846572-ce7a6378-50c5-4e04-94d3-63e4264e8228.jpg)

**Comment by j-travis** [comment]
Hello,
1. Check the console log of your browser. See if there is anything interesting
2. Run `sudo docker ps` make sure all the kasm containers are running and aren't constantly restarting
3. Run `sudo docker logs -f --tail 10 kasm_api` to monitor the logs - then try to login. See if there are any errors reported in the log

**Comment by proars** [comment]
Hello
It looks like someting wrong with api 
But I tried install on fresh Ubuntu 20.04 3 times, same problem 
btw Ubuntu running on Proxmox
1.
![1](https://user-images.githubusercontent.com/96272922/149848541-56b9a778-8db4-4958-8f6b-40914030abd1.jpg)

2. 
![2](https://user-images.githubusercontent.com/96272922/149848675-42fd9aa4-f84c-4f70-8d8d-09af410046b2.jpg)

3.
![3](https://user-images.githubusercontent.com/96272922/149848786-bbf13bb5-5c3a-4505-a5d7-f1201c45b476.jpg)

**Comment by j-travis** [comment]
You may be out of disk space.
Can you run `df`

Minimum requirement is for 50GB of free space:
https://kasmweb.com/docs/latest/install/system_requirements.html#resource-requirements

**Comment by proars** [comment]
Right i set 50GB 
![df](https://user-images.githubusercontent.com/96272922/149849129-402c9fbe-4ec3-4780-9c28-ab1d3a47f272.jpg)

fdisk
![fdisk](https://user-images.githubusercontent.com/96272922/149849141-6f029e93-d8fb-44f4-b89e-edec6eaf48d2.jpg)

**Comment by j-travis** [comment]
You'll need to be mindful during the ubuntu install of how LVM divvies up the space. It looks like root `/` is only allocated 24g - The installer may have some logic to only assign half the drive size

**Comment by proars** [comment]
Oh yes I see 
Thank you!
