### ISSUE TITLE
[REQUEST] AlmaLinux support

### ISSUE THREAD

**Issue by t3kg33k** [kasmtech/workspaces-issues#93]
This is a request to add AlmaLinux support, which is basically a branch of CentOS.

**Comment by j-travis** [comment]
Thanks for the request.
As you've probably seen, our installer is coded to support only certain distros/versions. However, the primary system requirements are really just openssl, docker > 18.06 and docker compose v2. If you pre-install these on your system, our installer will continue. You may consider giving that a try:

https://kasmweb.com/docs/latest/install/system_requirements.html#docker-and-docker-compose
https://kasmweb.com/docs/latest/how_to/other_operating_systems.html

**Comment by t3kg33k** [comment]
Thanks for the quick response. I will give it a try.

**Comment by t3kg33k** [comment]
Yeah, I don't think it is going to work. Your dependencies script is looking for _docker_ and _docker compose_ in the wrong directory for AlmaLinux 8.
Here is the current _docker info_
```
[ed@test01 kasm_release]$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-348.7.1.el8_5.x86_64
 Operating System: AlmaLinux 8.5 (Arctic Sphynx)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.649GiB
 Name: test01.offworld.lan
 ID: XLV2:MDU3:HOMJ:BVK3:FP3B:W2DP:7F3F:RNO3:6UIL:KZJN:TH6Z:F32M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

The current install for _docker compose_ per their website is (notice the destination directory):

_sudo curl -L "https://github.com/docker/compose/releases/download/v1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose_

Note: since the current version of _docker compose_ per their Github is v2.2.3, I substituted v1.29.2 with the current version.

Per my current version of docker, the /usr/local/lib/docker/cli-plugins/ directory does not exist.

**Comment by j-travis** [comment]
Workspaces 1.10 is expecting docker compose v2 which is installed as a CLI plugin.

https://github.com/docker/compose
https://docs.docker.com/compose/cli-command/

You can take a look at how we install it via `install_dependencies.sh` in the install package. This should work for you. (as sudo or root)
```
mkdir -p /usr/local/lib/docker/cli-plugins
curl -L https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
```

**Comment by t3kg33k** [comment]
> Workspaces 1.10 is expecting docker compose v2 which is installed as a CLI plugin.
> 
> https://github.com/docker/compose https://docs.docker.com/compose/cli-command/
> 
> You can take a look at how we install it via `install_dependencies.sh` in the install package. This should work for you. (as sudo or root)
> 
> ```
> mkdir -p /usr/local/lib/docker/cli-plugins
> curl -L https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/lib/docker/cli-plugins/docker-compose
> chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
> ```

I saw that section in the script. I will try making that directory but I don't think it will work.

**Comment by t3kg33k** [comment]
Looks like that work. However, I substituted v2.0.1 with v2.2.3.
Thanks for the assist. I'm checking out the Kasm Workspaces web interface now running on AlmaLinux machine.

**Comment by t3kg33k** [comment]
Web interface is running but I can't launch any Workspaces (containers?). 
Troubleshooting now...

**Comment by t3kg33k** [comment]
I tried installing it on a machine with more resources, still under AlmaLinux 8, and am not able to launch anything.
Not sure what is going on. Simply attempting to launch Brave displays an error. This is the last error message from the log:

host: tyrell.offworld.lan
ingest_date: 202201200242
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
message: Error during Create request for Server(33bf960e-7f60-4cdb-a0a2-afdd13009fec) : (Exception creating Kasm: Traceback (most recent call last): File "ProvisionAgent/__init__.py", line 319, in post File "ProvisionAgent/provision.py", line 552, in provision File "ProvisionAgent/provision.py", line 699, in generate_nginx_config Exception: Nginx failed to reload after generating config for container (0aee50637cc15209d780a87dff0a9e300b5e2a146557ae43b0dd5f579a3a3bb8) )
process: client_api_server
client_ip: 192.168.15.10
user_agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by j-travis** [comment]
I see.
Please provide the output from the following commands

```
sudo docker ps
sudo docker exec -it kasm_proxy curl -k <kasm server url>
```

For the second command please use the URL you enter into your browser to access your kasm workspaces app

**Comment by t3kg33k** [comment]
It's the last command that pointed me in the right direction:

```
sudo docker exec -it kasm_proxy curl -k https://tyrell
curl: (6) Could not resolve host: tyrell
```

It's a name resolution issue. Once I went to the IP address instead of the hostname of the server I was able to launch Brave and other containers.

**Comment by j-travis** [comment]
Yep thats what I was thinking. Glad its resolved

**Comment by t3kg33k** [comment]
Thanks for your help. This is cool. And I glad this runs on AlmaLinux 8.
