### ISSUE TITLE
Discord image not working

### ISSUE THREAD

**Issue by d3lac** [kasmtech/workspaces-issues#94]
https://www.kasmweb.com/docs/latest/guide/custom_images.html

Image `kasmweb/discord:1.10.0` 

Screenshots https://ibb.co/album/YbB1wr

Logging error
```
2022-01-18 18:41
host: hostname
ingest_date: 202201181311
application: kasm_api
levelname: ERROR
kasm_user_name: admin@kasm.local
message: No resources are available to create the requested Kasm. Please try again later or contact an Administrator : Agent does not have the requested image
process: client_api_server
client_ip: my.ip
user_agent: My browser
```

Other than the above, nothing else is captured so I'm unable to troubleshoot. Please suggest.

**Comment by j-travis** [comment]
Hi,
can you send the output of the following commands
```
cat /etc/os-release
uname -a
cat /proc/cpuinfo
cat /proc/meminfo
sudo docker images | grep kasmweb
```

**Comment by d3lac** [comment]
Thanks for responding, the instance runs on Oracle free tier ARM. 

Please see below,

> cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-poli                                                                                                                              cy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

> uname -a

Linux hostname 5.11.0-1022-oracle #23~20.04.1-Ubuntu SMP Fri Nov 12 15:45:47 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

> cat /proc/cpuinfo

processor       : 0
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 1
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 2
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

processor       : 3
BogoMIPS        : 50.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x3
CPU part        : 0xd0c
CPU revision    : 1

> cat /proc/meminfo

MemTotal:       24576628 kB
MemFree:        14014900 kB
MemAvailable:   22166132 kB
Buffers:          189172 kB
Cached:          7700688 kB
SwapCached:            0 kB
Active:          1505520 kB
Inactive:        8168572 kB
Active(anon):      32440 kB
Inactive(anon):  1847056 kB
Active(file):    1473080 kB
Inactive(file):  6321516 kB
Unevictable:       22516 kB
Mlocked:           19440 kB
SwapTotal:       4194300 kB
SwapFree:        4194300 kB
Dirty:               368 kB
Writeback:             0 kB
AnonPages:       1806804 kB
Mapped:           569800 kB
Shmem:             94124 kB
KReclaimable:     673636 kB
Slab:             784136 kB
SReclaimable:     673636 kB
SUnreclaim:       110500 kB
KernelStack:        8880 kB
PageTables:        19376 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    16482612 kB
Committed_AS:    7179128 kB
VmallocTotal:   133143461888 kB
VmallocUsed:       23024 kB
VmallocChunk:          0 kB
Percpu:             3552 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:          32768 kB
CmaFree:           20480 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB

> sudo docker images | grep kasmweb

kasmweb/share                   1.10.0      0a8e0aaf3f35   2 months ago   73.8MB
kasmweb/agent                   1.10.0      9a9f71317ce4   2 months ago   98.6MB
kasmweb/manager                 1.10.0      abe7211f1175   2 months ago   87.7MB
kasmweb/api                     1.10.0      477746a97e21   2 months ago   151MB
kasmweb/ubuntu-bionic-desktop   1.10.0      604803ec3df2   2 months ago   2.21GB
kasmweb/vs-code                 1.10.0      05f17c11db38   2 months ago   1.42GB
kasmweb/remmina                 1.10.0      ca6cff0629b9   2 months ago   1.11GB
kasmweb/vlc                     1.10.0      b2a919894cdd   2 months ago   1.22GB
kasmweb/terminal                1.10.0      0d1124f31aaf   2 months ago   1.24GB
kasmweb/gimp                    1.10.0      b0153768784c   2 months ago   1.19GB
kasmweb/firefox                 1.10.0      ebfcc98323c4   2 months ago   1.32GB
kasmweb/discord                 1.10.0      ff892a035cf2   2 months ago   1.45GB
kasmweb/chromium                1.10.0      20f33ffa1d25   2 months ago   1.43GB
kasmweb/nginx                   latest      69f99328ef82   3 months ago   24MB

**Comment by j-travis** [comment]
Gotcha,
The issue is that our discord image doesn't support arm64.  Docker has a quirk in that it will try and pull the arm64 image, but if it dosent exist it will pull the amd64 architecture anyway - even though it cant run it.

https://hub.docker.com/r/kasmweb/discord/tags

**Comment by d3lac** [comment]
I thought the same, maybe I should try with amd64. Thanks for your help.
