### ISSUE TITLE
Raspberry pi arm64 Creation Error

### ISSUE THREAD

**Issue by Jurogas3** [kasmtech/workspaces-issues#96]
Hello, i recently installed kasm on my raspberry pi.
Everything worked fine until I try to create a session,
I get this error: "
An Unexpected Error occurred creating the Kasm. Please contact an Administrator : Error during Create request for Server(00973333-0887-4a65-98ea-2ac71472c219) : (Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 953, in raise_for_status requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create During handling of the above exception, another exception occurred: Traceback (most recent call last): File "ProvisionAgent/__init__.py", line 319, in post File "ProvisionAgent/provision.py", line 492, in provision File "docker/models/containers.py", line 812, in run File "docker/models/containers.py", line 870, in create File "docker/api/container.py", line 430, in create_container File "docker/api/container.py", line 441, in create_container_from_config File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted") )"
And the errors are rising.
I also get this Error:
"Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 953, in raise_for_status requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create During handling of the above exception, another exception occurred: Traceback (most recent call last): File "ProvisionAgent/__init__.py", line 319, in post File "ProvisionAgent/provision.py", line 492, in provision File "docker/models/containers.py", line 812, in run File "docker/models/containers.py", line 870, in create File "docker/api/container.py", line 430, in create_container File "docker/api/container.py", line 441, in create_container_from_config File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted")" AND "
Error during Create request for Server(00973333-0887-4a65-98ea-2ac71472c219) : (Exception creating Kasm: Traceback (most recent call last): File "docker/api/client.py", line 268, in _raise_for_status File "requests/models.py", line 953, in raise_for_status requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create During handling of the above exception, another exception occurred: Traceback (most recent call last): File "ProvisionAgent/__init__.py", line 319, in post File "ProvisionAgent/provision.py", line 492, in provision File "docker/models/containers.py", line 812, in run File "docker/models/containers.py", line 870, in create File "docker/api/container.py", line 430, in create_container File "docker/api/container.py", line 441, in create_container_from_config File "docker/api/client.py", line 274, in _result File "docker/api/client.py", line 270, in _raise_for_status File "docker/errors.py", line 31, in create_api_error_from_http_exception docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted") )"
Thanks in advance!

**Comment by j-travis** [comment]
Hi,
can you please post the output of the following commands
```
sudo docker info
cat /etc/os-release
uname -a
```

**Comment by Jurogas3** [comment]
> Hi, can you please post the output of the following commands
> 
> ```
> sudo docker info
> cat /etc/os-release
> uname -a
> ```

sudo docker info:
"Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.1)

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.42-v8+
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.633GiB
 Name: raspberrypi
 ID: CBVQ:LGVT:KMNV:LQP3:D5IP:ERLZ:HTAI:OZDZ:LACY:AFGA:M44B:7TLX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support"

cat /etc/os-release:
"PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/""

uname -a:
"Linux raspberrypi 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux"

**Comment by j-travis** [comment]
Look like your system/kernel can't support a number of features we require

```
WARNING: No memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support"
```

You may consider updating to a newer build of raspberry pi OS

**Comment by Jurogas3** [comment]
> Look like your system/kernel can't support a number of features we require
> 
> ```
> WARNING: No memory limit support
> WARNING: No oom kill disable support
> WARNING: No cpu cfs quota support
> WARNING: No cpu cfs period support"
> ```
> 
> You may consider updating to a newer build of raspberry pi OS

Huh? Someone in the youtube comments of a video I saw with the name "Kasm Technologies"
said: Yes, you can install Kasm Workspaces on your Pi 4 if you run the beta ARM64 build of raspberry pi OS, or the ARM64 build of Ubuntu 20.04 LTS.

And I got the newest build of the beta arm64 os, should I use Ubuntu instead?

**Comment by j-travis** [comment]
It looks like you may have got the oldest from 05/20
https://downloads.raspberrypi.org/raspios_arm64/images/

**Comment by Jurogas3** [comment]
> It looks like you may have got the oldest from 05/20 https://downloads.raspberrypi.org/raspios_arm64/images/

Uff, I'm going to install that and will return the result.
Thanks!

**Comment by Jurogas3** [comment]
> It looks like you may have got the oldest from 05/20 https://downloads.raspberrypi.org/raspios_arm64/images/

It works! Thank you so much, I love it!
