### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by sohail579** [kasmtech/workspaces-issues#97]
Followed the documentation and installed Kasm on ubuntu server 20.04.3.  it all seemed to install fine and gave me the admin credentials at the end. 

however wen i use them to log in it wont log in.  i get a login failed error

have you seen this before

**Comment by j-travis** [comment]
Hi, 
it sounds similar to this issue. Turns out the disk was out of space. Can you review please:
https://github.com/kasmtech/workspaces-issues/issues/90

**Comment by sohail579** [comment]
yes you are right for some reason it only allocated 24GB.  I set the VM to have 50.  can i extend it or do i need to start fresh?

![image](https://user-images.githubusercontent.com/57506081/149975336-a3ab32dc-9495-46a6-9847-49719fdd528f.png)

**Comment by j-travis** [comment]
There is likely a way to extend it - but if this is fresh VM it may be just as fast to re-install. 
I'll close this issue now since we know what it is. Thanks !
