### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Mrkitty22** [kasmtech/workspaces-issues#99]
![image](https://user-images.githubusercontent.com/66155797/150007849-2ddd2721-6937-4621-ae24-29fe457a1633.png)
and also:
psycopg2.OperationalError: could not connect to server: Connection refused
    Is the server running on host "db" (172.18.0.2) and accepting
    TCP/IP connections on port 5432?

**Comment by j-travis** [comment]
Hello, can you please provide the output of the following commands:

```
cat /etc/os-release
df
sudo docker --version
sudo docker info | grep compose
uname -a
```

We've had a few reports of this recently and it relates to host based firewalls. Can you please review these tickets and see if they apply to your install:

https://github.com/kasmtech/workspaces-issues/issues/80
https://github.com/kasmtech/workspaces-issues/issues/16

**Comment by Mrkitty22** [comment]
![image](https://user-images.githubusercontent.com/66155797/150010650-f569df2f-0727-492f-bb32-b4a836e88b80.png)
![image](https://user-images.githubusercontent.com/66155797/150010655-e618cd7b-0c30-460e-a74a-b5d5d575f6bd.png)
![image](https://user-images.githubusercontent.com/66155797/150010851-b23aff8c-22a6-48bd-861c-ac8936173b42.png)
![image](https://user-images.githubusercontent.com/66155797/150010897-95e4a26d-4fd7-4857-9dd3-3509b4fa603f.png)
![image](https://user-images.githubusercontent.com/66155797/150010944-41334669-4fd9-4178-a7d0-ab3193496e9e.png)
I reinstalled the server so this is before running the installation script

**Comment by Mrkitty22** [comment]
I tried to clear the ip tables and disable firewall but still. the same error: 
![image](https://user-images.githubusercontent.com/66155797/150114385-701b1107-9d87-4ec6-8fa3-d384e29d8ef0.png)

**Comment by mmcclaskey** [comment]
Are you using a cloud provider or hosted service? Many of them puppet iptables and this essentially breaks the networking in docker. While you can clear the existing rules, they can be added back in by the cloud provider's software. We have this issue on Oracle cloud and we have had people report these issues on various cloud providers and managed service providers. 

After the failed install, can you run 'iptables -L' and provide the output

**Comment by Mrkitty22** [comment]
here:
![image](https://user-images.githubusercontent.com/66155797/150148726-ed37e644-5806-4199-b9a9-621609372ea9.png)
(its a bare metal server from hetzner)

**Comment by Mrkitty22** [comment]
I asked my cloud provider and he said that his firewall doesn't block any connections to docker or to kasm.

**Comment by mmcclaskey** [comment]
Please provide your email via our chat support so we can contact you directly.

**Comment by Mrkitty22** [comment]
I did

**Comment by Mrkitty22** [comment]
It was an error in my file system after I canceled the software raid and wipe all my disks it works.
